/* =========================================================
   STOCKFLOW — API CONNECTION
   File: api.js

   Frontend
       ↓
   StockFlowAPI
       ↓
   Google Apps Script
       ↓
   Google Sheets + Firebase

   IMPORTANT:
   - No OTP generation happens here.
   - OTPs are generated by the backend.
   - This file only sends requests and handles responses.
   - Real OTPs must NOT be exposed to the browser.
   ========================================================= */

(function (window) {

    "use strict";


    /* =========================================================
       CONFIGURATION
       ========================================================= */

    const CONFIG =
        window.STOCKFLOW_CONFIG ||
        window.CONFIG ||
        {};

    const API_CONFIG =
        CONFIG.API ||
        {};

    const API_URL = String(
        CONFIG.API_URL ||
        CONFIG.APPS_SCRIPT_URL ||
        CONFIG.GOOGLE_APPS_SCRIPT_URL ||
        CONFIG.BACKEND_URL ||
        ""
    ).trim();


    const REQUEST_TIMEOUT =
        Number(
            API_CONFIG.TIMEOUT ||
            CONFIG.API_TIMEOUT ||
            30000
        );


    /*
     * IMPORTANT:
     *
     * config.js uses RETRY_COUNT.
     *
     * Keep compatibility with older configurations that may
     * use RETRY or API_RETRY_COUNT.
     */

    const RETRY_COUNT =
        Number(
            API_CONFIG.RETRY_COUNT ??
            API_CONFIG.RETRY ??
            CONFIG.API_RETRY_COUNT ??
            CONFIG.API_RETRY ??
            0
        );


    const RETRY_DELAY =
        Number(
            API_CONFIG.RETRY_DELAY ??
            CONFIG.API_RETRY_DELAY ??
            1000
        );


    const CONTENT_TYPE =
        API_CONFIG.CONTENT_TYPE ||
        "text/plain;charset=utf-8";


    /* =========================================================
       ERROR CLASS
       ========================================================= */

    class StockFlowAPIError extends Error {

        constructor(
            message,
            code = "API_ERROR",
            details = null
        ) {

            super(
                message ||
                "StockFlow API error."
            );

            this.name =
                "StockFlowAPIError";

            this.code =
                code ||
                "API_ERROR";

            this.details =
                details;

            this.status =
                details?.status ??
                null;

            this.action =
                details?.action ??
                null;

            this.data =
                details?.data ??
                null;

            this.response =
                details?.response ??
                null;

            this.rawResponse =
                details?.rawResponse ??
                null;

            this.originalError =
                details?.originalError ??
                null;

            this.isTransportError =
                details?.isTransportError === true;
        }
    }


    /* =========================================================
       BASIC HELPERS
       ========================================================= */

    function safeString(value) {

        if (
            value === null ||
            value === undefined
        ) {

            return "";
        }

        return String(value).trim();
    }


    function parsePossibleObject(value) {

        if (!value) {
            return null;
        }


        if (
            typeof value === "object"
        ) {

            return value;
        }


        if (
            typeof value === "string"
        ) {

            try {

                return JSON.parse(
                    value
                );

            } catch (_) {

                return null;
            }
        }


        return null;
    }


    function getNestedObjectCandidates(
        value
    ) {

        const candidates = [];


        if (!value) {
            return candidates;
        }


        const direct =
            parsePossibleObject(
                value
            );


        if (direct) {

            candidates.push(
                direct
            );
        }


        if (
            direct &&
            direct.data
        ) {

            const data =
                parsePossibleObject(
                    direct.data
                );


            if (data) {

                candidates.push(
                    data
                );
            }
        }


        if (
            direct &&
            direct.response
        ) {

            const response =
                parsePossibleObject(
                    direct.response
                );


            if (response) {

                candidates.push(
                    response
                );
            }
        }


        if (
            direct &&
            direct.result
        ) {

            const result =
                parsePossibleObject(
                    direct.result
                );


            if (result) {

                candidates.push(
                    result
                );
            }
        }


        return candidates;
    }


    function getServerErrorCode(
        error
    ) {

        if (!error) {
            return "";
        }


        if (
            error.code
        ) {

            return safeString(
                error.code
            );
        }


        const directCandidates = [

            error.data,

            error.response,

            error.result,

            error.details,

            error.rawResponse

        ];


        for (
            const candidate
            of directCandidates
        ) {

            const objects =
                getNestedObjectCandidates(
                    candidate
                );


            for (
                const object
                of objects
            ) {

                if (
                    object &&
                    object.code
                ) {

                    return safeString(
                        object.code
                    );
                }
            }
        }


        return "";
    }


    function getServerErrorMessage(
        error
    ) {

        if (!error) {
            return "";
        }


        /*
         * Don't use generic transport-error text as the
         * backend's business message.
         */

        if (
            error.message &&
            !(
                error instanceof
                StockFlowAPIError
            )
        ) {

            return safeString(
                error.message
            );
        }


        if (
            error instanceof
            StockFlowAPIError &&
            error.message &&
            error.code !==
                "NETWORK_ERROR" &&
            error.code !==
                "TIMEOUT"
        ) {

            return safeString(
                error.message
            );
        }


        const directCandidates = [

            error.data,

            error.response,

            error.result,

            error.details,

            error.rawResponse

        ];


        for (
            const candidate
            of directCandidates
        ) {

            const objects =
                getNestedObjectCandidates(
                    candidate
                );


            for (
                const object
                of objects
            ) {

                if (
                    object &&
                    object.message
                ) {

                    return safeString(
                        object.message
                    );
                }


                if (
                    object &&
                    object.error
                ) {

                    return safeString(
                        object.error
                    );
                }
            }
        }


        return "";
    }


    function normalizeResult(
        result
    ) {

        if (
            result === null ||
            result === undefined
        ) {

            return {

                success:
                    false,

                code:
                    "EMPTY_RESPONSE",

                message:
                    "Empty server response."
            };
        }


        if (
            typeof result === "string"
        ) {

            const parsed =
                parsePossibleObject(
                    result
                );


            if (parsed) {

                return parsed;
            }
        }


        return result;
    }


    /* =========================================================
       API URL VALIDATION
       ========================================================= */

    function validateApiUrl() {

        if (!API_URL) {

            throw new StockFlowAPIError(
                "StockFlow API URL is not configured.",
                "MISSING_API_URL"
            );
        }


        if (
            !API_URL.includes(
                "script.google.com/macros/s/"
            )
        ) {

            console.warn(
                "STOCKFLOW: API URL does not look like a Google Apps Script Web App."
            );
        }


        if (
            !API_URL.endsWith(
                "/exec"
            )
        ) {

            console.warn(
                "STOCKFLOW: API URL does not end with /exec."
            );
        }
    }


    /* =========================================================
       RESPONSE SUCCESS CHECK
       ========================================================= */

    function isFailedServerResponse(
        data
    ) {

        if (!data) {
            return true;
        }


        if (
            data.success === false
        ) {

            return true;
        }


        if (
            data.ok === false
        ) {

            return true;
        }


        if (
            String(
                data.status ||
                ""
            ).toLowerCase() ===
            "error"
        ) {

            return true;
        }


        return false;
    }


    /* =========================================================
       RESPONSE PARSER
       ========================================================= */

    async function parseResponse(
        response,
        action
    ) {

        const text =
            await response.text();


        let data = null;


        /* -----------------------------------------------------
           Empty response
           ----------------------------------------------------- */

        if (
            !text ||
            !text.trim()
        ) {

            throw new StockFlowAPIError(

                response.ok
                    ? "The server returned an empty response."
                    : `Server returned HTTP ${response.status}.`,

                response.ok
                    ? "EMPTY_RESPONSE"
                    : "HTTP_ERROR",

                {

                    status:
                        response.status,

                    action,

                    rawResponse:
                        text,

                    response
                }
            );
        }


        /* -----------------------------------------------------
           JSON response
           ----------------------------------------------------- */

        try {

            data =
                JSON.parse(
                    text
                );

        } catch (error) {

            throw new StockFlowAPIError(

                "The server returned an invalid JSON response.",

                "INVALID_JSON",

                {

                    status:
                        response.status,

                    action,

                    rawResponse:
                        text,

                    response,

                    originalError:
                        error
                }
            );
        }


        /* -----------------------------------------------------
           HTTP failure
           ----------------------------------------------------- */

        if (
            !response.ok
        ) {

            throw new StockFlowAPIError(

                data?.message ||
                data?.error ||
                `Server returned HTTP ${response.status}.`,

                data?.code ||
                "HTTP_ERROR",

                {

                    status:
                        response.status,

                    action,

                    data,

                    response,

                    rawResponse:
                        text
                }
            );
        }


        /* -----------------------------------------------------
           Backend business failure
           ----------------------------------------------------- */

        if (
            isFailedServerResponse(
                data
            )
        ) {

            throw new StockFlowAPIError(

                data?.message ||
                data?.error ||
                "The server rejected the request.",

                data?.code ||
                "REQUEST_FAILED",

                {

                    status:
                        response.status,

                    action,

                    data,

                    response,

                    rawResponse:
                        text
                }
            );
        }


        return data;
    }


    /* =========================================================
       DELAY
       ========================================================= */

    function wait(ms) {

        return new Promise(
            resolve => {

                setTimeout(
                    resolve,
                    ms
                );
            }
        );
    }


    /* =========================================================
       GENERIC REQUEST
       ========================================================= */

    async function request(
        action,
        payload = {},
        options = {}
    ) {

        validateApiUrl();


        if (!action) {

            throw new StockFlowAPIError(
                "API action is required.",
                "MISSING_ACTION"
            );
        }


        const body = {

            action:
                safeString(
                    action
                ),

            ...(
                payload &&
                typeof payload ===
                    "object"
                    ? payload
                    : {}
            )
        };


        const maxRetries =
            Number.isFinite(
                options.retries
            )
                ? Number(
                    options.retries
                )
                : RETRY_COUNT;


        let lastError =
            null;


        for (
            let attempt = 0;
            attempt <= maxRetries;
            attempt++
        ) {

            const controller =
                new AbortController();


            const timeout =
                setTimeout(
                    () => {

                        controller.abort();

                    },
                    REQUEST_TIMEOUT
                );


            try {

                console.debug(
                    "STOCKFLOW API REQUEST:",
                    {

                        action,

                        attempt:
                            attempt + 1,

                        body
                    }
                );


                const response =
                    await fetch(
                        API_URL,
                        {

                            method:
                                "POST",

                            headers: {

                                "Content-Type":
                                    CONTENT_TYPE
                            },

                            body:
                                JSON.stringify(
                                    body
                                ),

                            mode:
                                "cors",

                            credentials:
                                "omit",

                            redirect:
                                "follow",

                            signal:
                                controller.signal
                        }
                    );


                const result =
                    await parseResponse(
                        response,
                        action
                    );


                console.debug(
                    "STOCKFLOW API RESPONSE:",
                    {

                        action,

                        result
                    }
                );


                return result;


            } catch (error) {

                /* -------------------------------------------------
                   Timeout
                   ------------------------------------------------- */

                if (
                    error?.name ===
                    "AbortError"
                ) {

                    lastError =
                        new StockFlowAPIError(

                            "The StockFlow server took too long to respond.",

                            "TIMEOUT",

                            {

                                action,

                                originalError:
                                    error,

                                isTransportError:
                                    true
                            }
                        );
                }


                /* -------------------------------------------------
                   Existing StockFlow API error
                   ------------------------------------------------- */

                else if (
                    error instanceof
                    StockFlowAPIError
                ) {

                    lastError =
                        error;
                }


                /* -------------------------------------------------
                   Native fetch/network error
                   ------------------------------------------------- */

                else {

                    lastError =
                        new StockFlowAPIError(

                            "Unable to connect to the StockFlow server.",

                            "NETWORK_ERROR",

                            {

                                action,

                                originalError:
                                    error,

                                isTransportError:
                                    true
                            }
                        );
                }


                const code =
                    getServerErrorCode(
                        lastError
                    );


                const transportError =
                    lastError?.isTransportError ===
                        true ||

                    code ===
                        "NETWORK_ERROR" ||

                    code ===
                        "TIMEOUT";


                /*
                 * NEVER retry business errors.
                 */

                if (
                    !transportError ||
                    attempt >=
                        maxRetries
                ) {

                    throw lastError;
                }


                await wait(
                    RETRY_DELAY
                );

            } finally {

                clearTimeout(
                    timeout
                );
            }
        }


        throw (
            lastError ||

            new StockFlowAPIError(
                "Unknown StockFlow API error.",
                "API_ERROR"
            )
        );
    }


    /* =========================================================
       IDENTITY BUILDER
       ========================================================= */

    function buildIdentity(
        data = {}
    ) {

        return safeString(

            data.identity ||

            data.username ||

            data.gmail ||

            data.email ||

            data.phone ||

            data.uid ||

            ""
        );
    }


    /* =========================================================
       AUTHENTICATION — REGISTER
       ========================================================= */

    async function register(
        data = {}
    ) {

        const firstName =
            safeString(
                data.firstName
            );


        const lastName =
            safeString(
                data.lastName
            );


        const name =
            safeString(
                data.name
            ) ||

            [
                firstName,
                lastName
            ]
                .filter(Boolean)
                .join(" ");


        return normalizeResult(

            await request(

                "register",

                {

                    firstName:
                        firstName,

                    lastName:
                        lastName,

                    name:
                        name,

                    username:
                        safeString(
                            data.username
                        ),

                    age:
                        data.age ?? "",

                    gmail:
                        safeString(
                            data.gmail ||
                            data.email
                        ),

                    email:
                        safeString(
                            data.email ||
                            data.gmail
                        ),

                    phone:
                        safeString(
                            data.phone
                        ),

                    password:
                        safeString(
                            data.password
                        ),

                    confirmPassword:
                        safeString(
                            data.confirmPassword
                        ),

                    role:
                        safeString(
                            data.role
                        ) ||
                        "Employee"
                }
            )
        );
    }


    /* =========================================================
       ADMIN REGISTRATION
       ========================================================= */

    async function registerAdmin(
        data = {}
    ) {

        const firstName =
            safeString(
                data.firstName
            );


        const lastName =
            safeString(
                data.lastName
            );


        const name =
            safeString(
                data.name
            ) ||

            [
                firstName,
                lastName
            ]
                .filter(Boolean)
                .join(" ");


        return normalizeResult(

            await request(

                "registerAdmin",

                {

                    firstName:
                        firstName,

                    lastName:
                        lastName,

                    name:
                        name,

                    username:
                        safeString(
                            data.username
                        ),

                    age:
                        data.age ?? "",

                    gmail:
                        safeString(
                            data.gmail ||
                            data.email
                        ),

                    email:
                        safeString(
                            data.email ||
                            data.gmail
                        ),

                    phone:
                        safeString(
                            data.phone
                        ),

                    password:
                        safeString(
                            data.password
                        ),

                    confirmPassword:
                        safeString(
                            data.confirmPassword
                        ),

                    role:
                        "Admin",

                    adminRegistrationKey:
                        safeString(
                            data.adminRegistrationKey
                        )
                }
            )
        );
    }


    /* =========================================================
       LOGIN
       ========================================================= */

    async function login(
        data = {}
    ) {

        return normalizeResult(

            await request(

                "login",

                {

                    identity:
                        buildIdentity(
                            data
                        ),

                    username:
                        safeString(
                            data.username
                        ),

                    email:
                        safeString(
                            data.email
                        ),

                    gmail:
                        safeString(
                            data.gmail ||
                            data.email
                        ),

                    phone:
                        safeString(
                            data.phone
                        ),

                    password:
                        safeString(
                            data.password
                        )
                }
            )
        );
    }


    /* =========================================================
       OTP — VERIFY
       ========================================================= */

    async function verifyOtp(
        data = {}
    ) {

        const channel =
            safeString(

                data.channel ||

                data.otpChannel

            ).toLowerCase() ||
            "email";


        const normalizedChannel =
            channel === "phone"
                ? "phone"
                : "email";


        const payload = {

            uid:
                safeString(
                    data.uid
                ),

            identity:
                buildIdentity(
                    data
                ),

            username:
                safeString(
                    data.username
                ),

            email:
                safeString(
                    data.email
                ),

            gmail:
                safeString(
                    data.gmail ||
                    data.email
                ),

            phone:
                safeString(
                    data.phone
                ),

            channel:
                normalizedChannel,

            otpChannel:
                normalizedChannel,

            /*
             * IMPORTANT:
             *
             * This is the OTP entered manually by the user.
             *
             * It is NOT generated here.
             */

            otp:
                safeString(
                    data.otp
                )
        };


        try {

            const result =
                await request(
                    "verifyOtp",
                    payload
                );


            return normalizeResult(
                result
            );


        } catch (error) {

            /*
             * Business errors should be returned to
             * verify.js so the user remains on verify.html.
             *
             * Examples:
             *
             * OTP_INVALID
             * OTP_EXPIRED
             * OTP_LOCKED
             * ACCOUNT_NOT_FOUND
             * ACCOUNT_DISABLED
             */

            if (
                error?.data &&
                error?.isTransportError !== true
            ) {

                return normalizeResult(
                    error.data
                );
            }


            throw error;
        }
    }


    /* =========================================================
       OTP — PREPARE
       ========================================================= */

    async function prepareOtp(
        data = {}
    ) {

        const channel =
            safeString(

                data.channel ||

                data.otpChannel

            ).toLowerCase() ||
            "email";


        const normalizedChannel =
            channel === "phone"
                ? "phone"
                : "email";


        const payload = {

            uid:
                safeString(
                    data.uid
                ),

            identity:
                buildIdentity(
                    data
                ),

            username:
                safeString(
                    data.username
                ),

            email:
                safeString(
                    data.email
                ),

            gmail:
                safeString(
                    data.gmail ||
                    data.email
                ),

            phone:
                safeString(
                    data.phone
                ),

            channel:
                normalizedChannel,

            otpChannel:
                normalizedChannel
        };


        try {

            const result =
                await request(

                    "prepareOtp",

                    payload
                );


            return normalizeResult(
                result
            );


        } catch (error) {

            /*
             * IMPORTANT:
             *
             * Business errors must be returned instead of
             * being mistaken for a connection failure.
             */

            if (
                error?.data &&
                error?.isTransportError !== true
            ) {

                return normalizeResult(
                    error.data
                );
            }


            const code =
                getServerErrorCode(
                    error
                );


            const message =
                String(

                    getServerErrorMessage(
                        error
                    ) ||

                    error?.message ||

                    ""

                ).toLowerCase();


            /*
             * Compatibility with older Apps Script versions
             * which may not have prepareOtp.
             *
             * Only use resendOtp when the backend genuinely
             * reports an unknown/unsupported action.
             */

            const missingAction =
                code ===
                    "UNKNOWN_ACTION" ||

                message.includes(
                    "unknown action"
                ) ||

                message.includes(
                    "unsupported action"
                ) ||

                message.includes(
                    "action not found"
                );


            if (
                missingAction
            ) {

                try {

                    const fallback =
                        await request(

                            "resendOtp",

                            payload
                        );


                    return normalizeResult(
                        fallback
                    );


                } catch (fallbackError) {

                    if (
                        fallbackError?.data &&
                        fallbackError?.isTransportError !== true
                    ) {

                        return normalizeResult(
                            fallbackError.data
                        );
                    }


                    throw fallbackError;
                }
            }


            throw error;
        }
    }


    /* =========================================================
       OTP — RESEND
       ========================================================= */

    async function resendOtp(
        data = {}
    ) {

        const channel =
            safeString(

                data.channel ||

                data.otpChannel

            ).toLowerCase() ||
            "email";


        const normalizedChannel =
            channel === "phone"
                ? "phone"
                : "email";


        return normalizeResult(

            await request(

                "resendOtp",

                {

                    uid:
                        safeString(
                            data.uid
                        ),

                    identity:
                        buildIdentity(
                            data
                        ),

                    username:
                        safeString(
                            data.username
                        ),

                    email:
                        safeString(
                            data.email
                        ),

                    gmail:
                        safeString(
                            data.gmail ||
                            data.email
                        ),

                    phone:
                        safeString(
                            data.phone
                        ),

                    channel:
                        normalizedChannel,

                    otpChannel:
                        normalizedChannel
                }
            )
        );
    }


    /* =========================================================
       OTP — REQUEST
       ========================================================= */

    async function requestOtp(
        data = {}
    ) {

        return prepareOtp(
            data
        );
    }


    /* =========================================================
       OTP — UPDATE
       ========================================================= */

    async function updateOtp(
        data = {}
    ) {

        return resendOtp(
            data
        );
    }


    /* =========================================================
       SESSION
       ========================================================= */

    async function session(
        data = {}
    ) {

        return normalizeResult(

            await request(

                "session",

                {

                    token:
                        safeString(
                            data.token
                        ) ||

                        localStorage.getItem(
                            "STOCKFLOW_TOKEN"
                        ) ||

                        ""
                }
            )
        );
    }


    /* =========================================================
       REQUIRE SESSION
       ========================================================= */

    async function requireSession(
        data = {}
    ) {

        return normalizeResult(

            await request(

                "requireSession",

                {

                    token:
                        safeString(
                            data.token
                        ) ||

                        localStorage.getItem(
                            "STOCKFLOW_TOKEN"
                        ) ||

                        ""
                }
            )
        );
    }


    /* =========================================================
       LOGOUT
       ========================================================= */

    async function logout(
        data = {}
    ) {

        return normalizeResult(

            await request(

                "logout",

                {

                    token:
                        safeString(
                            data.token
                        ) ||

                        localStorage.getItem(
                            "STOCKFLOW_TOKEN"
                        ) ||

                        ""
                }
            )
        );
    }


    /* =========================================================
       GET USER
       ========================================================= */

    async function getUser(
        identity
    ) {

        const data =
            typeof identity === "object" &&
            identity !== null

                ? identity

                : {
                    identity:
                        safeString(
                            identity
                        )
                };


        const payload = {

            uid:
                safeString(
                    data.uid
                ),

            identity:
                buildIdentity(
                    data
                ),

            username:
                safeString(
                    data.username
                ),

            email:
                safeString(
                    data.email
                ),

            gmail:
                safeString(
                    data.gmail ||
                    data.email
                ),

            phone:
                safeString(
                    data.phone
                )
        };


        return normalizeResult(

            await request(

                "getUser",

                payload
            )
        );
    }


    /* =========================================================
       LIST USERS
       ========================================================= */

    async function listUsers(
        data = {}
    ) {

        return normalizeResult(

            await request(

                "listUsers",

                {

                    token:
                        safeString(
                            data.token
                        ) ||

                        localStorage.getItem(
                            "STOCKFLOW_TOKEN"
                        ) ||

                        ""
                }
            )
        );
    }


    /* =========================================================
       UPDATE STATUS
       ========================================================= */

    async function updateStatus(
        username,
        status,
        token = ""
    ) {

        if (
            typeof username ===
            "object"
        ) {

            const data =
                username;


            return normalizeResult(

                await request(

                    "updateStatus",

                    {

                        username:
                            safeString(
                                data.username
                            ),

                        status:
                            safeString(
                                data.status
                            ),

                        token:
                            safeString(
                                data.token
                            ) ||

                            localStorage.getItem(
                                "STOCKFLOW_TOKEN"
                            ) ||

                            ""
                    }
                )
            );
        }


        return normalizeResult(

            await request(

                "updateStatus",

                {

                    username:
                        safeString(
                            username
                        ),

                    status:
                        safeString(
                            status
                        ),

                    token:
                        safeString(
                            token
                        ) ||

                        localStorage.getItem(
                            "STOCKFLOW_TOKEN"
                        ) ||

                        ""
                }
            )
        );
    }


    /* =========================================================
       PASSWORD RECOVERY
       ========================================================= */

    async function forgotPassword(
        data = {}
    ) {

        return normalizeResult(

            await request(

                "forgotPassword",

                {

                    identity:
                        buildIdentity(
                            data
                        ),

                    email:
                        safeString(
                            data.email
                        ),

                    gmail:
                        safeString(
                            data.gmail ||
                            data.email
                        ),

                    phone:
                        safeString(
                            data.phone
                        ),

                    channel:
                        safeString(
                            data.channel ||
                            data.otpChannel
                        ) ||

                        "email",

                    otpChannel:
                        safeString(
                            data.otpChannel ||
                            data.channel
                        ) ||

                        "email"
                }
            )
        );
    }


    /* =========================================================
       VERIFY RECOVERY OTP
       ========================================================= */

    async function verifyRecoveryOtp(
        data = {}
    ) {

        return normalizeResult(

            await request(

                "verifyRecoveryOtp",

                {

                    identity:
                        buildIdentity(
                            data
                        ),

                    uid:
                        safeString(
                            data.uid
                        ),

                    username:
                        safeString(
                            data.username
                        ),

                    email:
                        safeString(
                            data.email
                        ),

                    gmail:
                        safeString(
                            data.gmail ||
                            data.email
                        ),

                    phone:
                        safeString(
                            data.phone
                        ),

                    otp:
                        safeString(
                            data.otp
                        )
                }
            )
        );
    }


    /* =========================================================
       RESET PASSWORD
       ========================================================= */

    async function resetPassword(
        data = {}
    ) {

        return normalizeResult(

            await request(

                "resetPassword",

                {

                    identity:
                        buildIdentity(
                            data
                        ),

                    uid:
                        safeString(
                            data.uid
                        ),

                    token:
                        safeString(
                            data.token ||
                            data.recoveryToken
                        ),

                    recoveryToken:
                        safeString(
                            data.recoveryToken ||
                            data.token
                        ),

                    password:
                        safeString(
                            data.password ||
                            data.newPassword
                        ),

                    newPassword:
                        safeString(
                            data.newPassword ||
                            data.password
                        ),

                    confirmPassword:
                        safeString(
                            data.confirmPassword
                        )
                }
            )
        );
    }


    /* =========================================================
       ACTIVITY
       ========================================================= */

    async function listActivity(
        data = {}
    ) {

        return normalizeResult(

            await request(

                "listActivity",

                {

                    token:
                        safeString(
                            data.token
                        ) ||

                        localStorage.getItem(
                            "STOCKFLOW_TOKEN"
                        ) ||

                        "",

                    limit:
                        Number(
                            data.limit
                        ) ||
                        100
                }
            )
        );
    }


    /* =========================================================
       GENERIC INVENTORY
       ========================================================= */

    async function inventory(
        action,
        data = {}
    ) {

        if (!action) {

            throw new StockFlowAPIError(
                "Inventory action is required.",
                "MISSING_INVENTORY_ACTION"
            );
        }


        const token =
            safeString(
                data.token
            ) ||

            localStorage.getItem(
                "STOCKFLOW_TOKEN"
            ) ||

            "";


        return normalizeResult(

            await request(

                action,

                {

                    ...data,

                    token
                }
            )
        );
    }


    /* =========================================================
       PRODUCTS
       ========================================================= */

    async function listProducts(
        data = {}
    ) {

        return inventory(
            "listProducts",
            data
        );
    }


    async function createProduct(
        data = {}
    ) {

        return inventory(
            "createProduct",
            data
        );
    }


    async function updateProduct(
        data = {}
    ) {

        return inventory(
            "updateProduct",
            data
        );
    }


    async function deleteProduct(
        data = {}
    ) {

        return inventory(
            "deleteProduct",
            data
        );
    }


    /* =========================================================
       CATEGORIES
       ========================================================= */

    async function listCategories(
        data = {}
    ) {

        return inventory(
            "listCategories",
            data
        );
    }


    async function createCategory(
        data = {}
    ) {

        return inventory(
            "createCategory",
            data
        );
    }


    async function updateCategory(
        data = {}
    ) {

        return inventory(
            "updateCategory",
            data
        );
    }


    async function deleteCategory(
        data = {}
    ) {

        return inventory(
            "deleteCategory",
            data
        );
    }


    /* =========================================================
       SUPPLIERS
       ========================================================= */

    async function listSuppliers(
        data = {}
    ) {

        return inventory(
            "listSuppliers",
            data
        );
    }


    async function createSupplier(
        data = {}
    ) {

        return inventory(
            "createSupplier",
            data
        );
    }


    async function updateSupplier(
        data = {}
    ) {

        return inventory(
            "updateSupplier",
            data
        );
    }


    async function deleteSupplier(
        data = {}
    ) {

        return inventory(
            "deleteSupplier",
            data
        );
    }


    /* =========================================================
       STOCK IN
       ========================================================= */

    async function listStockIn(
        data = {}
    ) {

        return inventory(
            "listStockIn",
            data
        );
    }


    async function createStockIn(
        data = {}
    ) {

        return inventory(
            "createStockIn",
            data
        );
    }


    /* =========================================================
       STOCK OUT
       ========================================================= */

    async function listStockOut(
        data = {}
    ) {

        return inventory(
            "listStockOut",
            data
        );
    }


    async function createStockOut(
        data = {}
    ) {

        return inventory(
            "createStockOut",
            data
        );
    }


    /* =========================================================
       TRANSACTIONS
       ========================================================= */

    async function listTransactions(
        data = {}
    ) {

        return inventory(
            "listTransactions",
            data
        );
    }


    /* =========================================================
       DASHBOARD
       ========================================================= */

    async function dashboard(
        data = {}
    ) {

        return inventory(
            "dashboard",
            data
        );
    }


    /* =========================================================
       HEALTH CHECK
       ========================================================= */

    async function health() {

        validateApiUrl();


        const controller =
            new AbortController();


        const timeout =
            setTimeout(

                () => {

                    controller.abort();

                },

                REQUEST_TIMEOUT
            );


        try {

            const response =
                await fetch(

                    API_URL,

                    {

                        method:
                            "GET",

                        redirect:
                            "follow",

                        signal:
                            controller.signal
                    }
                );


            const text =
                await response.text();


            if (
                !text ||
                !text.trim()
            ) {

                return {

                    success:
                        response.ok,

                    code:
                        response.ok
                            ? "EMPTY_RESPONSE"
                            : "HTTP_ERROR",

                    message:
                        response.ok

                            ? "Empty health response."

                            : `Health check returned HTTP ${response.status}.`
                };
            }


            try {

                return JSON.parse(
                    text
                );

            } catch (_) {

                return {

                    success:
                        response.ok,

                    code:
                        response.ok
                            ? "INVALID_JSON"
                            : "HTTP_ERROR",

                    message:
                        response.ok

                            ? "Health check returned invalid JSON."

                            : `Health check returned HTTP ${response.status}.`,

                    raw:
                        text
                };
            }


        } catch (error) {

            if (
                error?.name ===
                "AbortError"
            ) {

                throw new StockFlowAPIError(

                    "Unable to reach the StockFlow backend because the health check timed out.",

                    "TIMEOUT",

                    {

                        originalError:
                            error,

                        isTransportError:
                            true
                    }
                );
            }


            throw new StockFlowAPIError(

                "Unable to reach the StockFlow backend.",

                "HEALTH_CHECK_FAILED",

                {

                    originalError:
                        error,

                    isTransportError:
                        true
                }
            );

        } finally {

            clearTimeout(
                timeout
            );
        }
    }


    /* =========================================================
       PUBLIC API
       ========================================================= */

    const StockFlowAPI = {

        /* Core */
        request,
        health,

        /* Authentication */
        register,
        registerAdmin,
        login,

        /* OTP */
        verifyOtp,
        prepareOtp,
        resendOtp,
        requestOtp:
            prepareOtp,
        updateOtp,

        /* Session */
        session,
        requireSession,
        logout,

        /* Users */
        getUser,
        listUsers,
        updateStatus,

        /* Password recovery */
        forgotPassword,
        verifyRecoveryOtp,
        resetPassword,

        /* Activity */
        listActivity,

        /* Generic inventory */
        inventory,

        /* Products */
        listProducts,
        createProduct,
        updateProduct,
        deleteProduct,

        /* Categories */
        listCategories,
        createCategory,
        updateCategory,
        deleteCategory,

        /* Suppliers */
        listSuppliers,
        createSupplier,
        updateSupplier,
        deleteSupplier,

        /* Stock */
        listStockIn,
        createStockIn,

        listStockOut,
        createStockOut,

        /* Transactions */
        listTransactions,

        /* Dashboard */
        dashboard,

        /* Error class */
        StockFlowAPIError
    };


    /* =========================================================
       GLOBAL EXPORT
       ========================================================= */

    window.StockFlowAPI =
        StockFlowAPI;


    /*
     * Legacy compatibility.
     */

    window.API =
        StockFlowAPI;


    /* =========================================================
       DEBUG
       ========================================================= */

    console.log(
        "%cStockFlow API loaded",
        "font-weight:bold;"
    );


    console.log(
        "StockFlow API endpoint:",
        API_URL ||
        "(not configured)"
    );


    console.log(
        "StockFlow API methods:",
        Object.keys(
            StockFlowAPI
        )
    );


})(window);
