const SF=window.STOCKFLOW_CONFIG||{};
const DEMO_USER={fullName:"Admin User",username:"admin",age:25,email:"admin@stockflow.local",phone:"09123456789",password:"StockFlow@123",role:"Admin",verified:true};
const fbUrl=p=>`${(SF.FIREBASE_DATABASE_URL||"").replace(/\/$/,"")}/${String(p).replace(/^\//,"")}.json`;
async function fbGet(p){const r=await fetch(fbUrl(p));if(!r.ok)throw Error(`Firebase GET ${r.status}`);return r.json()}
async function fbPut(p,d){const r=await fetch(fbUrl(p),{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(d)});if(!r.ok)throw Error(`Firebase PUT ${r.status}`);return r.json()}
async function sheetPost(d){if(!SF.ENABLE_GOOGLE_SHEET_SYNC||!SF.GOOGLE_SHEET_API_URL)return{skipped:true};const r=await fetch(SF.GOOGLE_SHEET_API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(d)});return r.json()}
function setMessage(e,t,x){if(e){e.className=`form-message show ${t}`;e.textContent=x}}
function clearErrors(f){f.querySelectorAll(".field-error").forEach(x=>x.textContent="");f.querySelectorAll("input").forEach(x=>x.classList.remove("invalid"))}
function error(i,m){i.classList.add("invalid");const e=i.closest(".field")?.querySelector(".field-error");if(e)e.textContent=m}
function validEmail(v){return/^\S+@\S+\.\S+$/.test(v)}
function validPhone(v){return/^(09\d{9}|\+639\d{9})$/.test(v.replace(/[\s-]/g,""))}
function score(v){return(v.length>=8?1:0)+(/[A-Z]/.test(v)?1:0)+(/[a-z]/.test(v)?1:0)+(\d/.test(v)?1:0)+(/[^A-Za-z0-9]/.test(v)?1:0)}
document.querySelectorAll(".password-toggle").forEach(b=>b.addEventListener("click",()=>{const i=document.getElementById(b.dataset.target),show=i.type==="password";i.type=show?"text":"password";b.textContent=show?"Hide":"Show"}));
const lf=document.getElementById("loginForm");
if(lf)lf.addEventListener("submit",async e=>{e.preventDefault();clearErrors(lf);const id=document.getElementById("loginIdentity"),pw=document.getElementById("loginPassword"),msg=document.getElementById("loginMessage");if(!id.value.trim()){error(id,"Username or email is required.");return}if(!pw.value){error(pw,"Password is required.");return}try{let found=null;if(SF.ENABLE_GOOGLE_SHEET_SYNC&&SF.GOOGLE_SHEET_API_URL){const r=await sheetPost({action:"login",identity:id.value.trim(),password:pw.value});if(!r.success){setMessage(msg,"error",r.message||"Invalid login.");return}if(!r.verified){setMessage(msg,"error","Your account is not verified yet.");return}found={username:r.user.username,role:r.user.accountStatus,fullName:r.user.name,verified:true}}else{const users=await fbGet("users");if(users)for(const[uid,u]of Object.entries(users))if((u.username===id.value.trim()||u.email===id.value.trim())&&u.password===pw.value){found={...u,uid};break}if(!found&&id.value.trim()==="admin"&&pw.value==="StockFlow@123")found=DEMO_USER;if(!found){setMessage(msg,"error","Invalid username/email or password.");return}if(found.verified===false){setMessage(msg,"error","Your account is not verified yet.");return}found={username:found.username,role:found.role||"Employee",fullName:found.fullName,verified:true}}sessionStorage.setItem("stockflow_session",JSON.stringify(found));location.href="dashboard.html"}catch(err){setMessage(msg,"error","Database connection failed. Check Firebase rules or Google Apps Script URL.")}});
const rf=document.getElementById("registerForm");
if(rf){const pw=document.getElementById("registerPassword"),bar=document.getElementById("passwordBar"),hint=document.getElementById("passwordHint");pw.addEventListener("input",()=>{const s=score(pw.value);bar.style.width=s*20+"%";hint.textContent=s<3?"Weak password":s<5?"Medium password":"Strong password"});rf.addEventListener("submit",async e=>{e.preventDefault();clearErrors(rf);const n=document.getElementById("fullName"),u=document.getElementById("username"),a=document.getElementById("age"),g=document.getElementById("email"),ph=document.getElementById("phone"),cp=document.getElementById("confirmPassword"),terms=document.getElementById("terms"),msg=document.getElementById("registerMessage");let ok=true;if(n.value.trim().length<2){error(n,"Enter your full name.");ok=false}if(!/^[A-Za-z0-9_.-]{4,20}$/.test(u.value.trim())){error(u,"Use 4–20 valid username characters.");ok=false}if(+a.value<18||+a.value>100){error(a,"Age must be 18–100.");ok=false}if(!validEmail(g.value.trim())){error(g,"Enter a valid email.");ok=false}if(!validPhone(ph.value.trim())){error(ph,"Use 09XXXXXXXXX or +639XXXXXXXXX.");ok=false}if(score(pw.value)<5){error(pw,"Use 8+ chars, uppercase, lowercase, number and symbol.");ok=false}if(cp.value!==pw.value){error(cp,"Passwords do not match.");ok=false}if(!terms.checked){setMessage(msg,"error","Please agree to the Terms and Conditions.");ok=false}if(!ok)return;try{const uid=`sf_${Date.now()}_${Math.random().toString(36).slice(2,8)}`,user={fullName:n.value.trim(),username:u.value.trim(),age:+a.value,email:g.value.trim(),phone:ph.value.trim(),password:pw.value,role:"Employee",verified:false,createdAt:new Date().toISOString()};if(SF.ENABLE_GOOGLE_SHEET_SYNC&&SF.GOOGLE_SHEET_API_URL){const r=await sheetPost({action:"register",name:user.fullName,username:user.username,password:user.password,age:user.age,gmail:user.email,phone:user.phone});if(!r.success){setMessage(msg,"error",r.message||"Registration failed.");return}sessionStorage.setItem("stockflow_demo_otp",r.otp||"123456")}else{await fbPut(`users/${uid}`,user);sessionStorage.setItem("stockflow_demo_otp","123456")}sessionStorage.setItem("stockflow_pending_user",JSON.stringify({username:user.username,email:user.email,phone:user.phone,uid}));location.href="verify.html"}catch(err){setMessage(msg,"error","Registration could not be saved. Check Firebase connection/rules.")}})}
const vf=document.getElementById("verifyForm");
if(vf){const ins=[...document.querySelectorAll("#otpInputs input")],pending=JSON.parse(sessionStorage.getItem("stockflow_pending_user")||"null"),dest=document.getElementById("verifyDestination"),msg=document.getElementById("verifyMessage");if(pending)dest.textContent=pending.email;ins.forEach((i,n)=>{i.addEventListener("input",()=>{i.value=i.value.replace(/\D/g,"");if(i.value&&n<ins.length-1)ins[n+1].focus()});i.addEventListener("keydown",e=>{if(e.key==="Backspace"&&!i.value&&n)ins[n-1].focus()})});vf.addEventListener("submit",async e=>{e.preventDefault();const otp=ins.map(i=>i.value).join(""),expected=sessionStorage.getItem("stockflow_demo_otp")||"123456";if(otp!==expected){setMessage(msg,"error","Incorrect verification code.");return}try{if(SF.ENABLE_GOOGLE_SHEET_SYNC&&SF.GOOGLE_SHEET_API_URL){const r=await sheetPost({action:"verifyOtp",identity:pending.username,otp});if(!r.success){setMessage(msg,"error",r.message||"Verification failed.");return}}else if(pending?.uid){const u=await fbGet(`users/${pending.uid}`);if(u){u.verified=true;await fbPut(`users/${pending.uid}`,u)}}sessionStorage.removeItem("stockflow_pending_user");sessionStorage.removeItem("stockflow_demo_otp");setMessage(msg,"success","Account verified. Redirecting to login...");setTimeout(()=>location.href="login.html",900)}catch(err){setMessage(msg,"error","Verification failed.")}});let sec=60,rs=document.getElementById("resendOtp"),cd=document.getElementById("countdown");const timer=setInterval(()=>{sec--;if(cd)cd.textContent=sec;if(sec<=0){clearInterval(timer);rs.disabled=false;rs.textContent="Resend code"}},1000);rs?.addEventListener("click",async()=>{try{if(SF.ENABLE_GOOGLE_SHEET_SYNC&&SF.GOOGLE_SHEET_API_URL){const r=await sheetPost({action:"updateOtp",identity:pending.username});if(r.success)sessionStorage.setItem("stockflow_demo_otp",r.otp)}else sessionStorage.setItem("stockflow_demo_otp",String(Math.floor(100000+Math.random()*900000)));setMessage(msg,"success","A new development OTP was generated.")}catch{setMessage(msg,"error","Unable to generate OTP.")}rs.disabled=true})}
const ff=document.getElementById("forgotForm");if(ff)ff.addEventListener("submit",e=>{e.preventDefault();clearErrors(ff);const i=document.getElementById("recoveryContact"),m=document.getElementById("forgotMessage"),v=i.value.trim();if(!v){error(i,"Enter email or phone.");return}if(v.includes("@")&&!validEmail(v)){error(i,"Enter a valid email.");return}if(!v.includes("@")&&!validPhone(v)){error(i,"Enter a valid phone number.");return}setMessage(m,"success","Recovery request accepted in this prototype. Connect Firebase Authentication for the production password-reset flow.")});
