/* =========================================================
   STOCKFLOW - GOOGLE APPS SCRIPT BACKEND
   =========================================================

   Main responsibilities:

   - Employee registration
   - Admin registration
   - Login
   - OTP generation
   - OTP storage in Google Sheets
   - OTP synchronization with Firebase
   - Email OTP
   - Phone OTP through Twilio
   - OTP verification
   - Account status management
   - Password recovery
   - Recovery OTP verification
   - Server-side recovery token
   - Password reset
   - User lookup
   - API status endpoint

   IMPORTANT:

   OTP IS GENERATED ONLY HERE ON THE SERVER.

   Frontend JavaScript must NEVER generate the OTP.

   DEMO_MODE = false:
   OTP is generated and stored only on the server.
   The OTP is never returned to the frontend.

   The verification page requires the user to manually enter
   the code received through the configured delivery channel.
   ========================================================= */


/* =========================================================
   CONFIGURATION
   ========================================================= */

const SHEET_ID =
    "1w3j0sV9rDiBvS4cpHU31iGb4KIeyUPoALZf5vLH2ivY";


const SHEET_NAME =
    "USER";


const APP_NAME =
    "StockFlow";


/*
 * Public email branding.
 * APP_NAME remains the internal API/system name.
 */
const EMAIL_SENDER_NAME =
    "Creator Bitos";


const EMAIL_BRAND_NAME =
    "Bitos' Phone Accessories Inventory";


const EMAIL_FOOTER =
    "— By Creator Bitos";


const FIREBASE_URL =
    "https://midtermexamproject-default-rtdb.firebaseio.com/";


/*
 * OTP security mode.
 *
 * OTP is always generated by Code.gs, stored in Sheets/Firebase,
 * and delivered through the selected provider.
 * The OTP is never returned to frontend JavaScript.
 */

const DEMO_MODE =
    false;


/* =========================================================
   OTP SETTINGS
   ========================================================= */

const OTP_LENGTH =
    6;


const OTP_EXPIRATION_MINUTES =
    10;


const OTP_MAX_ATTEMPTS =
    4;


const OTP_LOCK_MINUTES =
    30;


const OTP_RESEND_COOLDOWN_SECONDS =
    120;


/* =========================================================
   USER TABLE HEADERS
   ========================================================= */

const HEADERS = [

    "UID",
    "NAME",
    "USERNAME",
    "PASSWORD",
    "AGE",
    "ACCOUNT_S",
    "GMAIL",
    "PHONE NO.",
    "ROLE",
    "VERIFIED",
    "OTP",
    "OTP EXPIRES",
    "OTP ATTEMPTS",
    "OTP LOCK UNTIL",
    "OTP CHANNEL",
    "CREATED AT",
    "VERIFIED AT",
    "LAST OTP SENT",
    "LAST LOGIN",
    "LAST EMAIL OTP SENT",
    "LAST PHONE OTP SENT"

];


/* =========================================================
   GENERAL HELPERS
   ========================================================= */

function safeString(value) {

    return String(
        value === null ||
        value === undefined
            ? ""
            : value
    ).trim();

}


function normalizeEmail(value) {

    return safeString(
        value
    ).toLowerCase();

}


function normalizeUsername(value) {

    return safeString(
        value
    ).toLowerCase();

}


function normalizePhone(value) {

    let phone =
        safeString(value)
            .replace(/\s+/g, "");


    if (
        phone.indexOf("+63") === 0
    ) {

        phone =
            "0" +
            phone.substring(3);

    }


    if (
        phone.indexOf("63") === 0 &&
        phone.length === 12
    ) {

        phone =
            "0" +
            phone.substring(2);

    }


    return phone;

}


function normalizeChannel(value) {

    const channel =
        safeString(value)
            .toLowerCase();


    if (
        channel === "phone" ||
        channel === "sms"
    ) {

        return "phone";

    }


    if (
        channel === "both"
    ) {

        return "both";

    }


    return "email";

}


function normalizeStatus(value) {

    const status =
        safeString(value)
            .toUpperCase();


    if (
        status === "VERIFIED"
    ) {

        return "VERIFIED";

    }


    if (
        status === "SUSPENDED"
    ) {

        return "SUSPENDED";

    }


    if (
        status === "DISABLED"
    ) {

        return "DISABLED";

    }


    if (
        status === "BLOCKED"
    ) {

        return "BLOCKED";

    }


    return "PENDING";

}


function normalizeRole(value) {

    const role =
        safeString(value)
            .toLowerCase();


    if (
        role === "admin" ||
        role === "administrator"
    ) {

        return "Admin";

    }


    if (
        role === "manager"
    ) {

        return "Manager";

    }


    return "Employee";

}


/* =========================================================
   DATE HELPERS
   ========================================================= */

function now() {

    return new Date();

}


function addMinutes(
    date,
    minutes
) {

    return new Date(
        date.getTime() +
        Number(minutes) * 60 * 1000
    );

}


function addSeconds(
    date,
    seconds
) {

    return new Date(
        date.getTime() +
        Number(seconds) * 1000
    );

}


function parseDate(value) {

    if (!value) {
        return null;
    }


    if (
        Object.prototype.toString.call(value) ===
        "[object Date]"
    ) {

        return isNaN(
            value.getTime()
        )
            ? null
            : value;

    }


    const date =
        new Date(value);


    if (
        isNaN(
            date.getTime()
        )
    ) {

        return null;

    }


    return date;

}


/* =========================================================
   BOOLEAN HELPERS
   ========================================================= */

function toBoolean(value) {

    if (
        value === true
    ) {

        return true;

    }


    const text =
        safeString(value)
            .toLowerCase();


    return (
        text === "true" ||
        text === "yes" ||
        text === "1"
    );

}


/* =========================================================
   UID
   ========================================================= */

function generateUID() {

    return (
        "SF-" +
        Utilities.getUuid()
            .replace(/-/g, "")
            .substring(0, 16)
            .toUpperCase()
    );

}


/* =========================================================
   OTP GENERATION
   ========================================================= */

function generateOTP() {

    /*
     * IMPORTANT:
     *
     * OTP generation exists ONLY in Code.gs.
     *
     * verify.js and recovery.js never generate OTPs.
     */

    let otp = "";


    for (
        let i = 0;
        i < OTP_LENGTH;
        i++
    ) {

        otp += Math.floor(
            Math.random() * 10
        );

    }


    return otp;

}


/* =========================================================
   SHEET
   ========================================================= */

function getSheet() {

    const spreadsheet =
        SpreadsheetApp.openById(
            SHEET_ID
        );


    let sheet =
        spreadsheet.getSheetByName(
            SHEET_NAME
        );


    if (!sheet) {

        sheet =
            spreadsheet.insertSheet(
                SHEET_NAME
            );

    }


    ensureHeaders(
        sheet
    );


    return sheet;

}


function ensureHeaders(
    sheet
) {

    const required =
        HEADERS.length;


    const currentColumns =
        Math.max(
            sheet.getMaxColumns(),
            required
        );


    if (
        sheet.getMaxColumns() <
        required
    ) {

        sheet.insertColumnsAfter(
            sheet.getMaxColumns(),
            required -
            sheet.getMaxColumns()
        );

    }


    const current =
        sheet
            .getRange(
                1,
                1,
                1,
                required
            )
            .getValues()[0];


    let needsUpdate =
        false;


    for (
        let i = 0;
        i < required;
        i++
    ) {

        if (
            safeString(
                current[i]
            ) !==
            HEADERS[i]
        ) {

            needsUpdate =
                true;

            break;

        }

    }


    if (needsUpdate) {

        sheet
            .getRange(
                1,
                1,
                1,
                required
            )
            .setValues([
                HEADERS
            ]);

    }

}


function getRows() {

    const sheet =
        getSheet();


    const lastRow =
        sheet.getLastRow();


    if (
        lastRow < 2
    ) {

        return [];

    }


    const values =
        sheet
            .getRange(
                2,
                1,
                lastRow - 1,
                HEADERS.length
            )
            .getValues();


    return values.map(
        (
            row,
            index
        ) => {

            const user = {};


            HEADERS.forEach(
                (
                    header,
                    column
                ) => {

                    user[header] =
                        row[column];

                }
            );


            user._row =
                index + 2;


            return user;

        }
    );

}


/* =========================================================
   USER OBJECT
   ========================================================= */

function userToResponse(
    user
) {

    if (!user) {

        return null;

    }


    return {

        uid:
            safeString(
                user["UID"]
            ),

        name:
            safeString(
                user["NAME"]
            ),

        username:
            safeString(
                user["USERNAME"]
            ),

        age:
            user["AGE"],

        accountStatus:
            normalizeStatus(
                user["ACCOUNT_S"]
            ),

        gmail:
            normalizeEmail(
                user["GMAIL"]
            ),

        email:
            normalizeEmail(
                user["GMAIL"]
            ),

        phone:
            normalizePhone(
                user["PHONE NO."]
            ),

        role:
            normalizeRole(
                user["ROLE"]
            ),

        verified:
            toBoolean(
                user["VERIFIED"]
            ),

        createdAt:
            user["CREATED AT"] || "",

        verifiedAt:
            user["VERIFIED AT"] || "",

        lastLogin:
            user["LAST LOGIN"] || ""

    };

}


/* =========================================================
   USER LOOKUP
   ========================================================= */

function findUser(
    identity
) {

    const value =
        safeString(identity);


    if (!value) {

        return null;

    }


    const normalized =
        value.toLowerCase();


    const phone =
        normalizePhone(
            value
        );


    const rows =
        getRows();


    for (
        let i = 0;
        i < rows.length;
        i++
    ) {

        const user =
            rows[i];


        const uid =
            safeString(
                user["UID"]
            )
                .toLowerCase();


        const username =
            normalizeUsername(
                user["USERNAME"]
            );


        const gmail =
            normalizeEmail(
                user["GMAIL"]
            );


        const userPhone =
            normalizePhone(
                user["PHONE NO."]
            );


        if (
            uid === normalized ||
            username === normalized ||
            gmail === normalized ||
            (
                phone &&
                userPhone &&
                phone === userPhone
            )
        ) {

            return user;

        }

    }


    return null;

}


function findUserByUid(
    uid
) {

    const value =
        safeString(uid);


    if (!value) {
        return null;
    }


    const rows =
        getRows();


    for (
        let i = 0;
        i < rows.length;
        i++
    ) {

        if (
            safeString(
                rows[i]["UID"]
            ) === value
        ) {

            return rows[i];

        }

    }


    return null;

}


/* =========================================================
   DUPLICATE CHECK
   ========================================================= */

function findDuplicateUser(
    username,
    gmail,
    phone
) {

    const normalizedUsername =
        normalizeUsername(
            username
        );


    const normalizedGmail =
        normalizeEmail(
            gmail
        );


    const normalizedPhone =
        normalizePhone(
            phone
        );


    const rows =
        getRows();


    for (
        let i = 0;
        i < rows.length;
        i++
    ) {

        const user =
            rows[i];


        if (
            normalizeUsername(
                user["USERNAME"]
            ) ===
            normalizedUsername
        ) {

            return {
                user,
                code:
                    "USERNAME_EXISTS"
            };

        }


        if (
            normalizeEmail(
                user["GMAIL"]
            ) ===
            normalizedGmail
        ) {

            return {
                user,
                code:
                    "EMAIL_EXISTS"
            };

        }


        if (
            normalizePhone(
                user["PHONE NO."]
            ) ===
            normalizedPhone
        ) {

            return {
                user,
                code:
                    "PHONE_EXISTS"
            };

        }

    }


    return null;

}


/* =========================================================
   VALIDATION
   ========================================================= */

function validateRegistrationData(
    data
) {

    const firstName =
        safeString(
            data.firstName
        );


    const lastName =
        safeString(
            data.lastName
        );


    const name =
        safeString(
            data.name ||
            (
                firstName +
                " " +
                lastName
            )
        );


    const username =
        normalizeUsername(
            data.username
        );


    const age =
        Number(
            data.age
        );


    const gmail =
        normalizeEmail(
            data.gmail ||
            data.email
        );


    const phone =
        normalizePhone(
            data.phone
        );


    const password =
        safeString(
            data.password
        );


    if (
        !firstName ||
        firstName.length < 2
    ) {

        return {
            valid: false,
            code:
                "INVALID_FIRST_NAME",
            message:
                "Please enter a valid first name."
        };

    }


    if (
        !lastName ||
        lastName.length < 2
    ) {

        return {
            valid: false,
            code:
                "INVALID_LAST_NAME",
            message:
                "Please enter a valid last name."
        };

    }


    if (
        !username ||
        username.length < 4 ||
        username.length > 30 ||
        !/^[a-zA-Z0-9._]+$/.test(
            username
        )
    ) {

        return {
            valid: false,
            code:
                "INVALID_USERNAME",
            message:
                "Username must be 4–30 characters and may contain only letters, numbers, dots, and underscores."
        };

    }


    if (
        !Number.isInteger(age) ||
        age < 18 ||
        age > 100
    ) {

        return {
            valid: false,
            code:
                "INVALID_AGE",
            message:
                "Age must be between 18 and 100."
        };

    }


    if (
        !/^[^\s@]+@gmail\.com$/i.test(
            gmail
        )
    ) {

        return {
            valid: false,
            code:
                "INVALID_GMAIL",
            message:
                "Please enter a valid Gmail address ending in @gmail.com."
        };

    }


    if (
        !/^09\d{9}$/.test(
            phone
        )
    ) {

        return {
            valid: false,
            code:
                "INVALID_PHONE",
            message:
                "Please enter a valid Philippine mobile number in 09XXXXXXXXX format."
        };

    }


    if (
        password.length < 8
    ) {

        return {
            valid: false,
            code:
                "INVALID_PASSWORD",
            message:
                "Password must be at least 8 characters."
        };

    }


    if (
        !/[A-Z]/.test(
            password
        ) ||
        !/[a-z]/.test(
            password
        ) ||
        !/\d/.test(
            password
        ) ||
        !/[^A-Za-z0-9]/.test(
            password
        )
    ) {

        return {
            valid: false,
            code:
                "INVALID_PASSWORD",
            message:
                "Password must include uppercase, lowercase, number, and special character."
        };

    }


    if (
        data.confirmPassword !==
        undefined &&
        safeString(
            data.confirmPassword
        ) !== password
    ) {

        return {
            valid: false,
            code:
                "PASSWORD_MISMATCH",
            message:
                "Passwords do not match."
        };

    }


    return {

        valid: true,

        data: {

            firstName,
            lastName,
            name,
            username,
            age,
            gmail,
            phone,
            password

        }

    };

}


/* =========================================================
   FIREBASE HELPERS
   ========================================================= */

function firebaseBaseUrl() {

    return FIREBASE_URL.replace(
        /\/+$/,
        ""
    );

}


function firebaseRequest(
    path,
    method,
    payload
) {

    const url =
        firebaseBaseUrl() +
        "/" +
        path.replace(
            /^\/+/,
            ""
        ) +
        ".json";


    const options = {

        method:
            method || "get",

        muteHttpExceptions:
            true,

        contentType:
            "application/json"

    };


    if (
        payload !== undefined &&
        payload !== null
    ) {

        options.payload =
            JSON.stringify(
                payload
            );

    }


    const response =
        UrlFetchApp.fetch(
            url,
            options
        );


    const code =
        response.getResponseCode();


    const text =
        response.getContentText();


    if (
        code < 200 ||
        code >= 300
    ) {

        throw new Error(
            "Firebase request failed: HTTP " +
            code +
            " " +
            text
        );

    }


    if (!text) {
        return null;
    }


    try {

        return JSON.parse(
            text
        );

    } catch (error) {

        return text;

    }

}


function firebaseUserPath(
    uid
) {

    return (
        "stockflow/users/" +
        encodeURIComponent(
            uid
        )
    );

}


/* =========================================================
   FIREBASE USER SAVE
   ========================================================= */

function saveFirebaseUser(
    user
) {

    if (!user) {
        return false;
    }


    const uid =
        safeString(
            user["UID"]
        );


    if (!uid) {
        return false;
    }


    /*
     * IMPORTANT:
     *
     * Password is intentionally NOT written to Firebase.
     *
     * The existing school-project Sheet continues to contain
     * the password because that is part of the existing schema.
     */

    const payload = {

        uid,

        name:
            safeString(
                user["NAME"]
            ),

        username:
            safeString(
                user["USERNAME"]
            ),

        age:
            Number(
                user["AGE"]
            ),

        gmail:
            normalizeEmail(
                user["GMAIL"]
            ),

        phone:
            normalizePhone(
                user["PHONE NO."]
            ),

        role:
            normalizeRole(
                user["ROLE"]
            ),

        verified:
            toBoolean(
                user["VERIFIED"]
            ),

        accountStatus:
            normalizeStatus(
                user["ACCOUNT_S"]
            ),

        createdAt:
            user["CREATED AT"] || "",

        verifiedAt:
            user["VERIFIED AT"] || "",

        lastLogin:
            user["LAST LOGIN"] || ""

    };


    firebaseRequest(
        firebaseUserPath(
            uid
        ),
        "put",
        payload
    );


    return true;

}


/* =========================================================
   FIREBASE OTP
   ========================================================= */

function saveOtpToFirebase(
    user,
    otp,
    channel,
    expiresAt,
    attempts,
    lockUntil
) {

    const uid =
        safeString(
            user["UID"]
        );


    if (!uid) {
        throw new Error(
            "Missing UID for Firebase OTP storage."
        );
    }


    const payload = {

        otp:
            safeString(
                otp
            ),

        channel:
            normalizeChannel(
                channel
            ),

        expiresAt:
            expiresAt
                .toISOString(),

        attempts:
            Number(
                attempts || 0
            ),

        lockUntil:
            lockUntil
                ? lockUntil.toISOString()
                : "",

        updatedAt:
            now().toISOString()

    };


    firebaseRequest(
        firebaseUserPath(
            uid
        ) +
        "/otp",
        "put",
        payload
    );


    return true;

}


function updateFirebaseOtpAttempts(
    user,
    attempts,
    lockUntil
) {

    const uid =
        safeString(
            user["UID"]
        );


    if (!uid) {
        return false;
    }


    const payload = {

        attempts:
            Number(
                attempts || 0
            ),

        lockUntil:
            lockUntil
                ? lockUntil.toISOString()
                : "",

        updatedAt:
            now().toISOString()

    };


    firebaseRequest(
        firebaseUserPath(
            uid
        ) +
        "/otp",
        "patch",
        payload
    );


    return true;

}


function clearFirebaseOtpFields(
    user
) {

    const uid =
        safeString(
            user["UID"]
        );


    if (!uid) {
        return false;
    }


    firebaseRequest(
        firebaseUserPath(
            uid
        ) +
        "/otp",
        "delete"
    );


    return true;

}


/* =========================================================
   FIREBASE VERIFIED / STATUS SYNC
   ========================================================= */

function syncFirebaseUserStatus(
    user,
    status,
    verified
) {

    const uid =
        safeString(
            user["UID"]
        );


    if (!uid) {
        return false;
    }


    const normalizedStatus =
        normalizeStatus(
            status
        );


    const payload = {

        accountStatus:
            normalizedStatus,

        verified:
            Boolean(
                verified
            ),

        statusUpdatedAt:
            now().toISOString()

    };


    firebaseRequest(
        firebaseUserPath(
            uid
        ),
        "patch",
        payload
    );


    return true;

}


/* =========================================================
   EMAIL
   ========================================================= */

function escapeHtml(value) {

    return safeString(value)
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#39;");

}


function sendEmailOTP(
    email,
    otp,
    recipientName
) {

    const destination =
        normalizeEmail(
            email
        );


    if (!destination) {

        return {

            success: false,

            sent: false,

            configured: false,

            message:
                "No Gmail address is registered."

        };

    }


    const safeOtp =
        escapeHtml(otp);


    const safeBrand =
        escapeHtml(EMAIL_BRAND_NAME);


    const safeFooter =
        escapeHtml(EMAIL_FOOTER);


    const safeRecipientName =
        escapeHtml(
            recipientName ||
            "there"
        );


    const subject =
        EMAIL_BRAND_NAME +
        " - Your verification code";


    const plainBody =
        EMAIL_BRAND_NAME +
        "\n\n" +
        "Hello " +
        safeString(recipientName || "there") +
        ",\n\n" +
        "Your verification code is:\n\n" +
        safeString(otp) +
        "\n\n" +
        "This code expires in " +
        OTP_EXPIRATION_MINUTES +
        " minutes.\n\n" +
        "If you did not request this verification code, you can ignore this email.\n\n" +
        EMAIL_FOOTER;


    const htmlBody =
        '<div style="font-family:Arial,Helvetica,sans-serif;max-width:760px;margin:0 auto;padding:24px;color:#111827;line-height:1.6;">' +
            '<div style="font-size:28px;font-weight:700;color:#2563eb;margin-bottom:28px;">' +
                safeBrand +
            '</div>' +
            '<div style="font-size:20px;margin-bottom:24px;">Hello ' +
                safeRecipientName +
                ',</div>' +
            '<div style="font-size:20px;margin-bottom:18px;">Your verification code is:</div>' +
            '<div style="background:#dfe4ea;border-radius:18px;padding:34px 20px;text-align:center;margin:26px 0 32px;">' +
                '<div style="font-size:50px;line-height:1;font-weight:700;letter-spacing:12px;color:#10213f;">' +
                    safeOtp +
                '</div>' +
            '</div>' +
            '<div style="font-size:20px;margin-bottom:24px;">This code expires in <strong>' +
                OTP_EXPIRATION_MINUTES +
                ' minutes.</strong></div>' +
            '<div style="font-size:18px;color:#64748b;margin-bottom:22px;">If you did not request this verification code, you can ignore this email.</div>' +
            '<div style="font-size:18px;color:#777777;">' +
                safeFooter +
            '</div>' +
        '</div>';


    MailApp.sendEmail({

        to:
            destination,

        subject:
            subject,

        body:
            plainBody,

        htmlBody:
            htmlBody,

        name:
            EMAIL_SENDER_NAME

    });


    return {

        success: true,

        sent: true,

        configured: true,

        senderName:
            EMAIL_SENDER_NAME,

        brandName:
            EMAIL_BRAND_NAME

    };

}


/* =========================================================
   TWILIO
   ========================================================= */

function getTwilioSettings() {

    const properties =
        PropertiesService
            .getScriptProperties();


    return {

        accountSid:
            safeString(
                properties.getProperty(
                    "TWILIO_ACCOUNT_SID"
                )
            ),

        authToken:
            safeString(
                properties.getProperty(
                    "TWILIO_AUTH_TOKEN"
                )
            ),

        phoneNumber:
            safeString(
                properties.getProperty(
                    "TWILIO_PHONE_NUMBER"
                )
            )

    };

}


function sendPhoneOTP(
    phone,
    otp
) {

    const destination =
        normalizePhone(
            phone
        );


    if (!destination) {

        return {

            success: false,

            sent: false,

            message:
                "No registered phone number is available."

        };

    }


    const settings =
        getTwilioSettings();


    if (
        !settings.accountSid ||
        !settings.authToken ||
        !settings.phoneNumber
    ) {

        return {

            success: false,

            sent: false,

            configured: false,

            message:
                "Phone OTP delivery is not configured."

        };

    }


    const url =
        "https://api.twilio.com/2010-04-01/Accounts/" +
        encodeURIComponent(
            settings.accountSid
        ) +
        "/Messages.json";


    const payload = {

        To:
            "+63" +
            destination.substring(1),

        From:
            settings.phoneNumber,

        Body:
            APP_NAME +
            " verification code: " +
            otp +
            ". Expires in " +
            OTP_EXPIRATION_MINUTES +
            " minutes."

    };


    const authorization =
        Utilities.base64Encode(
            settings.accountSid +
            ":" +
            settings.authToken
        );


    const response =
        UrlFetchApp.fetch(
            url,
            {

                method:
                    "post",

                muteHttpExceptions:
                    true,

                headers: {

                    Authorization:
                        "Basic " +
                        authorization

                },

                payload

            }
        );


    const code =
        response.getResponseCode();


    if (
        code < 200 ||
        code >= 300
    ) {

        throw new Error(
            "Twilio phone delivery failed: HTTP " +
            code +
            " " +
            response.getContentText()
        );

    }


    return {

        success: true,

        sent: true,

        configured: true

    };

}


/* =========================================================
   OTP DELIVERY
   ========================================================= */

function sendOTPByChannel(
    user,
    otp,
    channel
) {

    const selectedChannel =
        normalizeChannel(
            channel
        );


    const result = {

        emailSent:
            false,

        smsSent:
            false,

        emailAttempted:
            false,

        smsAttempted:
            false,

        emailError:
            "",

        smsError:
            "",

        deliveryConfigured:
            false

    };


    if (
        selectedChannel === "email" ||
        selectedChannel === "both"
    ) {

        result.emailAttempted =
            true;


        try {

            const emailResult =
                sendEmailOTP(
                    user["GMAIL"],
                    otp,
                    user["NAME"]
                );


            result.emailSent =
                Boolean(
                    emailResult.sent
                );


            if (
                emailResult.configured !==
                false
            ) {

                result.deliveryConfigured =
                    true;

            }

        } catch (error) {

            result.emailError =
                safeString(
                    error.message
                );

        }

    }


    if (
        selectedChannel === "phone" ||
        selectedChannel === "both"
    ) {

        result.smsAttempted =
            true;


        try {

            const phoneResult =
                sendPhoneOTP(
                    user["PHONE NO."],
                    otp
                );


            result.smsSent =
                Boolean(
                    phoneResult.sent
                );


            if (
                phoneResult.configured !==
                false
            ) {

                result.deliveryConfigured =
                    true;

            }

        } catch (error) {

            result.smsError =
                safeString(
                    error.message
                );

        }

    }


    return result;

}


/* =========================================================
   OTP SHEET STORAGE
   ========================================================= */

function saveOtp(
    user,
    otp,
    channel
) {

    const sheet =
        getSheet();


    const row =
        Number(
            user._row
        );


    if (
        !row ||
        row < 2
    ) {

        throw new Error(
            "Invalid user row for OTP storage."
        );

    }


    const generatedAt =
        now();


    const expiresAt =
        addMinutes(
            generatedAt,
            OTP_EXPIRATION_MINUTES
        );


    const attempts =
        0;


    const lockUntil =
        null;


    const timestamp =
        generatedAt;


    const normalizedChannel =
        normalizeChannel(
            channel
        );


    const channelColumn =
        HEADERS.indexOf(
            "OTP CHANNEL"
        ) + 1;


    const otpColumn =
        HEADERS.indexOf(
            "OTP"
        ) + 1;


    const expiresColumn =
        HEADERS.indexOf(
            "OTP EXPIRES"
        ) + 1;


    const attemptsColumn =
        HEADERS.indexOf(
            "OTP ATTEMPTS"
        ) + 1;


    const lockColumn =
        HEADERS.indexOf(
            "OTP LOCK UNTIL"
        ) + 1;


    const lastOtpColumn =
        HEADERS.indexOf(
            "LAST OTP SENT"
        ) + 1;


    const emailLastColumn =
        HEADERS.indexOf(
            "LAST EMAIL OTP SENT"
        ) + 1;


    const phoneLastColumn =
        HEADERS.indexOf(
            "LAST PHONE OTP SENT"
        ) + 1;


    sheet
        .getRange(
            row,
            otpColumn
        )
        .setValue(
            otp
        );


    sheet
        .getRange(
            row,
            expiresColumn
        )
        .setValue(
            expiresAt
        );


    sheet
        .getRange(
            row,
            attemptsColumn
        )
        .setValue(
            attempts
        );


    sheet
        .getRange(
            row,
            lockColumn
        )
        .setValue(
            ""
        );


    sheet
        .getRange(
            row,
            channelColumn
        )
        .setValue(
            normalizedChannel
        );


    sheet
        .getRange(
            row,
            lastOtpColumn
        )
        .setValue(
            timestamp
        );


    /*
     * Independent channel timestamps.
     */

    if (
        normalizedChannel === "email"
    ) {

        sheet
            .getRange(
                row,
                emailLastColumn
            )
            .setValue(
                timestamp
            );

    }


    if (
        normalizedChannel === "phone"
    ) {

        sheet
            .getRange(
                row,
                phoneLastColumn
            )
            .setValue(
                timestamp
            );

    }


    if (
        normalizedChannel === "both"
    ) {

        sheet
            .getRange(
                row,
                emailLastColumn
            )
            .setValue(
                timestamp
            );


        sheet
            .getRange(
                row,
                phoneLastColumn
            )
            .setValue(
                timestamp
            );

    }


    /*
     * Firebase is part of the same OTP state.
     */

    try {

        saveOtpToFirebase(
            user,
            otp,
            normalizedChannel,
            expiresAt,
            attempts,
            lockUntil
        );

    } catch (error) {

        /*
         * Roll the Sheet OTP back if Firebase storage fails.
         */

        clearSheetOtp(
            user
        );


        throw error;

    }


    return {

        otp,
        expiresAt,
        attempts,
        lockUntil,
        channel:
            normalizedChannel

    };

}


/* =========================================================
   CLEAR SHEET OTP
   ========================================================= */

function clearSheetOtp(
    user
) {

    const sheet =
        getSheet();


    const row =
        Number(
            user._row
        );


    if (
        !row ||
        row < 2
    ) {

        return false;

    }


    const columns = [

        "OTP",
        "OTP EXPIRES",
        "OTP ATTEMPTS",
        "OTP LOCK UNTIL",
        "OTP CHANNEL"

    ];


    columns.forEach(
        (header) => {

            const column =
                HEADERS.indexOf(
                    header
                ) + 1;


            if (
                column > 0
            ) {

                sheet
                    .getRange(
                        row,
                        column
                    )
                    .setValue(
                        ""
                    );

            }

        }
    );


    return true;

}


/* =========================================================
   CLEAR OTP COMPLETELY
   ========================================================= */

function clearOtpCompletely(
    user
) {

    clearSheetOtp(
        user
    );


    try {

        clearFirebaseOtpFields(
            user
        );

    } catch (error) {

        console.error(
            "Firebase OTP cleanup failed:",
            error
        );

    }


    return true;

}


/* =========================================================
   OTP COOLDOWN
   ========================================================= */

function getChannelLastSent(
    user,
    channel
) {

    const normalized =
        normalizeChannel(
            channel
        );


    if (
        normalized === "phone"
    ) {

        return parseDate(
            user["LAST PHONE OTP SENT"]
        );

    }


    return parseDate(
        user["LAST EMAIL OTP SENT"]
    );

}


function getRemainingCooldown(
    user,
    channel
) {

    const lastSent =
        getChannelLastSent(
            user,
            channel
        );


    if (!lastSent) {
        return 0;
    }


    const unlockTime =
        addSeconds(
            lastSent,
            OTP_RESEND_COOLDOWN_SECONDS
        );


    const remaining =
        Math.ceil(
            (
                unlockTime.getTime() -
                now().getTime()
            ) / 1000
        );


    return Math.max(
        0,
        remaining
    );

}


/* =========================================================
   OTP LOCK
   ========================================================= */

function getOtpLockUntil(
    user
) {

    return parseDate(
        user["OTP LOCK UNTIL"]
    );

}


function isOtpLocked(
    user
) {

    const lockUntil =
        getOtpLockUntil(
            user
        );


    if (!lockUntil) {
        return false;
    }


    return (
        lockUntil.getTime() >
        now().getTime()
    );

}


/* =========================================================
   ACTIVE OTP
   ========================================================= */

function getActiveOtp(
    user
) {

    const otp =
        safeString(
            user["OTP"]
        );


    const expiresAt =
        parseDate(
            user["OTP EXPIRES"]
        );


    if (
        !otp ||
        !expiresAt
    ) {

        return null;

    }


    if (
        expiresAt.getTime() <=
        now().getTime()
    ) {

        return null;

    }


    return {

        otp,

        expiresAt

    };

}


/* =========================================================
   OTP RESPONSE
   ========================================================= */

function buildOtpResponse(
    user,
    otpData,
    channel,
    delivery,
    message
) {

    const response = {

        success:
            true,

        code:
            "OTP_READY",

        message:
            message ||
            "Verification code is ready.",

        otpReady:
            true,

        /* OTP is never returned to frontend JavaScript. */
        otp:
            "",

        uid:
            safeString(
                user["UID"]
            ),

        username:
            safeString(
                user["USERNAME"]
            ),

        gmail:
            normalizeEmail(
                user["GMAIL"]
            ),

        email:
            normalizeEmail(
                user["GMAIL"]
            ),

        phone:
            normalizePhone(
                user["PHONE NO."]
            ),

        channel:
            normalizeChannel(
                channel
            ),

        expiresAt:
            otpData.expiresAt
                .toISOString(),

        cooldown:
            OTP_RESEND_COOLDOWN_SECONDS,

        emailSent:
            Boolean(
                delivery &&
                delivery.emailSent
            ),

        smsSent:
            Boolean(
                delivery &&
                delivery.smsSent
            ),

        deliveryConfigured:
            Boolean(
                delivery &&
                delivery.deliveryConfigured
            ),

        demoMode:
            DEMO_MODE

    };


    return response;

}


/* =========================================================
   OTP IDENTITY
   ========================================================= */

function resolveOtpIdentity(
    data
) {

    const identity =
        safeString(
            data.identity
        );


    if (identity) {

        const user =
            findUser(
                identity
            );


        if (user) {
            return user;
        }

    }


    const uid =
        safeString(
            data.uid
        );


    if (uid) {

        const user =
            findUserByUid(
                uid
            );


        if (user) {
            return user;
        }

    }


    const username =
        normalizeUsername(
            data.username
        );


    if (username) {

        const user =
            findUser(
                username
            );


        if (user) {
            return user;
        }

    }


    const email =
        normalizeEmail(
            data.email ||
            data.gmail
        );


    if (email) {

        const user =
            findUser(
                email
            );


        if (user) {
            return user;
        }

    }


    const phone =
        normalizePhone(
            data.phone
        );


    if (phone) {

        const user =
            findUser(
                phone
            );


        if (user) {
            return user;
        }

    }


    return null;

}


/* =========================================================
   OTP CHANNEL
   ========================================================= */

function resolveOtpChannel(
    data
) {

    const channel =
        normalizeChannel(
            data.channel
        );


    return channel;

}


/* =========================================================
   PREPARE OTP
   ========================================================= */

function prepareOtp(
    data
) {

    data =
        data || {};


    const purpose =
        safeString(
            data.purpose
        ).toLowerCase();


    const isRecoveryRequest =
        purpose === "recovery" ||
        purpose === "password_recovery" ||
        purpose === "forgot_password";


    const user =
        resolveOtpIdentity(
            data
        );


    if (!user) {

        return {

            success: false,

            code:
                "ACCOUNT_NOT_FOUND",

            message:
                "Account does not exist."

        };

    }


    const status =
        normalizeStatus(
            user["ACCOUNT_S"]
        );


    if (
        status === "DISABLED"
    ) {

        return {

            success: false,

            code:
                "ACCOUNT_DISABLED",

            message:
                "This account is disabled."

        };

    }


    if (
        status === "SUSPENDED"
    ) {

        return {

            success: false,

            code:
                "ACCOUNT_SUSPENDED",

            message:
                "This account is suspended."

        };

    }


    if (
        status === "BLOCKED"
    ) {

        return {

            success: false,

            code:
                "ACCOUNT_BLOCKED",

            message:
                "This account is blocked."

        };

    }


    if (
        toBoolean(
            user["VERIFIED"]
        ) &&
        !isRecoveryRequest
    ) {

        return {

            success: false,

            code:
                "ALREADY_VERIFIED",

            message:
                "This account is already verified."

        };

    }


    if (
        isOtpLocked(
            user
        )
    ) {

        const lockUntil =
            getOtpLockUntil(
                user
            );


        return {

            success: false,

            code:
                "OTP_LOCKED",

            message:
                "Too many incorrect attempts. Please try again after the temporary lock expires.",

            lockUntil:
                lockUntil
                    ? lockUntil.toISOString()
                    : ""

        };

    }


    const channel =
        resolveOtpChannel(
            data
        );


    /*
     * BOTH is allowed internally, but the frontend buttons
     * use independent email/phone channels.
     */

    if (
        channel !== "email" &&
        channel !== "phone" &&
        channel !== "both"
    ) {

        return {

            success: false,

            code:
                "INVALID_OTP_CHANNEL",

            message:
                "Invalid verification method."

        };

    }


    /*
     * Independent cooldown.
     *
     * Email cooldown does NOT block phone.
     * Phone cooldown does NOT block email.
     */

    if (
        channel === "email" ||
        channel === "phone"
    ) {

        const remaining =
            getRemainingCooldown(
                user,
                channel
            );


        if (
            remaining > 0
        ) {

            /*
             * If an active OTP exists, tell the frontend it
             * remains available rather than generating another.
             */

            const activeOtp =
                getActiveOtp(
                    user
                );


            if (
                activeOtp &&
                normalizeChannel(
                    user["OTP CHANNEL"]
                ) === channel
            ) {

                const delivery = {

                    emailSent:
                        false,

                    smsSent:
                        false,

                    deliveryConfigured:
                        false

                };


                return buildOtpResponse(
                    user,
                    activeOtp,
                    channel,
                    delivery,
                    "Your existing verification code is still active."
                );

            }


            return {

                success: false,

                code:
                    "OTP_COOLDOWN",

                message:
                    "Please wait before requesting another verification code.",

                cooldown:
                    remaining,

                channel

            };

        }

    }


    /*
     * Generate a BRAND NEW server-side OTP.
     */

    const otp =
        generateOTP();


    let otpData;


    try {

        otpData =
            saveOtp(
                user,
                otp,
                channel
            );

    } catch (error) {

        return {

            success: false,

            code:
                "OTP_STORAGE_ERROR",

            message:
                "Unable to securely store the verification code right now.",

            detail:
                DEMO_MODE
                    ? safeString(
                        error.message
                    )
                    : ""

        };

    }


    /*
     * Delivery is attempted after storage.
     */

    const delivery =
        sendOTPByChannel(
            user,
            otp,
            channel
        );


    const delivered =
        Boolean(
            delivery.emailSent ||
            delivery.smsSent
        );


    /*
     * OTP delivery must succeed before the request is reported
     * as successful. The OTP itself is never returned to the
     * frontend.
     */
    if (
        !delivered
    ) {

        clearOtpCompletely(
            user
        );


        let deliveryMessage =
            "The verification code could not be delivered. Please try again.";


        if (
            channel === "email"
        ) {

            deliveryMessage =
                "The verification code could not be sent to Gmail. Please check the email delivery configuration and try again.";

        }


        if (
            channel === "phone"
        ) {

            deliveryMessage =
                "The verification code could not be sent by SMS. Please check the phone delivery configuration and try again.";

        }


        return {

            success: false,

            code:
                "OTP_DELIVERY_FAILED",

            message:
                deliveryMessage,

            emailSent:
                Boolean(
                    delivery.emailSent
                ),

            smsSent:
                Boolean(
                    delivery.smsSent
                ),

            emailError:
                safeString(
                    delivery.emailError
                ),

            smsError:
                safeString(
                    delivery.smsError
                ),

            channel

        };

    }


    let message =
        "Verification code request accepted.";


    if (
        channel === "email" &&
        delivery.emailSent
    ) {

        message =
            "Verification code request accepted. Check the registered Gmail address for the code.";

    }


    if (
        channel === "phone" &&
        delivery.smsSent
    ) {

        message =
            "Verification code request accepted. Check the registered phone for the code.";

    }


    if (
        channel === "both"
    ) {

        message =
            "Verification code request accepted. Check the selected verification channels for the code.";

    }


    return buildOtpResponse(
        user,
        otpData,
        channel,
        delivery,
        message
    );

}


/* =========================================================
   COMPATIBILITY OTP FUNCTIONS
   ========================================================= */

function generateOtp(
    data
) {

    return prepareOtp(
        data
    );

}


function resendOTP(
    data
) {

    data =
        data || {};


    const channel =
        resolveOtpChannel(
            data
        );


    /*
     * resendOTP obeys the exact same independent
     * channel cooldown.
     */

    return prepareOtp(
        data
    );

}


function requestOtp(
    data
) {

    return resendOTP(
        data
    );

}


/* =========================================================
   VERIFY OTP
   ========================================================= */

function verifyOTP(
    data
) {

    data =
        data || {};


    const user =
        resolveOtpIdentity(
            data
        );


    if (!user) {

        return {

            success: false,

            code:
                "ACCOUNT_NOT_FOUND",

            message:
                "Account does not exist."

        };

    }


    if (
        toBoolean(
            user["VERIFIED"]
        )
    ) {

        return {

            success: false,

            code:
                "ALREADY_VERIFIED",

            message:
                "This account is already verified."

        };

    }


    if (
        isOtpLocked(
            user
        )
    ) {

        return {

            success: false,

            code:
                "OTP_LOCKED",

            message:
                "Too many incorrect attempts. Please try again after the temporary lock expires."

        };

    }


    const submittedOtp =
        safeString(
            data.otp
        );


    if (
        !/^\d{6}$/.test(
            submittedOtp
        )
    ) {

        return {

            success: false,

            code:
                "INVALID_OTP",

            message:
                "Please enter the complete 6-digit verification code."

        };

    }


    const storedOtp =
        safeString(
            user["OTP"]
        );


    const expiresAt =
        parseDate(
            user["OTP EXPIRES"]
        );


    if (
        !storedOtp ||
        !expiresAt
    ) {

        return {

            success: false,

            code:
                "OTP_NOT_READY",

            message:
                "Your verification code is not ready yet. Please request a new code."

        };

    }


    if (
        expiresAt.getTime() <=
        now().getTime()
    ) {

        clearOtpCompletely(
            user
        );


        return {

            success: false,

            code:
                "OTP_EXPIRED",

            message:
                "This verification code has expired. Please request a new code."

        };

    }


    const attempts =
        Number(
            user["OTP ATTEMPTS"] || 0
        );


    /*
     * Compare server-stored OTP.
     */

    if (
        submittedOtp !==
        storedOtp
    ) {

        const newAttempts =
            attempts + 1;


        let lockUntil =
            null;


        if (
            newAttempts >=
            OTP_MAX_ATTEMPTS
        ) {

            lockUntil =
                addMinutes(
                    now(),
                    OTP_LOCK_MINUTES
                );

        }


        const sheet =
            getSheet();


        const row =
            Number(
                user._row
            );


        const attemptsColumn =
            HEADERS.indexOf(
                "OTP ATTEMPTS"
            ) + 1;


        const lockColumn =
            HEADERS.indexOf(
                "OTP LOCK UNTIL"
            ) + 1;


        sheet
            .getRange(
                row,
                attemptsColumn
            )
            .setValue(
                newAttempts
            );


        sheet
            .getRange(
                row,
                lockColumn
            )
            .setValue(
                lockUntil || ""
            );


        try {

            updateFirebaseOtpAttempts(
                user,
                newAttempts,
                lockUntil
            );

        } catch (error) {

            console.error(
                "Firebase OTP attempt sync failed:",
                error
            );

        }


        if (
            newAttempts >=
            OTP_MAX_ATTEMPTS
        ) {

            return {

                success: false,

                code:
                    "OTP_LOCKED",

                message:
                    "Too many incorrect attempts. Your verification is temporarily locked for 30 minutes.",

                attempts:
                    newAttempts

            };

        }


        return {

            success: false,

            code:
                "INVALID_OTP",

            message:
                "The verification code is incorrect.",

            attempts:
                newAttempts,

            remainingAttempts:
                OTP_MAX_ATTEMPTS -
                newAttempts

        };

    }


    /*
     * OTP IS CORRECT.
     *
     * Mark the account verified.
     */

    const sheet =
        getSheet();


    const row =
        Number(
            user._row
        );


    const statusColumn =
        HEADERS.indexOf(
            "ACCOUNT_S"
        ) + 1;


    const verifiedColumn =
        HEADERS.indexOf(
            "VERIFIED"
        ) + 1;


    const verifiedAtColumn =
        HEADERS.indexOf(
            "VERIFIED AT"
        ) + 1;


    sheet
        .getRange(
            row,
            statusColumn
        )
        .setValue(
            "VERIFIED"
        );


    sheet
        .getRange(
            row,
            verifiedColumn
        )
        .setValue(
            true
        );


    sheet
        .getRange(
            row,
            verifiedAtColumn
        )
        .setValue(
            now()
        );


    /*
     * Clear OTP from Sheet and Firebase.
     */

    clearOtpCompletely(
        user
    );


    /*
     * Synchronize Firebase status correctly.
     */

    try {

        syncFirebaseUserStatus(
            user,
            "VERIFIED",
            true
        );

    } catch (error) {

        console.error(
            "Firebase verified status sync failed:",
            error
        );

    }


    /*
     * Refresh the user object.
     */

    user["ACCOUNT_S"] =
        "VERIFIED";


    user["VERIFIED"] =
        true;


    user["VERIFIED AT"] =
        now();


    return {

        success: true,

        code:
            "ACCOUNT_VERIFIED",

        message:
            "Account verified successfully.",

        verified:
            true,

        accountStatus:
            "VERIFIED",

        redirect:
            "dashboard.html",

        user:
            userToResponse(
                user
            )

    };

}


/* =========================================================
   LOGIN
   ========================================================= */

function loginUser(
    data
) {

    data =
        data || {};


    const identity =
        safeString(
            data.identity ||
            data.username ||
            data.email ||
            data.gmail ||
            data.phone
        );


    const password =
        safeString(
            data.password
        );


    if (!identity) {

        return {

            success: false,

            code:
                "IDENTITY_REQUIRED",

            message:
                "Please enter your username, email, or phone number."

        };

    }


    if (!password) {

        return {

            success: false,

            code:
                "PASSWORD_REQUIRED",

            message:
                "Please enter your password."

        };

    }


    const user =
        findUser(
            identity
        );


    if (!user) {

        return {

            success: false,

            code:
                "ACCOUNT_NOT_FOUND",

            message:
                "Account does not exist."

        };

    }


    const storedPassword =
        safeString(
            user["PASSWORD"]
        );


    if (
        password !==
        storedPassword
    ) {

        return {

            success: false,

            code:
                "INVALID_CREDENTIALS",

            message:
                "Invalid username/email or password."

        };

    }


    const status =
        normalizeStatus(
            user["ACCOUNT_S"]
        );


    if (
        status === "DISABLED"
    ) {

        return {

            success: false,

            code:
                "ACCOUNT_DISABLED",

            message:
                "This account is disabled."

        };

    }


    if (
        status === "SUSPENDED"
    ) {

        return {

            success: false,

            code:
                "ACCOUNT_SUSPENDED",

            message:
                "This account is suspended."

        };

    }


    if (
        status === "BLOCKED"
    ) {

        return {

            success: false,

            code:
                "ACCOUNT_BLOCKED",

            message:
                "This account is blocked."

        };

    }


    if (
        !toBoolean(
            user["VERIFIED"]
        ) ||
        status === "PENDING"
    ) {

        return {

            success: false,

            code:
                "REQUIRES_VERIFICATION",

            message:
                "Account is not verified. Please verify your OTP.",

            verified:
                false,

            requiresVerification:
                true,

            needsVerification:
                true,

            uid:
                safeString(
                    user["UID"]
                ),

            username:
                safeString(
                    user["USERNAME"]
                ),

            gmail:
                normalizeEmail(
                    user["GMAIL"]
                ),

            email:
                normalizeEmail(
                    user["GMAIL"]
                ),

            phone:
                normalizePhone(
                    user["PHONE NO."]
                ),

            redirect:
                "verify.html"

        };

    }


    const sheet =
        getSheet();


    const row =
        Number(
            user._row
        );


    const lastLoginColumn =
        HEADERS.indexOf(
            "LAST LOGIN"
        ) + 1;


    const loginTime =
        now();


    sheet
        .getRange(
            row,
            lastLoginColumn
        )
        .setValue(
            loginTime
        );


    user["LAST LOGIN"] =
        loginTime;


    try {

        firebaseRequest(
            firebaseUserPath(
                user["UID"]
            ),
            "patch",
            {

                lastLogin:
                    loginTime.toISOString()

            }
        );

    } catch (error) {

        console.error(
            "Firebase last-login sync failed:",
            error
        );

    }


    return {

        success: true,

        code:
            "LOGIN_SUCCESS",

        message:
            "Login successful.",

        verified:
            true,

        accountStatus:
            "VERIFIED",

        redirect:
            "dashboard.html",

        user:
            userToResponse(
                user
            )

    };

}


/* =========================================================
   GET USER
   ========================================================= */

function getUser(
    data
) {

    data =
        data || {};


    const user =
        resolveOtpIdentity(
            data
        );


    if (!user) {

        return {

            success: false,

            code:
                "ACCOUNT_NOT_FOUND",

            message:
                "Account does not exist."

        };

    }


    return {

        success: true,

        code:
            "USER_FOUND",

        message:
            "User found.",

        user:
            userToResponse(
                user
            )

    };

}


/* =========================================================
   UPDATE ACCOUNT STATUS
   ========================================================= */

function updateAccountStatus(
    data
) {

    data =
        data || {};


    const user =
        resolveOtpIdentity(
            data
        );


    if (!user) {

        return {

            success: false,

            code:
                "ACCOUNT_NOT_FOUND",

            message:
                "Account does not exist."

        };

    }


    const requestedStatus =
        normalizeStatus(
            data.status ||
            data.accountStatus
        );


    const verified =
        requestedStatus ===
        "VERIFIED";


    const sheet =
        getSheet();


    const row =
        Number(
            user._row
        );


    const statusColumn =
        HEADERS.indexOf(
            "ACCOUNT_S"
        ) + 1;


    const verifiedColumn =
        HEADERS.indexOf(
            "VERIFIED"
        ) + 1;


    sheet
        .getRange(
            row,
            statusColumn
        )
        .setValue(
            requestedStatus
        );


    sheet
        .getRange(
            row,
            verifiedColumn
        )
        .setValue(
            verified
        );


    user["ACCOUNT_S"] =
        requestedStatus;


    user["VERIFIED"] =
        verified;


    /*
     * FIXED:
     *
     * We no longer call markFirebaseUserVerified()
     * unconditionally.
     *
     * Firebase now receives the actual requested status.
     */

    try {

        syncFirebaseUserStatus(
            user,
            requestedStatus,
            verified
        );

    } catch (error) {

        console.error(
            "Firebase account-status sync failed:",
            error
        );

        return {

            success: false,

            code:
                "FIREBASE_SYNC_ERROR",

            message:
                "Account status was changed in Google Sheets, but Firebase synchronization failed."

        };

    }


    return {

        success: true,

        code:
            "ACCOUNT_STATUS_UPDATED",

        message:
            "Account status updated successfully.",

        accountStatus:
            requestedStatus,

        verified,

        user:
            userToResponse(
                user
            )

    };

}


/* =========================================================
   PASSWORD RECOVERY
   ========================================================= */

function forgotPassword(
    data
) {

    data =
        data || {};


    const user =
        resolveOtpIdentity(
            data
        );


    /*
     * For this school-project requirement we explicitly
     * report missing accounts.
     */

    if (!user) {

        return {

            success: false,

            code:
                "ACCOUNT_NOT_FOUND",

            message:
                "Account does not exist."

        };

    }


    const status =
        normalizeStatus(
            user["ACCOUNT_S"]
        );


    if (
        status === "DISABLED"
    ) {

        return {

            success: false,

            code:
                "ACCOUNT_DISABLED",

            message:
                "This account is disabled."

        };

    }


    if (
        status === "SUSPENDED"
    ) {

        return {

            success: false,

            code:
                "ACCOUNT_SUSPENDED",

            message:
                "This account is suspended."

        };

    }


    if (
        status === "BLOCKED"
    ) {

        return {

            success: false,

            code:
                "ACCOUNT_BLOCKED",

            message:
                "This account is blocked."

        };

    }


    /*
     * Password recovery should only be available for
     * an existing verified account.
     */

    if (
        !toBoolean(
            user["VERIFIED"]
        )
    ) {

        return {

            success: false,

            code:
                "RECOVERY_NOT_ALLOWED",

            message:
                "This account has not completed verification yet."

        };

    }


    const channel =
        normalizeChannel(
            data.channel ||
            "email"
        );


    /*
     * Use the same server OTP engine.
     */

    const response =
        prepareOtp({

            identity:
                data.identity,

            uid:
                user["UID"],

            username:
                user["USERNAME"],

            email:
                user["GMAIL"],

            gmail:
                user["GMAIL"],

            phone:
                user["PHONE NO."],

            channel,

            purpose:
                "recovery"

        });


    if (
        !response.success
    ) {

        return response;

    }


    /*
     * Change the public message to make the purpose clear.
     */

    response.code =
        "RECOVERY_OTP_READY";


    response.message =
        response.emailSent ||
        response.smsSent
            ? "Password recovery code request accepted. Check your registered verification channel for the code."
            : "Password recovery code could not be delivered.";


    return response;

}


/* =========================================================
   RECOVERY TOKEN
   ========================================================= */

function recoveryTokenKey(
    uid
) {

    return (
        "SF_RECOVERY_" +
        safeString(
            uid
        )
    );

}


function createRecoveryToken(
    user
) {

    const uid =
        safeString(
            user["UID"]
        );


    if (!uid) {

        throw new Error(
            "Missing UID for recovery token."
        );

    }


    const token =
        Utilities.getUuid() +
        "-" +
        Utilities.getUuid();


    const expiresAt =
        addMinutes(
            now(),
            10
        );


    const record = {

        token,

        uid,

        expiresAt:
            expiresAt.toISOString()

    };


    PropertiesService
        .getScriptProperties()
        .setProperty(
            recoveryTokenKey(
                uid
            ),
            JSON.stringify(
                record
            )
        );


    return {

        token,

        expiresAt

    };

}


function getRecoveryTokenRecord(
    uid
) {

    const value =
        PropertiesService
            .getScriptProperties()
            .getProperty(
                recoveryTokenKey(
                    uid
                )
            );


    if (!value) {
        return null;
    }


    try {

        return JSON.parse(
            value
        );

    } catch (error) {

        return null;

    }

}


function clearRecoveryToken(
    uid
) {

    PropertiesService
        .getScriptProperties()
        .deleteProperty(
            recoveryTokenKey(
                uid
            )
        );

}


/* =========================================================
   VERIFY RECOVERY OTP
   ========================================================= */

function verifyRecoveryOtp(
    data
) {

    data =
        data || {};


    const user =
        resolveOtpIdentity(
            data
        );


    if (!user) {

        return {

            success: false,

            code:
                "ACCOUNT_NOT_FOUND",

            message:
                "Account does not exist."

        };

    }


    if (
        !toBoolean(
            user["VERIFIED"]
        )
    ) {

        return {

            success: false,

            code:
                "RECOVERY_NOT_ALLOWED",

            message:
                "This account has not completed verification yet."

        };

    }


    const otp =
        safeString(
            data.otp
        );


    if (
        !/^\d{6}$/.test(
            otp
        )
    ) {

        return {

            success: false,

            code:
                "INVALID_OTP",

            message:
                "Please enter the complete 6-digit recovery code."

        };

    }


    if (
        isOtpLocked(
            user
        )
    ) {

        return {

            success: false,

            code:
                "OTP_LOCKED",

            message:
                "Too many incorrect attempts. Please try again after the temporary lock expires."

        };

    }


    const storedOtp =
        safeString(
            user["OTP"]
        );


    const expiresAt =
        parseDate(
            user["OTP EXPIRES"]
        );


    if (
        !storedOtp ||
        !expiresAt
    ) {

        return {

            success: false,

            code:
                "OTP_NOT_READY",

            message:
                "Your recovery code is not ready yet. Please request a new code."

        };

    }


    if (
        expiresAt.getTime() <=
        now().getTime()
    ) {

        clearOtpCompletely(
            user
        );


        return {

            success: false,

            code:
                "OTP_EXPIRED",

            message:
                "This recovery code has expired. Please request a new code."

        };

    }


    const attempts =
        Number(
            user["OTP ATTEMPTS"] || 0
        );


    if (
        otp !==
        storedOtp
    ) {

        const newAttempts =
            attempts + 1;


        let lockUntil =
            null;


        if (
            newAttempts >=
            OTP_MAX_ATTEMPTS
        ) {

            lockUntil =
                addMinutes(
                    now(),
                    OTP_LOCK_MINUTES
                );

        }


        const sheet =
            getSheet();


        const row =
            Number(
                user._row
            );


        const attemptsColumn =
            HEADERS.indexOf(
                "OTP ATTEMPTS"
            ) + 1;


        const lockColumn =
            HEADERS.indexOf(
                "OTP LOCK UNTIL"
            ) + 1;


        sheet
            .getRange(
                row,
                attemptsColumn
            )
            .setValue(
                newAttempts
            );


        sheet
            .getRange(
                row,
                lockColumn
            )
            .setValue(
                lockUntil || ""
            );


        try {

            updateFirebaseOtpAttempts(
                user,
                newAttempts,
                lockUntil
            );

        } catch (error) {

            console.error(
                "Firebase recovery attempt sync failed:",
                error
            );

        }


        if (
            newAttempts >=
            OTP_MAX_ATTEMPTS
        ) {

            return {

                success: false,

                code:
                    "OTP_LOCKED",

                message:
                    "Too many incorrect attempts. Password recovery is temporarily locked for 30 minutes."

            };

        }


        return {

            success: false,

            code:
                "INVALID_OTP",

            message:
                "The recovery code is incorrect.",

            attempts:
                newAttempts,

            remainingAttempts:
                OTP_MAX_ATTEMPTS -
                newAttempts

        };

    }


    /*
     * Correct recovery OTP.
     *
     * DO NOT mark the account as verified.
     */

    let recovery;


    try {

        recovery =
            createRecoveryToken(
                user
            );

    } catch (error) {

        return {

            success: false,

            code:
                "RECOVERY_TOKEN_ERROR",

            message:
                "Unable to create a secure password-recovery session."

        };

    }


    /*
     * OTP has now been consumed.
     */

    clearOtpCompletely(
        user
    );


    return {

        success: true,

        code:
            "RECOVERY_VERIFIED",

        message:
            "Recovery code verified successfully. You may now create a new password.",

        recoveryToken:
            recovery.token,

        recoveryTokenExpiresAt:
            recovery.expiresAt
                .toISOString(),

        uid:
            safeString(
                user["UID"]
            ),

        username:
            safeString(
                user["USERNAME"]
            ),

        gmail:
            normalizeEmail(
                user["GMAIL"]
            ),

        email:
            normalizeEmail(
                user["GMAIL"]
            ),

        phone:
            normalizePhone(
                user["PHONE NO."]
            ),

        verified:
            true

    };

}


/* =========================================================
   RESET PASSWORD
   ========================================================= */

function resetPassword(
    data
) {

    data =
        data || {};


    const recoveryToken =
        safeString(
            data.recoveryToken ||
            data.token
        );


    if (!recoveryToken) {

        return {

            success: false,

            code:
                "RECOVERY_TOKEN_INVALID",

            message:
                "Your recovery session is invalid. Please verify the recovery code again."

        };

    }


    const uid =
        safeString(
            data.uid
        );


    if (!uid) {

        return {

            success: false,

            code:
                "RECOVERY_TOKEN_INVALID",

            message:
                "Your recovery session is invalid."

        };

    }


    const record =
        getRecoveryTokenRecord(
            uid
        );


    if (!record) {

        return {

            success: false,

            code:
                "RECOVERY_TOKEN_INVALID",

            message:
                "Your recovery session is invalid or has already been used."

        };

    }


    if (
        safeString(
            record.token
        ) !==
        recoveryToken
    ) {

        return {

            success: false,

            code:
                "RECOVERY_TOKEN_INVALID",

            message:
                "Your recovery session is invalid."

        };

    }


    const tokenExpiresAt =
        parseDate(
            record.expiresAt
        );


    if (
        !tokenExpiresAt ||
        tokenExpiresAt.getTime() <=
        now().getTime()
    ) {

        clearRecoveryToken(
            uid
        );


        return {

            success: false,

            code:
                "RECOVERY_EXPIRED",

            message:
                "Your password recovery session has expired. Please start again."

        };

    }


    const user =
        findUserByUid(
            uid
        );


    if (!user) {

        clearRecoveryToken(
            uid
        );


        return {

            success: false,

            code:
                "ACCOUNT_NOT_FOUND",

            message:
                "Account does not exist."

        };

    }


    const password =
        safeString(
            data.newPassword ||
            data.password
        );


    const confirmPassword =
        safeString(
            data.confirmPassword
        );


    if (
        password.length < 8
    ) {

        return {

            success: false,

            code:
                "PASSWORD_INVALID",

            message:
                "Password must be at least 8 characters."

        };

    }


    if (
        !/[A-Z]/.test(
            password
        ) ||
        !/[a-z]/.test(
            password
        ) ||
        !/\d/.test(
            password
        ) ||
        !/[^A-Za-z0-9]/.test(
            password
        )
    ) {

        return {

            success: false,

            code:
                "PASSWORD_INVALID",

            message:
                "Password must include uppercase, lowercase, number, and special character."

        };

    }


    if (
        password !==
        confirmPassword
    ) {

        return {

            success: false,

            code:
                "PASSWORD_MISMATCH",

            message:
                "Passwords do not match."

        };

    }


    /*
     * Update password in the existing USER sheet.
     */

    const sheet =
        getSheet();


    const row =
        Number(
            user._row
        );


    const passwordColumn =
        HEADERS.indexOf(
            "PASSWORD"
        ) + 1;


    sheet
        .getRange(
            row,
            passwordColumn
        )
        .setValue(
            password
        );


    /*
     * Password reset is complete.
     */

    clearRecoveryToken(
        uid
    );


    /*
     * Any old OTP state is removed.
     */

    clearOtpCompletely(
        user
    );


    /*
     * Firebase does NOT receive the plaintext password.
     *
     * We only synchronize the fact that the account remains
     * verified and the password was changed.
     */

    try {

        firebaseRequest(
            firebaseUserPath(
                uid
            ),
            "patch",
            {

                passwordUpdatedAt:
                    now().toISOString(),

                verified:
                    true,

                accountStatus:
                    "VERIFIED"

            }
        );

    } catch (error) {

        console.error(
            "Firebase password metadata sync failed:",
            error
        );

    }


    return {

        success: true,

        code:
            "PASSWORD_RESET_SUCCESS",

        message:
            "Your password has been reset successfully. You can now sign in with your new password.",

        uid,

        verified:
            true,

        accountStatus:
            "VERIFIED",

        redirect:
            "auth.html#login"

    };

}


/* =========================================================
   EMPLOYEE REGISTRATION
   ========================================================= */

function registerUser(
    data
) {

    data =
        data || {};


    const validation =
        validateRegistrationData(
            data
        );


    if (
        !validation.valid
    ) {

        return {

            success: false,

            code:
                validation.code,

            message:
                validation.message

        };

    }


    const registration =
        validation.data;


    const duplicate =
        findDuplicateUser(
            registration.username,
            registration.gmail,
            registration.phone
        );


    if (duplicate) {

        let message =
            "An account with these details already exists.";


        if (
            duplicate.code ===
            "USERNAME_EXISTS"
        ) {

            message =
                "Username already exists.";

        }


        if (
            duplicate.code ===
            "EMAIL_EXISTS"
        ) {

            message =
                "This Gmail address is already registered.";

        }


        if (
            duplicate.code ===
            "PHONE_EXISTS"
        ) {

            message =
                "This phone number is already registered.";

        }


        return {

            success: false,

            code:
                duplicate.code,

            message

        };

    }


    const uid =
        generateUID();


    const createdAt =
        now();


    const sheet =
        getSheet();


    const rowValues = [

        uid,

        registration.name,

        registration.username,

        registration.password,

        registration.age,

        "PENDING",

        registration.gmail,

        registration.phone,

        "Employee",

        false,

        "",

        "",

        0,

        "",

        "",

        createdAt,

        "",

        "",

        "",

        "",

        ""

    ];


    sheet.appendRow(
        rowValues
    );


    const newRow =
        sheet.getLastRow();


    const user = {};


    HEADERS.forEach(
        (
            header,
            index
        ) => {

            user[header] =
                rowValues[index];

        }
    );


    user._row =
        newRow;


    /*
     * Save account to Firebase.
     */

    try {

        saveFirebaseUser(
            user
        );

    } catch (error) {

        /*
         * Roll the registration back if Firebase creation
         * fails, keeping Sheets and Firebase synchronized.
         */

        sheet.deleteRow(
            newRow
        );


        return {

            success: false,

            code:
                "FIREBASE_REGISTRATION_ERROR",

            message:
                "The account could not be synchronized with the database. Please try again."

        };

    }


    /*
     * Automatically issue the initial EMAIL verification code.
     * The code is generated and stored server-side and sent by
     * Gmail. It is never returned to the frontend.
     */
    const otpResponse =
        prepareOtp({

            uid:
                uid,

            channel:
                "email",

            purpose:
                "registration"

        });


    const otpReady =
        Boolean(
            otpResponse &&
            otpResponse.success
        );


    const emailSent =
        Boolean(
            otpResponse &&
            otpResponse.emailSent
        );


    const registrationMessage =
        otpReady && emailSent
            ? "Account created successfully. A verification code was requested for your Gmail address."
            : "Account created successfully, but the verification code could not be delivered. Open the verification page and use Send code to try again.";



    return {

        success: true,

        code:
            "REGISTRATION_SUCCESS",

        message:
            registrationMessage,

        uid,

        username:
            registration.username,

        name:
            registration.name,

        gmail:
            registration.gmail,

        email:
            registration.gmail,

        phone:
            registration.phone,

        role:
            "Employee",

        verified:
            false,

        accountStatus:
            "PENDING",

        otpReady:
            otpReady,

        emailSent:
            emailSent,

        otpExpiresAt:
            otpReady &&
            otpResponse.expiresAt
                ? otpResponse.expiresAt
                : "",

        otpCooldownSeconds:
            otpReady
                ? Number(
                    otpResponse.cooldown ||
                    OTP_RESEND_COOLDOWN_SECONDS
                )
                : 0,

        redirect:
            "verify.html"

    };

}


/* =========================================================
   ADMIN REGISTRATION
   ========================================================= */

function registerAdmin(
    data
) {

    data =
        data || {};


    const validation =
        validateRegistrationData(
            data
        );


    if (
        !validation.valid
    ) {

        return {

            success: false,

            code:
                validation.code,

            message:
                validation.message

        };

    }


    const registration =
        validation.data;


    const duplicate =
        findDuplicateUser(
            registration.username,
            registration.gmail,
            registration.phone
        );


    if (duplicate) {

        let message =
            "An account with these details already exists.";


        if (
            duplicate.code ===
            "USERNAME_EXISTS"
        ) {

            message =
                "Username already exists.";

        }


        if (
            duplicate.code ===
            "EMAIL_EXISTS"
        ) {

            message =
                "This Gmail address is already registered.";

        }


        if (
            duplicate.code ===
            "PHONE_EXISTS"
        ) {

            message =
                "This phone number is already registered.";

        }


        return {

            success: false,

            code:
                duplicate.code,

            message

        };

    }


    /*
     * Admin registration is kept as a separate backend
     * operation so a normal Employee registration can never
     * silently become an Admin.
     */

    const uid =
        generateUID();


    const createdAt =
        now();


    const sheet =
        getSheet();


    const rowValues = [

        uid,

        registration.name,

        registration.username,

        registration.password,

        registration.age,

        "PENDING",

        registration.gmail,

        registration.phone,

        "Admin",

        false,

        "",

        "",

        0,

        "",

        "",

        createdAt,

        "",

        "",

        "",

        "",

        ""

    ];


    sheet.appendRow(
        rowValues
    );


    const newRow =
        sheet.getLastRow();


    const user = {};


    HEADERS.forEach(
        (
            header,
            index
        ) => {

            user[header] =
                rowValues[index];

        }
    );


    user._row =
        newRow;


    try {

        saveFirebaseUser(
            user
        );

    } catch (error) {

        sheet.deleteRow(
            newRow
        );


        return {

            success: false,

            code:
                "FIREBASE_REGISTRATION_ERROR",

            message:
                "The admin account could not be synchronized with the database. Please try again."

        };

    }


    /*
     * Automatically issue the initial EMAIL verification code.
     * The code is generated and stored server-side and sent by
     * Gmail. It is never returned to the frontend.
     */
    const otpResponse =
        prepareOtp({

            uid:
                uid,

            channel:
                "email",

            purpose:
                "registration"

        });


    const otpReady =
        Boolean(
            otpResponse &&
            otpResponse.success
        );


    const emailSent =
        Boolean(
            otpResponse &&
            otpResponse.emailSent
        );


    const registrationMessage =
        otpReady && emailSent
            ? "Admin account created successfully. A verification code was requested for the Gmail address."
            : "Admin account created successfully, but the verification code could not be delivered. Open the verification page and use Send code to try again.";


    return {

        success: true,

        code:
            "ADMIN_REGISTRATION_SUCCESS",

        message:
            registrationMessage,

        uid,

        username:
            registration.username,

        name:
            registration.name,

        gmail:
            registration.gmail,

        email:
            registration.gmail,

        phone:
            registration.phone,

        role:
            "Admin",

        verified:
            false,

        accountStatus:
            "PENDING",

        otpReady:
            otpReady,

        emailSent:
            emailSent,

        otpExpiresAt:
            otpReady &&
            otpResponse.expiresAt
                ? otpResponse.expiresAt
                : "",

        otpCooldownSeconds:
            otpReady
                ? Number(
                    otpResponse.cooldown ||
                    OTP_RESEND_COOLDOWN_SECONDS
                )
                : 0,

        redirect:
            "verify.html"

    };

}


/* =========================================================
   API REQUEST ROUTER
   ========================================================= */

function parseRequestBody(
    e
) {

    if (
        !e ||
        !e.postData ||
        !e.postData.contents
    ) {

        return {};

    }


    const raw =
        safeString(
            e.postData.contents
        );


    if (!raw) {
        return {};
    }


    try {

        return JSON.parse(
            raw
        );

    } catch (error) {

        return {};

    }

}


/* =========================================================
   DO POST
   ========================================================= */

function doPost(
    e
) {

    try {

        const data =
            parseRequestBody(
                e
            );


        const action =
            safeString(
                data.action ||
                data.operation ||
                data.request
            ).toLowerCase();


        let result;


        switch (action) {


            /* ---------------------------------------------
               REGISTRATION
            --------------------------------------------- */

            case "register":

                result =
                    registerUser(
                        data
                    );

                break;


            case "registeruser":

                result =
                    registerUser(
                        data
                    );

                break;


            case "registeradmin":

                result =
                    registerAdmin(
                        data
                    );

                break;


            /* ---------------------------------------------
               LOGIN
            --------------------------------------------- */

            case "login":

                result =
                    loginUser(
                        data
                    );

                break;


            case "loginuser":

                result =
                    loginUser(
                        data
                    );

                break;


            /* ---------------------------------------------
               OTP
            --------------------------------------------- */

            case "prepareotp":

                result =
                    prepareOtp(
                        data
                    );

                break;


            case "generateotp":

                result =
                    generateOtp(
                        data
                    );

                break;


            case "resendotp":

                result =
                    resendOTP(
                        data
                    );

                break;


            case "requestotp":

                result =
                    requestOtp(
                        data
                    );

                break;


            case "verifyotp":

                result =
                    verifyOTP(
                        data
                    );

                break;


            /* ---------------------------------------------
               USER
            --------------------------------------------- */

            case "getuser":

                result =
                    getUser(
                        data
                    );

                break;


            /* ---------------------------------------------
               ACCOUNT STATUS
            --------------------------------------------- */

            case "updatestatus":

                result =
                    updateAccountStatus(
                        data
                    );

                break;


            case "updateaccountstatus":

                result =
                    updateAccountStatus(
                        data
                    );

                break;


            /* ---------------------------------------------
               PASSWORD RECOVERY
            --------------------------------------------- */

            case "forgotpassword":

                result =
                    forgotPassword(
                        data
                    );

                break;


            case "verifyrecoveryotp":

                result =
                    verifyRecoveryOtp(
                        data
                    );

                break;


            case "resetpassword":

                result =
                    resetPassword(
                        data
                    );

                break;


            /* ---------------------------------------------
               UNKNOWN ACTION
            --------------------------------------------- */

            default:

                result = {

                    success: false,

                    code:
                        "UNKNOWN_ACTION",

                    message:
                        "Unknown API action."

                };

                break;

        }


        return jsonResponse(
            result
        );

    } catch (error) {

        console.error(
            "STOCKFLOW doPost error:",
            error
        );


        return jsonResponse({

            success: false,

            code:
                "SERVER_ERROR",

            message:
                "The server encountered an unexpected error.",

            detail:
                DEMO_MODE
                    ? safeString(
                        error.message
                    )
                    : ""

        });

    }

}


/* =========================================================
   DO GET
   ========================================================= */

function doGet(
    e
) {

    return jsonResponse({

        success: true,

        code:
            "ONLINE",

        status:
            "ONLINE",

        message:
            APP_NAME +
            " API is online.",

        app:
            APP_NAME,

        demoMode:
            DEMO_MODE,

        emailBranding: {

            senderName:
                EMAIL_SENDER_NAME,

            brandName:
                EMAIL_BRAND_NAME,

            footer:
                EMAIL_FOOTER

        },

        sheet:
            SHEET_NAME,

        otp: {

            length:
                OTP_LENGTH,

            expirationMinutes:
                OTP_EXPIRATION_MINUTES,

            maxAttempts:
                OTP_MAX_ATTEMPTS,

            lockMinutes:
                OTP_LOCK_MINUTES,

            resendCooldownSeconds:
                OTP_RESEND_COOLDOWN_SECONDS

        },

        endpoints: [

            "register",
            "registerAdmin",
            "login",
            "prepareOtp",
            "generateOtp",
            "resendOtp",
            "requestOtp",
            "verifyOtp",
            "getUser",
            "updateStatus",
            "forgotPassword",
            "verifyRecoveryOtp",
            "resetPassword"

        ]

    });

}


/* =========================================================
   JSON RESPONSE
   ========================================================= */

function jsonResponse(
    data
) {

    return ContentService
        .createTextOutput(
            JSON.stringify(
                data
            )
        )
        .setMimeType(
            ContentService.MimeType.JSON
        );

}


/* =========================================================
   STARTUP / DIAGNOSTIC
   ========================================================= */

function testStockFlowBackend() {

    const sheet =
        getSheet();


    const result = {

        success:
            true,

        app:
            APP_NAME,

        sheet:
            SHEET_NAME,

        sheetId:
            SHEET_ID,

        firebase:
            FIREBASE_URL,

        demoMode:
            DEMO_MODE,

        otpLength:
            OTP_LENGTH,

        otpExpirationMinutes:
            OTP_EXPIRATION_MINUTES,

        otpMaxAttempts:
            OTP_MAX_ATTEMPTS,

        otpLockMinutes:
            OTP_LOCK_MINUTES,

        otpCooldownSeconds:
            OTP_RESEND_COOLDOWN_SECONDS,

        rowCount:
            Math.max(
                0,
                sheet.getLastRow() - 1
            )

    };


    console.log(
        JSON.stringify(
            result,
            null,
            2
        )
    );


    return result;

}
