/* =========================================================
   STOCKFLOW - GOOGLE APPS SCRIPT BACKEND
   =========================================================
   System:
   StockFlow | Phone Accessories Inventory Management System

   Storage:
   - Google Sheets
   - Firebase Realtime Database

   Authentication:
   - Username / Gmail / Phone
   - Server-generated OTP
   - Email / Phone OTP
   - 4 failed OTP attempts
   - 30-minute OTP lock
   - 120-second independent resend cooldown

   IMPORTANT:
   - OTP is NEVER generated by frontend JavaScript.
   - OTP is generated here on the Apps Script server.
   - DEMO_MODE returns the real server-generated OTP to the frontend
     so the school-project demo can automatically fill the OTP boxes.
   ========================================================= */


/* =========================================================
   1. CONFIGURATION
   ========================================================= */

const SHEET_ID =
  "1w3j0sV9rDiBvS4cpHU31iGb4KIeyUPoALZf5vLH2ivY";

const SHEET_NAME = "USER";

const APP_NAME = "StockFlow";

const FIREBASE_URL =
  "https://midtermexamproject-default-rtdb.firebaseio.com/";

/*
 * SCHOOL PROJECT DEMO MODE
 *
 * true:
 * - Returns the actual backend-generated OTP to frontend.
 * - Allows OTP verification even if MailApp/Twilio is not configured.
 * - Does NOT create fake OTPs.
 *
 * false:
 * - OTP should be delivered through the configured provider.
 */
const DEMO_MODE = true;


/* =========================================================
   OTP SETTINGS
   ========================================================= */

const OTP_LENGTH = 6;

const OTP_EXPIRATION_MS =
  10 * 60 * 1000; // 10 minutes

const OTP_MAX_ATTEMPTS = 4;

const OTP_LOCK_MS =
  30 * 60 * 1000; // 30 minutes

const OTP_COOLDOWN_MS =
  120 * 1000; // 2 minutes


/* =========================================================
   PASSWORD SETTINGS
   ========================================================= */

const PASSWORD_MIN_LENGTH = 8;


/* =========================================================
   USER SHEET HEADERS
   ========================================================= */

const HEADERS = [
  "UID",
  "NAME",
  "USERNAME",
  "PASSWORD",
  "AGE",
  "ACCOUNT_S",
  "GMAIL",
  "PHONE NO.",
  "ROLE",
  "VERIFIED",
  "OTP",
  "OTP EXPIRES",
  "OTP ATTEMPTS",
  "OTP LOCK UNTIL",
  "OTP CHANNEL",
  "CREATED AT",
  "VERIFIED AT",
  "LAST OTP SENT",
  "LAST LOGIN",
  "LAST EMAIL OTP SENT",
  "LAST PHONE OTP SENT"
];


/* =========================================================
   2. GOOGLE SHEET HELPERS
   ========================================================= */

function getSheet() {
  const spreadsheet =
    SpreadsheetApp.openById(SHEET_ID);

  let sheet =
    spreadsheet.getSheetByName(SHEET_NAME);

  if (!sheet) {
    sheet =
      spreadsheet.insertSheet(SHEET_NAME);
  }

  ensureHeaders(sheet);

  return sheet;
}


function ensureHeaders(sheet) {
  const requiredColumns = HEADERS.length;

  if (sheet.getMaxColumns() < requiredColumns) {
    sheet.insertColumnsAfter(
      sheet.getMaxColumns(),
      requiredColumns - sheet.getMaxColumns()
    );
  }

  const currentHeaders =
    sheet
      .getRange(1, 1, 1, requiredColumns)
      .getValues()[0];

  let needsUpdate = false;

  for (let i = 0; i < HEADERS.length; i++) {
    if (currentHeaders[i] !== HEADERS[i]) {
      needsUpdate = true;
      break;
    }
  }

  if (needsUpdate) {
    sheet
      .getRange(1, 1, 1, HEADERS.length)
      .setValues([HEADERS]);
  }
}


function getRows() {
  const sheet = getSheet();

  const lastRow =
    sheet.getLastRow();

  if (lastRow < 2) {
    return [];
  }

  const values =
    sheet
      .getRange(
        2,
        1,
        lastRow - 1,
        HEADERS.length
      )
      .getValues();

  return values.map(function(row, index) {
    return {
      rowNumber: index + 2,
      values: row
    };
  });
}


/* =========================================================
   3. NORMALIZATION HELPERS
   ========================================================= */

function safeString(value) {
  if (value === null || value === undefined) {
    return "";
  }

  return String(value).trim();
}


function normalizeUsername(value) {
  return safeString(value).toLowerCase();
}


function normalizeEmail(value) {
  return safeString(value).toLowerCase();
}


function normalizePhone(value) {
  let phone =
    safeString(value).replace(/\s+/g, "");

  /*
   * Convert:
   * +639XXXXXXXXX
   * 639XXXXXXXXX
   * 09XXXXXXXXX
   * into:
   * 09XXXXXXXXX
   */

  if (phone.indexOf("+63") === 0) {
    phone =
      "0" + phone.substring(3);
  } else if (phone.indexOf("63") === 0 &&
             phone.length === 12) {
    phone =
      "0" + phone.substring(2);
  }

  return phone;
}


function normalizeIdentity(value) {
  const identity =
    safeString(value);

  if (!identity) {
    return "";
  }

  if (
    identity.indexOf("@") !== -1
  ) {
    return normalizeEmail(identity);
  }

  if (
    /^(\+63|63|09)\d+$/.test(identity)
  ) {
    return normalizePhone(identity);
  }

  return normalizeUsername(identity);
}


function normalizeChannel(value) {
  const channel =
    safeString(value).toLowerCase();

  if (
    channel === "phone" ||
    channel === "sms" ||
    channel === "mobile"
  ) {
    return "phone";
  }

  return "email";
}


function normalizeRole(value) {
  const role =
    safeString(value).toLowerCase();

  if (role === "admin") {
    return "Admin";
  }

  if (role === "manager") {
    return "Manager";
  }

  return "Employee";
}


function normalizeAccountStatus(value) {
  const status =
    safeString(value).toUpperCase();

  const allowed = [
    "PENDING",
    "VERIFIED",
    "SUSPENDED",
    "DISABLED",
    "BLOCKED"
  ];

  if (allowed.indexOf(status) !== -1) {
    return status;
  }

  return "PENDING";
}


function normalizeBoolean(value) {
  if (
    value === true ||
    value === "true" ||
    value === "TRUE" ||
    value === 1 ||
    value === "1"
  ) {
    return true;
  }

  return false;
}


/* =========================================================
   4. UID
   ========================================================= */

function generateUID() {
  const timestamp =
    new Date().getTime();

  const randomPart =
    Math.floor(
      Math.random() * 1000000
    )
      .toString()
      .padStart(6, "0");

  return (
    "SF-" +
    timestamp +
    "-" +
    randomPart
  );
}


/* =========================================================
   5. SERVER OTP GENERATION
   ========================================================= */

function generateOTP() {
  let otp = "";

  for (let i = 0; i < OTP_LENGTH; i++) {
    otp += Math.floor(
      Math.random() * 10
    );
  }

  return otp;
}


/* =========================================================
   6. PASSWORD VALIDATION
   ========================================================= */

function validatePassword(password) {
  const value =
    safeString(password);

  if (
    value.length <
    PASSWORD_MIN_LENGTH
  ) {
    return {
      valid: false,
      message:
        "Password must be at least 8 characters."
    };
  }

  if (!/[A-Z]/.test(value)) {
    return {
      valid: false,
      message:
        "Password must contain at least one uppercase letter."
    };
  }

  if (!/[a-z]/.test(value)) {
    return {
      valid: false,
      message:
        "Password must contain at least one lowercase letter."
    };
  }

  if (!/[0-9]/.test(value)) {
    return {
      valid: false,
      message:
        "Password must contain at least one number."
    };
  }

  if (!/[^A-Za-z0-9]/.test(value)) {
    return {
      valid: false,
      message:
        "Password must contain at least one special character."
    };
  }

  return {
    valid: true,
    message: ""
  };
}


/* =========================================================
   7. USER OBJECT
   ========================================================= */

function rowToUser(rowObject) {
  if (!rowObject) {
    return null;
  }

  const row =
    rowObject.values;

  const verified =
    normalizeBoolean(row[9]);

  const accountStatus =
    normalizeAccountStatus(row[5]);

  return {
    rowNumber: rowObject.rowNumber,

    uid: safeString(row[0]),

    name: safeString(row[1]),

    username: safeString(row[2]),

    password: safeString(row[3]),

    age: row[4],

    accountStatus: accountStatus,

    gmail: normalizeEmail(row[6]),

    email: normalizeEmail(row[6]),

    phone: normalizePhone(row[7]),

    role: normalizeRole(row[8]),

    verified: verified,

    otp: safeString(row[10]),

    otpExpires: row[11],

    otpAttempts:
      Number(row[12]) || 0,

    otpLockUntil: row[13],

    otpChannel:
      safeString(row[14]),

    createdAt: row[15],

    verifiedAt: row[16],

    lastOtpSent: row[17],

    lastLogin: row[18],

    lastEmailOtpSent: row[19],

    lastPhoneOtpSent: row[20]
  };
}


/* =========================================================
   8. FIND USER
   ========================================================= */

function findUser(identifier) {
  const normalized =
    normalizeIdentity(identifier);

  if (!normalized) {
    return null;
  }

  const rows =
    getRows();

  for (let i = 0; i < rows.length; i++) {
    const user =
      rowToUser(rows[i]);

    if (!user) {
      continue;
    }

    if (
      safeString(user.uid)
        .toLowerCase() === normalized ||

      normalizeUsername(user.username) === normalized ||

      normalizeEmail(user.gmail) === normalized ||

      normalizePhone(user.phone) === normalized
    ) {
      return user;
    }
  }

  return null;
}


/* =========================================================
   9. FIND USER BY MULTIPLE POSSIBLE IDENTITIES
   ========================================================= */

function resolveUser(data) {
  data =
    data || {};

  const candidates = [
    data.uid,
    data.identity,
    data.username,
    data.gmail,
    data.email,
    data.phone
  ];

  for (let i = 0; i < candidates.length; i++) {
    const value =
      safeString(candidates[i]);

    if (!value) {
      continue;
    }

    const user =
      findUser(value);

    if (user) {
      return user;
    }
  }

  return null;
}


/* =========================================================
   10. REGISTRATION VALIDATION
   ========================================================= */

function validateRegistrationData(data) {
  data =
    data || {};

  const firstName =
    safeString(
      data.firstName ||
      data.firstname
    );

  const lastName =
    safeString(
      data.lastName ||
      data.lastname
    );

  const name =
    safeString(
      data.name ||
      (
        firstName +
        " " +
        lastName
      )
    );

  const username =
    normalizeUsername(
      data.username
    );

  const age =
    Number(data.age);

  const gmail =
    normalizeEmail(
      data.gmail ||
      data.email
    );

  const phone =
    normalizePhone(
      data.phone ||
      data.phoneNumber
    );

  const password =
    safeString(
      data.password
    );

  if (!name) {
    return {
      valid: false,
      code: "NAME_REQUIRED",
      message:
        "Full name is required."
    };
  }

  if (
    !username ||
    username.length < 4 ||
    username.length > 30
  ) {
    return {
      valid: false,
      code: "INVALID_USERNAME",
      message:
        "Username must be 4 to 30 characters."
    };
  }

  if (
    !/^[a-z0-9._-]+$/.test(username)
  ) {
    return {
      valid: false,
      code: "INVALID_USERNAME",
      message:
        "Username may contain letters, numbers, dots, underscores, and hyphens only."
    };
  }

  if (
    !Number.isFinite(age) ||
    age < 18 ||
    age > 100
  ) {
    return {
      valid: false,
      code: "INVALID_AGE",
      message:
        "Age must be between 18 and 100."
    };
  }

  if (
    !gmail ||
    !/^[a-zA-Z0-9._%+-]+@gmail\.com$/i.test(gmail)
  ) {
    return {
      valid: false,
      code: "INVALID_GMAIL",
      message:
        "Please enter a valid Gmail address."
    };
  }

  if (
    !/^09\d{9}$/.test(phone)
  ) {
    return {
      valid: false,
      code: "INVALID_PHONE",
      message:
        "Please enter a valid Philippine mobile number."
    };
  }

  const passwordResult =
    validatePassword(password);

  if (!passwordResult.valid) {
    return {
      valid: false,
      code: "INVALID_PASSWORD",
      message:
        passwordResult.message
    };
  }

  if (
    safeString(data.confirmPassword) &&
    password !==
    safeString(data.confirmPassword)
  ) {
    return {
      valid: false,
      code: "PASSWORD_MISMATCH",
      message:
        "Passwords do not match."
    };
  }

  return {
    valid: true,
    code: "VALID",
    message: "",

    name: name,
    username: username,
    age: age,
    gmail: gmail,
    phone: phone,
    password: password
  };
}


/* =========================================================
   11. DUPLICATE ACCOUNT CHECK
   ========================================================= */

function checkDuplicateUser(
  username,
  gmail,
  phone
) {
  const rows =
    getRows();

  const normalizedUsername =
    normalizeUsername(username);

  const normalizedGmail =
    normalizeEmail(gmail);

  const normalizedPhone =
    normalizePhone(phone);

  for (let i = 0; i < rows.length; i++) {
    const user =
      rowToUser(rows[i]);

    if (
      normalizeUsername(user.username) ===
      normalizedUsername
    ) {
      return {
        duplicate: true,
        code: "USERNAME_EXISTS",
        message:
          "Username already exists."
      };
    }

    if (
      normalizeEmail(user.gmail) ===
      normalizedGmail
    ) {
      return {
        duplicate: true,
        code: "EMAIL_EXISTS",
        message:
          "Gmail address is already registered."
      };
    }

    if (
      normalizePhone(user.phone) ===
      normalizedPhone
    ) {
      return {
        duplicate: true,
        code: "PHONE_EXISTS",
        message:
          "Phone number is already registered."
      };
    }
  }

  return {
    duplicate: false
  };
}


/* =========================================================
   12. FIREBASE HELPERS
   ========================================================= */

function firebaseBaseUrl() {
  return FIREBASE_URL.replace(/\/+$/, "");
}


function firebaseRequest(
  path,
  method,
  payload
) {
  const url =
    firebaseBaseUrl() +
    "/" +
    path.replace(/^\/+/, "") +
    ".json";

  const options = {
    method:
      method || "get",

    muteHttpExceptions: true,

    contentType:
      "application/json"
  };

  if (
    payload !== undefined
  ) {
    options.payload =
      JSON.stringify(payload);
  }

  const response =
    UrlFetchApp.fetch(
      url,
      options
    );

  const status =
    response.getResponseCode();

  const text =
    response.getContentText();

  if (
    status < 200 ||
    status >= 300
  ) {
    throw new Error(
      "Firebase HTTP " +
      status +
      ": " +
      text
    );
  }

  if (!text) {
    return null;
  }

  try {
    return JSON.parse(text);
  } catch (error) {
    return text;
  }
}


/* =========================================================
   13. FIREBASE USER SAVE
   ========================================================= */

function saveFirebaseUser(user) {
  if (!user || !user.uid) {
    return false;
  }

  const path =
    "users/" +
    encodeURIComponent(
      user.uid
    );

  const payload = {
    uid: user.uid,

    name: user.name,

    username: user.username,

    age: user.age,

    accountStatus:
      normalizeAccountStatus(
        user.accountStatus
      ),

    gmail: user.gmail,

    email: user.gmail,

    phone: user.phone,

    role: user.role,

    verified:
      normalizeBoolean(
        user.verified
      ),

    createdAt:
      user.createdAt ||
      new Date().toISOString()
  };

  /*
   * Kept for compatibility with the
   * current school-project structure.
   */
  if (user.password) {
    payload.password =
      user.password;
  }

  firebaseRequest(
    path,
    "put",
    payload
  );

  return true;
}


/* =========================================================
   14. FIREBASE OTP SAVE
   ========================================================= */

function saveOtpToFirebase(
  user,
  otp,
  channel,
  expiresAt
) {
  if (!user || !user.uid) {
    return false;
  }

  const path =
    "users/" +
    encodeURIComponent(
      user.uid
    ) +
    "/otp";

  const payload = {
    code: otp,

    channel: channel,

    expiresAt:
      expiresAt.toISOString(),

    attempts: 0,

    lockUntil: "",

    updatedAt:
      new Date().toISOString()
  };

  firebaseRequest(
    path,
    "put",
    payload
  );

  return true;
}


/* =========================================================
   15. FIREBASE OTP ATTEMPTS
   ========================================================= */

function updateFirebaseOtpAttempts(
  user,
  attempts,
  lockUntil
) {
  if (!user || !user.uid) {
    return false;
  }

  const path =
    "users/" +
    encodeURIComponent(
      user.uid
    ) +
    "/otp";

  const payload = {
    attempts:
      Number(attempts) || 0,

    lockUntil:
      lockUntil
        ? new Date(lockUntil).toISOString()
        : "",

    updatedAt:
      new Date().toISOString()
  };

  firebaseRequest(
    path,
    "patch",
    payload
  );

  return true;
}


/* =========================================================
   16. CLEAR FIREBASE OTP
   ========================================================= */

function clearOtpFromFirebase(user) {
  if (!user || !user.uid) {
    return false;
  }

  const path =
    "users/" +
    encodeURIComponent(
      user.uid
    ) +
    "/otp";

  firebaseRequest(
    path,
    "delete"
  );

  return true;
}


function clearFirebaseOtpFields(user) {
  return clearOtpFromFirebase(user);
}


/* =========================================================
   17. FIREBASE ACCOUNT STATUS SYNC
   ========================================================= */

function syncFirebaseAccountStatus(
  user,
  status
) {
  if (!user || !user.uid) {
    return false;
  }

  const normalizedStatus =
    normalizeAccountStatus(
      status
    );

  const verified =
    normalizedStatus === "VERIFIED";

  const path =
    "users/" +
    encodeURIComponent(
      user.uid
    );

  const payload = {
    accountStatus:
      normalizedStatus,

    verified:
      verified,

    updatedAt:
      new Date().toISOString()
  };

  firebaseRequest(
    path,
    "patch",
    payload
  );

  return true;
}


/* =========================================================
   18. FIREBASE VERIFIED MARKER
   ========================================================= */

function markFirebaseUserVerified(user) {
  return syncFirebaseAccountStatus(
    user,
    "VERIFIED"
  );
}


/* =========================================================
   19. EMAIL
   ========================================================= */

function sendOtpEmail(
  user,
  otp
) {
  const email =
    normalizeEmail(
      user.gmail ||
      user.email
    );

  if (!email) {
    return {
      sent: false,
      error:
        "No Gmail address is registered."
    };
  }

  const subject =
    APP_NAME +
    " - Verification Code";

  const body =
    "Hello " +
    safeString(user.name) +
    ",\n\n" +

    "Your " +
    APP_NAME +
    " verification code is:\n\n" +

    otp +
    "\n\n" +

    "This code will expire in 10 minutes.\n\n" +

    "If you did not request this code, please ignore this message.\n\n" +

    "Regards,\n" +
    APP_NAME;

  try {
    MailApp.sendEmail({
      to: email,
      subject: subject,
      body: body
    });

    return {
      sent: true,
      error: ""
    };

  } catch (error) {
    return {
      sent: false,
      error:
        safeString(
          error.message
        )
    };
  }
}


/* =========================================================
   20. TWILIO SMS
   ========================================================= */

function getTwilioSettings() {
  const properties =
    PropertiesService
      .getScriptProperties();

  return {
    accountSid:
      safeString(
        properties.getProperty(
          "TWILIO_ACCOUNT_SID"
        )
      ),

    authToken:
      safeString(
        properties.getProperty(
          "TWILIO_AUTH_TOKEN"
        )
      ),

    from:
      safeString(
        properties.getProperty(
          "TWILIO_PHONE_NUMBER"
        )
      )
  };
}


function sendOtpSms(
  user,
  otp
) {
  const settings =
    getTwilioSettings();

  if (
    !settings.accountSid ||
    !settings.authToken ||
    !settings.from
  ) {
    return {
      sent: false,
      error:
        "Twilio is not configured."
    };
  }

  const phone =
    normalizePhone(
      user.phone
    );

  if (!phone) {
    return {
      sent: false,
      error:
        "No phone number is registered."
    };
  }

  const internationalPhone =
    "+63" +
    phone.substring(1);

  const url =
    "https://api.twilio.com/2010-04-01/Accounts/" +
    settings.accountSid +
    "/Messages.json";

  const message =
    APP_NAME +
    " verification code: " +
    otp +
    ". Expires in 10 minutes.";

  const options = {
    method: "post",

    muteHttpExceptions: true,

    payload: {
      To: internationalPhone,
      From: settings.from,
      Body: message
    },

    headers: {
      Authorization:
        "Basic " +
        Utilities.base64Encode(
          settings.accountSid +
          ":" +
          settings.authToken
        )
    }
  };

  try {
    const response =
      UrlFetchApp.fetch(
        url,
        options
      );

    const status =
      response.getResponseCode();

    if (
      status >= 200 &&
      status < 300
    ) {
      return {
        sent: true,
        error: ""
      };
    }

    return {
      sent: false,
      error:
        response.getContentText()
    };

  } catch (error) {
    return {
      sent: false,
      error:
        safeString(
          error.message
        )
    };
  }
}


/* =========================================================
   21. SEND OTP BY CHANNEL
   ========================================================= */

function sendOTPByChannel(
  user,
  otp,
  channel
) {
  const selectedChannel =
    normalizeChannel(
      channel
    );

  let emailSent = false;
  let smsSent = false;

  let emailError = "";
  let smsError = "";

  if (
    selectedChannel === "email"
  ) {
    const emailResult =
      sendOtpEmail(
        user,
        otp
      );

    emailSent =
      emailResult.sent;

    emailError =
      emailResult.error;

  } else if (
    selectedChannel === "phone"
  ) {
    const smsResult =
      sendOtpSms(
        user,
        otp
      );

    smsSent =
      smsResult.sent;

    smsError =
      smsResult.error;
  }

  const delivered =
    emailSent ||
    smsSent;

  return {
    channel:
      selectedChannel,

    emailSent:
      emailSent,

    smsSent:
      smsSent,

    delivered:
      delivered,

    emailError:
      emailError,

    smsError:
      smsError
  };
}


/* =========================================================
   22. DATE HELPERS
   ========================================================= */

function toDate(value) {
  if (!value) {
    return null;
  }

  if (
    Object.prototype.toString.call(value) ===
    "[object Date]"
  ) {
    return isNaN(value.getTime())
      ? null
      : value;
  }

  const date =
    new Date(value);

  if (
    isNaN(date.getTime())
  ) {
    return null;
  }

  return date;
}


function isExpired(dateValue) {
  const date =
    toDate(dateValue);

  if (!date) {
    return true;
  }

  return (
    new Date().getTime() >=
    date.getTime()
  );
}


function isLocked(user) {
  if (!user) {
    return false;
  }

  const lockUntil =
    toDate(
      user.otpLockUntil
    );

  if (!lockUntil) {
    return false;
  }

  return (
    new Date().getTime() <
    lockUntil.getTime()
  );
}


/* =========================================================
   23. INDEPENDENT CHANNEL COOLDOWN
   ========================================================= */

function getChannelLastSent(
  user,
  channel
) {
  const selectedChannel =
    normalizeChannel(
      channel
    );

  if (
    selectedChannel === "phone"
  ) {
    return toDate(
      user.lastPhoneOtpSent
    );
  }

  return toDate(
    user.lastEmailOtpSent
  );
}


function getChannelCooldownRemaining(
  user,
  channel
) {
  const lastSent =
    getChannelLastSent(
      user,
      channel
    );

  if (!lastSent) {
    return 0;
  }

  const elapsed =
    new Date().getTime() -
    lastSent.getTime();

  const remaining =
    OTP_COOLDOWN_MS -
    elapsed;

  return Math.max(
    0,
    remaining
  );
}


function isChannelOnCooldown(
  user,
  channel
) {
  return (
    getChannelCooldownRemaining(
      user,
      channel
    ) > 0
  );
}


function cooldownSeconds(
  user,
  channel
) {
  return Math.ceil(
    getChannelCooldownRemaining(
      user,
      channel
    ) / 1000
  );
}


/* =========================================================
   24. SHEET OTP SAVE
   ========================================================= */

function saveOtp(
  user,
  otp,
  channel
) {
  const sheet =
    getSheet();

  const expiresAt =
    new Date(
      new Date().getTime() +
      OTP_EXPIRATION_MS
    );

  const now =
    new Date();

  const row =
    user.rowNumber;

  const previous =
    sheet
      .getRange(
        row,
        11,
        1,
        11
      )
      .getValues()[0];

  /*
   * Columns:
   * 11 OTP
   * 12 OTP EXPIRES
   * 13 OTP ATTEMPTS
   * 14 OTP LOCK UNTIL
   * 15 OTP CHANNEL
   * 16 CREATED AT
   * 17 VERIFIED AT
   * 18 LAST OTP SENT
   * 19 LAST LOGIN
   * 20 LAST EMAIL OTP SENT
   * 21 LAST PHONE OTP SENT
   */

  const values = [
    otp,
    expiresAt,
    0,
    "",
    normalizeChannel(channel),
    previous[5],
    previous[6],
    now,
    previous[8],
    previous[9],
    previous[10]
  ];

  if (
    normalizeChannel(channel) ===
    "email"
  ) {
    values[9] = now;
  } else {
    values[10] = now;
  }

  sheet
    .getRange(
      row,
      11,
      1,
      11
    )
    .setValues([
      values
    ]);

  try {
    saveOtpToFirebase(
      user,
      otp,
      normalizeChannel(channel),
      expiresAt
    );

    return {
      success: true,
      expiresAt: expiresAt
    };

  } catch (error) {

    /*
     * Roll back Sheet OTP if Firebase
     * cannot store the OTP.
     */
    sheet
      .getRange(
        row,
        11,
        1,
        11
      )
      .setValues([
        previous
      ]);

    throw error;
  }
}


/* =========================================================
   25. CLEAR SHEET OTP
   ========================================================= */

function clearSheetOtp(user) {
  if (!user) {
    return false;
  }

  const sheet =
    getSheet();

  const row =
    user.rowNumber;

  sheet
    .getRange(
      row,
      11,
      1,
      5
    )
    .clearContent();

  return true;
}


/* =========================================================
   26. CLEAR OTP COMPLETELY
   ========================================================= */

function clearOtpCompletely(user) {
  if (!user) {
    return false;
  }

  clearSheetOtp(user);

  try {
    clearOtpFromFirebase(user);
  } catch (error) {
    console.warn(
      "Firebase OTP cleanup failed: " +
      error.message
    );
  }

  return true;
}


/* =========================================================
   27. OTP RESPONSE
   ========================================================= */

function otpResponse(
  user,
  otp,
  channel,
  delivery,
  message
) {
  const selectedChannel =
    normalizeChannel(
      channel
    );

  const expiresAt =
    toDate(
      user.otpExpires
    );

  return {
    success: true,

    code: "OTP_READY",

    message:
      message ||
      "Verification code is ready.",

    otp:
      DEMO_MODE
        ? otp
        : undefined,

    otpReady: true,

    otpExpires:
      expiresAt
        ? expiresAt.toISOString()
        : null,

    channel:
      selectedChannel,

    uid:
      user.uid,

    username:
      user.username,

    name:
      user.name,

    gmail:
      user.gmail,

    email:
      user.gmail,

    phone:
      user.phone,

    role:
      user.role,

    accountStatus:
      user.accountStatus,

    verified:
      user.verified,

    emailSent:
      delivery
        ? delivery.emailSent
        : false,

    smsSent:
      delivery
        ? delivery.smsSent
        : false,

    delivered:
      delivery
        ? delivery.delivered
        : false,

    emailDelivery:
      delivery
        ? delivery.emailSent
        : false,

    phoneDelivery:
      delivery
        ? delivery.smsSent
        : false,

    cooldownSeconds:
      OTP_COOLDOWN_MS / 1000,

    demoMode:
      DEMO_MODE
  };
}


/* =========================================================
   28. REGISTER USER
   ========================================================= */

function registerUser(data) {
  data =
    data || {};

  const validation =
    validateRegistrationData(
      data
    );

  if (!validation.valid) {
    return {
      success: false,

      code:
        validation.code,

      message:
        validation.message
    };
  }

  const duplicate =
    checkDuplicateUser(
      validation.username,
      validation.gmail,
      validation.phone
    );

  if (duplicate.duplicate) {
    return {
      success: false,

      code:
        duplicate.code,

      message:
        duplicate.message
    };
  }

  const now =
    new Date();

  const uid =
    generateUID();

  const role =
    "Employee";

  const accountStatus =
    "PENDING";

  const verified =
    false;

  const sheet =
    getSheet();

  const row = [
    uid,

    validation.name,

    validation.username,

    validation.password,

    validation.age,

    accountStatus,

    validation.gmail,

    validation.phone,

    role,

    verified,

    "",
    "",
    0,
    "",
    "",

    now,
    "",

    "",
    "",
    "",
    ""
  ];

  sheet
    .appendRow(row);

  const newUser =
    findUser(uid);

  if (!newUser) {
    return {
      success: false,

      code:
        "REGISTRATION_SAVE_FAILED",

      message:
        "The account was created but could not be loaded. Please try again."
    };
  }

  try {
    saveFirebaseUser(
      newUser
    );
  } catch (error) {

    /*
     * If Firebase fails, remove the
     * newly-created Sheet row.
     */
    sheet.deleteRow(
      newUser.rowNumber
    );

    return {
      success: false,

      code:
        "FIREBASE_SAVE_FAILED",

      message:
        "The account could not be synchronized with the database. Please try again."
    };
  }

  return {
    success: true,

    code:
      "REGISTRATION_SUCCESS",

    message:
      "Registration successful. Please verify your account.",

    uid:
      newUser.uid,

    username:
      newUser.username,

    name:
      newUser.name,

    gmail:
      newUser.gmail,

    email:
      newUser.gmail,

    phone:
      newUser.phone,

    role:
      role,

    verified:
      false,

    accountStatus:
      accountStatus,

    otpReady:
      false,

    otpSent:
      false,

    redirect:
      "verify.html"
  };
}


/* =========================================================
   29. REGISTER ADMIN
   ========================================================= */

function registerAdmin(data) {
  data =
    data || {};

  const validation =
    validateRegistrationData(
      data
    );

  if (!validation.valid) {
    return {
      success: false,

      code:
        validation.code,

      message:
        validation.message
    };
  }

  const duplicate =
    checkDuplicateUser(
      validation.username,
      validation.gmail,
      validation.phone
    );

  if (duplicate.duplicate) {
    return {
      success: false,

      code:
        duplicate.code,

      message:
        duplicate.message
    };
  }

  const now =
    new Date();

  const uid =
    generateUID();

  const role =
    "Admin";

  const accountStatus =
    "PENDING";

  const sheet =
    getSheet();

  sheet.appendRow([
    uid,
    validation.name,
    validation.username,
    validation.password,
    validation.age,
    accountStatus,
    validation.gmail,
    validation.phone,
    role,
    false,
    "",
    "",
    0,
    "",
    "",
    now,
    "",
    "",
    "",
    "",
    ""
  ]);

  const newUser =
    findUser(uid);

  if (!newUser) {
    return {
      success: false,

      code:
        "REGISTRATION_SAVE_FAILED",

      message:
        "The account could not be created."
    };
  }

  try {
    saveFirebaseUser(
      newUser
    );
  } catch (error) {
    getSheet()
      .deleteRow(
        newUser.rowNumber
      );

    return {
      success: false,

      code:
        "FIREBASE_SAVE_FAILED",

      message:
        "The account could not be synchronized with Firebase."
    };
  }

  return {
    success: true,

    code:
      "REGISTRATION_SUCCESS",

    message:
      "Admin registration successful. Please verify the account.",

    uid:
      newUser.uid,

    username:
      newUser.username,

    name:
      newUser.name,

    gmail:
      newUser.gmail,

    email:
      newUser.gmail,

    phone:
      newUser.phone,

    role:
      role,

    verified:
      false,

    accountStatus:
      accountStatus,

    otpReady:
      false,

    otpSent:
      false,

    redirect:
      "verify.html"
  };
}


/* =========================================================
   30. OTP IDENTITY RESOLUTION
   ========================================================= */

function resolveOtpIdentity(data) {
  data =
    data || {};

  return (
    data.uid ||
    data.identity ||
    data.username ||
    data.gmail ||
    data.email ||
    data.phone ||
    ""
  );
}


/* =========================================================
   31. OTP CHANNEL RESOLUTION
   ========================================================= */

function resolveOtpChannel(data) {
  data =
    data || {};

  return normalizeChannel(
    data.channel ||
    "email"
  );
}


/* =========================================================
   32. PREPARE OTP
   ========================================================= */

function prepareOtp(data) {
  data =
    data || {};

  const identity =
    resolveOtpIdentity(
      data
    );

  const channel =
    resolveOtpChannel(
      data
    );

  const user =
    resolveUser(
      data
    ) ||
    findUser(identity);

  if (!user) {
    return {
      success: false,

      code:
        "ACCOUNT_NOT_FOUND",

      message:
        "Account does not exist."
    };
  }

  if (
    user.accountStatus ===
    "DISABLED"
  ) {
    return {
      success: false,

      code:
        "ACCOUNT_DISABLED",

      message:
        "This account is disabled."
    };
  }

  if (
    user.accountStatus ===
    "SUSPENDED"
  ) {
    return {
      success: false,

      code:
        "ACCOUNT_SUSPENDED",

      message:
        "This account is suspended."
    };
  }

  if (
    user.accountStatus ===
    "BLOCKED"
  ) {
    return {
      success: false,

      code:
        "ACCOUNT_BLOCKED",

      message:
        "This account is blocked."
    };
  }

  if (
    isLocked(user)
  ) {
    const lockUntil =
      toDate(
        user.otpLockUntil
      );

    return {
      success: false,

      code:
        "OTP_LOCKED",

      message:
        "Too many incorrect verification attempts. Please try again after the temporary lock expires.",

      locked: true,

      lockUntil:
        lockUntil
          ? lockUntil.toISOString()
          : null
    };
  }

  /*
   * If the user is already verified,
   * registration verification should not
   * generate another verification OTP.
   */
  if (
    user.verified &&
    user.accountStatus ===
    "VERIFIED"
  ) {
    return {
      success: false,

      code:
        "ALREADY_VERIFIED",

      message:
        "This account is already verified."
    };
  }

  /*
   * Independent cooldown:
   *
   * Email has its own timer.
   * Phone has its own timer.
   */
  if (
    isChannelOnCooldown(
      user,
      channel
    )
  ) {
    const seconds =
      cooldownSeconds(
        user,
        channel
      );

    /*
     * If an active OTP exists for the same
     * channel, return it in DEMO_MODE so
     * the frontend can display the current
     * backend OTP instead of generating
     * another one.
     */
    const activeOtp =
      safeString(
        user.otp
      );

    if (
      activeOtp &&
      !isExpired(
        user.otpExpires
      ) &&
      normalizeChannel(
        user.otpChannel
      ) === channel
    ) {
      const existingDelivery = {
        channel: channel,
        emailSent:
          false,
        smsSent:
          false,
        delivered:
          false
      };

      return otpResponse(
        user,
        activeOtp,
        channel,
        existingDelivery,
        "A verification code is already active. Please use the current code."
      );
    }

    return {
      success: false,

      code:
        "OTP_COOLDOWN",

      message:
        "Please wait " +
        seconds +
        " seconds before requesting another " +
        channel +
        " code.",

      cooldownSeconds:
        seconds,

      channel:
        channel
    };
  }

  /*
   * Generate REAL OTP on the backend.
   */
  const otp =
    generateOTP();

  /*
   * Save same OTP to Sheet + Firebase.
   */
  try {
    saveOtp(
      user,
      otp,
      channel
    );
  } catch (error) {
    return {
      success: false,

      code:
        "OTP_STORAGE_FAILED",

      message:
        "The verification code could not be stored. Please try again.",

      detail:
        safeString(
          error.message
        )
    };
  }

  /*
   * Reload user so timestamps and OTP
   * fields are current.
   */
  const updatedUser =
    findUser(
      user.uid
    ) || user;

  /*
   * Deliver OTP through selected channel.
   */
  const delivery =
    sendOTPByChannel(
      updatedUser,
      otp,
      channel
    );

  /*
   * SCHOOL DEMO MODE:
   *
   * We return the REAL generated OTP.
   *
   * We do NOT say that email/SMS was sent
   * if the provider is unavailable.
   */
  if (DEMO_MODE) {

    let message =
      "Verification code is ready.";

    if (
      delivery.delivered
    ) {
      message =
        channel === "email"
          ? "Verification code generated and sent by email."
          : "Verification code generated and sent by phone.";
    } else {
      message =
        "Verification code generated by the backend. Demo mode is enabled because delivery service is not configured.";
    }

    return otpResponse(
      updatedUser,
      otp,
      channel,
      delivery,
      message
    );
  }

  /*
   * PRODUCTION MODE:
   *
   * If the selected delivery method fails,
   * remove the OTP so it cannot be used.
   */
  if (
    !delivery.delivered
  ) {
    clearOtpCompletely(
      updatedUser
    );

    return {
      success: false,

      code:
        "OTP_DELIVERY_FAILED",

      message:
        channel === "email"
          ? "The verification email could not be sent."
          : "The verification SMS could not be sent."
    };
  }

  return otpResponse(
    updatedUser,
    otp,
    channel,
    delivery,
    channel === "email"
      ? "Verification code sent by email."
      : "Verification code sent by phone."
  );
}


/* =========================================================
   33. GENERATE OTP COMPATIBILITY
   ========================================================= */

function generateOtp(data) {
  return prepareOtp(
    data
  );
}


/* =========================================================
   34. RESEND OTP
   ========================================================= */

function resendOTP(data) {
  /*
   * Resend uses the same backend OTP generation
   * mechanism, but requires the current channel
   * cooldown to have expired.
   */
  return prepareOtp(
    data
  );
}


/* =========================================================
   35. REQUEST OTP COMPATIBILITY
   ========================================================= */

function requestOtp(data) {
  return resendOTP(
    data
  );
}


/* =========================================================
   36. VERIFY REGISTRATION OTP
   ========================================================= */

function verifyOTP(data) {
  data =
    data || {};

  const identity =
    resolveOtpIdentity(
      data
    );

  const otp =
    safeString(
      data.otp ||
      data.code
    ).replace(
      /\D/g,
      ""
    );

  if (
    otp.length !== OTP_LENGTH
  ) {
    return {
      success: false,

      code:
        "INVALID_OTP_FORMAT",

      message:
        "Please enter the complete 6-digit verification code."
    };
  }

  const user =
    resolveUser(
      data
    ) ||
    findUser(identity);

  if (!user) {
    return {
      success: false,

      code:
        "ACCOUNT_NOT_FOUND",

      message:
        "Account does not exist."
    };
  }

  if (
    user.accountStatus ===
    "DISABLED"
  ) {
    return {
      success: false,

      code:
        "ACCOUNT_DISABLED",

      message:
        "This account is disabled."
    };
  }

  if (
    user.accountStatus ===
    "SUSPENDED"
  ) {
    return {
      success: false,

      code:
        "ACCOUNT_SUSPENDED",

      message:
        "This account is suspended."
    };
  }

  if (
    user.accountStatus ===
    "BLOCKED"
  ) {
    return {
      success: false,

      code:
        "ACCOUNT_BLOCKED",

      message:
        "This account is blocked."
    };
  }

  if (
    user.verified
  ) {
    return {
      success: true,

      code:
        "ALREADY_VERIFIED",

      message:
        "Account is already verified.",

      uid:
        user.uid,

      username:
        user.username,

      name:
        user.name,

      gmail:
        user.gmail,

      email:
        user.gmail,

      phone:
        user.phone,

      role:
        user.role,

      verified:
        true,

      accountStatus:
        "VERIFIED"
    };
  }

  if (
    isLocked(user)
  ) {
    const lockUntil =
      toDate(
        user.otpLockUntil
      );

    return {
      success: false,

      code:
        "OTP_LOCKED",

      message:
        "Too many incorrect verification attempts. Please wait until the temporary lock expires.",

      locked: true,

      lockUntil:
        lockUntil
          ? lockUntil.toISOString()
          : null
    };
  }

  if (
    !user.otp
  ) {
    return {
      success: false,

      code:
        "OTP_NOT_READY",

      message:
        "No verification code is currently active. Please request a new code."
    };
  }

  if (
    isExpired(
      user.otpExpires
    )
  ) {
    clearOtpCompletely(
      user
    );

    return {
      success: false,

      code:
        "OTP_EXPIRED",

      message:
        "The verification code has expired. Please request a new code."
    };
  }

  /*
   * Compare server-stored OTP with
   * user-provided OTP.
   */
  if (
    otp !==
    safeString(user.otp)
  ) {
    const newAttempts =
      (Number(
        user.otpAttempts
      ) || 0) + 1;

    let lockUntil = "";

    if (
      newAttempts >=
      OTP_MAX_ATTEMPTS
    ) {
      lockUntil =
        new Date(
          new Date().getTime() +
          OTP_LOCK_MS
        );
    }

    const sheet =
      getSheet();

    sheet
      .getRange(
        user.rowNumber,
        13
      )
      .setValue(
        newAttempts
      );

    if (lockUntil) {
      sheet
        .getRange(
          user.rowNumber,
          14
        )
        .setValue(
          lockUntil
        );
    }

    try {
      updateFirebaseOtpAttempts(
        user,
        newAttempts,
        lockUntil
      );
    } catch (error) {
      console.warn(
        "Firebase OTP attempt sync failed: " +
        error.message
      );
    }

    if (
      newAttempts >=
      OTP_MAX_ATTEMPTS
    ) {
      return {
        success: false,

        code:
          "OTP_LOCKED",

        message:
          "You entered the wrong code 4 times. Your account verification is temporarily locked for 30 minutes.",

        locked: true,

        attempts:
          newAttempts,

        lockUntil:
          lockUntil.toISOString()
      };
    }

    return {
      success: false,

      code:
        "INVALID_OTP",

      message:
        "Incorrect verification code. Please try again.",

      attempts:
        newAttempts,

      remainingAttempts:
        OTP_MAX_ATTEMPTS -
        newAttempts
    };
  }

  /*
   * OTP is correct.
   *
   * Mark account verified.
   */
  const sheet =
    getSheet();

  const verifiedAt =
    new Date();

  sheet
    .getRange(
      user.rowNumber,
      6
    )
    .setValue(
      "VERIFIED"
    );

  sheet
    .getRange(
      user.rowNumber,
      10
    )
    .setValue(
      true
    );

  sheet
    .getRange(
      user.rowNumber,
      13
    )
    .setValue(
      0
    );

  sheet
    .getRange(
      user.rowNumber,
      14
    )
    .clearContent();

  sheet
    .getRange(
      user.rowNumber,
      17
    )
    .setValue(
      verifiedAt
    );

  /*
   * Clear OTP after successful verification.
   */
  clearSheetOtp(
    user
  );

  /*
   * Update Firebase with the ACTUAL
   * account status.
   */
  const updatedUser =
    findUser(
      user.uid
    ) || user;

  try {
    syncFirebaseAccountStatus(
      updatedUser,
      "VERIFIED"
    );

    clearFirebaseOtpFields(
      updatedUser
    );

  } catch (error) {
    /*
     * Sheet remains authoritative for this
     * school project, but report Firebase
     * synchronization failure.
     */
    console.warn(
      "Firebase verification sync failed: " +
      error.message
    );
  }

  const finalUser =
    findUser(
      user.uid
    ) || updatedUser;

  return {
    success: true,

    code:
      "ACCOUNT_VERIFIED",

    message:
      "Account verified successfully.",

    uid:
      finalUser.uid,

    username:
      finalUser.username,

    name:
      finalUser.name,

    gmail:
      finalUser.gmail,

    email:
      finalUser.gmail,

    phone:
      finalUser.phone,

    role:
      finalUser.role,

    verified:
      true,

    accountStatus:
      "VERIFIED",

    redirect:
      "dashboard.html"
  };
}


/* =========================================================
   37. LOGIN
   ========================================================= */

function loginUser(data) {
  data =
    data || {};

  const identity =
    safeString(
      data.identity ||
      data.username ||
      data.email ||
      data.gmail ||
      data.phone
    );

  const password =
    safeString(
      data.password
    );

  if (!identity) {
    return {
      success: false,

      code:
        "IDENTITY_REQUIRED",

      message:
        "Please enter your username, email, or phone number."
    };
  }

  if (!password) {
    return {
      success: false,

      code:
        "PASSWORD_REQUIRED",

      message:
        "Please enter your password."
    };
  }

  const user =
    findUser(
      identity
    );

  /*
   * IMPORTANT:
   * This now returns a clear business error
   * instead of being converted into a network
   * error by the frontend API layer.
   */
  if (!user) {
    return {
      success: false,

      code:
        "ACCOUNT_NOT_FOUND",

      message:
        "Account does not exist."
    };
  }

  if (
    user.accountStatus ===
    "SUSPENDED"
  ) {
    return {
      success: false,

      code:
        "ACCOUNT_SUSPENDED",

      message:
        "This account is suspended."
    };
  }

  if (
    user.accountStatus ===
    "DISABLED"
  ) {
    return {
      success: false,

      code:
        "ACCOUNT_DISABLED",

      message:
        "This account is disabled."
    };
  }

  if (
    user.accountStatus ===
    "BLOCKED"
  ) {
    return {
      success: false,

      code:
        "ACCOUNT_BLOCKED",

      message:
        "This account is blocked."
    };
  }

  /*
   * Password remains compatible with your
   * current USER sheet structure.
   */
  if (
    safeString(
      user.password
    ) !== password
  ) {
    return {
      success: false,

      code:
        "INVALID_CREDENTIALS",

      message:
        "Incorrect username/email/phone or password."
    };
  }

  /*
   * Pending/unverified account.
   */
  if (
    !user.verified ||
    user.accountStatus !==
    "VERIFIED"
  ) {
    return {
      success: false,

      code:
        "REQUIRES_VERIFICATION",

      message:
        "Account is not verified. Please verify your OTP.",

      verified:
        false,

      requiresVerification:
        true,

      needsVerification:
        true,

      uid:
        user.uid,

      username:
        user.username,

      gmail:
        user.gmail,

      email:
        user.gmail,

      phone:
        user.phone,

      role:
        user.role,

      accountStatus:
        user.accountStatus
    };
  }

  /*
   * Successful login.
   */
  const sheet =
    getSheet();

  sheet
    .getRange(
      user.rowNumber,
      19
    )
    .setValue(
      new Date()
    );

  const finalUser =
    findUser(
      user.uid
    ) || user;

  return {
    success: true,

    code:
      "LOGIN_SUCCESS",

    message:
      "Login successful.",

    uid:
      finalUser.uid,

    username:
      finalUser.username,

    name:
      finalUser.name,

    gmail:
      finalUser.gmail,

    email:
      finalUser.gmail,

    phone:
      finalUser.phone,

    role:
      finalUser.role,

    age:
      finalUser.age,

    verified:
      true,

    accountStatus:
      "VERIFIED",

    redirect:
      "dashboard.html"
  };
}


/* =========================================================
   38. GET USER
   ========================================================= */

function getUser(data) {
  data =
    data || {};

  const user =
    resolveUser(
      data
    );

  if (!user) {
    return {
      success: false,

      code:
        "ACCOUNT_NOT_FOUND",

      message:
        "Account does not exist."
    };
  }

  return {
    success: true,

    code:
      "USER_FOUND",

    message:
      "User found.",

    uid:
      user.uid,

    username:
      user.username,

    name:
      user.name,

    gmail:
      user.gmail,

    email:
      user.gmail,

    phone:
      user.phone,

    age:
      user.age,

    role:
      user.role,

    verified:
      user.verified,

    accountStatus:
      user.accountStatus,

    createdAt:
      user.createdAt,

    verifiedAt:
      user.verifiedAt,

    lastLogin:
      user.lastLogin
  };
}


/* =========================================================
   39. UPDATE ACCOUNT STATUS
   ========================================================= */

function updateAccountStatus(data) {
  data =
    data || {};

  const user =
    resolveUser(
      data
    );

  if (!user) {
    return {
      success: false,

      code:
        "ACCOUNT_NOT_FOUND",

      message:
        "Account does not exist."
    };
  }

  const requestedStatus =
    normalizeAccountStatus(
      data.status ||
      data.accountStatus
    );

  const sheet =
    getSheet();

  /*
   * Sheet account status.
   */
  sheet
    .getRange(
      user.rowNumber,
      6
    )
    .setValue(
      requestedStatus
    );

  /*
   * VERIFIED should only be true when
   * account status is actually VERIFIED.
   */
  const verified =
    requestedStatus ===
    "VERIFIED";

  sheet
    .getRange(
      user.rowNumber,
      10
    )
    .setValue(
      verified
    );

  /*
   * FIX:
   *
   * The old implementation always called
   * markFirebaseUserVerified(), which changed
   * SUSPENDED/DISABLED/BLOCKED accounts back
   * into VERIFIED in Firebase.
   *
   * This now synchronizes the ACTUAL requested
   * status.
   */
  try {
    syncFirebaseAccountStatus(
      user,
      requestedStatus
    );
  } catch (error) {
    return {
      success: false,

      code:
        "FIREBASE_STATUS_SYNC_FAILED",

      message:
        "Account status was updated in Google Sheets but could not be synchronized with Firebase.",

      detail:
        safeString(
          error.message
        )
    };
  }

  const updatedUser =
    findUser(
      user.uid
    ) || user;

  return {
    success: true,

    code:
      "ACCOUNT_STATUS_UPDATED",

    message:
      "Account status updated successfully.",

    uid:
      updatedUser.uid,

    username:
      updatedUser.username,

    role:
      updatedUser.role,

    verified:
      verified,

    accountStatus:
      requestedStatus
  };
}


/* =========================================================
   40. FORGOT PASSWORD
   ========================================================= */

function forgotPassword(data) {
  data =
    data || {};

  const identity =
    resolveOtpIdentity(
      data
    );

  const user =
    resolveUser(
      data
    ) ||
    findUser(identity);

  /*
   * For this StockFlow school project,
   * return ACCOUNT_NOT_FOUND so the frontend
   * can clearly show the user that the account
   * does not exist.
   */
  if (!user) {
    return {
      success: false,

      code:
        "ACCOUNT_NOT_FOUND",

      message:
        "Account does not exist."
    };
  }

  if (
    user.accountStatus ===
    "DISABLED"
  ) {
    return {
      success: false,

      code:
        "ACCOUNT_DISABLED",

      message:
        "This account is disabled."
    };
  }

  if (
    user.accountStatus ===
    "SUSPENDED"
  ) {
    return {
      success: false,

      code:
        "ACCOUNT_SUSPENDED",

      message:
        "This account is suspended."
    };
  }

  if (
    user.accountStatus ===
    "BLOCKED"
  ) {
    return {
      success: false,

      code:
        "ACCOUNT_BLOCKED",

      message:
        "This account is blocked."
    };
  }

  /*
   * Only verified accounts can perform
   * password recovery.
   */
  if (!user.verified) {
    return {
      success: false,

      code:
        "REQUIRES_VERIFICATION",

      message:
        "This account is not verified. Please verify the account first."
    };
  }

  /*
   * Recovery can use email or phone.
   * Default = email.
   */
  const channel =
    normalizeChannel(
      data.channel ||
      "email"
    );

  /*
   * Independent 120-second cooldown.
   */
  if (
    isChannelOnCooldown(
      user,
      channel
    )
  ) {
    const seconds =
      cooldownSeconds(
        user,
        channel
      );

    return {
      success: false,

      code:
        "OTP_COOLDOWN",

      message:
        "Please wait " +
        seconds +
        " seconds before requesting another " +
        channel +
        " recovery code.",

      cooldownSeconds:
        seconds,

      channel:
        channel
    };
  }

  const otp =
    generateOTP();

  try {
    saveOtp(
      user,
      otp,
      channel
    );
  } catch (error) {
    return {
      success: false,

      code:
        "OTP_STORAGE_FAILED",

      message:
        "The recovery code could not be stored. Please try again.",

      detail:
        safeString(
          error.message
        )
    };
  }

  const updatedUser =
    findUser(
      user.uid
    ) || user;

  const delivery =
    sendOTPByChannel(
      updatedUser,
      otp,
      channel
    );

  if (
    DEMO_MODE
  ) {
    let message =
      "Recovery code generated by the backend.";

    if (
      delivery.delivered
    ) {
      message =
        channel === "email"
          ? "Recovery code generated and sent by email."
          : "Recovery code generated and sent by phone.";
    }

    return {
      success: true,

      code:
        "RECOVERY_OTP_READY",

      message:
        message,

      otp:
        otp,

      otpReady:
        true,

      demoMode:
        true,

      uid:
        updatedUser.uid,

      username:
        updatedUser.username,

      name:
        updatedUser.name,

      gmail:
        updatedUser.gmail,

      email:
        updatedUser.gmail,

      phone:
        updatedUser.phone,

      channel:
        channel,

      emailSent:
        delivery.emailSent,

      smsSent:
        delivery.smsSent,

      delivered:
        delivery.delivered,

      otpExpires:
        updatedUser.otpExpires
          ? new Date(
              updatedUser.otpExpires
            ).toISOString()
          : null,

      cooldownSeconds:
        OTP_COOLDOWN_MS / 1000
    };
  }

  if (
    !delivery.delivered
  ) {
    clearOtpCompletely(
      updatedUser
    );

    return {
      success: false,

      code:
        "OTP_DELIVERY_FAILED",

      message:
        channel === "email"
          ? "The recovery email could not be sent."
          : "The recovery SMS could not be sent."
    };
  }

  return {
    success: true,

    code:
      "RECOVERY_OTP_READY",

    message:
      channel === "email"
        ? "Recovery code sent by email."
        : "Recovery code sent by phone.",

    otpReady:
      true,

    demoMode:
      false,

    uid:
      updatedUser.uid,

    username:
      updatedUser.username,

    gmail:
      updatedUser.gmail,

    email:
      updatedUser.gmail,

    phone:
      updatedUser.phone,

    channel:
      channel,

    emailSent:
      delivery.emailSent,

    smsSent:
      delivery.smsSent,

    delivered:
      delivery.delivered,

    otpExpires:
      updatedUser.otpExpires
        ? new Date(
            updatedUser.otpExpires
          ).toISOString()
        : null,

    cooldownSeconds:
      OTP_COOLDOWN_MS / 1000
  };
}


/* =========================================================
   41. RECOVERY TOKEN HELPERS
   ========================================================= */

function recoveryTokenKey(uid) {
  return (
    "SF_RECOVERY_" +
    safeString(uid)
  );
}


function createRecoveryToken(
  user
) {
  const token =
    Utilities.getUuid();

  const expiresAt =
    new Date(
      new Date().getTime() +
      10 * 60 * 1000
    );

  const payload = {
    token:
      token,

    uid:
      user.uid,

    expiresAt:
      expiresAt.toISOString()
  };

  PropertiesService
    .getScriptProperties()
    .setProperty(
      recoveryTokenKey(
        user.uid
      ),
      JSON.stringify(
        payload
      )
    );

  return {
    token:
      token,

    expiresAt:
      expiresAt
  };
}


function getRecoveryToken(
  uid
) {
  const raw =
    PropertiesService
      .getScriptProperties()
      .getProperty(
        recoveryTokenKey(
          uid
        )
      );

  if (!raw) {
    return null;
  }

  try {
    return JSON.parse(
      raw
    );
  } catch (error) {
    return null;
  }
}


function clearRecoveryToken(
  uid
) {
  PropertiesService
    .getScriptProperties()
    .deleteProperty(
      recoveryTokenKey(
        uid
      )
    );

  return true;
}


/* =========================================================
   42. VERIFY RECOVERY OTP
   ========================================================= */

function verifyRecoveryOtp(data) {
  data =
    data || {};

  const identity =
    resolveOtpIdentity(
      data
    );

  const otp =
    safeString(
      data.otp ||
      data.code
    ).replace(
      /\D/g,
      ""
    );

  if (
    otp.length !== OTP_LENGTH
  ) {
    return {
      success: false,

      code:
        "INVALID_OTP_FORMAT",

      message:
        "Please enter the complete 6-digit recovery code."
    };
  }

  const user =
    resolveUser(
      data
    ) ||
    findUser(identity);

  if (!user) {
    return {
      success: false,

      code:
        "ACCOUNT_NOT_FOUND",

      message:
        "Account does not exist."
    };
  }

  if (
    !user.verified
  ) {
    return {
      success: false,

      code:
        "REQUIRES_VERIFICATION",

      message:
        "This account is not verified."
    };
  }

  if (
    isLocked(user)
  ) {
    const lockUntil =
      toDate(
        user.otpLockUntil
      );

    return {
      success: false,

      code:
        "OTP_LOCKED",

      message:
        "Too many incorrect attempts. Please wait until the temporary lock expires.",

      locked: true,

      lockUntil:
        lockUntil
          ? lockUntil.toISOString()
          : null
    };
  }

  if (
    !user.otp
  ) {
    return {
      success: false,

      code:
        "OTP_NOT_READY",

      message:
        "No recovery code is currently active. Please request a new code."
    };
  }

  if (
    isExpired(
      user.otpExpires
    )
  ) {
    clearOtpCompletely(
      user
    );

    return {
      success: false,

      code:
        "OTP_EXPIRED",

      message:
        "The recovery code has expired. Please request a new code."
    };
  }

  if (
    otp !==
    safeString(
      user.otp
    )
  ) {
    const newAttempts =
      (Number(
        user.otpAttempts
      ) || 0) + 1;

    let lockUntil = "";

    if (
      newAttempts >=
      OTP_MAX_ATTEMPTS
    ) {
      lockUntil =
        new Date(
          new Date().getTime() +
          OTP_LOCK_MS
        );
    }

    const sheet =
      getSheet();

    sheet
      .getRange(
        user.rowNumber,
        13
      )
      .setValue(
        newAttempts
      );

    if (lockUntil) {
      sheet
        .getRange(
          user.rowNumber,
          14
        )
        .setValue(
          lockUntil
        );
    }

    try {
      updateFirebaseOtpAttempts(
        user,
        newAttempts,
        lockUntil
      );
    } catch (error) {
      console.warn(
        "Firebase recovery attempt sync failed: " +
        error.message
      );
    }

    if (
      newAttempts >=
      OTP_MAX_ATTEMPTS
    ) {
      return {
        success: false,

        code:
          "OTP_LOCKED",

        message:
          "You entered the wrong recovery code 4 times. Recovery is temporarily locked for 30 minutes.",

        locked: true,

        attempts:
          newAttempts,

        lockUntil:
          lockUntil.toISOString()
      };
    }

    return {
      success: false,

      code:
        "INVALID_OTP",

      message:
        "Incorrect recovery code. Please try again.",

      attempts:
        newAttempts,

      remainingAttempts:
        OTP_MAX_ATTEMPTS -
        newAttempts
    };
  }

  /*
   * Correct recovery OTP.
   *
   * Create a server-side recovery token.
   */
  const recovery =
    createRecoveryToken(
      user
    );

  /*
   * OTP cannot be reused after successful
   * recovery verification.
   */
  clearOtpCompletely(
    user
  );

  return {
    success: true,

    code:
      "RECOVERY_VERIFIED",

    message:
      "Recovery code verified. You may now create a new password.",

    recoveryVerified:
      true,

    otpVerified:
      true,

    recoveryToken:
      recovery.token,

    recoveryTokenExpires:
      recovery.expiresAt.toISOString(),

    uid:
      user.uid,

    username:
      user.username,

    gmail:
      user.gmail,

    email:
      user.gmail,

    phone:
      user.phone,

    role:
      user.role,

    verified:
      user.verified,

    accountStatus:
      user.accountStatus
  };
}


/* =========================================================
   43. RESET PASSWORD
   ========================================================= */

function resetPassword(data) {
  data =
    data || {};

  const uid =
    safeString(
      data.uid
    );

  const identity =
    safeString(
      data.identity ||
      data.username ||
      data.email ||
      data.gmail ||
      data.phone
    );

  const newPassword =
    safeString(
      data.newPassword ||
      data.password
    );

  const confirmPassword =
    safeString(
      data.confirmPassword
    );

  const recoveryToken =
    safeString(
      data.recoveryToken ||
      data.token
    );

  if (!recoveryToken) {
    return {
      success: false,

      code:
        "RECOVERY_TOKEN_REQUIRED",

      message:
        "Recovery verification is required before changing the password."
    };
  }

  if (
    newPassword !==
    confirmPassword
  ) {
    return {
      success: false,

      code:
        "PASSWORD_MISMATCH",

      message:
        "Passwords do not match."
    };
  }

  const passwordResult =
    validatePassword(
      newPassword
    );

  if (
    !passwordResult.valid
  ) {
    return {
      success: false,

      code:
        "INVALID_PASSWORD",

      message:
        passwordResult.message
    };
  }

  let user =
    null;

  if (uid) {
    user =
      findUser(uid);
  }

  if (!user && identity) {
    user =
      findUser(identity);
  }

  if (!user) {
    return {
      success: false,

      code:
        "ACCOUNT_NOT_FOUND",

      message:
        "Account does not exist."
    };
  }

  /*
   * Validate server-side recovery token.
   */
  const stored =
    getRecoveryToken(
      user.uid
    );

  if (!stored) {
    return {
      success: false,

      code:
        "RECOVERY_SESSION_EXPIRED",

      message:
        "Your password recovery session has expired. Please request a new recovery code."
    };
  }

  if (
    stored.token !==
    recoveryToken
  ) {
    return {
      success: false,

      code:
        "INVALID_RECOVERY_TOKEN",

      message:
        "Invalid password recovery session."
    };
  }

  if (
    !stored.expiresAt ||
    isExpired(
      stored.expiresAt
    )
  ) {
    clearRecoveryToken(
      user.uid
    );

    return {
      success: false,

      code:
        "RECOVERY_SESSION_EXPIRED",

      message:
        "Your password recovery session has expired. Please request a new recovery code."
    };
  }

  /*
   * Update password in Google Sheet.
   *
   * Existing project structure stores the
   * password in the USER sheet, so this keeps
   * compatibility with the current system.
   */
  const sheet =
    getSheet();

  sheet
    .getRange(
      user.rowNumber,
      4
    )
    .setValue(
      newPassword
    );

  /*
   * IMPORTANT:
   * Password reset does NOT automatically
   * change verification/account status.
   */
  clearRecoveryToken(
    user.uid
  );

  clearOtpCompletely(
    user
  );

  /*
   * Sync Firebase user password for compatibility
   * with the current project structure.
   */
  try {
    firebaseRequest(
      "users/" +
      encodeURIComponent(
        user.uid
      ),
      "patch",
      {
        password:
          newPassword,

        updatedAt:
          new Date().toISOString()
      }
    );
  } catch (error) {
    return {
      success: false,

      code:
        "FIREBASE_PASSWORD_SYNC_FAILED",

      message:
        "Password was updated locally but could not be synchronized with Firebase.",

      detail:
        safeString(
          error.message
        )
    };
  }

  return {
    success: true,

    code:
      "PASSWORD_RESET_SUCCESS",

    message:
      "Password reset successfully.",

    uid:
      user.uid,

    username:
      user.username,

    gmail:
      user.gmail,

    email:
      user.gmail,

    phone:
      user.phone,

    role:
      user.role,

    verified:
      user.verified,

    accountStatus:
      user.accountStatus,

    redirect:
      "auth.html"
  };
}


/* =========================================================
   44. REQUEST BODY PARSER
   ========================================================= */

function parseRequestBody(e) {
  if (
    !e ||
    !e.postData
  ) {
    return {};
  }

  const raw =
    safeString(
      e.postData.contents
    );

  if (!raw) {
    return {};
  }

  try {
    return JSON.parse(
      raw
    );
  } catch (error) {
    /*
     * Support form-style requests as a
     * compatibility fallback.
     */
    return e.parameter || {};
  }
}


/* =========================================================
   45. JSON RESPONSE
   ========================================================= */

function jsonResponse(data) {
  return ContentService
    .createTextOutput(
      JSON.stringify(
        data
      )
    )
    .setMimeType(
      ContentService
        .MimeType
        .JSON
    );
}


/* =========================================================
   46. doPost
   ========================================================= */

function doPost(e) {
  try {
    const data =
      parseRequestBody(
        e
      );

    const action =
      safeString(
        data.action ||
        data.endpoint ||
        data.operation
      ).toLowerCase();

    switch (action) {

      /* -----------------------------------------
         AUTHENTICATION
         ----------------------------------------- */

      case "register":
      case "registeruser":
        return jsonResponse(
          registerUser(
            data
          )
        );


      case "registeradmin":
      case "register_admin":
        return jsonResponse(
          registerAdmin(
            data
          )
        );


      case "login":
      case "loginuser":
        return jsonResponse(
          loginUser(
            data
          )
        );


      case "getuser":
      case "user":
        return jsonResponse(
          getUser(
            data
          )
        );


      /* -----------------------------------------
         REGISTRATION OTP
         ----------------------------------------- */

      case "prepareotp":
      case "prepare_otp":
        return jsonResponse(
          prepareOtp(
            data
          )
        );


      case "generateotp":
      case "generate_otp":
        return jsonResponse(
          generateOtp(
            data
          )
        );


      case "resendotp":
      case "resend_otp":
        return jsonResponse(
          resendOTP(
            data
          )
        );


      case "requestotp":
      case "request_otp":
        return jsonResponse(
          requestOtp(
            data
          )
        );


      case "verifyotp":
      case "verify_otp":
        return jsonResponse(
          verifyOTP(
            data
          )
        );


      /* -----------------------------------------
         PASSWORD RECOVERY
         ----------------------------------------- */

      case "forgotpassword":
      case "forgot_password":
        return jsonResponse(
          forgotPassword(
            data
          )
        );


      case "verifyrecoveryotp":
      case "verify_recovery_otp":
        return jsonResponse(
          verifyRecoveryOtp(
            data
          )
        );


      case "resetpassword":
      case "reset_password":
        return jsonResponse(
          resetPassword(
            data
          )
        );


      /* -----------------------------------------
         ACCOUNT MANAGEMENT
         ----------------------------------------- */

      case "updatestatus":
      case "update_status":
      case "updateaccountstatus":
      case "update_account_status":
        return jsonResponse(
          updateAccountStatus(
            data
          )
        );


      /* -----------------------------------------
         UNKNOWN ACTION
         ----------------------------------------- */

      default:
        return jsonResponse({
          success: false,

          code:
            "UNKNOWN_ACTION",

          message:
            "Unknown API action: " +
            (
              action ||
              "(empty)"
            )
        });
    }

  } catch (error) {

    console.error(
      "doPost error:",
      error
    );

    return jsonResponse({
      success: false,

      code:
        "SERVER_ERROR",

      message:
        "The server encountered an unexpected error.",

      detail:
        DEMO_MODE
          ? safeString(
              error.message
            )
          : undefined
    });
  }
}


/* =========================================================
   47. doGet
   ========================================================= */

function doGet() {
  return jsonResponse({
    success: true,

    code:
      "ONLINE",

    status:
      "ONLINE",

    message:
      APP_NAME +
      " API is online.",

    app:
      APP_NAME,

    demoMode:
      DEMO_MODE,

    sheet:
      SHEET_NAME,

    otp: {
      length:
        OTP_LENGTH,

      expirationMinutes:
        OTP_EXPIRATION_MS /
        60000,

      maxAttempts:
        OTP_MAX_ATTEMPTS,

      lockMinutes:
        OTP_LOCK_MS /
        60000,

      resendCooldownSeconds:
        OTP_COOLDOWN_MS /
        1000
    },

    endpoints: [
      "register",
      "registerAdmin",
      "login",
      "getUser",
      "prepareOtp",
      "generateOtp",
      "resendOtp",
      "requestOtp",
      "verifyOtp",
      "forgotPassword",
      "verifyRecoveryOtp",
      "resetPassword",
      "updateStatus"
    ]
  });
}


/* =========================================================
   48. OPTIONAL TEST FUNCTION
   ========================================================= */

function testStockFlowBackend() {
  const sheet =
    getSheet();

  console.log(
    "StockFlow backend test started."
  );

  console.log(
    "Sheet: " +
    sheet.getName()
  );

  console.log(
    "Firebase: " +
    FIREBASE_URL
  );

  console.log(
    "Demo mode: " +
    DEMO_MODE
  );

  console.log(
    "OTP length: " +
    OTP_LENGTH
  );

  console.log(
    "OTP expiration: " +
    (
      OTP_EXPIRATION_MS /
      60000
    ) +
    " minutes"
  );

  console.log(
    "OTP cooldown: " +
    (
      OTP_COOLDOWN_MS /
      1000
    ) +
    " seconds"
  );

  console.log(
    "Maximum OTP attempts: " +
    OTP_MAX_ATTEMPTS
  );

  console.log(
    "OTP lock: " +
    (
      OTP_LOCK_MS /
      60000
    ) +
    " minutes"
  );

  console.log(
    "StockFlow backend test completed."
  );

  return {
    success: true,

    message:
      "StockFlow backend configuration loaded successfully."
  };
}
