// ============================================================
// STOCKFLOW — GOOGLE APPS SCRIPT BACKEND
// File: Code.gs
//
// MIDTERM / DEMO BACKEND
//
// Google Sheets = primary datastore
// Firebase      = OTP / verification mirror
//
// IMPORTANT:
// No Gmail.
// No SMS.
// No Twilio.
//
// OTP is generated by Apps Script, stored in Google Sheets,
// mirrored to Firebase, and returned in DEMO_MODE.
//
// DO NOT create duplicate doPost(), doGet(), verifyOtp(),
// resendOtp(), register(), etc. in other .gs files.
// ============================================================


const SHEET_ID =
  "1w3j0sV9rDiBvS4cpHU31iGb4KIeyUPoALZf5vLH2ivY";

const APP_NAME =
  "STOCKFLOW";

const USER_SHEET =
  "USER";


// ============================================================
// OTP CONFIGURATION
// ============================================================

const OTP_LENGTH =
  6;

const OTP_EXPIRY_MINUTES =
  10;

const MAX_OTP_ATTEMPTS =
  4;

const OTP_LOCK_MINUTES =
  30;

// Keep this synchronized with config.js
const RESEND_COOLDOWN_SECONDS =
  60;


// ============================================================
// SESSION
// ============================================================

const SESSION_TTL_MINUTES =
  480;


// ============================================================
// USER SHEET
// ============================================================

const USER_HEADERS = [

  "UID",
  "NAME",
  "USERNAME",
  "PASSWORD",
  "AGE",
  "ACCOUNT_S",
  "GMAIL",
  "PHONE NO.",
  "ROLE",
  "VERIFIED",
  "OTP",
  "OTP EXPIRES",
  "OTP ATTEMPTS",
  "OTP LOCK UNTIL",
  "OTP CHANNEL",
  "CREATED AT",
  "VERIFIED AT",
  "LAST OTP SENT",
  "LAST LOGIN"

];


// ============================================================
// COMPATIBILITY ALIASES
// ============================================================

const SF_OTP_EXPIRY_MINUTES =
  OTP_EXPIRY_MINUTES;

const SF_MAX_OTP_ATTEMPTS =
  MAX_OTP_ATTEMPTS;

const SF_OTP_LOCK_MINUTES =
  OTP_LOCK_MINUTES;

const SF_RESEND_COOLDOWN_SECONDS =
  RESEND_COOLDOWN_SECONDS;

const SF_USER_HEADERS =
  USER_HEADERS;


// ============================================================
// PROPERTY HELPERS
// ============================================================

function sfProp(key) {

  return (
    PropertiesService
      .getScriptProperties()
      .getProperty(key) ||
    ""
  );

}


// Keep old prop() calls compatible.
function prop(key) {

  return sfProp(key);

}


// ============================================================
// DEMO MODE
// ============================================================
//
// For the midterm, DEMO_MODE defaults to TRUE.
//
// If you later add real email/SMS delivery, change the
// Script Property DEMO_MODE to false.
// ============================================================

function sfDemoMode() {

  const value =
    sfProp("DEMO_MODE");

  if (!value) {
    return true;
  }

  return [
    "true",
    "1",
    "yes",
    "on"
  ].includes(
    String(value)
      .trim()
      .toLowerCase()
  );

}


// ============================================================
// BASIC HELPERS
// ============================================================

function sfClean(value) {

  return String(
    value == null
      ? ""
      : value
  ).trim();

}


function clean(value) {

  return sfClean(value);

}


function sfEmail(value) {

  return sfClean(value)
    .toLowerCase();

}


function email(value) {

  return sfEmail(value);

}


function sfPhone(value) {

  let p =
    sfClean(value)
      .replace(
        /[\s\-()]/g,
        ""
      );

  if (
    /^09\d{9}$/.test(p)
  ) {

    return (
      "+63" +
      p.slice(1)
    );

  }

  if (
    /^639\d{9}$/.test(p)
  ) {

    return "+" + p;

  }

  if (
    /^\+639\d{9}$/.test(p)
  ) {

    return p;

  }

  return p;

}


function phone(value) {

  return sfPhone(value);

}


function validEmail(value) {

  return /^\S+@\S+\.\S+$/
    .test(
      sfEmail(value)
    );

}


function validPhone(value) {

  return /^\+639\d{9}$/
    .test(
      sfPhone(value)
    );

}


// ============================================================
// JSON RESPONSE
// ============================================================

function json(data) {

  return ContentService
    .createTextOutput(
      JSON.stringify(
        data
      )
    )
    .setMimeType(
      ContentService.MimeType.JSON
    );

}


// ============================================================
// ERROR MESSAGE
// ============================================================

function sfErrorMessage(error) {

  if (!error) {
    return "Unknown error.";
  }

  return (
    error.message ||
    String(error)
  );

}


// ============================================================
// ID
// ============================================================

function uid() {

  return (
    "sf_" +
    Date.now() +
    "_" +
    Utilities
      .getUuid()
      .replace(/-/g, "")
      .substring(0, 12)
  );

}


// ============================================================
// DATE
// ============================================================

function sfMinutesFromNow(minutes) {

  return new Date(
    Date.now() +
    Number(minutes) *
    60000
  );

}


// ============================================================
// OTP GENERATION
// ============================================================

function otp() {

  return String(
    Math.floor(
      100000 +
      Math.random() * 900000
    )
  );

}


function sfGenerateOtp() {

  return otp();

}


// ============================================================
// PASSWORD HASH
// ============================================================

function hashPassword(password) {

  return Utilities.base64Encode(
    Utilities.computeDigest(
      Utilities.DigestAlgorithm.SHA_256,
      String(password),
      Utilities.Charset.UTF_8
    )
  );

}


// ============================================================
// HTML ESCAPE
// ============================================================

function escapeHtml(value) {

  return sfClean(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");

}


// ============================================================
// SHEET
// ============================================================

function sheet(
  name,
  headers
) {

  const ss =
    SpreadsheetApp.openById(
      SHEET_ID
    );

  let s =
    ss.getSheetByName(
      name
    );

  if (!s) {

    s =
      ss.insertSheet(
        name
      );

  }

  if (
    s.getMaxColumns() <
    headers.length
  ) {

    s.insertColumnsAfter(
      s.getMaxColumns(),
      headers.length -
      s.getMaxColumns()
    );

  }

  s.getRange(
    1,
    1,
    1,
    headers.length
  )
    .setValues([
      headers
    ])
    .setFontWeight(
      "bold"
    );

  return s;

}


// ============================================================
// SHEET ROWS
// ============================================================

function rows(s) {

  if (
    s.getLastRow() < 2
  ) {

    return [];

  }

  return s.getRange(
    2,
    1,
    s.getLastRow() - 1,
    s.getLastColumn()
  )
    .getValues();

}


// ============================================================
// FIND USER
// ============================================================

function findUser(identity) {

  const target =
    sfClean(identity)
      .toLowerCase();

  if (!target) {
    return null;
  }

  const s =
    sheet(
      USER_SHEET,
      USER_HEADERS
    );

  const rs =
    rows(s);

  for (
    let i = 0;
    i < rs.length;
    i++
  ) {

    const r =
      rs[i];

    const uidValue =
      sfClean(r[0])
        .toLowerCase();

    const usernameValue =
      sfClean(r[2])
        .toLowerCase();

    const gmailValue =
      sfEmail(r[6]);

    const phoneValue =
      sfPhone(r[7])
        .toLowerCase();

    if (
      target === uidValue ||
      target === usernameValue ||
      target === gmailValue ||
      target === phoneValue
    ) {

      return {

        sheet: s,

        row:
          i + 2,

        values:
          r

      };

    }

  }

  return null;

}


function sfFindUser(identity) {

  return findUser(identity);

}


// ============================================================
// USER OBJECT
// ============================================================

function sfUserObject(row) {

  return {

    uid:
      sfClean(row[0]),

    name:
      sfClean(row[1]),

    username:
      sfClean(row[2]),

    age:
      row[4],

    accountStatus:
      sfClean(row[5]),

    gmail:
      sfClean(row[6]),

    email:
      sfClean(row[6]),

    phone:
      sfClean(row[7]),

    role:
      sfClean(row[8]) || "Employee",

    verified:
      row[9] === true ||
      String(row[9])
        .toUpperCase() === "TRUE"

  };

}


// ============================================================
// OTP IDENTITY
// ============================================================

function getOtpIdentity(data) {

  data =
    data || {};

  return (
    data.identity ||
    data.uid ||
    data.username ||
    data.email ||
    data.gmail ||
    data.phone ||
    data.phoneNumber ||
    data.mobile ||
    ""
  );

}


// ============================================================
// REGISTER
// ============================================================
//
// IMPORTANT:
// This function does NOT send Gmail/SMS.
//
// The OTP is generated by sfCreateOtp().
// ============================================================

function register(
  data,
  role
) {

  data =
    data || {};

  const name =
    sfClean(
      data.name
    );

  const username =
    sfClean(
      data.username
    );

  const password =
    String(
      data.password ||
      ""
    );

  const age =
    Number(
      data.age
    );

  const gmail =
    sfEmail(
      data.gmail ||
      data.email
    );

  const ph =
    sfPhone(
      data.phone ||
      data.phoneNumber ||
      data.mobile
    );

  // ----------------------------------------------------------
  // VALIDATION
  // ----------------------------------------------------------

  if (
    !name ||
    !username ||
    !password ||
    !age ||
    !validEmail(gmail) ||
    !validPhone(ph)
  ) {

    return {

      success: false,

      message:
        "Complete all required fields using a valid Gmail address and Philippine mobile number."

    };

  }

  if (
    username.length < 4 ||
    username.length > 30
  ) {

    return {

      success: false,

      message:
        "Username must be 4–30 characters."

    };

  }

  if (
    !/^[A-Za-z0-9._-]+$/.test(
      username
    )
  ) {

    return {

      success: false,

      message:
        "Username may only contain letters, numbers, dots, underscores, and hyphens."

    };

  }

  if (
    age < 18 ||
    age > 100
  ) {

    return {

      success: false,

      message:
        "Age must be between 18 and 100."

    };

  }

  if (
    password.length < 8
  ) {

    return {

      success: false,

      message:
        "Password must be at least 8 characters."

    };

  }

  // ----------------------------------------------------------
  // DUPLICATE CHECK
  // ----------------------------------------------------------

  if (
    findUser(username) ||
    findUser(gmail) ||
    findUser(ph)
  ) {

    return {

      success: false,

      message:
        "Username, email, or phone number is already registered."

    };

  }

  // ----------------------------------------------------------
  // CREATE USER
  // ----------------------------------------------------------

  const s =
    sheet(
      USER_SHEET,
      USER_HEADERS
    );

  const accountUid =
    uid();

  const now =
    new Date();

  const accountRole =
    role ||
    "Employee";

  // Initially pending.
  s.appendRow([

    accountUid,

    name,

    username,

    hashPassword(
      password
    ),

    age,

    "PENDING",

    gmail,

    ph,

    accountRole,

    false,

    "",

    "",

    0,

    "",

    "BOTH",

    now,

    "",

    "",

    ""

  ]);

  // ----------------------------------------------------------
  // GET CREATED USER
  // ----------------------------------------------------------

  const user =
    findUser(
      accountUid
    );

  if (!user) {

    return {

      success: false,

      message:
        "Unable to create the user account."

    };

  }

  // ----------------------------------------------------------
  // CREATE INITIAL OTP
  // ----------------------------------------------------------

  const otpResult =
    sfCreateOtp(
      user,
      "BOTH"
    );

  if (
    !otpResult ||
    !otpResult.success
  ) {

    try {

      s.deleteRow(
        user.row
      );

    } catch (deleteError) {

      console.error(
        "Registration rollback failed:",
        deleteError
      );

    }

    return {

      success: false,

      message:
        "Unable to create the verification code."

    };

  }

  // ----------------------------------------------------------
  // FIREBASE USER MIRROR
  // ----------------------------------------------------------

  try {

    if (
      typeof sfFirebaseSaveUser ===
      "function"
    ) {

      sfFirebaseSaveUser({

        uid:
          accountUid,

        name:
          name,

        username:
          username,

        age:
          age,

        accountStatus:
          "PENDING",

        gmail:
          gmail,

        phone:
          ph,

        role:
          accountRole,

        verified:
          false

      });

    }

  } catch (firebaseError) {

    console.error(
      "Firebase user mirror failed:",
      firebaseError
    );

  }

  // ----------------------------------------------------------
  // RESULT
  // ----------------------------------------------------------

  return {

    success: true,

    uid:
      accountUid,

    username:
      username,

    name:
      name,

    email:
      gmail,

    gmail:
      gmail,

    phone:
      ph,

    role:
      accountRole,

    verified:
      false,

    otpSent:
      true,

    emailSent:
      false,

    smsSent:
      false,

    channel:
      "BOTH",

    expiresAt:
      otpResult.expiresAt,

    message:
      "Registration successful. Your verification code is ready for the demo verification page.",

    otp:
      sfDemoMode()
        ? otpResult.otp
        : undefined,

    demoOtp:
      sfDemoMode()
        ? otpResult.otp
        : undefined

  };

}


// ============================================================
// LOGIN
// ============================================================

function login(data) {

  data =
    data || {};

  const identity =
    getOtpIdentity(
      data
    );

  const f =
    findUser(
      identity
    );

  if (!f) {

    return {

      success: false,

      message:
        "Invalid username/email or password."

    };

  }

  const supplied =
    String(
      data.password ||
      ""
    );

  const saved =
    String(
      f.values[3] ||
      ""
    );

  const hashed =
    hashPassword(
      supplied
    );

  const passwordOk =
    saved === hashed ||
    saved === supplied;

  if (!passwordOk) {

    return {

      success: false,

      message:
        "Invalid username/email or password."

    };

  }

  const status =
    sfClean(
      f.values[5]
    )
      .toUpperCase();

  if (
    status === "SUSPENDED" ||
    status === "DISABLED" ||
    status === "BLOCKED"
  ) {

    return {

      success: false,

      message:
        "This account is " +
        status.toLowerCase() +
        "."

    };

  }

  const verified =
    f.values[9] === true ||
    String(
      f.values[9]
    )
      .toUpperCase() ===
      "TRUE";

  // ----------------------------------------------------------
  // UNVERIFIED LOGIN
  // ----------------------------------------------------------

  if (!verified) {

    return {

      success: false,

      verified: false,

      requiresVerification:
        true,

      uid:
        f.values[0],

      username:
        f.values[2],

      gmail:
        f.values[6],

      email:
        f.values[6],

      phone:
        f.values[7],

      role:
        f.values[8],

      message:
        "Account is not verified. Please verify your account first."

    };

  }

  // ----------------------------------------------------------
  // CREATE SESSION
  // ----------------------------------------------------------

  const token =
    Utilities.getUuid() +
    "." +
    Utilities.getUuid();

  CacheService
    .getScriptCache()
    .put(

      "session_" +
      token,

      JSON.stringify({

        uid:
          f.values[0],

        username:
          f.values[2],

        role:
          f.values[8],

        name:
          f.values[1]

      }),

      SESSION_TTL_MINUTES * 60

    );

  // ----------------------------------------------------------
  // LAST LOGIN
  // ----------------------------------------------------------

  f.sheet
    .getRange(
      f.row,
      19
    )
    .setValue(
      new Date()
    );

  return {

    success: true,

    token:
      token,

    user:
      sfUserObject(
        f.values
      )

  };

}


// ============================================================
// SESSION
// ============================================================

function session(data) {

  data =
    data || {};

  const token =
    sfClean(
      data.token
    );

  if (!token) {

    return {

      success: false,

      message:
        "Session expired."

    };

  }

  const raw =
    CacheService
      .getScriptCache()
      .get(
        "session_" +
        token
      );

  if (!raw) {

    return {

      success: false,

      message:
        "Session expired."

    };

  }

  try {

    return {

      success: true,

      user:
        JSON.parse(
          raw
        )

    };

  } catch (error) {

    return {

      success: false,

      message:
        "Invalid session."

    };

  }

}


// ============================================================
// LOGOUT
// ============================================================

function logout(data) {

  data =
    data || {};

  const token =
    sfClean(
      data.token
    );

  if (token) {

    CacheService
      .getScriptCache()
      .remove(
        "session_" +
        token
      );

  }

  return {

    success: true,

    message:
      "Logged out successfully."

  };

}


// ============================================================
// REQUIRE SESSION
// ============================================================

function requireSession(data) {

  const result =
    session(
      data
    );

  if (
    !result.success
  ) {

    throw new Error(
      "Unauthorized"
    );

  }

  return result.user;

}


// ============================================================
// USER LOOKUP
// ============================================================

function getUser(data) {

  const identity =
    getOtpIdentity(
      data
    );

  const f =
    findUser(
      identity
    );

  if (!f) {

    return {

      success: false,

      message:
        "User not found."

    };

  }

  return {

    success: true,

    user:
      sfUserObject(
        f.values
      )

  };

}


// ============================================================
// UPDATE STATUS
// ============================================================

function updateStatus(data) {

  requireSession(
    data
  );

  const identity =
    data.username ||
    data.identity ||
    data.uid;

  const f =
    findUser(
      identity
    );

  if (!f) {

    return {

      success: false,

      message:
        "User not found."

    };

  }

  const newStatus =
    sfClean(
      data.status
    )
      .toUpperCase();

  if (!newStatus) {

    return {

      success: false,

      message:
        "Status is required."

    };

  }

  f.sheet
    .getRange(
      f.row,
      6
    )
    .setValue(
      newStatus
    );

  return {

    success: true,

    message:
      "Account status updated."

  };

}


// ============================================================
// PASSWORD RECOVERY
// ============================================================

function forgotPassword(data) {

  data =
    data || {};

  const identity =
    getOtpIdentity(
      data
    );

  const record =
    findUser(
      identity
    );

  // Do not reveal whether the account exists.
  if (!record) {

    return {

      success: true,

      found: false,

      message:
        "If the account exists, a recovery code is available."

    };

  }

  const result =
    sfCreateOtp(
      record,
      "BOTH"
    );

  if (
    !result.success
  ) {

    return {

      success: false,

      message:
        result.message ||
        "Unable to create recovery code."

    };

  }

  return {

    success: true,

    found: true,

    uid:
      result.uid,

    username:
      result.username,

    gmail:
      result.gmail,

    email:
      result.email,

    phone:
      result.phone,

    expiresAt:
      result.expiresAt,

    message:
      "Recovery code prepared for the registered account.",

    otp:
      sfDemoMode()
        ? result.otp
        : undefined,

    demoOtp:
      sfDemoMode()
        ? result.otp
        : undefined

  };

}


// ============================================================
// VERIFY RECOVERY OTP
// ============================================================

function verifyRecoveryOtp(data) {

  return sfVerifyOtp(
    data,
    true
  );

}


// ============================================================
// RESET PASSWORD
// ============================================================

function resetPassword(data) {

  data =
    data || {};

  const identity =
    getOtpIdentity(
      data
    );

  const record =
    findUser(
      identity
    );

  if (!record) {

    return {

      success: false,

      message:
        "Unable to reset password."

    };

  }

  const row =
    record.values;

  const submittedOtp =
    sfClean(
      data.otp
    );

  const storedOtp =
    sfClean(
      row[10]
    );

  const expires =
    row[11]
      ? new Date(row[11])
      : null;

  if (
    !submittedOtp ||
    submittedOtp !== storedOtp ||
    !expires ||
    isNaN(expires) ||
    Date.now() >
      expires.getTime()
  ) {

    return {

      success: false,

      message:
        "Invalid or expired recovery code."

    };

  }

  const password =
    String(
      data.newPassword ||
      ""
    );

  if (
    password.length < 8
  ) {

    return {

      success: false,

      message:
        "Password must be at least 8 characters."

    };

  }

  const confirm =
    String(
      data.confirmPassword ||
      data.confirmNewPassword ||
      ""
    );

  if (
    confirm &&
    password !== confirm
  ) {

    return {

      success: false,

      message:
        "Passwords do not match."

    };

  }

  record.sheet
    .getRange(
      record.row,
      4
    )
    .setValue(
      hashPassword(
        password
      )
    );

  // Clear OTP.
  record.sheet
    .getRange(
      record.row,
      11,
      1,
      4
    )
    .clearContent();

  record.sheet
    .getRange(
      record.row,
      13
    )
    .setValue(
      0
    );

  return {

    success: true,

    message:
      "Password reset successfully. You can now sign in."

  };

}


// ============================================================
// API DISPATCHER
// ============================================================

function doPost(e) {

  try {

    if (
      !e ||
      !e.postData ||
      !e.postData.contents
    ) {

      return json({

        success: false,

        message:
          "Empty request."

      });

    }

    const data =
      JSON.parse(
        e.postData.contents
      );

    const action =
      sfClean(
        data.action
      );

    switch (action) {

      // ------------------------------------------------------
      // AUTH
      // ------------------------------------------------------

      case "register":

        return json(
          register(
            data,
            "Employee"
          )
        );


      case "registerAdmin":

        if (
          sfClean(
            data.adminRegistrationKey
          ) !==
          sfProp(
            "ADMIN_REGISTRATION_KEY"
          )
        ) {

          return json({

            success: false,

            message:
              "Admin registration is restricted."

          });

        }

        return json(
          register(
            data,
            "Admin"
          )
        );


      case "login":

        return json(
          login(
            data
          )
        );


      case "session":

        return json(
          session(
            data
          )
        );


      case "logout":

        return json(
          logout(
            data
          )
        );


      case "getUser":

        return json(
          getUser(
            data
          )
        );


      case "updateStatus":

        return json(
          updateStatus(
            data
          )
        );


      // ------------------------------------------------------
      // OTP
      // ------------------------------------------------------

      case "prepareOtp":

      case "generateOtp":

      case "requestOtp":

        return json(
          generateOtp(
            data
          )
        );


      case "verifyOtp":

        return json(
          verifyOtp(
            data
          )
        );


      case "resendOtp":

        return json(
          resendOtp(
            data
          )
        );


      // ------------------------------------------------------
      // PASSWORD RECOVERY
      // ------------------------------------------------------

      case "forgotPassword":

        return json(
          forgotPassword(
            data
          )
        );


      case "verifyRecoveryOtp":

        return json(
          verifyRecoveryOtp(
            data
          )
        );


      case "resetPassword":

        return json(
          resetPassword(
            data
          )
        );


      // ------------------------------------------------------
      // INVENTORY
      // ------------------------------------------------------

      default:

        if (
          typeof SFInv_dispatch ===
          "function"
        ) {

          return json(
            SFInv_dispatch(
              action,
              data
            )
          );

        }

        return json({

          success: false,

          message:
            "Unknown API action: " +
            action

        });

    }

  } catch (error) {

    console.error(
      "StockFlow API error:",
      error
    );

    return json({

      success: false,

      message:
        sfErrorMessage(
          error
        )

    });

  }

}


// ============================================================
// GET / HEALTH CHECK
// ============================================================

function doGet(e) {

  return json({

    success: true,

    system:
      APP_NAME +
      " Inventory System",

    status:
      "ONLINE",

    demoMode:
      sfDemoMode(),

    timestamp:
      new Date()
        .toISOString()

  });

}
