// ============================================================
// STOCKFLOW — FIREBASE REALTIME DATABASE
// File: firebase.gs
//
// Google Apps Script -> Firebase Realtime Database
//
// FIREBASE STRUCTURE
// ------------------------------------------------------------
// /users/{UID}
// /otp/{UID}
//
// IMPORTANT
// ------------------------------------------------------------
// - Google Sheets remains the primary database.
// - Firebase mirrors the user/account and OTP information.
// - Passwords are NEVER stored in Firebase.
// - OTPs are generated ONLY by Code.gs.
// - This file NEVER generates an OTP.
// - The OTP stored here is the exact OTP generated by Code.gs.
// - Firebase uses UID as the database key.
// - Numeric ID is stored only as a user property.
// ============================================================


// ============================================================
// CONFIGURATION
// ============================================================

const SF_FIREBASE_DEFAULT_URL =
  "https://midtermexamproject-default-rtdb.firebaseio.com/";


// ============================================================
// FIREBASE DATABASE URL
// ============================================================

function sfFirebaseUrl() {

  let url = "";

  try {

    if (typeof getProperty === "function") {

      url =
        getProperty(
          "FIREBASE_DATABASE_URL"
        );

    }

  } catch (error) {

    console.error(
      "Unable to read FIREBASE_DATABASE_URL:",
      sfErrorMessage(error)
    );

  }

  if (!url) {

    url =
      SF_FIREBASE_DEFAULT_URL;

  }

  return String(url)
    .trim()
    .replace(/\/+$/, "");

}


// ============================================================
// FIREBASE AUTH TOKEN
// ============================================================
//
// Optional.
//
// If Firebase Realtime Database rules permit the Apps Script
// request, this can remain empty.
//
// If authentication is required, store the appropriate token
// in Apps Script Properties:
//
// FIREBASE_DATABASE_SECRET
//
// ============================================================

function sfFirebaseToken() {

  try {

    if (typeof getProperty === "function") {

      return String(
        getProperty(
          "FIREBASE_DATABASE_SECRET"
        ) || ""
      ).trim();

    }

  } catch (error) {

    console.error(
      "Unable to read Firebase authentication token:",
      sfErrorMessage(error)
    );

  }

  return "";

}


// ============================================================
// FIREBASE ENDPOINT
// ============================================================

function sfFirebaseEndpoint(path) {

  let cleanPath =
    String(path || "")
      .trim()
      .replace(/^\/+/, "")
      .replace(/\/+$/, "");

  let url =
    sfFirebaseUrl();

  if (cleanPath) {

    url +=
      "/" +
      cleanPath;

  }

  // Firebase Realtime Database REST API
  // requires the .json suffix.
  url += ".json";

  const token =
    sfFirebaseToken();

  if (token) {

    url +=
      "?auth=" +
      encodeURIComponent(token);

  }

  return url;

}


// ============================================================
// FIREBASE ERROR MESSAGE
// ============================================================

function sfErrorMessage(error) {

  if (!error) {

    return "Unknown Firebase error.";

  }

  if (error.message) {

    return String(
      error.message
    );

  }

  return String(
    error
  );

}


// ============================================================
// FIREBASE RESPONSE PARSER
// ============================================================

function sfFirebaseResponseData(response) {

  if (!response) {

    return null;

  }

  const text =
    response.getContentText();

  if (!text) {

    return null;

  }

  try {

    return JSON.parse(
      text
    );

  } catch (error) {

    return text;

  }

}


// ============================================================
// FIREBASE PUT
// ============================================================
//
// Completely creates/replaces the specified Firebase node.
//
// Example:
//
// /users/{UID}
//
// ============================================================

function sfFirebasePut(path, data) {

  const url =
    sfFirebaseEndpoint(
      path
    );

  try {

    const response =
      UrlFetchApp.fetch(
        url,
        {
          method: "put",

          contentType:
            "application/json",

          payload:
            JSON.stringify(
              data
            ),

          muteHttpExceptions:
            true,

          followRedirects:
            true
        }
      );

    const status =
      response.getResponseCode();

    const responseText =
      response.getContentText();

    console.log(
      "Firebase PUT:",
      path,
      "HTTP:",
      status,
      "Response:",
      responseText
    );

    if (
      status < 200 ||
      status >= 300
    ) {

      return {

        success: false,

        status: status,

        path: path,

        message:
          "Firebase PUT failed. HTTP " +
          status,

        response:
          responseText

      };

    }

    return {

      success: true,

      status: status,

      path: path,

      data:
        sfFirebaseResponseData(
          response
        )

    };

  } catch (error) {

    console.error(
      "Firebase PUT exception:",
      sfErrorMessage(error)
    );

    return {

      success: false,

      status: 0,

      path: path,

      message:
        sfErrorMessage(
          error
        )

    };

  }

}


// ============================================================
// FIREBASE PATCH
// ============================================================
//
// Updates only the specified Firebase properties.
//
// ============================================================

function sfFirebasePatch(path, data) {

  const url =
    sfFirebaseEndpoint(
      path
    );

  try {

    const response =
      UrlFetchApp.fetch(
        url,
        {
          method: "patch",

          contentType:
            "application/json",

          payload:
            JSON.stringify(
              data
            ),

          muteHttpExceptions:
            true,

          followRedirects:
            true
        }
      );

    const status =
      response.getResponseCode();

    const responseText =
      response.getContentText();

    console.log(
      "Firebase PATCH:",
      path,
      "HTTP:",
      status,
      "Response:",
      responseText
    );

    if (
      status < 200 ||
      status >= 300
    ) {

      return {

        success: false,

        status: status,

        path: path,

        message:
          "Firebase PATCH failed. HTTP " +
          status,

        response:
          responseText

      };

    }

    return {

      success: true,

      status: status,

      path: path,

      data:
        sfFirebaseResponseData(
          response
        )

    };

  } catch (error) {

    console.error(
      "Firebase PATCH exception:",
      sfErrorMessage(error)
    );

    return {

      success: false,

      status: 0,

      path: path,

      message:
        sfErrorMessage(
          error
        )

    };

  }

}


// ============================================================
// FIREBASE GET
// ============================================================

function sfFirebaseGet(path) {

  const url =
    sfFirebaseEndpoint(
      path
    );

  try {

    const response =
      UrlFetchApp.fetch(
        url,
        {
          method: "get",

          muteHttpExceptions:
            true,

          followRedirects:
            true
        }
      );

    const status =
      response.getResponseCode();

    const responseText =
      response.getContentText();

    console.log(
      "Firebase GET:",
      path,
      "HTTP:",
      status,
      "Response:",
      responseText
    );

    if (
      status < 200 ||
      status >= 300
    ) {

      return {

        success: false,

        status: status,

        path: path,

        message:
          "Firebase GET failed. HTTP " +
          status,

        response:
          responseText

      };

    }

    return {

      success: true,

      status: status,

      path: path,

      data:
        sfFirebaseResponseData(
          response
        )

    };

  } catch (error) {

    console.error(
      "Firebase GET exception:",
      sfErrorMessage(error)
    );

    return {

      success: false,

      status: 0,

      path: path,

      message:
        sfErrorMessage(
          error
        )

    };

  }

}


// ============================================================
// FIREBASE DELETE
// ============================================================

function sfFirebaseDelete(path) {

  const url =
    sfFirebaseEndpoint(
      path
    );

  try {

    const response =
      UrlFetchApp.fetch(
        url,
        {
          method: "delete",

          muteHttpExceptions:
            true,

          followRedirects:
            true
        }
      );

    const status =
      response.getResponseCode();

    const responseText =
      response.getContentText();

    console.log(
      "Firebase DELETE:",
      path,
      "HTTP:",
      status,
      "Response:",
      responseText
    );

    if (
      status < 200 ||
      status >= 300
    ) {

      return {

        success: false,

        status: status,

        path: path,

        message:
          "Firebase DELETE failed. HTTP " +
          status,

        response:
          responseText

      };

    }

    return {

      success: true,

      status: status,

      path: path

    };

  } catch (error) {

    console.error(
      "Firebase DELETE exception:",
      sfErrorMessage(error)
    );

    return {

      success: false,

      status: 0,

      path: path,

      message:
        sfErrorMessage(
          error
        )

    };

  }

}


// ============================================================
// SAVE USER TO FIREBASE
// ============================================================
//
// Firebase:
//
// /users/{UID}
//
// IMPORTANT:
// Password is intentionally excluded.
//
// ============================================================

function sfFirebaseSaveUser(user) {

  if (
    !user ||
    !user.uid
  ) {

    return {

      success: false,

      message:
        "Missing Firebase user UID."

    };

  }

  const uid =
    String(
      user.uid
    ).trim();

  const firebaseUser = {

    id:
      user.id != null
        ? Number(user.id)
        : "",

    uid:
      uid,

    name:
      user.name ||
      "",

    username:
      user.username ||
      "",

    age:
      user.age != null
        ? user.age
        : "",

    accountStatus:
      user.accountStatus ||
      "PENDING",

    gmail:
      user.gmail ||
      user.email ||
      "",

    phone:
      user.phone ||
      "",

    role:
      user.role ||
      "Employee",

    verified:
      user.verified === true,

    createdAt:
      user.createdAt ||
      new Date().toISOString()

  };

  // SECURITY:
  // No password field is ever added here.

  return sfFirebasePut(
    "users/" +
    encodeURIComponent(uid),
    firebaseUser
  );

}


// ============================================================
// SAVE ACTUAL OTP TO FIREBASE
// ============================================================
//
// IMPORTANT:
// This function DOES NOT generate an OTP.
//
// Code.gs generates the OTP:
//
// generateOTP()
//
// Then Code.gs passes that exact OTP here.
//
// Therefore:
//
// Google Sheets OTP
//       =
// Firebase OTP
//       =
// OTP returned by Code.gs
//
// ============================================================

function sfFirebaseSaveOtp(user) {

  if (
    !user ||
    !user.uid
  ) {

    return {

      success: false,

      message:
        "Missing Firebase OTP UID."

    };

  }

  if (
    !user.otp
  ) {

    return {

      success: false,

      message:
        "Missing actual OTP. " +
        "OTP must be generated by Code.gs first."

    };

  }

  const uid =
    String(
      user.uid
    ).trim();

  const otp =
    String(
      user.otp
    ).trim();

  // Require exactly six digits.
  if (
    !/^\d{6}$/.test(otp)
  ) {

    return {

      success: false,

      message:
        "Invalid OTP. Expected exactly 6 digits."

    };

  }

  const otpData = {

    uid:
      uid,

    id:
      user.id != null
        ? Number(user.id)
        : "",

    username:
      user.username ||
      "",

    gmail:
      user.gmail ||
      user.email ||
      "",

    phone:
      user.phone ||
      "",

    // THIS IS THE ACTUAL OTP GENERATED BY CODE.GS.
    otp:
      otp,

    otpExpires:
      user.otpExpires ||
      "",

    attempts:
      Number(
        user.attempts ||
        0
      ),

    channel:
      user.channel ||
      "BOTH",

    createdAt:
      new Date().toISOString()

  };

  return sfFirebasePut(
    "otp/" +
    encodeURIComponent(uid),
    otpData
  );

}


// ============================================================
// MARK USER VERIFIED
// ============================================================

function sfFirebaseMarkVerified(uid) {

  if (!uid) {

    return {

      success: false,

      message:
        "Missing UID."

    };

  }

  const cleanUid =
    String(
      uid
    ).trim();

  return sfFirebasePatch(

    "users/" +
    encodeURIComponent(
      cleanUid
    ),

    {

      verified:
        true,

      accountStatus:
        "ACTIVE",

      verifiedAt:
        new Date()
          .toISOString()

    }

  );

}


// ============================================================
// DELETE OTP AFTER SUCCESSFUL VERIFICATION
// ============================================================
//
// Once the actual OTP has been successfully verified,
// it should no longer remain in Firebase.
//
// ============================================================

function sfFirebaseDeleteOtp(uid) {

  if (!uid) {

    return {

      success: false,

      message:
        "Missing UID."

    };

  }

  return sfFirebaseDelete(

    "otp/" +
    encodeURIComponent(
      String(uid).trim()
    )

  );

}


// ============================================================
// GET FIREBASE USER
// ============================================================

function sfFirebaseGetUser(uid) {

  if (!uid) {

    return {

      success: false,

      message:
        "Missing UID."

    };

  }

  return sfFirebaseGet(

    "users/" +
    encodeURIComponent(
      String(uid).trim()
    )

  );

}


// ============================================================
// GET FIREBASE OTP
// ============================================================
//
// Useful for backend verification/debugging.
//
// ============================================================

function sfFirebaseGetOtp(uid) {

  if (!uid) {

    return {

      success: false,

      message:
        "Missing UID."

    };

  }

  return sfFirebaseGet(

    "otp/" +
    encodeURIComponent(
      String(uid).trim()
    )

  );

}


// ============================================================
// FIREBASE CONNECTION TEST
// ============================================================
//
// Run from Apps Script:
//
// testFirebaseConnection()
//
// ============================================================

function testFirebaseConnection() {

  console.log(
    "=========================================="
  );

  console.log(
    "STOCKFLOW FIREBASE CONNECTION TEST"
  );

  console.log(
    "=========================================="
  );

  console.log(
    "Firebase URL:",
    sfFirebaseUrl()
  );

  const result =
    sfFirebaseGet(
      ""
    );

  console.log(
    "Firebase connection result:",
    JSON.stringify(
      result
    )
  );

  return result;

}


// ============================================================
// FIREBASE WRITE TEST
// ============================================================
//
// Run:
//
// testFirebaseWrite()
//
// Creates:
//
// /stockflow_test
//
// This does NOT create an OTP.
//
// ============================================================

function testFirebaseWrite() {

  const testData = {

    system:
      "STOCKFLOW",

    test:
      true,

    message:
      "Firebase connection test successful.",

    timestamp:
      new Date()
        .toISOString()

  };

  const result =
    sfFirebasePut(
      "stockflow_test",
      testData
    );

  console.log(
    "Firebase write test:",
    JSON.stringify(
      result
    )
  );

  return result;

}


// ============================================================
// FIREBASE USER MIRROR TEST
// ============================================================
//
// Tests the exact structure used for users.
//
// Does NOT contain a password.
//
// ============================================================

function testFirebaseUserWrite() {

  const testUid =
    "test_" +
    new Date()
      .getTime();

  const testUser = {

    id: 999999,

    uid:
      testUid,

    name:
      "STOCKFLOW Firebase Test",

    username:
      "firebase_test",

    age:
      18,

    accountStatus:
      "PENDING",

    gmail:
      "firebase-test@example.com",

    phone:
      "09170000000",

    role:
      "Employee",

    verified:
      false,

    createdAt:
      new Date()
        .toISOString()

  };

  const result =
    sfFirebaseSaveUser(
      testUser
    );

  console.log(
    "Firebase user write test:",
    JSON.stringify(
      result
    )
  );

  return result;

}


// ============================================================
// FIREBASE OTP WRITE TEST
// ============================================================
//
// IMPORTANT:
// This test uses a fixed TEST VALUE only to test the Firebase
// write function itself.
//
// IT IS NOT USED BY THE REAL REGISTRATION OR OTP FLOW.
//
// The real application ALWAYS receives the OTP from Code.gs.
//
// ============================================================

function testFirebaseOtpWrite() {

  const testUid =
    "otp_test_" +
    new Date()
      .getTime();

  const testOtpUser = {

    id: 999999,

    uid:
      testUid,

    username:
      "otp_test",

    gmail:
      "firebase-test@example.com",

    phone:
      "09170000000",

    // TEST DATA ONLY.
    // Real OTPs NEVER come from this function.
    otp:
      "000000",

    otpExpires:
      new Date(
        Date.now() +
        10 * 60 * 1000
      ).toISOString(),

    attempts:
      0,

    channel:
      "BOTH"

  };

  const result =
    sfFirebaseSaveOtp(
      testOtpUser
    );

  console.log(
    "Firebase OTP write test:",
    JSON.stringify(
      result
    )
  );

  return result;

}


// ============================================================
// CLEAN FIREBASE TEST DATA
// ============================================================
//
// Optional helper for removing the test nodes created by:
//
// testFirebaseWrite()
// testFirebaseUserWrite()
// testFirebaseOtpWrite()
//
// ============================================================

function cleanupFirebaseTests() {

  const results = {};

  results.stockflowTest =
    sfFirebaseDelete(
      "stockflow_test"
    );

  return results;

}


// ============================================================
// END OF firebase.gs
// ============================================================
