const SHEET_NAME = "Users";
function getSheet_(){const ss=SpreadsheetApp.getActiveSpreadsheet();let s=ss.getSheetByName(SHEET_NAME);if(!s)s=ss.insertSheet(SHEET_NAME);if(s.getLastRow()===0)s.appendRow(["NAME","USERNAME","PASSWORD","AGE","ACCOUNT_S","GMAIL","PHONE NO.","OTP"]);return s;}
function json_(x){return ContentService.createTextOutput(JSON.stringify(x)).setMimeType(ContentService.MimeType.JSON);}
function doGet(e){const a=e.parameter.action||"health";if(a==="health")return json_({success:true,service:"StockFlow Google Sheets API",status:"online"});if(a==="users"){const v=getSheet_().getDataRange().getValues();return json_({success:true,users:v.slice(1).map(r=>({name:r[0],username:r[1],password:r[2],age:r[3],accountStatus:r[4],gmail:r[5],phone:r[6],otp:r[7]}))});}return json_({success:false,message:"Unknown GET action."});}
function doPost(e){try{const b=JSON.parse(e.postData.contents||"{}");switch(b.action){case"register":return register_(b);case"login":return login_(b);case"verifyOtp":return verify_(b);case"updateOtp":return updateOtp_(b);default:return json_({success:false,message:"Unknown action."});}}catch(err){return json_({success:false,message:err.message});}}
function register_(d){const s=getSheet_(),v=s.getDataRange().getValues(),u=String(d.username||"").trim(),g=String(d.gmail||"").trim().toLowerCase();for(let i=1;i<v.length;i++){if(String(v[i][1]).toLowerCase()===u.toLowerCase())return json_({success:false,message:"Username already exists."});if(String(v[i][5]).toLowerCase()===g)return json_({success:false,message:"Email already exists."});}const otp=otp_();s.appendRow([d.name||"",u,d.password||"",d.age||"","PENDING",g,d.phone||"",otp]);return json_({success:true,message:"Registration saved.",otp:otp});}
function login_(d){const v=getSheet_().getDataRange().getValues(),id=String(d.identity||"").trim().toLowerCase(),p=String(d.password||"");for(let i=1;i<v.length;i++){if((String(v[i][1]).toLowerCase()===id||String(v[i][5]).toLowerCase()===id)&&String(v[i][2])===p)return json_({success:true,verified:String(v[i][4]).toUpperCase()==="VERIFIED",user:{name:v[i][0],username:v[i][1],age:v[i][3],accountStatus:v[i][4],gmail:v[i][5],phone:v[i][6]}});}return json_({success:false,message:"Invalid username/email or password."});}
function verify_(d){const s=getSheet_(),v=s.getDataRange().getValues(),id=String(d.identity||"").trim().toLowerCase(),otp=String(d.otp||"").trim();for(let i=1;i<v.length;i++){if(String(v[i][1]).toLowerCase()===id||String(v[i][5]).toLowerCase()===id){if(String(v[i][7])!==otp)return json_({success:false,message:"Invalid OTP."});s.getRange(i+1,5).setValue("VERIFIED");s.getRange(i+1,8).setValue("");return json_({success:true,message:"Account verified."});}}return json_({success:false,message:"Account not found."});}
function updateOtp_(d){const s=getSheet_(),v=s.getDataRange().getValues(),id=String(d.identity||"").trim().toLowerCase(),o=otp_();for(let i=1;i<v.length;i++){if(String(v[i][1]).toLowerCase()===id||String(v[i][5]).toLowerCase()===id){s.getRange(i+1,8).setValue(o);return json_({success:true,otp:o});}}return json_({success:false,message:"Account not found."});}
function otp_(){return String(Math.floor(100000+Math.random()*900000));}
