// ============================================================
// STOCKFLOW — OTP BACKEND
// File: otp.gs
//
// DEMO / MIDTERM OTP IMPLEMENTATION
//
// No Gmail.
// No SMS.
// No Twilio.
//
// The generated OTP is:
//
// 1. Generated by Google Apps Script
// 2. Stored in Google Sheets
// 3. Mirrored to Firebase
// 4. Returned to the frontend in DEMO_MODE
//
// The frontend waits 3–5 seconds before automatically placing
// the returned OTP into the six OTP boxes.
//
// IMPORTANT:
// The OTP is generated ONLY here.
// otp.js does NOT generate its own OTP.
// ============================================================


// ------------------------------------------------------------
// CREATE OTP
// ------------------------------------------------------------

function sfCreateOtp(
  userRecord,
  channel
) {

  // ----------------------------------------------------------
  // Generate secure six-digit OTP
  // ----------------------------------------------------------

  const code =
    sfGenerateOtp();


  // ----------------------------------------------------------
  // Create expiration timestamp
  // ----------------------------------------------------------

  const expires =
    sfMinutesFromNow(
      SF_OTP_EXPIRY_MINUTES
    );


  // ----------------------------------------------------------
  // Normalize channel
  // ----------------------------------------------------------

  const normalizedChannel =
    String(
      channel || "BOTH"
    ).toUpperCase();


  // ----------------------------------------------------------
  // GOOGLE SHEETS
  //
  // Column 11 = OTP
  // Column 12 = OTP expiration
  // Column 13 = OTP attempts
  // Column 14 = OTP lock
  // Column 15 = OTP channel
  // Column 18 = last OTP sent
  // ----------------------------------------------------------

  userRecord.sheet
    .getRange(
      userRecord.row,
      11
    )
    .setValue(
      code
    );


  userRecord.sheet
    .getRange(
      userRecord.row,
      12
    )
    .setValue(
      expires
    );


  userRecord.sheet
    .getRange(
      userRecord.row,
      13
    )
    .setValue(
      0
    );


  userRecord.sheet
    .getRange(
      userRecord.row,
      14
    )
    .clearContent();


  userRecord.sheet
    .getRange(
      userRecord.row,
      15
    )
    .setValue(
      normalizedChannel
    );


  /*
   * Record the exact time this OTP was generated/sent.
   */
  userRecord.sheet
    .getRange(
      userRecord.row,
      18
    )
    .setValue(
      new Date()
    );


  // ----------------------------------------------------------
  // Read latest user information
  // ----------------------------------------------------------

  const values =
    userRecord.sheet
      .getRange(
        userRecord.row,
        1,
        1,
        SF_USER_HEADERS.length
      )
      .getValues()[0];


  // ----------------------------------------------------------
  // FIREBASE MIRROR
  // ----------------------------------------------------------

  sfFirebaseSaveOtp({

    uid:
      values[0],

    username:
      values[2],

    gmail:
      values[6],

    phone:
      values[7],

    otp:
      code,

    otpExpires:
      expires.toISOString(),

    attempts:
      0,

    channel:
      normalizedChannel

  });


  // ----------------------------------------------------------
  // RESPONSE
  // ----------------------------------------------------------

  const result = {

    success: true,

    uid:
      values[0],

    username:
      values[2],

    email:
      values[6],

    gmail:
      values[6],

    phone:
      values[7],

    channel:
      normalizedChannel,

    expiresAt:
      expires.toISOString(),

    message:
      "Verification code prepared."

  };


  // ----------------------------------------------------------
  // DEMO MODE
  // ----------------------------------------------------------
  //
  // The frontend needs the exact OTP that was generated and
  // stored in Firebase + Google Sheets.
  //
  // Therefore, in DEMO_MODE we return it as:
  //
  //     otp: "123456"
  //
  // This matches otp.js.
  //
  // In a production system, this should NOT be returned.
  // ----------------------------------------------------------

  if (sfDemoMode()) {

    result.otp =
      code;

    /*
     * Keep demoOtp as a compatibility alias in case another
     * existing part of the project still uses it.
     */
    result.demoOtp =
      code;
  }


  return result;
}


// ------------------------------------------------------------
// VERIFY OTP
// ------------------------------------------------------------

function verifyOtp(data) {

  data =
    data || {};


  // ----------------------------------------------------------
  // Identify account
  // ----------------------------------------------------------

  const identity =
    data.identity ||
    data.uid ||
    data.username ||
    data.email ||
    data.gmail ||
    data.phone;


  const record =
    sfFindUser(
      identity
    );


  if (!record) {

    return {

      success: false,

      message:
        "Account not found."

    };

  }


  const row =
    record.values;


  // ----------------------------------------------------------
  // ALREADY VERIFIED
  // ----------------------------------------------------------

  const verified =
    row[9] === true ||
    String(
      row[9]
    ).toUpperCase() === "TRUE";


  if (verified) {

    return {

      success: true,

      verified: true,

      message:
        "Account is already verified.",

      user:
        sfUserObject(
          row
        )

    };

  }


  // ----------------------------------------------------------
  // LOCK CHECK
  // ----------------------------------------------------------

  const lockUntil =
    row[13]
      ? new Date(row[13])
      : null;


  if (
    lockUntil &&
    !isNaN(lockUntil) &&
    Date.now() <
    lockUntil.getTime()
  ) {

    return {

      success: false,

      locked: true,

      message:
        "OTP verification is temporarily locked. Please try again later."

    };

  }


  // ----------------------------------------------------------
  // OTP EXPIRATION CHECK
  // ----------------------------------------------------------

  const expires =
    row[11]
      ? new Date(row[11])
      : null;


  if (
    !expires ||
    isNaN(expires) ||
    Date.now() >
    expires.getTime()
  ) {

    return {

      success: false,

      expired: true,

      message:
        "This verification code has expired. Please request a new code."

    };

  }


  // ----------------------------------------------------------
  // CLEAN SUBMITTED OTP
  // ----------------------------------------------------------

  const submittedOtp =
    sfClean(
      data.otp
    );


  // ----------------------------------------------------------
  // CLEAN STORED OTP
  // ----------------------------------------------------------

  const storedOtp =
    sfClean(
      row[10]
    );


  // ----------------------------------------------------------
  // INVALID OTP
  // ----------------------------------------------------------

  if (
    submittedOtp !==
    storedOtp
  ) {

    let attempts =
      Number(
        row[12]
      ) || 0;


    attempts++;


    // --------------------------------------------------------
    // Update attempt counter
    // --------------------------------------------------------

    record.sheet
      .getRange(
        record.row,
        13
      )
      .setValue(
        attempts
      );


    // --------------------------------------------------------
    // Maximum attempts reached
    // --------------------------------------------------------

    if (
      attempts >=
      SF_MAX_OTP_ATTEMPTS
    ) {

      const lock =
        sfMinutesFromNow(
          SF_OTP_LOCK_MINUTES
        );


      record.sheet
        .getRange(
          record.row,
          14
        )
        .setValue(
          lock
        );


      return {

        success: false,

        locked: true,

        remainingAttempts: 0,

        message:
          "Too many incorrect attempts. Your verification is temporarily locked for 30 minutes."

      };

    }


    // --------------------------------------------------------
    // Incorrect OTP but attempts remain
    // --------------------------------------------------------

    const remaining =
      SF_MAX_OTP_ATTEMPTS -
      attempts;


    return {

      success: false,

      remainingAttempts:
        remaining,

      message:
        "Invalid verification code. " +
        remaining +
        " attempt(s) remaining."

    };

  }


  // ==========================================================
  // OTP IS CORRECT
  // ==========================================================


  // ----------------------------------------------------------
  // Update account status
  // ----------------------------------------------------------

  record.sheet
    .getRange(
      record.row,
      6
    )
    .setValue(
      "VERIFIED"
    );


  // ----------------------------------------------------------
  // Mark account verified
  // ----------------------------------------------------------

  record.sheet
    .getRange(
      record.row,
      10
    )
    .setValue(
      true
    );


  // ----------------------------------------------------------
  // Remove OTP
  // ----------------------------------------------------------

  record.sheet
    .getRange(
      record.row,
      11
    )
    .clearContent();


  // ----------------------------------------------------------
  // Remove OTP expiration
  // ----------------------------------------------------------

  record.sheet
    .getRange(
      record.row,
      12
    )
    .clearContent();


  // ----------------------------------------------------------
  // Reset attempts
  // ----------------------------------------------------------

  record.sheet
    .getRange(
      record.row,
      13
    )
    .setValue(
      0
    );


  // ----------------------------------------------------------
  // Remove lock
  // ----------------------------------------------------------

  record.sheet
    .getRange(
      record.row,
      14
    )
    .clearContent();


  // ----------------------------------------------------------
  // Record verification time
  // ----------------------------------------------------------

  record.sheet
    .getRange(
      record.row,
      17
    )
    .setValue(
      new Date()
    );


  // ==========================================================
  // FIREBASE
  // ==========================================================

  sfFirebaseMarkVerified(
    row[0]
  );


  // ----------------------------------------------------------
  // Remove OTP mirror from Firebase
  // ----------------------------------------------------------

  sfFirebasePatch(
    "otp/" + row[0],
    {

      otp: null,

      verified: true,

      verifiedAt:
        new Date().toISOString()

    }
  );


  // ----------------------------------------------------------
  // Return updated user
  // ----------------------------------------------------------

  const updatedRow =
    record.sheet
      .getRange(
        record.row,
        1,
        1,
        SF_USER_HEADERS.length
      )
      .getValues()[0];


  return {

    success: true,

    verified: true,

    message:
      "Account verified successfully.",

    user:
      sfUserObject(
        updatedRow
      )

  };
}


// ------------------------------------------------------------
// RESEND OTP
// ------------------------------------------------------------

function resendOtp(data) {

  data =
    data || {};


  // ----------------------------------------------------------
  // Identify account
  // ----------------------------------------------------------

  const identity =
    data.identity ||
    data.uid ||
    data.username ||
    data.email ||
    data.gmail ||
    data.phone;


  const record =
    sfFindUser(
      identity
    );


  if (!record) {

    return {

      success: false,

      message:
        "Account not found."

    };

  }


  const row =
    record.values;


  // ----------------------------------------------------------
  // ALREADY VERIFIED
  // ----------------------------------------------------------

  const verified =
    row[9] === true ||
    String(
      row[9]
    ).toUpperCase() === "TRUE";


  if (verified) {

    return {

      success: false,

      message:
        "This account is already verified."

    };

  }


  // ==========================================================
  // RESEND COOLDOWN
  // ==========================================================

  const lastSent =
    row[17]
      ? new Date(row[17])
      : null;


  if (
    lastSent &&
    !isNaN(lastSent)
  ) {

    const elapsed =
      Date.now() -
      lastSent.getTime();


    const cooldownMilliseconds =
      SF_RESEND_COOLDOWN_SECONDS *
      1000;


    if (
      elapsed <
      cooldownMilliseconds
    ) {

      const remaining =
        Math.ceil(
          (
            cooldownMilliseconds -
            elapsed
          ) / 1000
        );


      return {

        success: false,

        cooldown: true,

        remainingSeconds:
          remaining,

        message:
          "Please wait " +
          remaining +
          " second(s) before requesting another code."

      };

    }

  }


  // ==========================================================
  // CREATE NEW OTP
  // ==========================================================

  return sfCreateOtp(
    record,
    data.channel ||
    data.otpChannel ||
    "BOTH"
  );
}
