/* ============================================================
   STOCKFLOW — OTP VERIFICATION CONTROLLER
   ============================================================
   
   FLOW:
   1. Verification page loads.
   2. Backend generates the OTP.
   3. Backend stores the OTP in Firebase + Google Sheets.
   4. Frontend waits 3–5 seconds.
   5. Returned OTP automatically fills the six boxes.
   6. User verifies the OTP.
   7. Resend generates/stores a new OTP and repeats the process.

   IMPORTANT:
   - OTP generation should be handled by the backend/API.
   - otp.js does NOT generate its own random OTP.
   - The OTP returned by the backend is the OTP displayed in
     the six boxes.
   ============================================================ */

(function () {
    "use strict";

    /* =========================================================
       GLOBAL CONFIGURATION
       ========================================================= */

    const API = window.StockFlowAPI || window.API || null;
    const CONFIG = window.STOCKFLOW_CONFIG || window.CONFIG || {};

    const OTP_LENGTH = Number(
        CONFIG.AUTH?.OTP_LENGTH || 6
    );

    const COOLDOWN_SECONDS = Math.max(
        120,
        Number(CONFIG.AUTH?.OTP_RESEND_COOLDOWN_SECONDS || 120)
    );

    /*
     * OTP generation delay.
     *
     * The actual OTP is generated by the backend.
     * This delay only controls when the generated OTP is revealed
     * and automatically inserted into the boxes.
     */
    const MIN_GENERATION_DELAY = 3000;
    const MAX_GENERATION_DELAY = 5000;


    /* =========================================================
       SESSION STORAGE KEYS
       ========================================================= */

    const STORAGE = {
        UID: "STOCKFLOW_OTP_UID",
        EMAIL: "STOCKFLOW_OTP_EMAIL",
        PHONE: "STOCKFLOW_OTP_PHONE",
        USERNAME: "STOCKFLOW_OTP_USERNAME",
        CHANNEL: "STOCKFLOW_OTP_CHANNEL",

        CODE: "STOCKFLOW_OTP_CODE",
        CODE_READY: "STOCKFLOW_OTP_CODE_READY",

        EMAIL_SENT: "STOCKFLOW_OTP_EMAIL_SENT",
        PHONE_SENT: "STOCKFLOW_OTP_PHONE_SENT"
    };


    /* =========================================================
       INTERNAL STATE
       ========================================================= */

    let verificationInProgress = false;

    let emailResendInProgress = false;
    let phoneResendInProgress = false;

    let cooldownTimer = null;
    let generationTimer = null;

    let otpGenerationInProgress = false;


    /* =========================================================
       DOM HELPERS
       ========================================================= */

    function getElement(...selectors) {
        for (const selector of selectors) {
            const element = document.querySelector(selector);

            if (element) {
                return element;
            }
        }

        return null;
    }


    function getOtpBoxes() {
        return Array.from(
            document.querySelectorAll(".otp-digit")
        );
    }


    function getOtpInput() {
        return getElement(
            "#otp",
            "#otpCode",
            "#verificationCode",
            "[name='otp']"
        );
    }


    function getVerifyButton() {
        return getElement(
            "#verifyOtpBtn",
            "[data-verify-otp]"
        );
    }


    function getEmailButton() {
        return getElement(
            "#resendEmailOtpBtn",
            "[data-resend-email-otp]"
        );
    }


    function getPhoneButton() {
        return getElement(
            "#resendPhoneOtpBtn",
            "[data-resend-phone-otp]"
        );
    }


    function getMessageElement() {
        return getElement(
            "#otpMessage",
            ".otp-message"
        );
    }


    function getEmailStatusElement() {
        return getElement(
            "#emailDeliveryStatus"
        );
    }


    function getPhoneStatusElement() {
        return getElement(
            "#phoneDeliveryStatus"
        );
    }


    function getEmailTimerElement() {
        return getElement(
            "#emailOtpTimer"
        );
    }


    function getPhoneTimerElement() {
        return getElement(
            "#phoneOtpTimer"
        );
    }


    /* =========================================================
       SESSION STORAGE
       ========================================================= */

    function getState() {
        return {
            uid: sessionStorage.getItem(STORAGE.UID) || "",
            email: sessionStorage.getItem(STORAGE.EMAIL) || "",
            phone: sessionStorage.getItem(STORAGE.PHONE) || "",
            username: sessionStorage.getItem(STORAGE.USERNAME) || "",
            channel: sessionStorage.getItem(STORAGE.CHANNEL) || "",

            code: sessionStorage.getItem(STORAGE.CODE) || "",

            codeReady:
                sessionStorage.getItem(STORAGE.CODE_READY) === "true",

            emailSent:
                sessionStorage.getItem(STORAGE.EMAIL_SENT) || "",

            phoneSent:
                sessionStorage.getItem(STORAGE.PHONE_SENT) || ""
        };
    }


    function saveState(data = {}) {
        const mappings = {
            uid: STORAGE.UID,
            email: STORAGE.EMAIL,
            phone: STORAGE.PHONE,
            username: STORAGE.USERNAME,
            channel: STORAGE.CHANNEL,
            code: STORAGE.CODE,
            emailSent: STORAGE.EMAIL_SENT,
            phoneSent: STORAGE.PHONE_SENT
        };

        Object.keys(mappings).forEach((key) => {
            if (
                data[key] !== undefined &&
                data[key] !== null
            ) {
                sessionStorage.setItem(
                    mappings[key],
                    String(data[key])
                );
            }
        });

        if (data.codeReady !== undefined) {
            sessionStorage.setItem(
                STORAGE.CODE_READY,
                data.codeReady ? "true" : "false"
            );
        }
    }


    function clearOtpCodeState() {
        sessionStorage.removeItem(STORAGE.CODE);
        sessionStorage.setItem(
            STORAGE.CODE_READY,
            "false"
        );
    }


    function clearOtpStorage() {
        Object.values(STORAGE).forEach((key) => {
            sessionStorage.removeItem(key);
        });
    }


    function hasVerificationState() {
        const state = getState();

        return Boolean(
            state.uid ||
            state.email ||
            state.phone ||
            state.username
        );
    }


    /* =========================================================
       MESSAGE HANDLING
       ========================================================= */

    function showMessage(message, type = "info") {
        const element = getMessageElement();

        if (!element) {
            return;
        }

        element.textContent = message;

        element.className = `otp-message ${type}`;

        element.hidden = false;

        element.style.display = "block";
    }


    function clearMessage() {
        const element = getMessageElement();

        if (!element) {
            return;
        }

        element.textContent = "";

        element.className = "otp-message";

        element.hidden = true;

        element.style.display = "none";
    }


    /* =========================================================
       MASKING
       ========================================================= */

    function maskEmail(email) {
        if (!email) {
            return "";
        }

        const parts = email.split("@");

        if (parts.length !== 2) {
            return email;
        }

        const username = parts[0];
        const domain = parts[1];

        if (username.length <= 2) {
            return `${username[0] || "*"}***@${domain}`;
        }

        return (
            username.substring(0, 2) +
            "***@" +
            domain
        );
    }


    function maskPhone(phone) {
        if (!phone) {
            return "";
        }

        const cleanPhone = String(phone).replace(
            /\s+/g,
            ""
        );

        if (cleanPhone.length <= 4) {
            return "***";
        }

        return (
            "*".repeat(
                Math.max(0, cleanPhone.length - 4)
            ) +
            cleanPhone.slice(-4)
        );
    }


    /* =========================================================
       OTP SANITIZATION
       ========================================================= */

    function sanitizeOtp(value) {
        return String(value || "")
            .replace(/\D/g, "")
            .slice(0, OTP_LENGTH);
    }


    /* =========================================================
       OTP BOX MANAGEMENT
       ========================================================= */

    function disableOtpBoxes(clear = true) {
        const boxes = getOtpBoxes();

        boxes.forEach((box) => {
            box.disabled = true;

            if (clear) {
                box.value = "";
            }
        });

        updateHiddenOtp();
    }


    function enableOtpBoxes() {
        const boxes = getOtpBoxes();

        boxes.forEach((box) => {
            box.disabled = false;
        });
    }


    function clearOtpBoxes() {
        const boxes = getOtpBoxes();

        boxes.forEach((box) => {
            box.value = "";
        });

        updateHiddenOtp();
    }


    function getEnteredOtp() {
        const boxes = getOtpBoxes();

        if (boxes.length === OTP_LENGTH) {
            return boxes
                .map((box) => sanitizeOtp(box.value))
                .join("");
        }

        const hiddenInput = getOtpInput();

        return hiddenInput
            ? sanitizeOtp(hiddenInput.value)
            : "";
    }


    function updateHiddenOtp() {
        const value = getOtpBoxes()
            .map((box) => sanitizeOtp(box.value))
            .join("");

        const hiddenInput = getOtpInput();

        if (hiddenInput) {
            hiddenInput.value = value;
        }

        return value;
    }


    function focusFirstEmptyBox() {
        const boxes = getOtpBoxes();

        const emptyBox = boxes.find(
            (box) => !sanitizeOtp(box.value)
        );

        if (emptyBox && !emptyBox.disabled) {
            emptyBox.focus();
        }
    }


    /* =========================================================
       AUTO-FILL GENERATED OTP
       ========================================================= */

    function fillOtpBoxes(code) {
        const cleanCode = sanitizeOtp(code);

        if (cleanCode.length !== OTP_LENGTH) {
            return false;
        }

        const boxes = getOtpBoxes();

        if (boxes.length !== OTP_LENGTH) {
            const hiddenInput = getOtpInput();

            if (hiddenInput) {
                hiddenInput.value = cleanCode;
            }

            return true;
        }

        enableOtpBoxes();

        boxes.forEach((box, index) => {
            box.value = cleanCode[index] || "";
        });

        updateHiddenOtp();

        /*
         * Focus the last box so the user can immediately see that
         * all six digits have been inserted.
         */
        if (boxes.length > 0) {
            boxes[boxes.length - 1].focus();
        }

        updateVerifyButton();

        return true;
    }


    /* =========================================================
       OTP BOX EVENT HANDLERS
       ========================================================= */

    function setupOtpBoxes() {
        const boxes = getOtpBoxes();

        if (!boxes.length) {
            return;
        }

        boxes.forEach((box, index) => {

            box.setAttribute(
                "inputmode",
                "numeric"
            );

            box.setAttribute(
                "autocomplete",
                "one-time-code"
            );

            box.setAttribute(
                "maxlength",
                "1"
            );


            /* -------------------------------------------------
               INPUT
               ------------------------------------------------- */

            box.addEventListener("input", (event) => {
                if (box.disabled) {
                    return;
                }

                const value = sanitizeOtp(
                    event.target.value
                );

                /*
                 * If multiple digits somehow enter this box,
                 * distribute them across the remaining boxes.
                 */
                if (value.length > 1) {
                    const digits = value.split("");

                    digits.forEach((digit, offset) => {
                        const targetIndex = index + offset;

                        if (boxes[targetIndex]) {
                            boxes[targetIndex].value = digit;
                        }
                    });

                    updateHiddenOtp();

                    const nextIndex = Math.min(
                        index + digits.length,
                        boxes.length - 1
                    );

                    boxes[nextIndex].focus();

                    updateVerifyButton();

                    return;
                }

                box.value = value;

                updateHiddenOtp();

                if (
                    value &&
                    index < boxes.length - 1
                ) {
                    boxes[index + 1].focus();
                }

                updateVerifyButton();
            });


            /* -------------------------------------------------
               KEYDOWN
               ------------------------------------------------- */

            box.addEventListener("keydown", (event) => {
                if (box.disabled) {
                    return;
                }

                if (event.key === "Backspace") {

                    if (!box.value && index > 0) {
                        event.preventDefault();

                        boxes[index - 1].value = "";

                        boxes[index - 1].focus();

                        updateHiddenOtp();

                        updateVerifyButton();
                    }

                    return;
                }


                if (
                    event.key === "ArrowLeft" &&
                    index > 0
                ) {
                    event.preventDefault();

                    boxes[index - 1].focus();

                    return;
                }


                if (
                    event.key === "ArrowRight" &&
                    index < boxes.length - 1
                ) {
                    event.preventDefault();

                    boxes[index + 1].focus();

                    return;
                }


                /*
                 * Prevent non-numeric characters.
                 */
                if (
                    event.key.length === 1 &&
                    !/\d/.test(event.key)
                ) {
                    event.preventDefault();
                }
            });


            /* -------------------------------------------------
               PASTE
               ------------------------------------------------- */

            box.addEventListener("paste", (event) => {
                if (box.disabled) {
                    return;
                }

                event.preventDefault();

                const pastedText =
                    event.clipboardData?.getData("text") || "";

                const code = sanitizeOtp(
                    pastedText
                );

                if (!code) {
                    return;
                }

                /*
                 * Paste the complete code starting from the
                 * current box.
                 */
                code.split("").forEach(
                    (digit, offset) => {
                        const targetIndex =
                            index + offset;

                        if (boxes[targetIndex]) {
                            boxes[targetIndex].value =
                                digit;
                        }
                    }
                );

                updateHiddenOtp();

                const focusIndex = Math.min(
                    index + code.length,
                    boxes.length - 1
                );

                boxes[focusIndex].focus();

                updateVerifyButton();
            });
        });
    }


    /* =========================================================
       VERIFY BUTTON
       ========================================================= */

    function updateVerifyButton() {
        const button = getVerifyButton();

        if (!button) {
            return;
        }

        const code = getEnteredOtp();

        const state = getState();

        const canVerify =
            !verificationInProgress &&
            state.codeReady &&
            code.length === OTP_LENGTH;

        button.disabled = !canVerify;
    }


    function setVerifyLoading(isLoading) {
        const button = getVerifyButton();

        if (!button) {
            return;
        }

        const text = button.querySelector(
            ".button-text"
        );

        const loader = button.querySelector(
            ".button-loader"
        );

        button.disabled = isLoading;

        button.classList.toggle(
            "is-loading",
            isLoading
        );

        if (text) {
            text.style.display =
                isLoading ? "none" : "";
        }

        if (loader) {
            loader.style.display =
                isLoading ? "inline-flex" : "none";
        }
    }


    /* =========================================================
       BACKEND OTP RESPONSE HANDLING
       ========================================================= */

    function extractOtpFromResponse(result) {
        if (!result) {
            return "";
        }

        /*
         * Support several possible API response structures.
         */
        const possibleCodes = [
            result.otp,
            result.code,
            result.verificationCode,

            result.data?.otp,
            result.data?.code,
            result.data?.verificationCode,

            result.result?.otp,
            result.result?.code,
            result.result?.verificationCode
        ];

        for (const possibleCode of possibleCodes) {
            const cleanCode = sanitizeOtp(
                possibleCode
            );

            if (cleanCode.length === OTP_LENGTH) {
                return cleanCode;
            }
        }

        return "";
    }


    function extractStateFromResponse(result) {
        if (!result) {
            return {};
        }

        const data =
            result.data ||
            result.result ||
            result;

        return {
            uid:
                data.uid ||
                data.userId ||
                data.id ||
                "",

            email:
                data.email ||
                "",

            phone:
                data.phone ||
                data.phoneNumber ||
                "",

            username:
                data.username ||
                data.user?.username ||
                "",

            channel:
                data.channel ||
                data.otpChannel ||
                ""
        };
    }


    /* =========================================================
       REQUEST OTP FROM BACKEND
       ========================================================= */

    async function requestGeneratedOtp(channel = "email") {

        if (!API) {
            throw new Error(
                "StockFlow API is not available."
            );
        }


        const state = getState();

        const payload = {
            uid: state.uid,
            username: state.username,
            email: state.email,
            phone: state.phone,

            channel: channel,
            otpChannel: channel
        };


        /*
         * Preferred method:
         * API.generateOtp()
         */
        if (typeof API.generateOtp === "function") {
            return await API.generateOtp(payload);
        }


        /*
         * Alternative naming:
         * API.createOtp()
         */
        if (typeof API.createOtp === "function") {
            return await API.createOtp(payload);
        }


        /*
         * Existing resend endpoint can also be used if that is
         * how your API is currently structured.
         */
        if (typeof API.resendOtp === "function") {
            return await API.resendOtp(payload);
        }


        throw new Error(
            "No OTP generation endpoint is available in StockFlow API."
        );
    }


    /* =========================================================
       DISPLAY GENERATED OTP
       ========================================================= */

    function displayGeneratedCode(code) {
        const cleanCode = sanitizeOtp(code);

        if (cleanCode.length !== OTP_LENGTH) {
            throw new Error(
                "The server returned an invalid OTP."
            );
        }


        /*
         * Store the exact server-generated OTP locally so the
         * verification request uses the same value.
         */
        saveState({
            code: cleanCode,
            codeReady: true
        });


        /*
         * Automatically insert the exact same code into
         * the six visible boxes.
         */
        fillOtpBoxes(cleanCode);


        /*
         * Update verification description.
         */
        const description = getElement(
            "#verificationDescription"
        );

        if (description) {
            description.textContent =
                "Your verification code is ready. The code has been automatically entered.";
        }


        const help = getElement(
            "#otpHelp"
        );

        if (help) {
            help.textContent =
                "Your six-digit verification code has been entered automatically.";
        }


        /*
         * Show confirmation popup/message.
         */
        showMessage(
            `Your verification code is ${cleanCode}.`,
            "success"
        );


        updateVerifyButton();
    }


    /* =========================================================
       GENERATION DELAY
       ========================================================= */

    function getRandomGenerationDelay() {
        return Math.floor(
            Math.random() *
            (
                MAX_GENERATION_DELAY -
                MIN_GENERATION_DELAY +
                1
            )
        ) + MIN_GENERATION_DELAY;
    }


    function waitForGenerationDelay() {
        return new Promise((resolve) => {

            const delay =
                getRandomGenerationDelay();

            if (generationTimer) {
                clearTimeout(generationTimer);
            }

            generationTimer = setTimeout(() => {
                generationTimer = null;

                resolve();

            }, delay);
        });
    }


    /* =========================================================
       PREPARE OTP
       ========================================================= */

    async function prepareOtp(channel = null) {

        if (otpGenerationInProgress) {
            return;
        }

        if (!hasVerificationState()) {
            showMessage(
                "Verification information is missing. Please return to registration and try again.",
                "error"
            );

            return;
        }


        otpGenerationInProgress = true;

        try {

            const state = getState();

            const selectedChannel =
                channel ||
                state.channel ||
                "email";


            /*
             * Reset the previous OTP.
             */
            clearOtpCodeState();

            disableOtpBoxes(true);

            updateVerifyButton();


            /*
             * Update page text while the OTP is being generated.
             */
            const description = getElement(
                "#verificationDescription"
            );

            if (description) {
                description.textContent =
                    "Generating your verification code. Please wait a moment...";
            }


            const help = getElement(
                "#otpHelp"
            );

            if (help) {
                help.textContent =
                    "Your six-digit verification code is being prepared.";
            }


            clearMessage();


            /*
             * Ask the backend to generate/store the OTP.
             *
             * The backend is responsible for:
             * - generating the OTP
             * - storing it in Firebase
             * - storing it in Google Sheets
             */
            const result =
                await requestGeneratedOtp(
                    selectedChannel
                );


            /*
             * Extract the OTP returned by the backend.
             */
            const generatedCode =
                extractOtpFromResponse(result);


            if (generatedCode.length !== OTP_LENGTH) {
                throw new Error(
                    "The OTP was generated, but the server did not return a valid six-digit code."
                );
            }


            /*
             * Save any updated verification state returned
             * by the backend.
             */
            const returnedState =
                extractStateFromResponse(result);

            saveState(returnedState);


            /*
             * IMPORTANT:
             *
             * The backend OTP is already generated and stored.
             * We now wait 3–5 seconds before revealing it and
             * automatically entering it into the six boxes.
             */
            await waitForGenerationDelay();


            /*
             * Make sure the page is still active.
             */
            if (
                !document.body.contains(
                    getElement("#otpForm")
                )
            ) {
                return;
            }


            /*
             * Automatically fill the six boxes.
             */
            displayGeneratedCode(
                generatedCode
            );


        } catch (error) {

            console.error(
                "OTP preparation failed:",
                error
            );


            clearOtpCodeState();

            disableOtpBoxes(true);

            updateVerifyButton();


            showMessage(
                normalizeOtpError(error),
                "error"
            );


            const description = getElement(
                "#verificationDescription"
            );

            if (description) {
                description.textContent =
                    "We could not prepare your verification code. Please try again.";
            }

        } finally {

            otpGenerationInProgress = false;
        }
    }


    /* =========================================================
       VERIFY OTP
       ========================================================= */

    async function verifyOtp() {

        if (verificationInProgress) {
            return;
        }


        const code = sanitizeOtp(
            getEnteredOtp()
        );

        const state = getState();


        if (code.length !== OTP_LENGTH) {
            showMessage(
                "Please enter the complete six-digit verification code.",
                "error"
            );

            focusFirstEmptyBox();

            return;
        }


        if (!state.codeReady) {
            showMessage(
                "Your verification code is not ready yet. Please wait a moment.",
                "error"
            );

            return;
        }


        if (!hasVerificationState()) {
            showMessage(
                "Your verification session has expired. Please return to registration and try again.",
                "error"
            );

            return;
        }


        if (!API) {
            showMessage(
                "The verification service is currently unavailable.",
                "error"
            );

            return;
        }


        if (
            typeof API.verifyOtp !== "function"
        ) {
            showMessage(
                "OTP verification is not configured in the API.",
                "error"
            );

            return;
        }


        verificationInProgress = true;

        setVerifyLoading(true);

        clearMessage();


        try {

            const payload = {
                uid: state.uid,

                username: state.username,

                email: state.email,

                phone: state.phone,

                channel: state.channel,

                otpChannel: state.channel,

                otp: code
            };


            const result =
                await API.verifyOtp(
                    payload
                );


            if (
                result &&
                result.success === false
            ) {
                throw new Error(
                    result.message ||
                    "The verification code is incorrect or has expired."
                );
            }


            /*
             * Save authentication information returned by
             * the backend.
             */
            if (result?.token) {
                sessionStorage.setItem(
                    "STOCKFLOW_TOKEN",
                    result.token
                );
            }


            if (result?.data?.token) {
                sessionStorage.setItem(
                    "STOCKFLOW_TOKEN",
                    result.data.token
                );
            }


            if (result?.user) {
                sessionStorage.setItem(
                    "STOCKFLOW_USER",
                    JSON.stringify(result.user)
                );
            }


            if (result?.data?.user) {
                sessionStorage.setItem(
                    "STOCKFLOW_USER",
                    JSON.stringify(result.data.user)
                );
            }


            /*
             * Mark the account as verified.
             */
            sessionStorage.setItem(
                "STOCKFLOW_VERIFIED",
                "true"
            );


            showMessage(
                "Your account has been verified successfully!",
                "success"
            );


            /*
             * OTP should no longer remain in the browser
             * after successful verification.
             */
            clearOtpCodeState();


            /*
             * Redirect to dashboard.
             */
            setTimeout(() => {

                window.location.href =
                    "dashboard.html";

            }, 1000);


        } catch (error) {

            console.error(
                "OTP verification failed:",
                error
            );


            showMessage(
                normalizeOtpError(error),
                "error"
            );


            /*
             * Clear entered digits after a failed attempt.
             */
            clearOtpBoxes();

            focusFirstEmptyBox();


        } finally {

            verificationInProgress = false;

            setVerifyLoading(false);

            updateVerifyButton();
        }
    }


    /* =========================================================
       ERROR NORMALIZATION
       ========================================================= */

    function normalizeOtpError(error) {

        const rawMessage =
            error?.message ||
            error?.error ||
            String(error || "");


        const message =
            rawMessage.toLowerCase();


        if (
            (
                message.includes("invalid") ||
                message.includes("incorrect") ||
                message.includes("wrong") ||
                message.includes("expired")
            ) &&
            (
                message.includes("otp") ||
                message.includes("code") ||
                message.includes("verification")
            )
        ) {
            return "The verification code is incorrect or has expired.";
        }


        if (
            message.includes("too many") ||
            message.includes("rate limit")
        ) {
            return "Too many attempts. Please wait and try again.";
        }


        if (
            message.includes("network") ||
            message.includes("fetch")
        ) {
            return "Unable to connect to the verification service. Please check your connection and try again.";
        }


        return (
            rawMessage ||
            "Something went wrong while processing your verification code."
        );
    }


    /* =========================================================
       COOLDOWN STORAGE
       ========================================================= */

    function getSentKey(channel) {
        return channel === "phone"
            ? STORAGE.PHONE_SENT
            : STORAGE.EMAIL_SENT;
    }


    function getLastSent(channel) {
        const key = getSentKey(channel);

        return Number(
            sessionStorage.getItem(key) || 0
        );
    }


    function setLastSent(
        channel,
        timestamp = Date.now()
    ) {
        sessionStorage.setItem(
            getSentKey(channel),
            String(timestamp)
        );
    }


    function remainingCooldown(channel) {

        const lastSent =
            getLastSent(channel);

        if (!lastSent) {
            return 0;
        }


        const elapsed =
            Math.floor(
                (Date.now() - lastSent) / 1000
            );


        return Math.max(
            0,
            COOLDOWN_SECONDS - elapsed
        );
    }


    function formatTime(seconds) {

        const minutes =
            Math.floor(seconds / 60);

        const remainingSeconds =
            seconds % 60;


        return (
            String(minutes).padStart(2, "0") +
            ":" +
            String(remainingSeconds).padStart(2, "0")
        );
    }


    /* =========================================================
       UPDATE RESEND BUTTON
       ========================================================= */

    function updateMethodButton(channel) {

        const button =
            channel === "phone"
                ? getPhoneButton()
                : getEmailButton();


        const timerElement =
            channel === "phone"
                ? getPhoneTimerElement()
                : getEmailTimerElement();


        if (!button) {
            return;
        }


        const remaining =
            remainingCooldown(channel);


        const busy =
            channel === "phone"
                ? phoneResendInProgress
                : emailResendInProgress;


        button.disabled =
            busy || remaining > 0;


        if (busy) {

            button.textContent =
                "Sending...";

        } else if (remaining > 0) {

            if (timerElement) {
                timerElement.textContent =
                    formatTime(remaining);
            }

        } else {

            /*
             * Restore original button text.
             */
            if (channel === "phone") {
                button.textContent =
                    "Send code by phone";
            } else {
                button.textContent =
                    "Send code by email";
            }

            if (timerElement) {
                timerElement.textContent =
                    "";
            }
        }
    }


    /* =========================================================
       UPDATE ALL COOLDOWN UI
       ========================================================= */

    function updateCooldownUI() {

        updateMethodButton("email");

        updateMethodButton("phone");


        const emailRemaining =
            remainingCooldown("email");

        const phoneRemaining =
            remainingCooldown("phone");


        if (
            emailRemaining <= 0 &&
            phoneRemaining <= 0
        ) {
            if (cooldownTimer) {
                clearInterval(
                    cooldownTimer
                );

                cooldownTimer = null;
            }
        }
    }


    function startCooldownTicker() {

        if (cooldownTimer) {
            clearInterval(
                cooldownTimer
            );
        }


        updateCooldownUI();


        if (
            remainingCooldown("email") <= 0 &&
            remainingCooldown("phone") <= 0
        ) {
            return;
        }


        cooldownTimer =
            setInterval(() => {

                updateCooldownUI();

            }, 1000);
    }


    /* =========================================================
       SEND / RESEND OTP
       ========================================================= */

    async function sendCode(channel) {

        if (
            channel !== "email" &&
            channel !== "phone"
        ) {
            return;
        }


        const isPhone =
            channel === "phone";


        const isBusy =
            isPhone
                ? phoneResendInProgress
                : emailResendInProgress;


        if (isBusy) {
            return;
        }


        const remaining =
            remainingCooldown(channel);


        if (remaining > 0) {

            showMessage(
                `Please wait ${formatTime(remaining)} before requesting another code.`,
                "error"
            );

            return;
        }


        if (!API) {

            showMessage(
                "The verification service is currently unavailable.",
                "error"
            );

            return;
        }


        if (
            typeof API.resendOtp !== "function" &&
            typeof API.generateOtp !== "function" &&
            typeof API.createOtp !== "function"
        ) {

            showMessage(
                "OTP resend is not configured in the API.",
                "error"
            );

            return;
        }


        const state = getState();


        if (!hasVerificationState()) {

            showMessage(
                "Your verification session is missing. Please return to registration.",
                "error"
            );

            return;
        }


        /*
         * Make sure the selected destination exists.
         */
        if (
            channel === "email" &&
            !state.email
        ) {

            showMessage(
                "No email address is available for verification.",
                "error"
            );

            return;
        }


        if (
            channel === "phone" &&
            !state.phone
        ) {

            showMessage(
                "No phone number is available for verification.",
                "error"
            );

            return;
        }


        /*
         * Set the correct busy state.
         */
        if (isPhone) {
            phoneResendInProgress = true;
        } else {
            emailResendInProgress = true;
        }


        updateMethodButton(channel);


        try {

            /*
             * Remove the previous OTP immediately.
             */
            clearOtpCodeState();

            disableOtpBoxes(true);

            updateVerifyButton();


            showMessage(
                `Generating a new ${channel} verification code...`,
                "info"
            );


            const payload = {
                uid: state.uid,

                username: state.username,

                email: state.email,

                phone: state.phone,

                channel: channel,

                otpChannel: channel
            };


            /*
             * Prefer resendOtp for an actual resend.
             */
            let result;


            if (
                typeof API.resendOtp === "function"
            ) {

                result =
                    await API.resendOtp(
                        payload
                    );

            } else if (
                typeof API.generateOtp === "function"
            ) {

                result =
                    await API.generateOtp(
                        payload
                    );

            } else {

                result =
                    await API.createOtp(
                        payload
                    );
            }


            /*
             * Extract the NEW backend-generated OTP.
             */
            const generatedCode =
                extractOtpFromResponse(result);


            if (
                generatedCode.length !== OTP_LENGTH
            ) {

                throw new Error(
                    "The server did not return a valid six-digit OTP."
                );
            }


            /*
             * Save any updated verification state.
             */
            const returnedState =
                extractStateFromResponse(result);

            saveState({
                ...returnedState,
                channel: channel
            });


            /*
             * Store the new send timestamp.
             *
             * The cooldown begins when the resend request
             * succeeds.
             */
            setLastSent(
                channel,
                Date.now()
            );


            /*
             * Wait 3–5 seconds before revealing/auto-filling
             * the newly generated code.
             */
            await waitForGenerationDelay();


            /*
             * Display and automatically insert the NEW code.
             */
            displayGeneratedCode(
                generatedCode
            );


            showMessage(
                `A new verification code is ready: ${generatedCode}`,
                "success"
            );


            /*
             * Start resend cooldown.
             */
            startCooldownTicker();


        } catch (error) {

            console.error(
                "OTP resend failed:",
                error
            );


            showMessage(
                normalizeOtpError(error),
                "error"
            );


            clearOtpCodeState();

            disableOtpBoxes(true);

            updateVerifyButton();


        } finally {

            if (isPhone) {
                phoneResendInProgress = false;
            } else {
                emailResendInProgress = false;
            }


            updateMethodButton(
                channel
            );


            updateCooldownUI();
        }
    }


    /* =========================================================
       DISPLAY DESTINATIONS
       ========================================================= */

    function displayDestinations() {

        const state = getState();


        const emailStatus =
            getEmailStatusElement();


        const phoneStatus =
            getPhoneStatusElement();


        if (emailStatus) {

            if (state.email) {

                emailStatus.textContent =
                    `Code sent to ${maskEmail(state.email)}`;

            } else {

                emailStatus.textContent =
                    "No email address available";
            }
        }


        if (phoneStatus) {

            if (state.phone) {

                phoneStatus.textContent =
                    `Code sent to ${maskPhone(state.phone)}`;

            } else {

                phoneStatus.textContent =
                    "No phone number available";
            }
        }
    }


    /* =========================================================
       INITIALIZE SEND TIMES
       ========================================================= */

    function initializeSentTimes() {

        const state = getState();


        /*
         * Only initialize an email timestamp if there is
         * already an explicit indication that an email OTP
         * was sent.
         *
         * Do NOT automatically create a cooldown merely because
         * an email address exists.
         */

        if (
            state.email &&
            state.emailSent
        ) {
            sessionStorage.setItem(
                STORAGE.EMAIL_SENT,
                state.emailSent
            );
        }


        if (
            state.phone &&
            state.phoneSent
        ) {
            sessionStorage.setItem(
                STORAGE.PHONE_SENT,
                state.phoneSent
            );
        }
    }


    /* =========================================================
       FORM / BUTTON SETUP
       ========================================================= */

    function setupButtons() {

        const form = getElement(
            "#otpForm"
        );


        if (form) {

            form.addEventListener(
                "submit",
                (event) => {

                    event.preventDefault();

                    verifyOtp();
                }
            );
        }


        const emailButton =
            getEmailButton();


        if (emailButton) {

            emailButton.addEventListener(
                "click",
                (event) => {

                    event.preventDefault();

                    sendCode("email");
                }
            );
        }


        const phoneButton =
            getPhoneButton();


        if (phoneButton) {

            phoneButton.addEventListener(
                "click",
                (event) => {

                    event.preventDefault();

                    sendCode("phone");
                }
            );
        }


        /*
         * Back to login button.
         */
        const backButtons =
            document.querySelectorAll(
                "[data-back-login]"
            );


        backButtons.forEach((button) => {

            button.addEventListener(
                "click",
                () => {

                    clearOtpStorage();

                }
            );
        });
    }


    /* =========================================================
       PAGE INITIALIZATION
       ========================================================= */

    async function initialize() {

        /*
         * Only execute OTP controller on verify.html.
         */
        const currentPage =
            window.location.pathname
                .split("/")
                .pop()
                .toLowerCase();


        /*
         * Legacy compatibility:
         * verify-otp.html redirects to verify.html.
         */
        if (
            currentPage === "verify-otp.html"
        ) {

            window.location.replace(
                "verify.html"
            );

            return;
        }


        if (
            currentPage &&
            currentPage !== "verify.html"
        ) {
            return;
        }


        setupOtpBoxes();

        setupButtons();

        displayDestinations();

        initializeSentTimes();

        updateCooldownUI();

        startCooldownTicker();


        /*
         * Check whether registration supplied the required
         * verification information.
         */
        if (!hasVerificationState()) {

            disableOtpBoxes(true);

            showMessage(
                "Verification information is missing. Please return to registration and try again.",
                "error"
            );

            return;
        }


        /*
         * Generate the first OTP.
         *
         * Backend:
         * Firebase + Google Sheets
         *
         * Frontend:
         * wait 3–5 seconds
         * then auto-fill six boxes
         */
        await prepareOtp();
    }


    /* =========================================================
       PUBLIC API
       ========================================================= */

    window.StockFlowOTP = {

        verify: verifyOtp,

        resend: sendCode,

        sanitize: sanitizeOtp,

        getState: getState,

        maskEmail: maskEmail,

        maskPhone: maskPhone,

        prepare: prepareOtp,

        clear: clearOtpStorage
    };


    /*
     * Legacy alias.
     */
    window.OTP = window.StockFlowOTP;


    /* =========================================================
       DOM READY
       ========================================================= */

    if (
        document.readyState === "loading"
    ) {

        document.addEventListener(
            "DOMContentLoaded",
            initialize
        );

    } else {

        initialize();
    }


})();
