/*
=========================================================
STOCKFLOW OTP VERIFICATION CONTROLLER
Phone Accessories Inventory Management System
=========================================================

OTP FLOW
--------

register.js
    ↓
Google Apps Script
    ↓
Code.gs
    ↓
Real 6-digit OTP generated by backend
    ↓
Google Sheets + Firebase
    ↓
verify.html
    ↓
otp.js
    ↓
StockFlowAPI.prepareOtp()
    ↓
Backend returns the SAME generated OTP
    ↓
3–5 second UI display delay
    ↓
Six OTP boxes automatically filled
    ↓
User clicks Verify Account
    ↓
StockFlowAPI.verifyOtp()
    ↓
Code.gs verifies OTP
    ↓
Employee Dashboard


IMPORTANT SECURITY RULES
------------------------

1. OTP is NEVER generated in this browser.
2. OTP is NEVER generated with Math.random().
3. No hardcoded OTP is used.
4. Code.gs is the ONLY component that generates OTPs.
5. The browser only displays the OTP returned by Code.gs.
6. The exact backend OTP is used.
7. The backend OTP is stored in Google Sheets.
8. The backend OTP is stored in Firebase.
9. Email and phone OTP requests use independent cooldowns.
10. Each resend generates a NEW backend OTP.
11. Each resend has a 120-second cooldown.
12. Clicking a method card only selects the method.
13. Clicking "Send code by email" requests an email OTP.
14. Clicking "Send code by phone" requests a phone OTP.
15. The browser does NOT pretend to send Gmail or SMS.
16. Real email/SMS delivery is handled only by Code.gs
    and its configured provider.
=========================================================
*/

(function () {

    "use strict";


    /* =====================================================
       CONFIGURATION
       ===================================================== */

    const CONFIG =
        window.STOCKFLOW_CONFIG ||
        window.CONFIG ||
        {};


    const AUTH_CONFIG =
        CONFIG.AUTH ||
        {};


    const ROUTES =
        CONFIG.ROUTES ||
        {};


    const STORAGE =
        CONFIG.STORAGE ||
        {};


    const API =
        window.StockFlowAPI ||
        window.API ||
        null;


    /* =====================================================
       PAGE CHECK
       ===================================================== */

    const isVerificationPage =
        document.getElementById("otpForm") ||
        document.querySelector(".otp-digit") ||
        document.getElementById("verifyOtpBtn");


    if (!isVerificationPage) {

        return;
    }


    /* =====================================================
       CONSTANTS
       ===================================================== */

    const OTP_LENGTH =
        Number(
            AUTH_CONFIG.OTP_LENGTH ||
            6
        );


    /*
     * Backend requirement:
     *
     * Email cooldown  = 120 seconds
     * Phone cooldown  = 120 seconds
     *
     * The frontend uses 120 seconds even if the old
     * config.js still contains the previous 60-second value.
     */

    const RESEND_COOLDOWN =
        120;


    const OTP_EXPIRATION_MINUTES =
        Number(
            AUTH_CONFIG.OTP_EXPIRATION_MINUTES ||
            10
        );


    const MAX_OTP_ATTEMPTS =
        Number(
            AUTH_CONFIG.MAX_OTP_ATTEMPTS ||
            4
        );


    const OTP_LOCK_MINUTES =
        Number(
            AUTH_CONFIG.OTP_LOCK_MINUTES ||
            30
        );


    /*
     * Fixed UI delay.
     *
     * IMPORTANT:
     *
     * There is NO OTP generation here.
     *
     * The backend has already generated the OTP before
     * this timer starts.
     *
     * A fixed 4-second delay is used so otp.js contains
     * absolutely NO Math.random() usage.
     */

    const OTP_DISPLAY_DELAY =
        4000;


    /* =====================================================
       DOM HELPERS
       ===================================================== */

    const $ = function (id) {

        return document.getElementById(id);
    };


    const $$ = function (selector) {

        return Array.from(
            document.querySelectorAll(
                selector
            )
        );
    };


    /* =====================================================
       ELEMENTS
       ===================================================== */

    const otpForm =
        $("otpForm");


    const verifyButton =
        $("verifyOtpBtn") ||
        $("verifyButton") ||
        $("verifyBtn") ||
        document.querySelector(
            "[data-verify-otp]"
        );


    const otpMessage =
        $("otpMessage");


    const otpHelp =
        $("otpHelp");


    const verificationDescription =
        $("verificationDescription");


    const emailDeliveryStatus =
        $("emailDeliveryStatus");


    const phoneDeliveryStatus =
        $("phoneDeliveryStatus");


    const emailTimer =
        $("emailOtpTimer");


    const phoneTimer =
        $("phoneOtpTimer");


    const emailResendButton =
        $("resendEmailOtpBtn") ||
        document.querySelector(
            "[data-resend-email-otp]"
        );


    const phoneResendButton =
        $("resendPhoneOtpBtn") ||
        document.querySelector(
            "[data-resend-phone-otp]"
        );


    /* =====================================================
       OTP INPUTS
       ===================================================== */

    let otpInputs =
        $$(".otp-digit");


    /*
     * Fallback for numeric OTP inputs using another class.
     */

    if (
        otpInputs.length !== OTP_LENGTH
    ) {

        const fallbackInputs =
            $$("#otpForm input[inputmode='numeric']");


        if (
            fallbackInputs.length >=
            OTP_LENGTH
        ) {

            otpInputs =
                fallbackInputs.slice(
                    0,
                    OTP_LENGTH
                );
        }
    }


    const hiddenOtp =
        $("otp") ||
        $("otpCode") ||
        $("verificationCode");


    /* =====================================================
       STORAGE KEYS
       ===================================================== */

    const KEY = {

        UID:
            STORAGE.OTP_UID ||
            "STOCKFLOW_OTP_UID",

        EMAIL:
            STORAGE.OTP_EMAIL ||
            "STOCKFLOW_OTP_EMAIL",

        PHONE:
            STORAGE.OTP_PHONE ||
            "STOCKFLOW_OTP_PHONE",

        USERNAME:
            STORAGE.OTP_USERNAME ||
            "STOCKFLOW_OTP_USERNAME",

        IDENTITY:
            STORAGE.OTP_IDENTITY ||
            "STOCKFLOW_OTP_IDENTITY",

        CHANNEL:
            STORAGE.OTP_CHANNEL ||
            "STOCKFLOW_OTP_CHANNEL",

        CODE:
            STORAGE.OTP_CODE ||
            "STOCKFLOW_OTP_CODE",

        READY:
            STORAGE.OTP_READY ||
            "STOCKFLOW_OTP_CODE_READY",

        EMAIL_SENT:
            STORAGE.OTP_EMAIL_SENT ||
            "STOCKFLOW_OTP_EMAIL_SENT",

        PHONE_SENT:
            STORAGE.OTP_PHONE_SENT ||
            "STOCKFLOW_OTP_PHONE_SENT"
    };


    /* =====================================================
       RUNTIME STATE
       ===================================================== */

    const state = {

        uid:
            "",

        username:
            "",

        email:
            "",

        phone:
            "",

        identity:
            "",

        channel:
            "email",

        /*
         * ONLY the actual OTP returned by Code.gs.
         */

        backendOtp:
            "",

        prepared:
            false,

        verifying:
            false,

        preparing:
            false,

        resending:
            false,

        verified:
            false,

        emailCooldown:
            0,

        phoneCooldown:
            0,

        emailTimer:
            null,

        phoneTimer:
            null,

        otpDisplayTimer:
            null
    };


    /* =====================================================
       SAFE STORAGE
       ===================================================== */

    function storageGet(
        storage,
        key
    ) {

        try {

            return storage.getItem(
                key
            ) || "";

        } catch (error) {

            console.warn(
                "[STOCKFLOW OTP] Storage read failed:",
                error
            );

            return "";
        }
    }


    function storageSet(
        storage,
        key,
        value
    ) {

        try {

            storage.setItem(
                key,
                String(
                    value ?? ""
                )
            );

        } catch (error) {

            console.warn(
                "[STOCKFLOW OTP] Storage write failed:",
                error
            );
        }
    }


    function storageRemove(
        storage,
        key
    ) {

        try {

            storage.removeItem(
                key
            );

        } catch (error) {

            console.warn(
                "[STOCKFLOW OTP] Storage removal failed:",
                error
            );
        }
    }


    function getSession(
        key
    ) {

        return storageGet(
            window.sessionStorage,
            key
        );
    }


    function setSession(
        key,
        value
    ) {

        storageSet(
            window.sessionStorage,
            key,
            value
        );
    }


    function removeSession(
        key
    ) {

        storageRemove(
            window.sessionStorage,
            key
        );
    }


    /* =====================================================
       SAVED VALUE
       ===================================================== */

    function getSavedValue(
        key
    ) {

        const sessionValue =
            getSession(
                key
            );


        if (sessionValue) {

            return sessionValue;
        }


        return storageGet(
            window.localStorage,
            key
        );
    }


    function saveValue(
        key,
        value
    ) {

        setSession(
            key,
            value
        );


        storageSet(
            window.localStorage,
            key,
            value
        );
    }


    function removeSavedValue(
        key
    ) {

        removeSession(
            key
        );


        storageRemove(
            window.localStorage,
            key
        );
    }


    /* =====================================================
       STRING HELPERS
       ===================================================== */

    function clean(
        value
    ) {

        if (
            value === null ||
            typeof value ===
                "undefined"
        ) {

            return "";
        }


        return String(
            value
        ).trim();
    }


    function firstValue() {

        for (
            let i = 0;
            i < arguments.length;
            i++
        ) {

            const value =
                clean(
                    arguments[i]
                );


            if (value) {

                return value;
            }
        }


        return "";
    }


    /* =====================================================
       NORMALIZE PHONE
       ===================================================== */

    function normalizePhone(
        value
    ) {

        return clean(
            value
        ).replace(
            /[\s()-]/g,
            ""
        );
    }


    /* =====================================================
       LOAD STATE
       ===================================================== */

    function loadState() {

        state.uid =
            getSavedValue(
                KEY.UID
            );


        state.username =
            getSavedValue(
                KEY.USERNAME
            );


        state.email =
            getSavedValue(
                KEY.EMAIL
            );


        state.phone =
            getSavedValue(
                KEY.PHONE
            );


        state.identity =
            getSavedValue(
                KEY.IDENTITY
            );


        state.channel =
            getSavedValue(
                KEY.CHANNEL
            ) ||
            "email";


        if (
            state.channel !== "email" &&
            state.channel !== "phone"
        ) {

            state.channel =
                "email";
        }


        if (!state.identity) {

            state.identity =
                firstValue(
                    state.username,
                    state.email,
                    state.phone,
                    state.uid
                );
        }


        if (state.identity) {

            saveValue(
                KEY.IDENTITY,
                state.identity
            );
        }
    }


    /* =====================================================
       SAVE STATE
       ===================================================== */

    function saveState() {

        saveValue(
            KEY.UID,
            state.uid
        );


        saveValue(
            KEY.USERNAME,
            state.username
        );


        saveValue(
            KEY.EMAIL,
            state.email
        );


        saveValue(
            KEY.PHONE,
            state.phone
        );


        saveValue(
            KEY.IDENTITY,
            state.identity
        );


        saveValue(
            KEY.CHANNEL,
            state.channel
        );
    }


    /* =====================================================
       RESOLVE IDENTITY
       ===================================================== */

    function resolveIdentity() {

        state.identity =
            firstValue(
                state.identity,
                state.username,
                state.email,
                state.phone,
                state.uid
            );


        return state.identity;
    }


    /* =====================================================
       MESSAGE
       ===================================================== */

    function showMessage(
        message,
        type = "error"
    ) {

        if (!otpMessage) {

            return;
        }


        otpMessage.textContent =
            message || "";


        otpMessage.classList.remove(
            "success",
            "error",
            "warning",
            "info",
            "show"
        );


        otpMessage.classList.add(
            type
        );


        otpMessage.classList.add(
            "show"
        );


        otpMessage.hidden =
            false;


        otpMessage.setAttribute(
            "role",
            "alert"
        );
    }


    function hideMessage() {

        if (!otpMessage) {

            return;
        }


        otpMessage.textContent =
            "";


        otpMessage.classList.remove(
            "success",
            "error",
            "warning",
            "info",
            "show"
        );


        otpMessage.hidden =
            true;
    }


    /* =====================================================
       BUTTON LOADING
       ===================================================== */

    function setButtonLoading(
        button,
        loading,
        loadingText
    ) {

        if (!button) {

            return;
        }


        if (loading) {

            if (
                !button.dataset.originalText
            ) {

                button.dataset.originalText =
                    button.textContent;
            }


            button.disabled =
                true;


            button.textContent =
                loadingText ||
                "Please wait...";

        } else {

            button.disabled =
                false;


            if (
                button.dataset.originalText
            ) {

                button.textContent =
                    button.dataset.originalText;
            }
        }
    }


    /* =====================================================
       OTP VALUE
       ===================================================== */

    function getOtpValue() {

        if (
            otpInputs.length >=
            OTP_LENGTH
        ) {

            return otpInputs
                .slice(
                    0,
                    OTP_LENGTH
                )
                .map(
                    function (
                        input
                    ) {

                        return clean(
                            input.value
                        ).replace(
                            /\D/g,
                            ""
                        );
                    }
                )
                .join("")
                .slice(
                    0,
                    OTP_LENGTH
                );
        }


        if (hiddenOtp) {

            return clean(
                hiddenOtp.value
            ).replace(
                /\D/g,
                ""
            ).slice(
                0,
                OTP_LENGTH
            );
        }


        return "";
    }


    /* =====================================================
       SET OTP VALUE
       ===================================================== */

    function setOtpValue(
        code
    ) {

        const normalized =
            clean(
                code
            ).replace(
                /\D/g,
                ""
            ).slice(
                0,
                OTP_LENGTH
            );


        otpInputs.forEach(
            function (
                input,
                index
            ) {

                input.value =
                    normalized[index] ||
                    "";
            }
        );


        if (hiddenOtp) {

            hiddenOtp.value =
                normalized;
        }


        updateVerifyButton();
    }


    /* =====================================================
       ENABLE OTP INPUTS
       ===================================================== */

    function enableOtpInputs() {

        otpInputs.forEach(
            function (
                input
            ) {

                input.disabled =
                    false;
            }
        );
    }


    /* =====================================================
       DISABLE OTP INPUTS
       ===================================================== */

    function disableOtpInputs() {

        otpInputs.forEach(
            function (
                input
            ) {

                input.disabled =
                    true;
            }
        );


        if (verifyButton) {

            verifyButton.disabled =
                true;
        }
    }


    /* =====================================================
       VERIFY BUTTON
       ===================================================== */

    function updateVerifyButton() {

        if (!verifyButton) {

            return;
        }


        const otp =
            getOtpValue();


        verifyButton.disabled =
            state.verifying ||
            otp.length !== OTP_LENGTH;
    }


    /* =====================================================
       OTP INPUT INITIALIZATION
       ===================================================== */

    function initializeOtpInputs() {

        if (
            !otpInputs.length
        ) {

            return;
        }


        otpInputs.forEach(
            function (
                input,
                index
            ) {

                input.setAttribute(
                    "maxlength",
                    "1"
                );


                input.setAttribute(
                    "inputmode",
                    "numeric"
                );


                input.setAttribute(
                    "autocomplete",
                    index === 0
                        ? "one-time-code"
                        : "off"
                );


                input.addEventListener(
                    "input",
                    function () {

                        const value =
                            clean(
                                input.value
                            ).replace(
                                /\D/g,
                                ""
                            );


                        input.value =
                            value.slice(
                                0,
                                1
                            );


                        if (
                            input.value &&
                            index <
                                otpInputs.length - 1
                        ) {

                            otpInputs[
                                index + 1
                            ].focus();
                        }


                        updateHiddenOtp();


                        updateVerifyButton();
                    }
                );


                input.addEventListener(
                    "keydown",
                    function (
                        event
                    ) {

                        if (
                            event.key ===
                                "Backspace" &&
                            !input.value &&
                            index > 0
                        ) {

                            otpInputs[
                                index - 1
                            ].focus();
                        }


                        if (
                            event.key ===
                                "ArrowLeft" &&
                            index > 0
                        ) {

                            otpInputs[
                                index - 1
                            ].focus();
                        }


                        if (
                            event.key ===
                                "ArrowRight" &&
                            index <
                                otpInputs.length - 1
                        ) {

                            otpInputs[
                                index + 1
                            ].focus();
                        }
                    }
                );


                input.addEventListener(
                    "paste",
                    function (
                        event
                    ) {

                        event.preventDefault();


                        const clipboard =
                            event.clipboardData ||
                            window.clipboardData;


                        if (!clipboard) {

                            return;
                        }


                        const pasted =
                            clipboard
                                .getData(
                                    "text"
                                )
                                .replace(
                                    /\D/g,
                                    ""
                                )
                                .slice(
                                    0,
                                    OTP_LENGTH
                                );


                        if (!pasted) {

                            return;
                        }


                        setOtpValue(
                            pasted
                        );


                        const targetIndex =
                            Math.min(
                                pasted.length,
                                otpInputs.length
                            ) - 1;


                        if (
                            targetIndex >= 0
                        ) {

                            otpInputs[
                                targetIndex
                            ].focus();
                        }
                    }
                );
            }
        );
    }


    /* =====================================================
       HIDDEN OTP
       ===================================================== */

    function updateHiddenOtp() {

        if (!hiddenOtp) {

            return;
        }


        hiddenOtp.value =
            getOtpValue();
    }


    /* =====================================================
       FIXED OTP DISPLAY DELAY
       ===================================================== */

    function getOtpDisplayDelay() {

        /*
         * Fixed delay only.
         *
         * No OTP generation.
         * No Math.random().
         */

        return OTP_DISPLAY_DELAY;
    }


    /* =====================================================
       RESPONSE DATA
       ===================================================== */

    function getResponseData(
        response
    ) {

        if (
            !response ||
            typeof response !==
                "object"
        ) {

            return {};
        }


        if (
            response.data &&
            typeof response.data ===
                "object"
        ) {

            return {
                ...response,
                ...response.data
            };
        }


        return response;
    }


    /* =====================================================
       RESPONSE SUCCESS CHECK
       ===================================================== */

    function isResponseSuccessful(
        response
    ) {

        const data =
            getResponseData(
                response
            );


        if (
            data.success === false ||
            data.ok === false ||
            data.status === "ERROR" ||
            data.status === "error"
        ) {

            return false;
        }


        return true;
    }


    /* =====================================================
       EXTRACT BACKEND OTP
       ===================================================== */

    function extractBackendOtp(
        response
    ) {

        const data =
            getResponseData(
                response
            );


        /*
         * ONLY backend-returned fields are accepted.
         *
         * There is deliberately no fallback OTP.
         */

        const possibleOtp =
            firstValue(
                data.otp,
                data.OTP,
                data.code,
                data.verificationCode,
                data.verification_code
            );


        const normalized =
            clean(
                possibleOtp
            ).replace(
                /\D/g,
                ""
            );


        if (
            normalized.length ===
            OTP_LENGTH
        ) {

            return normalized;
        }


        return "";
    }


    /* =====================================================
       STORE BACKEND OTP
       ===================================================== */

    function storeBackendOtp(
        otp
    ) {

        const normalized =
            clean(
                otp
            ).replace(
                /\D/g,
                ""
            );


        if (
            normalized.length !==
            OTP_LENGTH
        ) {

            return false;
        }


        /*
         * This is the exact OTP returned by Code.gs.
         */

        state.backendOtp =
            normalized;


        saveValue(
            KEY.CODE,
            normalized
        );


        saveValue(
            KEY.READY,
            "true"
        );


        return true;
    }


    /* =====================================================
       CLEAR BACKEND OTP
       ===================================================== */

    function clearBackendOtp() {

        state.backendOtp =
            "";


        removeSavedValue(
            KEY.CODE
        );


        removeSavedValue(
            KEY.READY
        );
    }


    /* =====================================================
       DISPLAY BACKEND OTP
       ===================================================== */

    function displayBackendOtp(
        code
    ) {

        const normalized =
            clean(
                code
            ).replace(
                /\D/g,
                ""
            );


        if (
            normalized.length !==
            OTP_LENGTH
        ) {

            return false;
        }


        /*
         * Display exactly what the backend returned.
         */

        state.backendOtp =
            normalized;


        enableOtpInputs();


        setOtpValue(
            normalized
        );


        state.prepared =
            true;


        if (otpHelp) {

            otpHelp.textContent =
                "Your verification code is ready. Click Verify Account to continue.";
        }


        showMessage(
            "Your verification code is ready.",
            "success"
        );


        if (
            otpInputs.length
        ) {

            otpInputs[0].focus();
        }


        updateVerifyButton();


        return true;
    }


    /* =====================================================
       PREPARING MESSAGE
       ===================================================== */

    function displayPreparingMessage() {

        hideMessage();


        disableOtpInputs();


        clearVisibleOtp();


        if (otpHelp) {

            otpHelp.textContent =
                "Preparing your verification code...";
        }
    }


    /* =====================================================
       DESTINATIONS
       ===================================================== */

    function displayDestinations() {

        const email =
            clean(
                state.email
            );


        const phone =
            normalizePhone(
                state.phone
            );


        if (
            verificationDescription
        ) {

            verificationDescription.textContent =
                "Choose a verification method, then enter the 6-digit verification code.";
        }


        if (
            emailDeliveryStatus
        ) {

            if (email) {

                emailDeliveryStatus.textContent =
                    "Verification code for " +
                    maskEmail(email) +
                    ".";

            } else {

                emailDeliveryStatus.textContent =
                    "No Gmail address is available.";
            }
        }


        if (
            phoneDeliveryStatus
        ) {

            if (phone) {

                phoneDeliveryStatus.textContent =
                    "Verification code for " +
                    maskPhone(phone) +
                    ".";

            } else {

                phoneDeliveryStatus.textContent =
                    "No mobile number is available.";
            }
        }
    }


    /* =====================================================
       MASK EMAIL
       ===================================================== */

    function maskEmail(
        email
    ) {

        const value =
            clean(
                email
            );


        const at =
            value.indexOf("@");


        if (
            at <= 0
        ) {

            return value;
        }


        const name =
            value.slice(
                0,
                at
            );


        const domain =
            value.slice(
                at
            );


        if (
            name.length <= 2
        ) {

            return (
                name.charAt(0) +
                "*" +
                domain
            );
        }


        return (
            name.charAt(0) +
            "*".repeat(
                Math.min(
                    name.length - 1,
                    4
                )
            ) +
            domain
        );
    }


    /* =====================================================
       MASK PHONE
       ===================================================== */

    function maskPhone(
        phone
    ) {

        const value =
            normalizePhone(
                phone
            );


        if (
            value.length <= 4
        ) {

            return value;
        }


        return (
            "*".repeat(
                Math.max(
                    0,
                    value.length - 4
                )
            ) +
            value.slice(-4)
        );
    }


    /* =====================================================
       METHOD CARDS
       ===================================================== */

    function getMethodCards() {

        return $$(
            ".verification-method"
        );
    }


    /* =====================================================
       SET ACTIVE CHANNEL
       ===================================================== */

    function setActiveChannel(
        channel
    ) {

        if (
            channel !== "email" &&
            channel !== "phone"
        ) {

            return;
        }


        state.channel =
            channel;


        saveValue(
            KEY.CHANNEL,
            channel
        );


        getMethodCards()
            .forEach(
                function (
                    card
                ) {

                    const cardChannel =
                        card.dataset
                            .verificationMethod;


                    card.classList.toggle(
                        "active",
                        cardChannel ===
                            channel
                    );
                }
            );
    }


    /* =====================================================
       INITIALIZE METHOD CARDS
       ===================================================== */

    function initializeMethodCards() {

        const cards =
            getMethodCards();


        cards.forEach(
            function (
                card
            ) {

                const channel =
                    card.dataset
                        .verificationMethod;


                if (
                    channel !== "email" &&
                    channel !== "phone"
                ) {

                    return;
                }


                card.setAttribute(
                    "role",
                    "button"
                );


                card.setAttribute(
                    "tabindex",
                    "0"
                );


                /*
                 * IMPORTANT:
                 *
                 * Clicking the card ONLY selects the method.
                 *
                 * It does NOT generate a new OTP.
                 *
                 * The button inside the card performs the
                 * actual OTP request.
                 */

                card.addEventListener(
                    "click",
                    function (
                        event
                    ) {

                        if (
                            event.target.closest(
                                "button"
                            )
                        ) {

                            return;
                        }


                        setActiveChannel(
                            channel
                        );


                        hideMessage();
                    }
                );


                card.addEventListener(
                    "keydown",
                    function (
                        event
                    ) {

                        if (
                            event.key === "Enter" ||
                            event.key === " "
                        ) {

                            event.preventDefault();


                            setActiveChannel(
                                channel
                            );


                            hideMessage();
                        }
                    }
                );
            }
        );


        setActiveChannel(
            state.channel
        );
    }


    /* =====================================================
       POSITION EMAIL BUTTON
       ===================================================== */

    function positionEmailAction() {

        if (
            !emailResendButton
        ) {

            return;
        }


        const emailCard =
            document.querySelector(
                '.verification-method[data-verification-method="email"]'
            );


        if (
            !emailCard
        ) {

            return;
        }


        emailResendButton.classList.add(
            "verification-method-action"
        );


        emailResendButton.textContent =
            "Send code by email";


        if (
            !emailCard.contains(
                emailResendButton
            )
        ) {

            emailCard.appendChild(
                emailResendButton
            );
        }
    }


    /* =====================================================
       REQUEST BACKEND OTP
       ===================================================== */

    async function requestBackendOtp(
        mode = "prepare"
    ) {

        if (!API) {

            throw new Error(
                "StockFlowAPI is not available."
            );
        }


        const identity =
            resolveIdentity();


        if (!identity) {

            throw new Error(
                "Username or Gmail is required."
            );
        }


        saveState();


        const payload = {

            uid:
                state.uid,

            identity:
                identity,

            username:
                state.username,

            email:
                state.email,

            gmail:
                state.email,

            phone:
                state.phone,

            channel:
                state.channel
        };


        if (
            mode === "resend"
        ) {

            return await API.resendOtp(
                payload
            );
        }


        return await API.prepareOtp(
            payload
        );
    }


    /* =====================================================
       SYNCHRONIZE BACKEND ACCOUNT DATA
       ===================================================== */

    function synchronizeBackendData(
        response
    ) {

        const data =
            getResponseData(
                response
            );


        state.uid =
            firstValue(
                data.uid,
                data.UID,
                state.uid
            );


        state.username =
            firstValue(
                data.username,
                data.USERNAME,
                state.username
            );


        state.email =
            firstValue(
                data.email,
                data.gmail,
                data.GMAIL,
                state.email
            );


        state.phone =
            firstValue(
                data.phone,
                data.phoneNumber,
                data["PHONE NO."],
                state.phone
            );


        state.identity =
            firstValue(
                data.identity,
                state.identity,
                state.username,
                state.email,
                state.phone,
                state.uid
            );


        /*
         * If backend explicitly returns the channel,
         * synchronize it too.
         */

        const returnedChannel =
            clean(
                data.channel
            ).toLowerCase();


        if (
            returnedChannel === "email" ||
            returnedChannel === "phone"
        ) {

            state.channel =
                returnedChannel;
        }


        saveState();
    }


    /* =====================================================
       PREPARE INITIAL OTP
       ===================================================== */

    async function prepareOtp() {

        if (
            state.preparing
        ) {

            return;
        }


        /*
         * If an OTP is already visibly prepared,
         * do not automatically generate another one.
         */

        if (
            state.prepared &&
            state.backendOtp
        ) {

            return;
        }


        state.preparing =
            true;


        displayPreparingMessage();


        try {

            /*
             * Initial preparation uses the currently
             * selected channel.
             *
             * Default is email.
             */

            const response =
                await requestBackendOtp(
                    "prepare"
                );


            const data =
                getResponseData(
                    response
                );


            if (
                !isResponseSuccessful(
                    response
                )
            ) {

                throw createApiError(
                    data
                );
            }


            synchronizeBackendData(
                response
            );


            displayDestinations();


            /*
             * ONLY accept the actual OTP returned
             * from Code.gs.
             */

            const backendOtp =
                extractBackendOtp(
                    response
                );


            if (!backendOtp) {

                throw new Error(
                    "The verification service did not return the generated OTP."
                );
            }


            const stored =
                storeBackendOtp(
                    backendOtp
                );


            if (!stored) {

                throw new Error(
                    "The backend returned an invalid verification code."
                );
            }


            /*
             * Keep boxes disabled until the display delay
             * has completed.
             */

            disableOtpInputs();


            clearVisibleOtp();


            if (otpHelp) {

                otpHelp.textContent =
                    "Your verification code is being prepared...";
            }


            /*
             * Start cooldown after successful backend
             * OTP generation.
             *
             * This applies only to the selected channel.
             *
             * Email and phone cooldowns remain independent.
             */

            startCooldown(
                state.channel
            );


            /*
             * Fixed 4-second display delay.
             *
             * No OTP generation occurs here.
             */

            const delayMs =
                getOtpDisplayDelay();


            state.otpDisplayTimer =
                setTimeout(
                    function () {

                        state.otpDisplayTimer =
                            null;


                        displayBackendOtp(
                            backendOtp
                        );

                    },
                    delayMs
                );


        } catch (error) {

            console.error(
                "[STOCKFLOW OTP] Prepare failed:",
                error
            );


            state.prepared =
                false;


            clearBackendOtp();


            disableOtpInputs();


            showMessage(
                getErrorMessage(
                    error
                ),
                "error"
            );


            if (otpHelp) {

                otpHelp.textContent =
                    "We could not prepare your verification code. Please try again.";
            }

        } finally {

            state.preparing =
                false;


            updateResendButtons();
        }
    }


    /* =====================================================
       SEND / RESEND CODE
       ===================================================== */

    async function sendCode(
        channel
    ) {

        if (
            channel !== "email" &&
            channel !== "phone"
        ) {

            return;
        }


        if (
            state.resending ||
            state.preparing
        ) {

            return;
        }


        /*
         * Validate destination.
         */

        if (
            channel === "email" &&
            !state.email
        ) {

            showMessage(
                "No Gmail address is available for this account.",
                "error"
            );


            return;
        }


        if (
            channel === "phone" &&
            !state.phone
        ) {

            showMessage(
                "No mobile number is available for this account.",
                "error"
            );


            return;
        }


        const cooldown =
            channel === "email"
                ? state.emailCooldown
                : state.phoneCooldown;


        if (
            cooldown > 0
        ) {

            showMessage(
                "Please wait " +
                cooldown +
                " seconds before requesting another code.",
                "warning"
            );


            return;
        }


        /*
         * Select requested channel.
         */

        setActiveChannel(
            channel
        );


        state.resending =
            true;


        const button =
            channel === "email"
                ? emailResendButton
                : phoneResendButton;


        setButtonLoading(
            button,
            true,
            "Preparing..."
        );


        hideMessage();


        /*
         * Cancel previous display timer.
         */

        if (
            state.otpDisplayTimer
        ) {

            clearTimeout(
                state.otpDisplayTimer
            );


            state.otpDisplayTimer =
                null;
        }


        /*
         * The previous OTP must never remain visible.
         */

        clearBackendOtp();


        clearVisibleOtp();


        disableOtpInputs();


        if (otpHelp) {

            otpHelp.textContent =
                "Preparing your new verification code...";
        }


        try {

            const response =
                await requestBackendOtp(
                    "resend"
                );


            const data =
                getResponseData(
                    response
                );


            if (
                !isResponseSuccessful(
                    response
                )
            ) {

                throw createApiError(
                    data
                );
            }


            synchronizeBackendData(
                response
            );


            /*
             * Make sure backend response corresponds to
             * the channel requested by the user.
             */

            const responseChannel =
                clean(
                    data.channel
                ).toLowerCase();


            if (
                responseChannel === "email" ||
                responseChannel === "phone"
            ) {

                state.channel =
                    responseChannel;


                saveValue(
                    KEY.CHANNEL,
                    responseChannel
                );
            }


            displayDestinations();


            /*
             * ONLY accept backend-generated OTP.
             */

            const backendOtp =
                extractBackendOtp(
                    response
                );


            if (!backendOtp) {

                throw new Error(
                    "The verification service did not return the new generated OTP."
                );
            }


            const stored =
                storeBackendOtp(
                    backendOtp
                );


            if (!stored) {

                throw new Error(
                    "The backend returned an invalid verification code."
                );
            }


            if (otpHelp) {

                otpHelp.textContent =
                    "Your new verification code is being prepared...";
            }


            /*
             * Fixed 4-second display delay.
             *
             * No OTP generation happens here.
             */

            const delayMs =
                getOtpDisplayDelay();


            state.otpDisplayTimer =
                setTimeout(
                    function () {

                        state.otpDisplayTimer =
                            null;


                        displayBackendOtp(
                            backendOtp
                        );

                    },
                    delayMs
                );


            /*
             * Cooldown begins only after Code.gs
             * successfully generates the new OTP.
             */

            startCooldown(
                channel
            );


        } catch (error) {

            console.error(
                "[STOCKFLOW OTP] Resend failed:",
                error
            );


            /*
             * Do not leave an invalid/stale OTP in
             * browser storage after a failed request.
             */

            clearBackendOtp();


            clearVisibleOtp();


            disableOtpInputs();


            showMessage(
                getErrorMessage(
                    error
                ),
                "error"
            );


            if (otpHelp) {

                otpHelp.textContent =
                    "We could not generate a new verification code. Please try again.";
            }

        } finally {

            state.resending =
                false;


            setButtonLoading(
                button,
                false
            );


            updateResendButtons();
        }
    }


    /* =====================================================
       CLEAR VISIBLE OTP
       ===================================================== */

    function clearVisibleOtp() {

        otpInputs.forEach(
            function (
                input
            ) {

                input.value =
                    "";
            }
        );


        if (hiddenOtp) {

            hiddenOtp.value =
                "";
        }


        updateVerifyButton();
    }


    /* =====================================================
       VERIFY ACCOUNT
       ===================================================== */

    async function verifyAccount() {

        if (
            state.verifying
        ) {

            return;
        }


        const otp =
            getOtpValue();


        if (
            otp.length !==
            OTP_LENGTH
        ) {

            showMessage(
                "Please enter the complete 6-digit verification code.",
                "error"
            );


            if (
                otpInputs.length
            ) {

                const firstEmpty =
                    otpInputs.find(
                        function (
                            input
                        ) {

                            return !input.value;
                        }
                    );


                (
                    firstEmpty ||
                    otpInputs[0]
                ).focus();
            }


            return;
        }


        const identity =
            resolveIdentity();


        if (!identity) {

            showMessage(
                "Username or Gmail is required.",
                "error"
            );


            return;
        }


        /*
         * Prevent verification against an OTP that was
         * not issued by the current backend request.
         */

        if (
            !state.backendOtp
        ) {

            showMessage(
                "No active backend-issued verification code is available. Please request a new code.",
                "error"
            );


            return;
        }


        /*
         * Local comparison is only an early check.
         *
         * Code.gs remains the authoritative verifier.
         */

        if (
            otp !== state.backendOtp
        ) {

            showMessage(
                "The verification code is incorrect. Please try again.",
                "error"
            );


            return;
        }


        if (!API) {

            showMessage(
                "The verification service is unavailable.",
                "error"
            );


            return;
        }


        state.verifying =
            true;


        if (verifyButton) {

            if (
                !verifyButton.dataset.originalText
            ) {

                verifyButton.dataset.originalText =
                    verifyButton.textContent;
            }


            verifyButton.disabled =
                true;


            verifyButton.textContent =
                "Verifying...";
        }


        hideMessage();


        try {

            const response =
                await API.verifyOtp(
                    {

                        uid:
                            state.uid,

                        identity:
                            identity,

                        username:
                            state.username,

                        email:
                            state.email,

                        gmail:
                            state.email,

                        phone:
                            state.phone,

                        channel:
                            state.channel,

                        otp:
                            otp
                    }
                );


            const data =
                getResponseData(
                    response
                );


            if (
                !isResponseSuccessful(
                    response
                )
            ) {

                throw createApiError(
                    data
                );
            }


            /*
             * Backend verification succeeded.
             */

            state.verified =
                true;


            /*
             * Save authentication token if provided.
             */

            const token =
                firstValue(
                    data.token,
                    data.sessionToken,
                    data.session,
                    data.authToken
                );


            if (token) {

                saveValue(
                    STORAGE.TOKEN ||
                    "STOCKFLOW_TOKEN",
                    token
                );
            }


            /*
             * Save verified user information.
             */

            const user =
                data.user ||
                data.account ||
                data.profile ||
                null;


            if (
                user &&
                typeof user ===
                    "object"
            ) {

                try {

                    saveValue(
                        STORAGE.USER ||
                        "STOCKFLOW_USER",
                        JSON.stringify(
                            user
                        )
                    );

                } catch (error) {

                    console.warn(
                        "[STOCKFLOW OTP] Could not save user:",
                        error
                    );
                }
            }


            /*
             * OTP is no longer needed in browser storage.
             */

            clearBackendOtp();


            showMessage(
                "Account verified successfully. Redirecting to the Employee Dashboard...",
                "success"
            );


            /*
             * Stop cooldown timers before redirect.
             */

            clearTimers();


            /*
             * Direct dashboard redirect.
             */

            setTimeout(
                function () {

                    const dashboard =
                        ROUTES.DASHBOARD ||
                        "dashboard.html";


                    window.location.href =
                        dashboard;

                },
                700
            );


        } catch (error) {

            console.error(
                "[STOCKFLOW OTP] Verification failed:",
                error
            );


            state.verifying =
                false;


            if (verifyButton) {

                verifyButton.textContent =
                    verifyButton.dataset.originalText ||
                    "Verify Account";
            }


            showMessage(
                getErrorMessage(
                    error
                ),
                "error"
            );


            updateVerifyButton();
        }
    }


    /* =====================================================
       CREATE API ERROR
       ===================================================== */

    function createApiError(
        data
    ) {

        const error =
            new Error(
                firstValue(
                    data.message,
                    data.error,
                    data.errorMessage,
                    "The verification service returned an error."
                )
            );


        error.code =
            firstValue(
                data.code,
                data.errorCode,
                data.status
            );


        error.response =
            data;


        return error;
    }


    /* =====================================================
       ERROR MESSAGE
       ===================================================== */

    function getErrorMessage(
        error
    ) {

        if (!error) {

            return "Something went wrong. Please try again.";
        }


        const code =
            clean(
                error.code
            );


        const message =
            clean(
                error.message
            );


        const lowerMessage =
            message.toLowerCase();


        /* -------------------------------------------------
           IDENTITY
        ------------------------------------------------- */

        if (
            code ===
                "OTP_IDENTITY_MISSING" ||
            lowerMessage.includes(
                "username or gmail is required"
            )
        ) {

            return "Username or Gmail is required.";
        }


        /* -------------------------------------------------
           INVALID OTP
        ------------------------------------------------- */

        if (
            code ===
                "INVALID_OTP" ||
            code ===
                "OTP_INVALID"
        ) {

            return "The verification code is incorrect. Please try again.";
        }


        /* -------------------------------------------------
           EXPIRED OTP
        ------------------------------------------------- */

        if (
            code ===
                "OTP_EXPIRED"
        ) {

            return (
                "Your verification code has expired. " +
                "Please request a new code."
            );
        }


        /* -------------------------------------------------
           LOCKED
        ------------------------------------------------- */

        if (
            code ===
                "OTP_LOCKED" ||
            code ===
                "ACCOUNT_LOCKED"
        ) {

            return (
                "Verification is temporarily locked. " +
                "Please try again after " +
                OTP_LOCK_MINUTES +
                " minutes."
            );
        }


        /* -------------------------------------------------
           MAXIMUM ATTEMPTS
        ------------------------------------------------- */

        if (
            code ===
                "MAX_ATTEMPTS"
        ) {

            return (
                "You have reached the maximum verification attempts. " +
                "Please try again after " +
                OTP_LOCK_MINUTES +
                " minutes."
            );
        }


        /* -------------------------------------------------
           COOLDOWN
        ------------------------------------------------- */

        if (
            code ===
                "OTP_COOLDOWN"
        ) {

            return (
                "Please wait before requesting another verification code."
            );
        }


        /* -------------------------------------------------
           USER NOT FOUND
        ------------------------------------------------- */

        if (
            code ===
                "USER_NOT_FOUND" ||
            code ===
                "ACCOUNT_NOT_FOUND"
        ) {

            return (
                "No registered account was found for this verification request."
            );
        }


        /* -------------------------------------------------
           OTP NOT RETURNED
        ------------------------------------------------- */

        if (
            lowerMessage.includes(
                "did not return the generated otp"
            ) ||
            lowerMessage.includes(
                "did not return the new generated otp"
            )
        ) {

            return (
                "The verification service generated no usable verification code. " +
                "Please try again."
            );
        }


        /* -------------------------------------------------
           INVALID BACKEND OTP
        ------------------------------------------------- */

        if (
            lowerMessage.includes(
                "invalid verification code"
            )
        ) {

            return (
                "The verification service returned an invalid code. Please try again."
            );
        }


        /* -------------------------------------------------
           NETWORK
        ------------------------------------------------- */

        if (
            code ===
                "NETWORK_ERROR"
        ) {

            return (
                "Unable to connect to the verification service. Please try again."
            );
        }


        /* -------------------------------------------------
           TIMEOUT
        ------------------------------------------------- */

        if (
            code ===
                "TIMEOUT"
        ) {

            return (
                "The verification service took too long to respond. Please try again."
            );
        }


        /* -------------------------------------------------
           API CONFIGURATION
        ------------------------------------------------- */

        if (
            code ===
                "API_URL_MISSING" ||
            code ===
                "API_URL_INVALID"
        ) {

            return (
                "The verification service is not configured correctly."
            );
        }


        /* -------------------------------------------------
           SERVER
        ------------------------------------------------- */

        if (
            code ===
                "SERVER_ERROR" ||
            code ===
                "API_ERROR"
        ) {

            return (
                message ||
                "The verification service returned an error. Please try again."
            );
        }


        /* -------------------------------------------------
           GENERIC BACKEND MESSAGE
        ------------------------------------------------- */

        if (message) {

            return message;
        }


        return (
            "Something went wrong. Please try again."
        );
    }


    /* =====================================================
       COOLDOWN STORAGE
       ===================================================== */

    function getCooldownKey(
        channel
    ) {

        return (
            channel === "email"
                ? KEY.EMAIL_SENT
                : KEY.PHONE_SENT
        );
    }


    /* =====================================================
       START COOLDOWN
       ===================================================== */

    function startCooldown(
        channel
    ) {

        if (
            channel !== "email" &&
            channel !== "phone"
        ) {

            return;
        }


        const now =
            Date.now();


        const key =
            getCooldownKey(
                channel
            );


        saveValue(
            key,
            String(
                now
            )
        );


        if (
            channel === "email"
        ) {

            state.emailCooldown =
                RESEND_COOLDOWN;


            runCooldown(
                "email"
            );

        } else {

            state.phoneCooldown =
                RESEND_COOLDOWN;


            runCooldown(
                "phone"
            );
        }
    }


    /* =====================================================
       LOAD COOLDOWN
       ===================================================== */

    function loadCooldown(
        channel
    ) {

        const key =
            getCooldownKey(
                channel
            );


        const raw =
            getSavedValue(
                key
            );


        if (!raw) {

            return 0;
        }


        const timestamp =
            Number(
                raw
            );


        if (
            !Number.isFinite(
                timestamp
            )
        ) {

            removeSavedValue(
                key
            );


            return 0;
        }


        const elapsed =
            Math.floor(
                (
                    Date.now() -
                    timestamp
                ) /
                1000
            );


        const remaining =
            RESEND_COOLDOWN -
            elapsed;


        if (
            remaining <= 0
        ) {

            removeSavedValue(
                key
            );


            return 0;
        }


        return remaining;
    }


    /* =====================================================
       RUN COOLDOWN
       ===================================================== */

    function runCooldown(
        channel
    ) {

        if (
            channel === "email"
        ) {

            if (
                state.emailTimer
            ) {

                clearInterval(
                    state.emailTimer
                );
            }


            state.emailTimer =
                setInterval(
                    function () {

                        state.emailCooldown =
                            Math.max(
                                0,
                                state.emailCooldown - 1
                            );


                        if (
                            state.emailCooldown <=
                            0
                        ) {

                            clearInterval(
                                state.emailTimer
                            );


                            state.emailTimer =
                                null;


                            removeSavedValue(
                                KEY.EMAIL_SENT
                            );
                        }


                        updateTimerDisplay(
                            "email"
                        );


                        updateResendButtons();

                    },
                    1000
                );

        } else {

            if (
                state.phoneTimer
            ) {

                clearInterval(
                    state.phoneTimer
                );
            }


            state.phoneTimer =
                setInterval(
                    function () {

                        state.phoneCooldown =
                            Math.max(
                                0,
                                state.phoneCooldown - 1
                            );


                        if (
                            state.phoneCooldown <=
                            0
                        ) {

                            clearInterval(
                                state.phoneTimer
                            );


                            state.phoneTimer =
                                null;


                            removeSavedValue(
                                KEY.PHONE_SENT
                            );
                        }


                        updateTimerDisplay(
                            "phone"
                        );


                        updateResendButtons();

                    },
                    1000
                );
        }


        updateTimerDisplay(
            channel
        );


        updateResendButtons();
    }


    /* =====================================================
       UPDATE TIMER DISPLAY
       ===================================================== */

    function updateTimerDisplay(
        channel
    ) {

        const seconds =
            channel === "email"
                ? state.emailCooldown
                : state.phoneCooldown;


        const timer =
            channel === "email"
                ? emailTimer
                : phoneTimer;


        if (!timer) {

            return;
        }


        if (
            seconds <= 0
        ) {

            timer.textContent =
                "Ready";


            return;
        }


        const minutes =
            Math.floor(
                seconds / 60
            );


        const remainingSeconds =
            seconds % 60;


        timer.textContent =
            "Resend available in " +
            minutes +
            ":" +
            String(
                remainingSeconds
            ).padStart(
                2,
                "0"
            );
    }


    /* =====================================================
       UPDATE RESEND BUTTONS
       ===================================================== */

    function updateResendButtons() {

        if (
            emailResendButton
        ) {

            emailResendButton.disabled =
                state.emailCooldown > 0 ||
                state.resending ||
                state.preparing ||
                !state.email;
        }


        if (
            phoneResendButton
        ) {

            phoneResendButton.disabled =
                state.phoneCooldown > 0 ||
                state.resending ||
                state.preparing ||
                !state.phone;
        }
    }


    /* =====================================================
       INITIALIZE COOLDOWNS
       ===================================================== */

    function initializeCooldowns() {

        state.emailCooldown =
            loadCooldown(
                "email"
            );


        state.phoneCooldown =
            loadCooldown(
                "phone"
            );


        if (
            state.emailCooldown > 0
        ) {

            runCooldown(
                "email"
            );
        }


        if (
            state.phoneCooldown > 0
        ) {

            runCooldown(
                "phone"
            );
        }


        updateResendButtons();
    }


    /* =====================================================
       BUTTON EVENTS
       ===================================================== */

    function initializeButtons() {

        if (
            verifyButton
        ) {

            verifyButton.addEventListener(
                "click",
                function (
                    event
                ) {

                    event.preventDefault();


                    verifyAccount();
                }
            );
        }


        if (
            emailResendButton
        ) {

            emailResendButton.addEventListener(
                "click",
                function (
                    event
                ) {

                    event.preventDefault();


                    event.stopPropagation();


                    setActiveChannel(
                        "email"
                    );


                    sendCode(
                        "email"
                    );
                }
            );
        }


        if (
            phoneResendButton
        ) {

            phoneResendButton.addEventListener(
                "click",
                function (
                    event
                ) {

                    event.preventDefault();


                    event.stopPropagation();


                    setActiveChannel(
                        "phone"
                    );


                    sendCode(
                        "phone"
                    );
                }
            );
        }


        if (
            otpForm
        ) {

            otpForm.addEventListener(
                "submit",
                function (
                    event
                ) {

                    event.preventDefault();


                    verifyAccount();
                }
            );
        }
    }


    /* =====================================================
       KEYBOARD BEHAVIOR
       ===================================================== */

    function initializeKeyboardBehavior() {

        otpInputs.forEach(
            function (
                input
            ) {

                input.addEventListener(
                    "keydown",
                    function (
                        event
                    ) {

                        if (
                            event.key ===
                            "Enter"
                        ) {

                            event.preventDefault();


                            if (
                                getOtpValue()
                                    .length ===
                                OTP_LENGTH
                            ) {

                                verifyAccount();
                            }
                        }
                    }
                );
            }
        );
    }


    /* =====================================================
       RECOVERY LINK
       ===================================================== */

    function initializeRecoveryLink() {

        const link =
            $("recoveryLink") ||
            document.querySelector(
                'a[href*="recovery"]'
            );


        if (!link) {

            return;
        }


        const recoveryRoute =
            ROUTES.RECOVERY ||
            "recovery.html";


        link.setAttribute(
            "href",
            recoveryRoute
        );
    }


    /* =====================================================
       LEGACY OTP PAGE
       ===================================================== */

    function handleLegacyOtpPage() {

        const path =
            window.location.pathname
                .split("/")
                .pop()
                .toLowerCase();


        if (
            path ===
            "verify-otp.html"
        ) {

            const verifyRoute =
                ROUTES.VERIFY ||
                "verify.html";


            window.location.replace(
                verifyRoute
            );


            return true;
        }


        return false;
    }


    /* =====================================================
       CLEAR TIMERS
       ===================================================== */

    function clearTimers() {

        if (
            state.emailTimer
        ) {

            clearInterval(
                state.emailTimer
            );


            state.emailTimer =
                null;
        }


        if (
            state.phoneTimer
        ) {

            clearInterval(
                state.phoneTimer
            );


            state.phoneTimer =
                null;
        }


        if (
            state.otpDisplayTimer
        ) {

            clearTimeout(
                state.otpDisplayTimer
            );


            state.otpDisplayTimer =
                null;
        }
    }


    /* =====================================================
       CLEANUP
       ===================================================== */

    window.addEventListener(
        "beforeunload",
        function () {

            clearTimers();
        }
    );


    /* =====================================================
       INITIALIZE
       ===================================================== */

    async function initialize() {

        if (
            handleLegacyOtpPage()
        ) {

            return;
        }


        loadState();


        /*
         * Registration must have saved the identity before
         * redirecting to verify.html.
         */

        if (
            !resolveIdentity()
        ) {

            disableOtpInputs();


            showMessage(
                "Username or Gmail is required.",
                "error"
            );


            if (otpHelp) {

                otpHelp.textContent =
                    "Return to the registration page and open verification again.";
            }


            updateResendButtons();


            return;
        }


        saveState();


        displayDestinations();


        positionEmailAction();


        initializeMethodCards();


        initializeOtpInputs();


        initializeKeyboardBehavior();


        initializeButtons();


        initializeRecoveryLink();


        initializeCooldowns();


        /*
         * Remove old browser-side OTP.
         *
         * A fresh backend OTP will be requested.
         */

        clearBackendOtp();


        clearVisibleOtp();


        disableOtpInputs();


        /*
         * Request the real OTP from Code.gs.
         */

        await prepareOtp();
    }


    /* =====================================================
       PUBLIC CONTROLLER
       ===================================================== */

    window.StockFlowOTP = {

        getState:
            function () {

                return {
                    ...state
                };
            },


        prepare:
            prepareOtp,


        resend:
            sendCode,


        verify:
            verifyAccount,


        getOtp:
            getOtpValue,


        setOtp:
            setOtpValue,


        clearOtp:
            clearVisibleOtp,


        clearBackendOtp:
            clearBackendOtp
    };


    /* =====================================================
       START
       ===================================================== */

    if (
        document.readyState ===
        "loading"
    ) {

        document.addEventListener(
            "DOMContentLoaded",
            initialize,
            {
                once: true
            }
        );

    } else {

        initialize();
    }

})();
