document.addEventListener("DOMContentLoaded",async()=>{
"use strict";const $=id=>document.getElementById(id),form=$("productForm"),rows=$("rows"),a=$("alert"),btn=$("saveButton");
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const alert=(m,t="error")=>{a.textContent=m||"";a.className="sf-alert show "+t;};
const clear=()=>{form.reset();$("id").value="";$("reorderLevel").value=5;$("status").value="ACTIVE";};
let products=[];
const load=async()=>{const r=await StockFlowAPI.listProducts();if(!r?.success)throw new Error(r?.message||"Unable to load products.");products=r.products||[];
rows.innerHTML=products.length?products.map(p=>{const s=Number(p.STOCK||0),re=Number(p.REORDER_LEVEL||5),c=!s?"out":s<=re?"low":"active",st=!s?"OUT":s<=re?"LOW":"OK";return `<tr><td>${esc(p.SKU)}</td><td><strong>${esc(p.NAME)}</strong></td><td>${esc(p.CATEGORY||"-")}</td><td>₱${Number(p.PRICE||0).toFixed(2)}</td><td>${s}</td><td><span class="badge ${String(p.STATUS).toUpperCase()==="ACTIVE"?"active":"out"}">${esc(p.STATUS||"ACTIVE")}</span></td><td><div class="sf-actions"><button class="sf-btn secondary edit" data-id="${esc(p.ID)}">Edit</button><button class="sf-btn danger del" data-id="${esc(p.ID)}">Delete</button></div></td></tr>`}).join(""):`<tr><td colspan="7" class="sf-empty">No products found.</td></tr>`;
rows.querySelectorAll(".edit").forEach(b=>b.onclick=()=>{const p=products.find(x=>String(x.ID)===String(b.dataset.id));if(!p)return;["id","sku","name","category","supplier","price","cost","stock","reorderLevel","status"].forEach(k=>$((k)).value=p[k.toUpperCase()]??"");window.scrollTo({top:0,behavior:"smooth"});});
rows.querySelectorAll(".del").forEach(b=>b.onclick=async()=>{if(!confirm("Delete this product?"))return;const r=await StockFlowAPI.deleteProduct(b.dataset.id);if(!r?.success)return alert(r?.message||"Unable to delete product.");alert(r.message||"Product deleted.","success");load();});};
try{const u=await StockFlowAuth.requireAuth();if(!u)return;$("clearButton").onclick=clear;form.onsubmit=async e=>{e.preventDefault();btn.disabled=true;try{const r=await StockFlowAPI.saveProduct({id:$("id").value,sku:$("sku").value.trim(),name:$("name").value.trim(),category:$("category").value.trim(),supplier:$("supplier").value.trim(),price:$("price").value,cost:$("cost").value,stock:$("stock").value,reorderLevel:$("reorderLevel").value,status:$("status").value});if(!r?.success)return alert(r?.message||"Unable to save product.");alert(r.message||"Product saved.","success");clear();await load();}finally{btn.disabled=false;}};await load();}catch(e){alert(e.message||"Unable to load products.");}
});