/*
=========================================================
STOCKFLOW ACCOUNT RECOVERY CONTROLLER
Phone Accessories Inventory Management System
=========================================================

FLOW
----

forgot-password.html
        ↓
Enter Gmail / phone / username
        ↓
Apps Script backend
        ↓
REAL backend OTP generated
        ↓
Google Sheets + Firebase
        ↓
recovery.html
        ↓
3–5 second demo delay
        ↓
SAME backend OTP fills 6 boxes
        ↓
Verify recovery code
        ↓
New password
        ↓
Reset password
        ↓
Success
        ↓
Login

IMPORTANT
---------

NO OTP IS GENERATED BY THIS FILE.

The OTP must come from the Apps Script backend.

=========================================================
*/

(function () {

    "use strict";


    /* =====================================================
       CONFIGURATION
       ===================================================== */

    const CONFIG =
        window.STOCKFLOW_CONFIG ||
        window.CONFIG ||
        {};


    const AUTH_CONFIG =
        CONFIG.AUTH ||
        {};


    const ROUTES =
        CONFIG.ROUTES ||
        {};


    const STORAGE =
        CONFIG.STORAGE ||
        {};


    const API =
        window.StockFlowAPI ||
        window.API ||
        null;


    /* =====================================================
       PAGE CHECK
       ===================================================== */

    const recoveryPage =
        document.getElementById(
            "recoveryOtpStep"
        ) ||
        document.getElementById(
            "newPasswordStep"
        ) ||
        document.getElementById(
            "recoverySuccessStep"
        );


    if (!recoveryPage) {

        return;
    }


    /* =====================================================
       CONSTANTS
       ===================================================== */

    const OTP_LENGTH =
        Number(
            AUTH_CONFIG.OTP_LENGTH ||
            6
        );


    const RESEND_COOLDOWN =
        Number(
            AUTH_CONFIG.OTP_RESEND_COOLDOWN_SECONDS ||
            120
        );


    const DEMO_MODE =
        CONFIG.DEMO_MODE === true;


    const DEMO_AUTO_FILL =
        AUTH_CONFIG.DEMO_AUTO_FILL !== false;


    const DEMO_DELAY_MIN =
        Number(
            AUTH_CONFIG.DEMO_AUTO_FILL_DELAY_MIN ||
            3000
        );


    const DEMO_DELAY_MAX =
        Number(
            AUTH_CONFIG.DEMO_AUTO_FILL_DELAY_MAX ||
            5000
        );


    /* =====================================================
       DOM HELPER
       ===================================================== */

    const $ = function (id) {

        return document.getElementById(
            id
        );
    };


    /* =====================================================
       DOM ELEMENTS
       ===================================================== */

    const recoveryOtpStep =
        $("recoveryOtpStep");


    const newPasswordStep =
        $("newPasswordStep");


    const recoverySuccessStep =
        $("recoverySuccessStep");


    const recoveryOtpForm =
        $("recoveryOtpForm");


    const recoveryOtpInputs =
        Array.from(
            document.querySelectorAll(
                "#recoveryOtpInputs input"
            )
        );


    const recoveryDestination =
        $("recoveryDestination");


    const recoveryMessage =
        $("recoveryMessage");


    const verifyRecoveryButton =
        $("verifyRecoveryButton");


    const resendRecoveryOtp =
        $("resendRecoveryOtp");


    const recoveryCountdown =
        $("recoveryCountdown");


    const newPasswordForm =
        $("newPasswordForm");


    const newPassword =
        $("newPassword");


    const confirmNewPassword =
        $("confirmNewPassword");


    const resetPasswordButton =
        $("resetPasswordButton");


    const passwordMessage =
        $("passwordMessage");


    const recoveryPasswordBar =
        $("recoveryPasswordBar");


    const recoveryPasswordHint =
        $("recoveryPasswordHint");


    const recoveryLoginButton =
        $("recoveryLoginButton");


    /* =====================================================
       STATE
       ===================================================== */

    const state = {

        identity: "",

        username: "",

        email: "",

        gmail: "",

        phone: "",

        uid: "",

        channel: "email",

        backendOtp: "",

        otpReady: false,

        otpVerified: false,

        recoveryVerified: false,

        requesting: false,

        verifying: false,

        resetting: false,

        countdown:
            RESEND_COOLDOWN,

        countdownTimer:
            null,

        demoTimer:
            null
    };


    /* =====================================================
       STORAGE KEYS
       ===================================================== */

    const STORAGE_KEYS = {

        IDENTITY:
            STORAGE.OTP_IDENTITY ||
            "STOCKFLOW_OTP_IDENTITY",

        USERNAME:
            STORAGE.OTP_USERNAME ||
            "STOCKFLOW_OTP_USERNAME",

        EMAIL:
            STORAGE.OTP_EMAIL ||
            "STOCKFLOW_OTP_EMAIL",

        PHONE:
            STORAGE.OTP_PHONE ||
            "STOCKFLOW_OTP_PHONE",

        UID:
            STORAGE.OTP_UID ||
            "STOCKFLOW_OTP_UID",

        CHANNEL:
            STORAGE.OTP_CHANNEL ||
            "STOCKFLOW_OTP_CHANNEL",

        RECOVERY_READY:
            "STOCKFLOW_RECOVERY_OTP_READY",

        RECOVERY_OTP:
            "STOCKFLOW_RECOVERY_DEMO_OTP",

        RECOVERY_STARTED:
            "STOCKFLOW_RECOVERY_STARTED",

        TOKEN:
            STORAGE.TOKEN ||
            "STOCKFLOW_TOKEN",

        USER:
            STORAGE.USER ||
            "STOCKFLOW_USER"
    };


    /* =====================================================
       STORAGE HELPERS
       ===================================================== */

    function storageGet(key) {

        try {

            return (
                sessionStorage.getItem(key) ||
                localStorage.getItem(key) ||
                ""
            );

        } catch (error) {

            return "";
        }
    }


    function storageSet(
        key,
        value
    ) {

        try {

            sessionStorage.setItem(
                key,
                String(
                    value ?? ""
                )
            );

            localStorage.setItem(
                key,
                String(
                    value ?? ""
                )
            );

        } catch (error) {

            console.warn(
                "[STOCKFLOW RECOVERY] Storage unavailable.",
                error
            );
        }
    }


    function storageRemove(key) {

        try {

            sessionStorage.removeItem(key);
            localStorage.removeItem(key);

        } catch (error) {

            /* Ignore storage errors. */
        }
    }


    /* =====================================================
       STRING HELPERS
       ===================================================== */

    function clean(value) {

        if (
            value === null ||
            typeof value === "undefined"
        ) {

            return "";
        }

        return String(value).trim();
    }


    function firstValue() {

        for (
            let i = 0;
            i < arguments.length;
            i++
        ) {

            const value =
                clean(
                    arguments[i]
                );

            if (value) {

                return value;
            }
        }

        return "";
    }


    /* =====================================================
       LOAD SAVED STATE
       ===================================================== */

    function loadSavedState() {

        state.identity =
            storageGet(
                STORAGE_KEYS.IDENTITY
            );


        state.username =
            storageGet(
                STORAGE_KEYS.USERNAME
            );


        state.email =
            storageGet(
                STORAGE_KEYS.EMAIL
            );


        state.gmail =
            storageGet(
                STORAGE_KEYS.EMAIL
            );


        state.phone =
            storageGet(
                STORAGE_KEYS.PHONE
            );


        state.uid =
            storageGet(
                STORAGE_KEYS.UID
            );


        state.channel =
            storageGet(
                STORAGE_KEYS.CHANNEL
            ) ||
            "email";


        state.backendOtp =
            storageGet(
                STORAGE_KEYS.RECOVERY_OTP
            );
    }


    /* =====================================================
       SAVE STATE
       ===================================================== */

    function saveState() {

        storageSet(
            STORAGE_KEYS.IDENTITY,
            state.identity
        );


        storageSet(
            STORAGE_KEYS.USERNAME,
            state.username
        );


        storageSet(
            STORAGE_KEYS.EMAIL,
            state.email
        );


        storageSet(
            STORAGE_KEYS.PHONE,
            state.phone
        );


        storageSet(
            STORAGE_KEYS.UID,
            state.uid
        );


        storageSet(
            STORAGE_KEYS.CHANNEL,
            state.channel
        );
    }


    /* =====================================================
       RESOLVE IDENTITY
       ===================================================== */

    function resolveIdentity() {

        state.identity =
            firstValue(

                state.identity,

                state.username,

                state.email,

                state.gmail,

                state.phone,

                state.uid
            );


        return state.identity;
    }


    /* =====================================================
       RESPONSE DATA
       ===================================================== */

    function getResponseData(response) {

        if (
            !response ||
            typeof response !== "object"
        ) {

            return {};
        }


        if (
            response.data &&
            typeof response.data === "object"
        ) {

            return {
                ...response,
                ...response.data
            };
        }


        return response;
    }


    /* =====================================================
       SHOW MESSAGE
       ===================================================== */

    function showMessage(
        element,
        message,
        type = "error"
    ) {

        if (!element) {

            return;
        }


        element.textContent =
            message || "";


        element.classList.remove(
            "success",
            "error",
            "warning",
            "info",
            "show"
        );


        element.classList.add(
            type
        );


        element.classList.add(
            "show"
        );


        element.hidden =
            false;
    }


    /* =====================================================
       HIDE MESSAGE
       ===================================================== */

    function hideMessage(element) {

        if (!element) {

            return;
        }


        element.textContent =
            "";


        element.classList.remove(
            "success",
            "error",
            "warning",
            "info",
            "show"
        );


        element.hidden =
            true;
    }


    /* =====================================================
       ERROR HANDLING
       ===================================================== */

    function getErrorCode(error) {

        return clean(
            error &&
            (
                error.code ||
                error.errorCode ||
                error.statusCode
            )
        ).toUpperCase();
    }


    function getErrorMessage(error) {

        if (!error) {

            return (
                "Something went wrong. Please try again."
            );
        }


        const code =
            getErrorCode(error);


        const message =
            clean(
                error.message
            );


        /*
         * Account errors.
         */

        if (
            code === "USER_NOT_FOUND" ||
            code === "ACCOUNT_NOT_FOUND" ||
            code === "RECOVERY_USER_NOT_FOUND"
        ) {

            return (
                "No registered StockFlow account was found for that information."
            );
        }


        if (
            code === "RECOVERY_IDENTITY_MISSING"
        ) {

            return (
                "Please provide your registered Gmail, phone number, or username."
            );
        }


        /*
         * OTP errors.
         */

        if (
            code === "INVALID_OTP" ||
            code === "OTP_INVALID"
        ) {

            return (
                "The recovery code is incorrect. Please try again."
            );
        }


        if (
            code === "OTP_EXPIRED"
        ) {

            return (
                "The recovery code has expired. Please request a new code."
            );
        }


        if (
            code === "OTP_LOCKED" ||
            code === "ACCOUNT_LOCKED"
        ) {

            return (
                "Recovery verification is temporarily locked. Please try again later."
            );
        }


        if (
            code === "MAX_ATTEMPTS"
        ) {

            return (
                "You have reached the maximum number of recovery attempts. Please try again later."
            );
        }


        if (
            code === "OTP_COOLDOWN"
        ) {

            return (
                "Please wait before requesting another recovery code."
            );
        }


        /*
         * Transport errors.
         */

        if (
            code === "NETWORK_ERROR" ||
            code === "HTTP_ERROR" ||
            code === "API_URL_MISSING" ||
            code === "API_URL_INVALID" ||
            code === "EMPTY_RESPONSE" ||
            code === "INVALID_JSON"
        ) {

            return (
                "Unable to connect to the recovery service. Please try again."
            );
        }


        if (
            code === "TIMEOUT"
        ) {

            return (
                "The recovery service took too long to respond. Please try again."
            );
        }


        if (
            error.name === "AbortError"
        ) {

            return (
                "The recovery service took too long to respond. Please try again."
            );
        }


        /*
         * ALWAYS preserve a legitimate backend message.
         */

        if (message) {

            return message;
        }


        return (
            "Something went wrong. Please try again."
        );
    }


    /* =====================================================
       DISPLAY DESTINATION
       ===================================================== */

    function displayDestination() {

        if (!recoveryDestination) {

            return;
        }


        const identity =
            resolveIdentity();


        if (!identity) {

            recoveryDestination.textContent =
                "Enter your registered Gmail, phone number, or username.";

            return;
        }


        let display =
            identity;


        if (
            identity.includes("@")
        ) {

            display =
                maskEmail(
                    identity
                );

        } else if (
            /^\+?\d+$/.test(
                identity.replace(
                    /[\s()-]/g,
                    ""
                )
            )
        ) {

            display =
                maskPhone(
                    identity
                );
        }


        recoveryDestination.textContent =
            display;
    }


    /* =====================================================
       MASK EMAIL
       ===================================================== */

    function maskEmail(email) {

        const value =
            clean(email);


        const at =
            value.indexOf("@");


        if (at <= 0) {

            return value;
        }


        const name =
            value.slice(
                0,
                at
            );


        const domain =
            value.slice(
                at
            );


        if (
            name.length <= 2
        ) {

            return (
                name.charAt(0) +
                "*" +
                domain
            );
        }


        return (
            name.charAt(0) +
            "*".repeat(
                Math.min(
                    name.length - 1,
                    4
                )
            ) +
            domain
        );
    }


    /* =====================================================
       MASK PHONE
       ===================================================== */

    function maskPhone(phone) {

        const value =
            clean(phone)
                .replace(
                    /[\s()-]/g,
                    ""
                );


        if (
            value.length <= 4
        ) {

            return value;
        }


        return (
            "*".repeat(
                Math.max(
                    0,
                    value.length - 4
                )
            ) +
            value.slice(-4)
        );
    }


    /* =====================================================
       SHOW STEP
       ===================================================== */

    function showStep(step) {

        if (recoveryOtpStep) {

            recoveryOtpStep.style.display =
                step === "otp"
                    ? ""
                    : "none";
        }


        if (newPasswordStep) {

            newPasswordStep.style.display =
                step === "password"
                    ? ""
                    : "none";
        }


        if (recoverySuccessStep) {

            recoverySuccessStep.style.display =
                step === "success"
                    ? ""
                    : "none";
        }
    }


    /* =====================================================
       OTP GET
       ===================================================== */

    function getOtp() {

        return recoveryOtpInputs
            .map(
                input =>
                    clean(
                        input.value
                    ).replace(
                        /\D/g,
                        ""
                    )
            )
            .join("")
            .slice(
                0,
                OTP_LENGTH
            );
    }


    /* =====================================================
       OTP SET
       ===================================================== */

    function setOtp(code) {

        const normalized =
            clean(code)
                .replace(
                    /\D/g,
                    ""
                )
                .slice(
                    0,
                    OTP_LENGTH
                );


        recoveryOtpInputs.forEach(
            function (
                input,
                index
            ) {

                input.value =
                    normalized[index] ||
                    "";
            }
        );


        updateVerifyButton();
    }


    /* =====================================================
       OTP CLEAR
       ===================================================== */

    function clearOtp() {

        recoveryOtpInputs.forEach(
            function (input) {

                input.value =
                    "";
            }
        );


        updateVerifyButton();
    }


    /* =====================================================
       VERIFY BUTTON
       ===================================================== */

    function updateVerifyButton() {

        if (!verifyRecoveryButton) {

            return;
        }


        verifyRecoveryButton.disabled =
            state.verifying ||
            getOtp().length !==
                OTP_LENGTH;
    }


    /* =====================================================
       OTP INPUT INITIALIZATION
       ===================================================== */

    function initializeOtpInputs() {

        recoveryOtpInputs.forEach(
            function (
                input,
                index
            ) {

                input.setAttribute(
                    "maxlength",
                    "1"
                );


                input.setAttribute(
                    "inputmode",
                    "numeric"
                );


                input.addEventListener(
                    "input",
                    function () {

                        input.value =
                            input.value
                                .replace(
                                    /\D/g,
                                    ""
                                )
                                .slice(
                                    0,
                                    1
                                );


                        if (
                            input.value &&
                            index <
                                recoveryOtpInputs.length - 1
                        ) {

                            recoveryOtpInputs[
                                index + 1
                            ].focus();
                        }


                        updateVerifyButton();
                    }
                );


                input.addEventListener(
                    "keydown",
                    function (event) {

                        if (
                            event.key ===
                                "Backspace" &&
                            !input.value &&
                            index > 0
                        ) {

                            recoveryOtpInputs[
                                index - 1
                            ].focus();
                        }


                        if (
                            event.key ===
                                "ArrowLeft" &&
                            index > 0
                        ) {

                            recoveryOtpInputs[
                                index - 1
                            ].focus();
                        }


                        if (
                            event.key ===
                                "ArrowRight" &&
                            index <
                                recoveryOtpInputs.length - 1
                        ) {

                            recoveryOtpInputs[
                                index + 1
                            ].focus();
                        }
                    }
                );


                input.addEventListener(
                    "paste",
                    function (event) {

                        event.preventDefault();


                        const pasted =
                            (
                                event.clipboardData ||
                                window.clipboardData
                            )
                                .getData("text")
                                .replace(
                                    /\D/g,
                                    ""
                                )
                                .slice(
                                    0,
                                    OTP_LENGTH
                                );


                        if (!pasted) {

                            return;
                        }


                        setOtp(
                            pasted
                        );


                        const focusIndex =
                            Math.min(
                                pasted.length,
                                recoveryOtpInputs.length
                            ) - 1;


                        if (
                            focusIndex >= 0
                        ) {

                            recoveryOtpInputs[
                                focusIndex
                            ].focus();
                        }
                    }
                );
            }
        );
    }


    /* =====================================================
       ENABLE OTP
       ===================================================== */

    function enableOtpInputs() {

        recoveryOtpInputs.forEach(
            function (input) {

                input.disabled =
                    false;
            }
        );


        updateVerifyButton();
    }


    /* =====================================================
       DISABLE OTP
       ===================================================== */

    function disableOtpInputs() {

        recoveryOtpInputs.forEach(
            function (input) {

                input.disabled =
                    true;
            }
        );


        if (verifyRecoveryButton) {

            verifyRecoveryButton.disabled =
                true;
        }
    }


    /* =====================================================
       DEMO DELAY
       =====================================================

       IMPORTANT:

       There is NO Math.random() here.

       We use the configured minimum delay.

       The OTP itself still comes from Apps Script.

       ===================================================== */

    function getDemoDelay() {

        const min =
            Math.max(
                0,
                DEMO_DELAY_MIN
            );


        const max =
            Math.max(
                min,
                DEMO_DELAY_MAX
            );


        /*
         * Use the configured minimum delay.
         *
         * This keeps the frontend deterministic and
         * prevents any confusion with OTP generation.
         */

        return min;
    }


    /* =====================================================
       START COUNTDOWN
       ===================================================== */

    function startCountdown() {

        stopCountdown();


        state.countdown =
            RESEND_COOLDOWN;


        updateCountdown();


        state.countdownTimer =
            setInterval(
                function () {

                    state.countdown--;


                    updateCountdown();


                    if (
                        state.countdown <= 0
                    ) {

                        stopCountdown();

                        updateCountdown();
                    }

                },
                1000
            );
    }


    /* =====================================================
       STOP COUNTDOWN
       ===================================================== */

    function stopCountdown() {

        if (
            state.countdownTimer
        ) {

            clearInterval(
                state.countdownTimer
            );


            state.countdownTimer =
                null;
        }
    }


    /* =====================================================
       UPDATE COUNTDOWN
       ===================================================== */

    function updateCountdown() {

        if (!recoveryCountdown) {

            return;
        }


        if (
            state.countdown <= 0
        ) {

            recoveryCountdown.textContent =
                "0";


            if (resendRecoveryOtp) {

                resendRecoveryOtp.disabled =
                    false;

                resendRecoveryOtp.innerHTML =
                    "Resend code";
            }


            return;
        }


        recoveryCountdown.textContent =
            String(
                state.countdown
            );


        if (resendRecoveryOtp) {

            resendRecoveryOtp.disabled =
                true;

            resendRecoveryOtp.innerHTML =
                "Resend in " +
                state.countdown +
                "s";
        }
    }


    /* =====================================================
       USE EXISTING BACKEND OTP
       ===================================================== */

    function prepareExistingOtp() {

        if (!state.backendOtp) {

            return false;
        }


        if (
            state.backendOtp.length !==
            OTP_LENGTH
        ) {

            state.backendOtp =
                "";


            storageRemove(
                STORAGE_KEYS.RECOVERY_OTP
            );


            return false;
        }


        state.otpReady =
            true;


        clearOtp();


        disableOtpInputs();


        startCountdown();


        const delay =
            DEMO_MODE &&
            DEMO_AUTO_FILL
                ? getDemoDelay()
                : 0;


        if (
            state.demoTimer
        ) {

            clearTimeout(
                state.demoTimer
            );
        }


        if (
            DEMO_MODE &&
            DEMO_AUTO_FILL
        ) {

            showMessage(
                recoveryMessage,
                "Your recovery code is being prepared...",
                "info"
            );


            state.demoTimer =
                setTimeout(
                    function () {

                        enableOtpInputs();


                        setOtp(
                            state.backendOtp
                        );


                        showMessage(
                            recoveryMessage,
                            "Recovery code prepared. The 6-digit code has been filled automatically.",
                            "success"
                        );


                        if (
                            recoveryOtpInputs.length
                        ) {

                            recoveryOtpInputs[
                                0
                            ].focus();
                        }

                    },
                    delay
                );


        } else {

            enableOtpInputs();


            showMessage(
                recoveryMessage,
                "Enter the 6-digit recovery code.",
                "info"
            );
        }


        return true;
    }


    /* =====================================================
       REQUEST NEW RECOVERY OTP
       ===================================================== */

    async function requestRecoveryOtp() {

        if (
            state.requesting
        ) {

            return;
        }


        if (!API) {

            showMessage(
                recoveryMessage,
                "The recovery service is not available.",
                "error"
            );

            return;
        }


        const identity =
            resolveIdentity();


        if (!identity) {

            showMessage(
                recoveryMessage,
                "Please provide your registered Gmail, phone number, or username.",
                "error"
            );

            return;
        }


        state.requesting =
            true;


        disableOtpInputs();


        clearOtp();


        hideMessage(
            recoveryMessage
        );


        try {

            /*
             * Ask backend to generate a NEW OTP.
             *
             * No frontend OTP generation.
             */

            const response =
                await API.requestOtp({

                    identity,

                    username:
                        state.username,

                    email:
                        state.email,

                    gmail:
                        state.gmail,

                    phone:
                        state.phone,

                    uid:
                        state.uid,

                    channel:
                        state.channel,

                    purpose:
                        "recovery"
                });


            const data =
                getResponseData(
                    response
                );


            const backendOtp =
                clean(
                    data.demoOtp ||
                    data.demoOTP ||
                    data.generatedOtp ||
                    data.generatedOTP ||
                    data.recoveryOtp ||
                    data.recoveryOTP ||
                    data.otp ||
                    data.OTP
                ).replace(
                    /\D/g,
                    ""
                );


            if (
                backendOtp.length !==
                OTP_LENGTH
            ) {

                /*
                 * Non-demo mode may intentionally not
                 * return the OTP.
                 */

                state.backendOtp =
                    "";


                storageRemove(
                    STORAGE_KEYS.RECOVERY_OTP
                );

            } else {

                state.backendOtp =
                    backendOtp;


                storageSet(
                    STORAGE_KEYS.RECOVERY_OTP,
                    backendOtp
                );
            }


            updateStateFromResponse(
                response
            );


            displayDestination();


            state.otpReady =
                true;


            startCountdown();


            if (
                DEMO_MODE &&
                DEMO_AUTO_FILL &&
                state.backendOtp
            ) {

                const delay =
                    getDemoDelay();


                showMessage(
                    recoveryMessage,
                    "Your recovery code is being prepared...",
                    "info"
                );


                state.demoTimer =
                    setTimeout(
                        function () {

                            enableOtpInputs();


                            setOtp(
                                state.backendOtp
                            );


                            showMessage(
                                recoveryMessage,
                                "Recovery code prepared. The 6-digit code has been filled automatically.",
                                "success"
                            );


                            if (
                                recoveryOtpInputs.length
                            ) {

                                recoveryOtpInputs[
                                    0
                                ].focus();
                            }

                        },
                        delay
                    );


            } else {

                enableOtpInputs();


                showMessage(
                    recoveryMessage,
                    "A recovery verification code is ready. Enter the 6-digit code to continue.",
                    "success"
                );
            }


        } catch (error) {

            console.error(
                "[STOCKFLOW RECOVERY] OTP request failed:",
                error
            );


            state.otpReady =
                false;


            state.backendOtp =
                "";


            storageRemove(
                STORAGE_KEYS.RECOVERY_OTP
            );


            disableOtpInputs();


            showMessage(
                recoveryMessage,
                getErrorMessage(error),
                "error"
            );

        } finally {

            state.requesting =
                false;
        }
    }


    /* =====================================================
       UPDATE STATE FROM RESPONSE
       ===================================================== */

    function updateStateFromResponse(response) {

        const data =
            getResponseData(
                response
            );


        state.uid =
            firstValue(
                data.uid,
                data.UID,
                state.uid
            );


        state.username =
            firstValue(
                data.username,
                data.USERNAME,
                state.username
            );


        state.email =
            firstValue(
                data.email,
                data.gmail,
                data.GMAIL,
                state.email
            );


        state.gmail =
            firstValue(
                data.gmail,
                data.email,
                state.gmail
            );


        state.phone =
            firstValue(
                data.phone,
                data.phoneNumber,
                data["PHONE NO."],
                state.phone
            );


        state.identity =
            firstValue(
                data.identity,
                state.identity,
                state.username,
                state.email,
                state.phone,
                state.uid
            );


        state.channel =
            firstValue(
                data.channel,
                state.channel
            );


        saveState();
    }


    /* =====================================================
       VERIFY RECOVERY OTP
       ===================================================== */

    async function verifyRecoveryCode() {

        if (
            state.verifying
        ) {

            return;
        }


        const otp =
            getOtp();


        if (
            otp.length !==
            OTP_LENGTH
        ) {

            showMessage(
                recoveryMessage,
                "Please enter the complete 6-digit recovery code.",
                "error"
            );

            return;
        }


        const identity =
            resolveIdentity();


        if (!identity) {

            showMessage(
                recoveryMessage,
                "Please provide your registered Gmail, phone number, or username.",
                "error"
            );

            return;
        }


        if (!API) {

            showMessage(
                recoveryMessage,
                "The recovery service is not available.",
                "error"
            );

            return;
        }


        state.verifying =
            true;


        if (verifyRecoveryButton) {

            verifyRecoveryButton.disabled =
                true;


            verifyRecoveryButton.dataset.originalText =
                verifyRecoveryButton.dataset.originalText ||
                verifyRecoveryButton.textContent;


            verifyRecoveryButton.textContent =
                "Verifying...";
        }


        hideMessage(
            recoveryMessage
        );


        try {

            const response =
                await API.verifyRecoveryOtp({

                    uid:
                        state.uid,

                    identity,

                    username:
                        state.username,

                    email:
                        state.email,

                    gmail:
                        state.gmail,

                    phone:
                        state.phone,

                    channel:
                        state.channel,

                    otp
                });


            updateStateFromResponse(
                response
            );


            state.otpVerified =
                true;


            state.recoveryVerified =
                true;


            showMessage(
                recoveryMessage,
                "Recovery code verified successfully.",
                "success"
            );


            setTimeout(
                function () {

                    showStep(
                        "password"
                    );


                    hideMessage(
                        recoveryMessage
                    );


                    if (newPassword) {

                        newPassword.focus();
                    }

                },
                500
            );


        } catch (error) {

            console.error(
                "[STOCKFLOW RECOVERY] OTP verification failed:",
                error
            );


            state.verifying =
                false;


            if (verifyRecoveryButton) {

                verifyRecoveryButton.textContent =
                    verifyRecoveryButton.dataset.originalText ||
                    "Verify recovery code";
            }


            showMessage(
                recoveryMessage,
                getErrorMessage(error),
                "error"
            );


            updateVerifyButton();
        }
    }


    /* =====================================================
       RESEND RECOVERY OTP
       ===================================================== */

    async function resendRecoveryCode() {

        if (
            state.countdown > 0 ||
            state.requesting
        ) {

            return;
        }


        /*
         * Remove previous OTP.
         */

        state.backendOtp =
            "";


        storageRemove(
            STORAGE_KEYS.RECOVERY_OTP
        );


        await requestRecoveryOtp();
    }


    /* =====================================================
       PASSWORD VALIDATION
       ===================================================== */

    function validatePassword(password) {

        const value =
            clean(password);


        return {

            length:
                value.length >= 8,

            uppercase:
                /[A-Z]/.test(value),

            lowercase:
                /[a-z]/.test(value),

            number:
                /[0-9]/.test(value),

            symbol:
                /[^A-Za-z0-9]/.test(value)
        };
    }


    /* =====================================================
       PASSWORD STRENGTH
       ===================================================== */

    function getPasswordStrength(password) {

        const checks =
            validatePassword(
                password
            );


        let score = 0;


        if (checks.length) {
            score++;
        }


        if (checks.uppercase) {
            score++;
        }


        if (checks.lowercase) {
            score++;
        }


        if (checks.number) {
            score++;
        }


        if (checks.symbol) {
            score++;
        }


        return {

            score,

            total: 5,

            checks
        };
    }


    /* =====================================================
       PASSWORD METER
       ===================================================== */

    function updatePasswordMeter() {

        if (!newPassword) {

            return;
        }


        const password =
            newPassword.value;


        const result =
            getPasswordStrength(
                password
            );


        if (recoveryPasswordBar) {

            const percentage =
                (
                    result.score /
                    result.total
                ) *
                100;


            recoveryPasswordBar.style.width =
                percentage + "%";
        }


        if (recoveryPasswordHint) {

            if (!password) {

                recoveryPasswordHint.textContent =
                    "Use 8+ characters with uppercase, lowercase, number and symbol.";

            } else if (
                result.score <= 2
            ) {

                recoveryPasswordHint.textContent =
                    "Weak password. Add uppercase, lowercase, number and symbol.";

            } else if (
                result.score === 3
            ) {

                recoveryPasswordHint.textContent =
                    "Moderate password. Add more complexity.";

            } else if (
                result.score === 4
            ) {

                recoveryPasswordHint.textContent =
                    "Strong password. One more requirement is recommended.";

            } else {

                recoveryPasswordHint.textContent =
                    "Strong password.";
            }
        }
    }


    /* =====================================================
       PASSWORD FORM VALIDATION
       ===================================================== */

    function validateNewPasswordForm() {

        const password =
            newPassword
                ? newPassword.value
                : "";


        const confirm =
            confirmNewPassword
                ? confirmNewPassword.value
                : "";


        const result =
            getPasswordStrength(
                password
            );


        if (!password) {

            return {

                valid: false,

                message:
                    "Please enter a new password."
            };
        }


        if (
            !result.checks.length ||
            !result.checks.uppercase ||
            !result.checks.lowercase ||
            !result.checks.number ||
            !result.checks.symbol
        ) {

            return {

                valid: false,

                message:
                    "Password must contain at least 8 characters, uppercase, lowercase, number, and symbol."
            };
        }


        if (!confirm) {

            return {

                valid: false,

                message:
                    "Please confirm your new password."
            };
        }


        if (
            password !==
            confirm
        ) {

            return {

                valid: false,

                message:
                    "Passwords do not match."
            };
        }


        return {

            valid: true,

            message: ""
        };
    }


    /* =====================================================
       RESET PASSWORD
       ===================================================== */

    async function resetPassword() {

        if (
            state.resetting
        ) {

            return;
        }


        if (
            !state.recoveryVerified
        ) {

            showMessage(
                passwordMessage,
                "Please verify your recovery code first.",
                "error"
            );

            return;
        }


        const validation =
            validateNewPasswordForm();


        if (!validation.valid) {

            showMessage(
                passwordMessage,
                validation.message,
                "error"
            );

            return;
        }


        if (!API) {

            showMessage(
                passwordMessage,
                "The recovery service is not available.",
                "error"
            );

            return;
        }


        state.resetting =
            true;


        if (resetPasswordButton) {

            resetPasswordButton.disabled =
                true;


            resetPasswordButton.dataset.originalText =
                resetPasswordButton.dataset.originalText ||
                resetPasswordButton.textContent;


            resetPasswordButton.textContent =
                "Resetting...";
        }


        hideMessage(
            passwordMessage
        );


        try {

            await API.resetPassword({

                uid:
                    state.uid,

                identity:
                    resolveIdentity(),

                username:
                    state.username,

                email:
                    state.email,

                gmail:
                    state.gmail,

                phone:
                    state.phone,

                newPassword:
                    newPassword.value,

                password:
                    newPassword.value,

                confirmPassword:
                    confirmNewPassword.value
            });


            /*
             * Clear recovery state.
             */

            state.backendOtp =
                "";


            state.otpReady =
                false;


            state.otpVerified =
                false;


            state.recoveryVerified =
                false;


            storageRemove(
                STORAGE_KEYS.IDENTITY
            );


            storageRemove(
                STORAGE_KEYS.USERNAME
            );


            storageRemove(
                STORAGE_KEYS.EMAIL
            );


            storageRemove(
                STORAGE_KEYS.PHONE
            );


            storageRemove(
                STORAGE_KEYS.UID
            );


            storageRemove(
                STORAGE_KEYS.CHANNEL
            );


            storageRemove(
                STORAGE_KEYS.RECOVERY_READY
            );


            storageRemove(
                STORAGE_KEYS.RECOVERY_OTP
            );


            storageRemove(
                STORAGE_KEYS.RECOVERY_STARTED
            );


            storageRemove(
                STORAGE_KEYS.TOKEN
            );


            storageRemove(
                STORAGE_KEYS.USER
            );


            showMessage(
                passwordMessage,
                "Your password has been successfully updated.",
                "success"
            );


            showStep(
                "success"
            );


        } catch (error) {

            console.error(
                "[STOCKFLOW RECOVERY] Password reset failed:",
                error
            );


            showMessage(
                passwordMessage,
                getErrorMessage(error),
                "error"
            );


        } finally {

            state.resetting =
                false;


            if (resetPasswordButton) {

                resetPasswordButton.disabled =
                    false;


                resetPasswordButton.textContent =
                    resetPasswordButton.dataset.originalText ||
                    "Reset password";
            }
        }
    }


    /* =====================================================
       PASSWORD TOGGLES
       ===================================================== */

    function initializePasswordToggles() {

        const buttons =
            document.querySelectorAll(
                ".password-toggle"
            );


        buttons.forEach(
            function (button) {

                button.addEventListener(
                    "click",
                    function () {

                        const targetId =
                            button.dataset.target;


                        const input =
                            targetId
                                ? $(targetId)
                                : null;


                        if (!input) {

                            return;
                        }


                        if (
                            input.type ===
                            "password"
                        ) {

                            input.type =
                                "text";


                            button.textContent =
                                "Hide";

                        } else {

                            input.type =
                                "password";


                            button.textContent =
                                "Show";
                        }
                    }
                );
            }
        );
    }


    /* =====================================================
       LOGIN REDIRECT
       ===================================================== */

    function continueToLogin() {

        const loginRoute =
            ROUTES.LOGIN ||
            "auth.html#login";


        window.location.href =
            loginRoute;
    }


    /* =====================================================
       EVENTS
       ===================================================== */

    function initializeEvents() {

        if (recoveryOtpForm) {

            recoveryOtpForm.addEventListener(
                "submit",
                function (event) {

                    event.preventDefault();

                    verifyRecoveryCode();
                }
            );
        }


        if (resendRecoveryOtp) {

            resendRecoveryOtp.addEventListener(
                "click",
                function (event) {

                    event.preventDefault();

                    resendRecoveryCode();
                }
            );
        }


        if (newPasswordForm) {

            newPasswordForm.addEventListener(
                "submit",
                function (event) {

                    event.preventDefault();

                    resetPassword();
                }
            );
        }


        if (newPassword) {

            newPassword.addEventListener(
                "input",
                function () {

                    updatePasswordMeter();

                    hideMessage(
                        passwordMessage
                    );
                }
            );
        }


        if (confirmNewPassword) {

            confirmNewPassword.addEventListener(
                "input",
                function () {

                    hideMessage(
                        passwordMessage
                    );
                }
            );
        }


        if (recoveryLoginButton) {

            recoveryLoginButton.addEventListener(
                "click",
                function () {

                    continueToLogin();
                }
            );
        }
    }


    /* =====================================================
       INITIALIZATION
       ===================================================== */

    async function initialize() {

        loadSavedState();


        initializeOtpInputs();


        initializePasswordToggles();


        initializeEvents();


        displayDestination();


        showStep(
            "otp"
        );


        disableOtpInputs();


        /*
         * IMPORTANT:
         *
         * If forgot-password.js already requested
         * the OTP, DO NOT request another OTP.
         */

        const recoveryReady =
            storageGet(
                STORAGE_KEYS.RECOVERY_READY
            );


        if (
            recoveryReady === "true" &&
            state.backendOtp
        ) {

            prepareExistingOtp();

            return;
        }


        /*
         * If we arrive here with an identity but
         * without a prepared OTP, request one.
         */

        if (
            resolveIdentity()
        ) {

            await requestRecoveryOtp();

            return;
        }


        showMessage(
            recoveryMessage,
            "Enter your registered Gmail, phone number, or username to begin account recovery.",
            "info"
        );
    }


    /* =====================================================
       PUBLIC API
       ===================================================== */

    window.StockFlowRecovery = {

        requestOtp:
            requestRecoveryOtp,

        resendOtp:
            resendRecoveryCode,

        verifyOtp:
            verifyRecoveryCode,

        resetPassword:
            resetPassword,

        getOtp:
            getOtp,

        setOtp:
            setOtp,

        getState:
            function () {

                return {
                    ...state
                };
            }
    };


    /* =====================================================
       START
       ===================================================== */

    if (
        document.readyState ===
        "loading"
    ) {

        document.addEventListener(
            "DOMContentLoaded",
            initialize,
            {
                once: true
            }
        );

    } else {

        initialize();
    }

})();
