/* ============================================================
   STOCKFLOW — REGISTRATION CONTROLLER
   ============================================================

   FLOW:

   Register Form
        ↓
   Validate registration data
        ↓
   StockFlowAPI.register()
        ↓
   Google Apps Script
        ↓
   Generate 6-digit OTP
        ↓
   Save account + OTP + expiry
        ↓
   Google Sheet USER
        ↓
   Firebase
        ↓
   Send OTP to Gmail
        ↓
   Save verification identity locally
        ↓
   Redirect to verify.html

   IMPORTANT:
   - OTP is generated by the backend.
   - OTP is NOT generated here.
   - OTP is NOT stored in sessionStorage.
   - Gmail is the primary verification method.
   - Phone number is stored for the account.
   - SMS should only be reported as sent when the backend
     actually confirms an SMS provider is configured.
   ============================================================ */


document.addEventListener("DOMContentLoaded", () => {

    "use strict";


    /* =========================================================
       FORM
       ========================================================= */

    const form =
        document.getElementById(
            "registerForm"
        );


    /*
     * Stop safely when the registration
     * form does not exist on the page.
     */

    if (!form) {
        return;
    }


    /* =========================================================
       CONFIGURATION
       ========================================================= */

    const CONFIG =
        window.STOCKFLOW_CONFIG ||
        window.CONFIG ||
        {};


    /*
     * Canonical verification page.
     *
     * We intentionally redirect directly to
     * verify.html instead of verify-otp.html.
     */

    const VERIFY_PAGE =
        (
            CONFIG.ROUTES &&
            CONFIG.ROUTES.VERIFY
        ) ||
        "verify.html";


    /*
     * Session-storage keys.
     *
     * These contain verification identity only.
     * The actual OTP is NEVER stored here.
     */

    const STORAGE_KEYS = {

        UID:
            CONFIG.OTP_UID_KEY ||
            "STOCKFLOW_OTP_UID",

        EMAIL:
            CONFIG.OTP_EMAIL_KEY ||
            "STOCKFLOW_OTP_EMAIL",

        PHONE:
            CONFIG.OTP_PHONE_KEY ||
            "STOCKFLOW_OTP_PHONE",

        USERNAME:
            CONFIG.OTP_USERNAME_KEY ||
            "STOCKFLOW_OTP_USERNAME",

        CHANNEL:
            CONFIG.OTP_CHANNEL_KEY ||
            "STOCKFLOW_OTP_CHANNEL",

        EMAIL_SENT:
            CONFIG.OTP_EMAIL_SENT_KEY ||
            "STOCKFLOW_OTP_EMAIL_SENT",

        PHONE_SENT:
            CONFIG.OTP_PHONE_SENT_KEY ||
            "STOCKFLOW_OTP_PHONE_SENT"

    };


    /* =========================================================
       ELEMENTS
       ========================================================= */

    const message =
        document.getElementById(
            "registerMessage"
        );


    const button =
        document.getElementById(
            "registerButton"
        ) ||
        form.querySelector(
            'button[type="submit"]'
        );


    /* ---------------------------------------------------------
       FIRST NAME
       --------------------------------------------------------- */

    const firstNameInput =
        document.getElementById(
            "registerFirstName"
        ) ||
        document.getElementById(
            "firstName"
        );


    /* ---------------------------------------------------------
       LAST NAME
       --------------------------------------------------------- */

    const lastNameInput =
        document.getElementById(
            "registerLastName"
        ) ||
        document.getElementById(
            "lastName"
        );


    /* ---------------------------------------------------------
       OLD FULL NAME FIELD
       --------------------------------------------------------- */

    const oldNameInput =
        document.getElementById(
            "registerName"
        );


    /* ---------------------------------------------------------
       USERNAME
       --------------------------------------------------------- */

    const usernameInput =
        document.getElementById(
            "registerUsername"
        );


    /* ---------------------------------------------------------
       AGE
       --------------------------------------------------------- */

    const ageInput =
        document.getElementById(
            "registerAge"
        );


    /* ---------------------------------------------------------
       EMAIL
       --------------------------------------------------------- */

    const emailInput =
        document.getElementById(
            "registerEmail"
        );


    /* ---------------------------------------------------------
       PHONE
       --------------------------------------------------------- */

    const phoneInput =
        document.getElementById(
            "registerPhone"
        );


    /* ---------------------------------------------------------
       PASSWORD
       --------------------------------------------------------- */

    const passwordInput =
        document.getElementById(
            "registerPassword"
        );


    /* ---------------------------------------------------------
       CONFIRM PASSWORD
       --------------------------------------------------------- */

    const confirmPasswordInput =
        document.getElementById(
            "registerConfirmPassword"
        );


    /* =========================================================
       OPTIONAL CONSENT CHECKBOXES
       =========================================================

       These are optional here so the script remains compatible
       with older versions of your registration page.

       If your HTML contains them, they will be validated.
       ========================================================= */

    const termsInput =
        document.getElementById(
            "registerTerms"
        ) ||
        document.getElementById(
            "terms"
        ) ||
        document.querySelector(
            '[name="terms"]'
        );


    const communicationsInput =
        document.getElementById(
            "registerCommunications"
        ) ||
        document.getElementById(
            "communications"
        ) ||
        document.querySelector(
            '[name="communications"]'
        );


    /* =========================================================
       MESSAGE HELPERS
       ========================================================= */

    function showMessage(
        text,
        type = "error"
    ) {

        if (!message) {
            return;
        }


        message.textContent =
            text || "";


        message.className =
            `auth-message ${type}`;

    }


    function clearMessage() {

        if (!message) {
            return;
        }


        message.textContent =
            "";


        message.className =
            "auth-message";

    }


    /* =========================================================
       LOADING STATE
       ========================================================= */

    function setLoading(
        loading
    ) {

        if (!button) {
            return;
        }


        const text =
            button.querySelector(
                ".button-text"
            );


        const loader =
            button.querySelector(
                ".button-loader"
            );


        button.disabled =
            loading;


        button.classList.toggle(
            "loading",
            loading
        );


        if (text) {

            text.hidden =
                loading;

        }


        if (loader) {

            loader.hidden =
                !loading;

        }


        button.setAttribute(
            "aria-busy",
            String(loading)
        );

    }


    /* =========================================================
       VALUE HELPERS
       ========================================================= */

    function getValue(
        input
    ) {

        return input
            ? input.value.trim()
            : "";

    }


    function getPasswordValue(
        input
    ) {

        return input
            ? input.value
            : "";

    }


    /* =========================================================
       NORMALIZE PHONE NUMBER
       =========================================================

       Accepted:

       09171234567
       +639171234567
       639171234567

       Internally we keep the user's 09XXXXXXXXX format
       for compatibility with the existing registration form.

       The backend can convert it to +63 when sending SMS.
       ========================================================= */

    function normalizePhone(
        value
    ) {

        let phone =
            String(value || "")
                .trim()
                .replace(/[\s()-]/g, "");


        if (
            phone.startsWith(
                "+63"
            )
        ) {

            phone =
                "0" +
                phone.substring(3);

        } else if (
            phone.startsWith(
                "63"
            )
        ) {

            phone =
                "0" +
                phone.substring(2);

        }


        return phone;

    }


    /* =========================================================
       VALIDATION
       ========================================================= */

    function validateRegistration(
        data
    ) {

        /* -----------------------------------------------------
           FIRST NAME
           ----------------------------------------------------- */

        if (!data.firstName) {

            return (
                "Please enter your first name."
            );

        }


        /* -----------------------------------------------------
           LAST NAME
           ----------------------------------------------------- */

        if (!data.lastName) {

            return (
                "Please enter your last name."
            );

        }


        /* -----------------------------------------------------
           NAME CHARACTERS
           ----------------------------------------------------- */

        const namePattern =
            /^[A-Za-zÀ-ÿ' -]+$/;


        if (
            !namePattern.test(
                data.firstName
            )
        ) {

            return (
                "First name contains invalid characters."
            );

        }


        if (
            !namePattern.test(
                data.lastName
            )
        ) {

            return (
                "Last name contains invalid characters."
            );

        }


        /* -----------------------------------------------------
           USERNAME
           ----------------------------------------------------- */

        if (!data.username) {

            return (
                "Please enter a username."
            );

        }


        if (
            data.username.length < 4 ||
            data.username.length > 30
        ) {

            return (
                "Username must contain 4–30 characters."
            );

        }


        if (
            !/^[A-Za-z0-9._-]+$/.test(
                data.username
            )
        ) {

            return (
                "Username may only contain letters, numbers, dots, underscores and hyphens."
            );

        }


        /* -----------------------------------------------------
           AGE
           ----------------------------------------------------- */

        if (
            !Number.isInteger(
                data.age
            )
        ) {

            return (
                "Please enter your age."
            );

        }


        if (
            data.age < 18 ||
            data.age > 100
        ) {

            return (
                "Please enter a valid age between 18 and 100."
            );

        }


        /* -----------------------------------------------------
           EMAIL
           ----------------------------------------------------- */

        if (!data.email) {

            return (
                "Please enter your Gmail address."
            );

        }


        const emailPattern =
            /^[^\s@]+@[^\s@]+\.[^\s@]+$/;


        if (
            !emailPattern.test(
                data.email
            )
        ) {

            return (
                "Please enter a valid Gmail address."
            );

        }


        /*
         * For this project, Gmail is the intended
         * verification destination.
         *
         * We don't require a custom domain.
         */

        if (
            !data.email
                .toLowerCase()
                .endsWith(
                    "@gmail.com"
                )
        ) {

            return (
                "Please use a valid @gmail.com address for email verification."
            );

        }


        /* -----------------------------------------------------
           PHONE
           ----------------------------------------------------- */

        if (!data.phone) {

            return (
                "Please enter your Philippine mobile number."
            );

        }


        const phonePattern =
            /^09\d{9}$/;


        if (
            !phonePattern.test(
                data.phone
            )
        ) {

            return (
                "Phone number must be in 09XXXXXXXXX format."
            );

        }


        /* -----------------------------------------------------
           PASSWORD
           ----------------------------------------------------- */

        if (!data.password) {

            return (
                "Please create a password."
            );

        }


        if (
            data.password.length < 8
        ) {

            return (
                "Password must contain at least 8 characters."
            );

        }


        /* -----------------------------------------------------
           CONFIRM PASSWORD
           ----------------------------------------------------- */

        if (!data.confirmPassword) {

            return (
                "Please confirm your password."
            );

        }


        if (
            data.password !==
            data.confirmPassword
        ) {

            return (
                "Passwords do not match."
            );

        }


        /* -----------------------------------------------------
           TERMS
           ----------------------------------------------------- */

        if (
            termsInput &&
            !termsInput.checked
        ) {

            return (
                "Please agree to the Privacy Policy and Terms before continuing."
            );

        }


        /* -----------------------------------------------------
           COMMUNICATIONS
           ----------------------------------------------------- */

        /*
         * This checkbox is intentionally optional.
         *
         * If it exists in the HTML and is required,
         * it will be checked here.
         */

        if (
            communicationsInput &&
            communicationsInput.dataset.required === "true" &&
            !communicationsInput.checked
        ) {

            return (
                "Please allow account verification communications to continue."
            );

        }


        return null;

    }


    /* =========================================================
       STORAGE HELPERS
       ========================================================= */

    function saveVerificationState(
        response,
        data
    ) {

        /*
         * Backend should preferably return:
         *
         * identity / uid / userId
         * email
         * phone
         * username
         * verification channel
         * emailSent
         * phoneSent
         *
         * We support several naming styles for
         * backward compatibility.
         */

        const identity =
            response.identity ||
            response.uid ||
            response.userId ||
            response.id ||
            response.username ||
            data.username;


        const email =
            response.email ||
            response.gmail ||
            data.email;


        const phone =
            response.phone ||
            data.phone;


        const username =
            response.username ||
            data.username;


        /*
         * Primary verification channel.
         *
         * Gmail is preferred because this project
         * does not require a paid SMS provider.
         */

        const channel =
            response.verificationChannel ||
            response.channel ||
            "email";


        /*
         * Store identity information only.
         *
         * NEVER store the actual OTP here.
         */

        try {

            sessionStorage.setItem(
                STORAGE_KEYS.UID,
                String(identity || "")
            );


            sessionStorage.setItem(
                STORAGE_KEYS.EMAIL,
                String(email || "")
            );


            sessionStorage.setItem(
                STORAGE_KEYS.PHONE,
                String(phone || "")
            );


            sessionStorage.setItem(
                STORAGE_KEYS.USERNAME,
                String(username || "")
            );


            sessionStorage.setItem(
                STORAGE_KEYS.CHANNEL,
                String(channel || "email")
            );


            sessionStorage.setItem(
                STORAGE_KEYS.EMAIL_SENT,
                String(
                    Boolean(
                        response.emailSent
                    )
                )
            );


            sessionStorage.setItem(
                STORAGE_KEYS.PHONE_SENT,
                String(
                    Boolean(
                        response.phoneSent
                    )
                )
            );


            /*
             * Older verification code compatibility.
             */

            sessionStorage.setItem(
                "stockflow_otp_identity",
                String(identity || "")
            );


            sessionStorage.setItem(
                "stockflow_otp_email",
                String(email || "")
            );


            sessionStorage.setItem(
                "stockflow_otp_phone",
                String(phone || "")
            );


            sessionStorage.setItem(
                "stockflow_otp_username",
                String(username || "")
            );


            return {
                identity,
                email,
                phone,
                username,
                channel
            };

        } catch (storageError) {

            console.warn(
                "STOCKFLOW verification state could not be saved:",
                storageError
            );


            return {
                identity,
                email,
                phone,
                username,
                channel
            };

        }

    }


    /* =========================================================
       BUILD SUCCESS MESSAGE
       ========================================================= */

    function buildSuccessMessage(
        response,
        verification
    ) {

        /*
         * Prefer the backend message if available.
         */

        if (
            response &&
            response.message
        ) {

            return response.message;

        }


        const emailSent =
            response &&
            response.emailSent === true;


        const phoneSent =
            response &&
            response.phoneSent === true;


        /*
         * Gmail only.
         */

        if (
            emailSent &&
            !phoneSent
        ) {

            return (
                `Registration successful. A verification code has been sent to ${verification.email}.`
            );

        }


        /*
         * Both email and SMS actually sent.
         */

        if (
            emailSent &&
            phoneSent
        ) {

            return (
                "Registration successful. Verification codes have been sent to your registered email and mobile number."
            );

        }


        /*
         * Backend registered the user but
         * did not report an actual delivery.
         */

        return (
            "Registration successful. Please continue to the verification page."
        );

    }


    /* =========================================================
       REDIRECT
       ========================================================= */

    function redirectToVerification() {

        /*
         * Directly open verify.html.
         *
         * Do NOT use verify-otp.html because that file
         * currently redirects immediately to verify.html.
         */

        window.location.replace(
            VERIFY_PAGE
        );

    }


    /* =========================================================
       SUBMIT
       ========================================================= */

    form.addEventListener(
        "submit",
        async event => {

            event.preventDefault();


            clearMessage();


            /* =================================================
               READ FIRST NAME
               ================================================= */

            let firstName =
                getValue(
                    firstNameInput
                );


            /* =================================================
               READ LAST NAME
               ================================================= */

            let lastName =
                getValue(
                    lastNameInput
                );


            /* =================================================
               OLD FULL NAME COMPATIBILITY
               ================================================= */

            if (
                (!firstName || !lastName) &&
                oldNameInput
            ) {

                const oldName =
                    getValue(
                        oldNameInput
                    );


                const nameParts =
                    oldName.split(/\s+/);


                if (!firstName) {

                    firstName =
                        nameParts.shift() ||
                        "";

                }


                if (!lastName) {

                    lastName =
                        nameParts.join(" ") ||
                        "";

                }

            }


            /* =================================================
               READ PHONE
               ================================================= */

            const phone =
                normalizePhone(
                    getValue(
                        phoneInput
                    )
                );


            /* =================================================
               READ FORM DATA
               ================================================= */

            const data = {

                firstName:
                    firstName,


                lastName:
                    lastName,


                name:
                    `${firstName} ${lastName}`
                        .replace(/\s+/g, " ")
                        .trim(),


                username:
                    getValue(
                        usernameInput
                    ),


                age:
                    Number(
                        getValue(
                            ageInput
                        )
                    ),


                email:
                    getValue(
                        emailInput
                    ).toLowerCase(),


                /*
                 * Keep both names for backend
                 * compatibility.
                 */

                gmail:
                    getValue(
                        emailInput
                    ).toLowerCase(),


                phone:
                    phone,


                password:
                    getPasswordValue(
                        passwordInput
                    ),


                confirmPassword:
                    getPasswordValue(
                        confirmPasswordInput
                    )

            };


            /* =================================================
               VALIDATE
               ================================================= */

            const validationError =
                validateRegistration(
                    data
                );


            if (validationError) {

                showMessage(
                    validationError,
                    "error"
                );


                return;

            }


            /* =================================================
               START LOADING
               ================================================= */

            setLoading(
                true
            );


            try {

                /* =============================================
                   API CHECK
                   ============================================= */

                if (
                    !window.StockFlowAPI ||
                    typeof window.StockFlowAPI.register !==
                        "function"
                ) {

                    throw new Error(
                        "STOCKFLOW registration service is unavailable."
                    );

                }


                /* =============================================
                   REGISTER ACCOUNT
                   =============================================

                   IMPORTANT:

                   The frontend does NOT generate the OTP.

                   Google Apps Script should:
                   1. Create the account.
                   2. Generate the random 6-digit OTP.
                   3. Save OTP to USER sheet.
                   4. Save OTP to Firebase.
                   5. Set expiration time.
                   6. Send Gmail OTP.
                   7. Return registration result.
                   ============================================= */

                const response =
                    await window.StockFlowAPI.register({

                        firstName:
                            data.firstName,


                        lastName:
                            data.lastName,


                        name:
                            data.name,


                        username:
                            data.username,


                        age:
                            data.age,


                        email:
                            data.email,


                        gmail:
                            data.gmail,


                        phone:
                            data.phone,


                        password:
                            data.password

                    });


                /* =============================================
                   EMPTY RESPONSE
                   ============================================= */

                if (!response) {

                    throw new Error(
                        "No response was received from the STOCKFLOW server."
                    );

                }


                /* =============================================
                   REGISTRATION FAILED
                   ============================================= */

                if (
                    response.success === false
                ) {

                    showMessage(
                        response.message ||
                        "Registration failed. Please check your information and try again.",
                        "error"
                    );


                    setLoading(
                        false
                    );


                    return;

                }


                /* =============================================
                   SAVE VERIFICATION STATE
                   ============================================= */

                const verification =
                    saveVerificationState(
                        response,
                        data
                    );


                /* =============================================
                   VERIFY THAT WE HAVE AN IDENTITY
                   ============================================= */

                if (
                    !verification.identity
                ) {

                    /*
                     * Do not redirect to verification if the
                     * backend failed to give us any identity.
                     *
                     * This prevents the verification page from
                     * immediately thinking the registration
                     * session is missing.
                     */

                    throw new Error(
                        "Registration completed, but the verification identity was not returned by the server."
                    );

                }


                /* =============================================
                   SUCCESS MESSAGE
                   ============================================= */

                showMessage(
                    buildSuccessMessage(
                        response,
                        verification
                    ),
                    "success"
                );


                /* =============================================
                   REDIRECT TO VERIFY PAGE
                   ============================================= */

                /*
                 * Short delay lets the user see the success
                 * message before moving to verification.
                 */

                window.setTimeout(
                    () => {

                        redirectToVerification();

                    },
                    1000
                );


            } catch (error) {

                console.error(
                    "STOCKFLOW registration error:",
                    error
                );


                showMessage(
                    error &&
                    error.message
                        ? error.message
                        : "Unable to create your account. Please try again.",
                    "error"
                );


                setLoading(
                    false
                );

            }

        }
    );


    /* =========================================================
       OPTIONAL: PREVENT DOUBLE SUBMISSION
       ========================================================= */

    form.addEventListener(
        "keydown",
        event => {

            if (
                event.key === "Enter" &&
                button &&
                button.disabled
            ) {

                event.preventDefault();

            }

        }
    );


});
