/* ============================================================
   STOCKFLOW — REGISTRATION CONTROLLER
   ============================================================

   MIDTERM DEMO FLOW:

   Register Form
        ↓
   Validate registration data
        ↓
   StockFlowAPI.register()
        ↓
   Google Apps Script
        ↓
   Generate random 6-digit OTP
        ↓
   Save account + OTP + expiry
        ↓
   Google Sheets USER
        ↓
   Firebase
        ↓
   Return registration result
        ↓
   Save verification identity
        ↓
   Redirect to verify.html
        ↓
   verify.html receives demo OTP
        ↓
   Auto-fill six OTP boxes

   IMPORTANT:
   - OTP is generated by the BACKEND.
   - OTP is NOT generated in this file.
   - OTP is NOT permanently stored in sessionStorage.
   - No real Gmail delivery is required for this midterm demo.
   - No real SMS delivery is required for this midterm demo.
   - Email and phone are stored as account information.
   ============================================================ */


document.addEventListener("DOMContentLoaded", () => {

    "use strict";


    /* =========================================================
       FORM
       ========================================================= */

    const form =
        document.getElementById(
            "registerForm"
        );


    if (!form) {
        return;
    }


    /* =========================================================
       CONFIGURATION
       ========================================================= */

    const CONFIG =
        window.STOCKFLOW_CONFIG ||
        window.CONFIG ||
        {};


    const ROUTES =
        CONFIG.ROUTES ||
        {};


    const VERIFY_PAGE =
        ROUTES.verify ||
        ROUTES.VERIFY ||
        "verify.html";


    /* =========================================================
       STORAGE KEYS
       ========================================================= */

    const STORAGE_KEYS = {

        UID:
            CONFIG.OTP_UID_KEY ||
            "STOCKFLOW_OTP_UID",

        EMAIL:
            CONFIG.OTP_EMAIL_KEY ||
            "STOCKFLOW_OTP_EMAIL",

        PHONE:
            CONFIG.OTP_PHONE_KEY ||
            "STOCKFLOW_OTP_PHONE",

        USERNAME:
            CONFIG.OTP_USERNAME_KEY ||
            "STOCKFLOW_OTP_USERNAME",

        CHANNEL:
            CONFIG.OTP_CHANNEL_KEY ||
            "STOCKFLOW_OTP_CHANNEL"

    };


    /* =========================================================
       ELEMENTS
       ========================================================= */

    const message =
        document.getElementById(
            "registerMessage"
        );


    const button =
        document.getElementById(
            "registerButton"
        ) ||
        form.querySelector(
            'button[type="submit"]'
        );


    /* =========================================================
       NAME
       ========================================================= */

    const firstNameInput =
        document.getElementById(
            "registerFirstName"
        ) ||
        document.getElementById(
            "firstName"
        );


    const lastNameInput =
        document.getElementById(
            "registerLastName"
        ) ||
        document.getElementById(
            "lastName"
        );


    const oldNameInput =
        document.getElementById(
            "registerName"
        );


    /* =========================================================
       OTHER FIELDS
       ========================================================= */

    const usernameInput =
        document.getElementById(
            "registerUsername"
        );


    const ageInput =
        document.getElementById(
            "registerAge"
        );


    const emailInput =
        document.getElementById(
            "registerEmail"
        );


    const phoneInput =
        document.getElementById(
            "registerPhone"
        );


    const passwordInput =
        document.getElementById(
            "registerPassword"
        );


    const confirmPasswordInput =
        document.getElementById(
            "registerConfirmPassword"
        );


    /* =========================================================
       OPTIONAL CHECKBOXES
       ========================================================= */

    const termsInput =
        document.getElementById(
            "registerTerms"
        ) ||
        document.getElementById(
            "terms"
        ) ||
        document.querySelector(
            '[name="terms"]'
        );


    const communicationsInput =
        document.getElementById(
            "registerCommunications"
        ) ||
        document.getElementById(
            "communications"
        ) ||
        document.querySelector(
            '[name="communications"]'
        );


    /* =========================================================
       MESSAGE HELPERS
       ========================================================= */

    function showMessage(
        text,
        type = "error"
    ) {

        if (!message) {
            return;
        }


        message.textContent =
            text || "";


        message.className =
            `auth-message ${type}`;

    }


    function clearMessage() {

        if (!message) {
            return;
        }


        message.textContent =
            "";


        message.className =
            "auth-message";

    }


    /* =========================================================
       LOADING STATE
       ========================================================= */

    function setLoading(
        loading
    ) {

        if (!button) {
            return;
        }


        button.disabled =
            loading;


        button.classList.toggle(
            "loading",
            loading
        );


        button.setAttribute(
            "aria-busy",
            String(loading)
        );


        const text =
            button.querySelector(
                ".button-text"
            );


        const loader =
            button.querySelector(
                ".button-loader"
            );


        if (text) {

            text.hidden =
                loading;

        }


        if (loader) {

            loader.hidden =
                !loading;

        }

    }


    /* =========================================================
       VALUE HELPERS
       ========================================================= */

    function getValue(
        input
    ) {

        return input
            ? input.value.trim()
            : "";

    }


    function getPasswordValue(
        input
    ) {

        return input
            ? input.value
            : "";

    }


    /* =========================================================
       PHONE NORMALIZATION
       =========================================================

       Accepted:

       09171234567
       +639171234567
       639171234567

       Internally stored as:

       09171234567
       ========================================================= */

    function normalizePhone(
        value
    ) {

        let phone =
            String(value || "")
                .trim()
                .replace(
                    /[\s()-]/g,
                    ""
                );


        if (
            phone.startsWith("+63")
        ) {

            phone =
                "0" +
                phone.substring(3);

        } else if (
            phone.startsWith("63")
        ) {

            phone =
                "0" +
                phone.substring(2);

        }


        return phone;

    }


    /* =========================================================
       VALIDATION
       ========================================================= */

    function validateRegistration(
        data
    ) {

        /* -----------------------------------------------------
           FIRST NAME
           ----------------------------------------------------- */

        if (!data.firstName) {

            return (
                "Please enter your first name."
            );

        }


        /* -----------------------------------------------------
           LAST NAME
           ----------------------------------------------------- */

        if (!data.lastName) {

            return (
                "Please enter your last name."
            );

        }


        /* -----------------------------------------------------
           NAME CHARACTERS
           ----------------------------------------------------- */

        const namePattern =
            /^[A-Za-zÀ-ÿ' -]+$/;


        if (
            !namePattern.test(
                data.firstName
            )
        ) {

            return (
                "First name contains invalid characters."
            );

        }


        if (
            !namePattern.test(
                data.lastName
            )
        ) {

            return (
                "Last name contains invalid characters."
            );

        }


        /* -----------------------------------------------------
           USERNAME
           ----------------------------------------------------- */

        if (!data.username) {

            return (
                "Please enter a username."
            );

        }


        if (
            data.username.length < 4 ||
            data.username.length > 30
        ) {

            return (
                "Username must contain 4–30 characters."
            );

        }


        if (
            !/^[A-Za-z0-9._-]+$/.test(
                data.username
            )
        ) {

            return (
                "Username may only contain letters, numbers, dots, underscores and hyphens."
            );

        }


        /* -----------------------------------------------------
           AGE
           ----------------------------------------------------- */

        if (
            !Number.isInteger(
                data.age
            )
        ) {

            return (
                "Please enter your age."
            );

        }


        if (
            data.age < 18 ||
            data.age > 100
        ) {

            return (
                "Please enter a valid age between 18 and 100."
            );

        }


        /* -----------------------------------------------------
           EMAIL
           ----------------------------------------------------- */

        if (!data.email) {

            return (
                "Please enter your Gmail address."
            );

        }


        const emailPattern =
            /^[^\s@]+@[^\s@]+\.[^\s@]+$/;


        if (
            !emailPattern.test(
                data.email
            )
        ) {

            return (
                "Please enter a valid Gmail address."
            );

        }


        if (
            !data.email
                .toLowerCase()
                .endsWith("@gmail.com")
        ) {

            return (
                "Please use a valid @gmail.com address."
            );

        }


        /* -----------------------------------------------------
           PHONE
           ----------------------------------------------------- */

        if (!data.phone) {

            return (
                "Please enter your Philippine mobile number."
            );

        }


        const phonePattern =
            /^09\d{9}$/;


        if (
            !phonePattern.test(
                data.phone
            )
        ) {

            return (
                "Phone number must be in 09XXXXXXXXX format."
            );

        }


        /* -----------------------------------------------------
           PASSWORD
           ----------------------------------------------------- */

        if (!data.password) {

            return (
                "Please create a password."
            );

        }


        if (
            data.password.length < 8
        ) {

            return (
                "Password must contain at least 8 characters."
            );

        }


        /* -----------------------------------------------------
           CONFIRM PASSWORD
           ----------------------------------------------------- */

        if (!data.confirmPassword) {

            return (
                "Please confirm your password."
            );

        }


        if (
            data.password !==
            data.confirmPassword
        ) {

            return (
                "Passwords do not match."
            );

        }


        /* -----------------------------------------------------
           TERMS
           ----------------------------------------------------- */

        if (
            termsInput &&
            !termsInput.checked
        ) {

            return (
                "Please agree to the Privacy Policy and Terms before continuing."
            );

        }


        /* -----------------------------------------------------
           COMMUNICATIONS
           ----------------------------------------------------- */

        if (
            communicationsInput &&
            communicationsInput.dataset.required ===
                "true" &&
            !communicationsInput.checked
        ) {

            return (
                "Please allow account verification communications to continue."
            );

        }


        return null;

    }


    /* =========================================================
       SAVE VERIFICATION STATE
       ========================================================= */

    function saveVerificationState(
        response,
        data
    ) {

        response =
            response || {};


        const identity =
            response.identity ||
            response.uid ||
            response.userId ||
            response.id ||
            response.username ||
            data.username;


        const uid =
            response.uid ||
            response.userId ||
            response.id ||
            "";


        const email =
            response.email ||
            response.gmail ||
            data.email;


        const phone =
            response.phone ||
            data.phone;


        const username =
            response.username ||
            data.username;


        /*
         * For this midterm project we keep the
         * verification channel informational.
         *
         * The actual OTP is handled by the backend.
         */

        const channel =
            response.verificationChannel ||
            response.channel ||
            "demo";


        try {

            sessionStorage.setItem(
                STORAGE_KEYS.UID,
                String(uid)
            );


            sessionStorage.setItem(
                STORAGE_KEYS.EMAIL,
                String(email)
            );


            sessionStorage.setItem(
                STORAGE_KEYS.PHONE,
                String(phone)
            );


            sessionStorage.setItem(
                STORAGE_KEYS.USERNAME,
                String(username)
            );


            sessionStorage.setItem(
                STORAGE_KEYS.CHANNEL,
                String(channel)
            );


            /*
             * Backward-compatible keys.
             */

            sessionStorage.setItem(
                "stockflow_otp_identity",
                String(identity || "")
            );


            sessionStorage.setItem(
                "stockflow_otp_email",
                String(email || "")
            );


            sessionStorage.setItem(
                "stockflow_otp_phone",
                String(phone || "")
            );


            sessionStorage.setItem(
                "stockflow_otp_username",
                String(username || "")
            );


        } catch (error) {

            console.warn(
                "STOCKFLOW: Unable to save verification state.",
                error
            );

        }


        return {

            identity:
                identity,

            uid:
                uid,

            email:
                email,

            phone:
                phone,

            username:
                username,

            channel:
                channel

        };

    }


    /* =========================================================
       SUCCESS MESSAGE
       ========================================================= */

    function buildSuccessMessage(
        response,
        verification
    ) {

        /*
         * Use backend message only if it exists.
         */

        if (
            response &&
            response.message
        ) {

            return response.message;

        }


        /*
         * Midterm demo wording.
         *
         * Do NOT claim Gmail/SMS was actually sent.
         */

        if (
            verification &&
            verification.email
        ) {

            return (
                "Registration successful. Your verification code is being prepared."
            );

        }


        return (
            "Registration successful. Continue to account verification."
        );

    }


    /* =========================================================
       REDIRECT
       ========================================================= */

    function redirectToVerification() {

        window.location.replace(
            VERIFY_PAGE
        );

    }


    /* =========================================================
       SUBMIT
       ========================================================= */

    form.addEventListener(
        "submit",
        async event => {

            event.preventDefault();


            clearMessage();


            /* =================================================
               READ NAME
               ================================================= */

            let firstName =
                getValue(
                    firstNameInput
                );


            let lastName =
                getValue(
                    lastNameInput
                );


            /* =================================================
               OLD FULL NAME COMPATIBILITY
               ================================================= */

            if (
                (!firstName || !lastName) &&
                oldNameInput
            ) {

                const oldName =
                    getValue(
                        oldNameInput
                    );


                const nameParts =
                    oldName.split(
                        /\s+/
                    );


                if (!firstName) {

                    firstName =
                        nameParts.shift() ||
                        "";

                }


                if (!lastName) {

                    lastName =
                        nameParts.join(" ") ||
                        "";

                }

            }


            /* =================================================
               PHONE
               ================================================= */

            const phone =
                normalizePhone(
                    getValue(
                        phoneInput
                    )
                );


            /* =================================================
               FORM DATA
               ================================================= */

            const email =
                getValue(
                    emailInput
                ).toLowerCase();


            const data = {

                firstName:
                    firstName,

                lastName:
                    lastName,

                name:
                    `${firstName} ${lastName}`
                        .replace(
                            /\s+/g,
                            " "
                        )
                        .trim(),

                username:
                    getValue(
                        usernameInput
                    ),

                age:
                    Number(
                        getValue(
                            ageInput
                        )
                    ),

                email:
                    email,

                gmail:
                    email,

                phone:
                    phone,

                password:
                    getPasswordValue(
                        passwordInput
                    ),

                confirmPassword:
                    getPasswordValue(
                        confirmPasswordInput
                    )

            };


            /* =================================================
               VALIDATE
               ================================================= */

            const validationError =
                validateRegistration(
                    data
                );


            if (validationError) {

                showMessage(
                    validationError,
                    "error"
                );

                return;

            }


            /* =================================================
               START LOADING
               ================================================= */

            setLoading(
                true
            );


            try {

                /* =============================================
                   API CHECK
                   ============================================= */

               if (
                   !window.StockFlowAPI ||
                   typeof window.StockFlowAPI.register !== "function"
               ) {
               
                   console.warn(
                       "STOCKFLOW: Registration API is not connected yet."
                   );
               
                   showMessage(
                       "Registration is ready. Database connectivity will be enabled shortly.",
                       "warning"
                   );
               
                   return;
               
               }


                /* =============================================
                   REGISTER
                   ============================================= */

                const response =
                    await window.StockFlowAPI.register({

                        firstName:
                            data.firstName,

                        lastName:
                            data.lastName,

                        name:
                            data.name,

                        username:
                            data.username,

                        age:
                            data.age,

                        email:
                            data.email,

                        gmail:
                            data.gmail,

                        phone:
                            data.phone,

                        password:
                            data.password

                    });


                /* =============================================
                   EMPTY RESPONSE
                   ============================================= */

                if (!response) {

                    throw new Error(
                        "No response was received from the STOCKFLOW server."
                    );

                }


                /* =============================================
                   REGISTRATION FAILED
                   ============================================= */

                if (
                    response.success === false
                ) {

                    showMessage(
                        response.message ||
                        "Registration failed. Please check your information and try again.",
                        "error"
                    );


                    return;

                }


                /* =============================================
                   SAVE VERIFICATION INFORMATION
                   ============================================= */

                const verification =
                    saveVerificationState(
                        response,
                        data
                    );


                /* =============================================
                   IDENTITY CHECK
                   ============================================= */

                if (
                    !verification.identity
                ) {

                    throw new Error(
                        "Registration completed, but the verification identity was not returned by the server."
                    );

                }


                /* =============================================
                   SUCCESS MESSAGE
                   ============================================= */

                showMessage(
                    buildSuccessMessage(
                        response,
                        verification
                    ),
                    "success"
                );


                /* =============================================
                   REDIRECT
                   ============================================= */

                window.setTimeout(
                    () => {

                        redirectToVerification();

                    },
                    900
                );


            } catch (error) {

                console.error(
                    "STOCKFLOW registration error:",
                    error
                );


               let errorMessage =
                            error &&
                            error.message
                                ? error.message
                                : "";
                        
                        if (
                            /unavailable|failed to fetch|network|fetch|connection/i
                                .test(errorMessage)
                        ) {
                        
                            errorMessage =
                                "Unable to connect to the registration system right now. Please try again.";
                        
                        }
                        
                        showMessage(
                            errorMessage ||
                            "Unable to create your account. Please check your information and try again.",
                            "error"
                        );


            } finally {

                setLoading(
                    false
                );

            }

        }
    );


    /* =========================================================
       PREVENT DOUBLE SUBMISSION
       ========================================================= */

    form.addEventListener(
        "keydown",
        event => {

            if (
                event.key === "Enter" &&
                button &&
                button.disabled
            ) {

                event.preventDefault();

            }

        }
    );

});
