/* =========================================================
   STOCKFLOW - VERIFY ACCOUNT
   verify.js

   FLOW:

   REGISTER
      ↓
   verify.html opens
      ↓
   Load pending registration state
      ↓
   Request backend-generated OTP
      ↓
   Wait 3–5 seconds ONLY HERE
      ↓
   Auto-fill backend OTP in DEMO_MODE
      ↓
   User clicks Verify Account
      ↓
   Apps Script verifies OTP
      ↓
   Save VERIFIED session
      ↓
   dashboard.html

   IMPORTANT:
   - Browser NEVER generates the OTP.
   - Math.random() is used ONLY for the 3–5 sec UI delay.
   - OTP is generated by Apps Script.
   - Delay starts only after verify.html is loaded.
   ========================================================= */

document.addEventListener("DOMContentLoaded", () => {
    "use strict";


    /* =====================================================
       CONFIGURATION
       ===================================================== */

    const CONFIG =
        window.STOCKFLOW_CONFIG ||
        window.CONFIG ||
        {};

    const AUTH_CONFIG =
        CONFIG.AUTH ||
        {};

    const ROUTES =
        CONFIG.ROUTES ||
        {};

    const API =
        window.StockFlowAPI ||
        window.API;


    const REGISTER_ROUTE =
        ROUTES.REGISTER ||
        "auth.html#register";

    const DASHBOARD_ROUTE =
        ROUTES.DASHBOARD ||
        "dashboard.html";


    const OTP_LENGTH =
        Number(
            AUTH_CONFIG.OTP_LENGTH ||
            CONFIG.OTP_LENGTH ||
            6
        );


    const RESEND_COOLDOWN =
        Number(
            AUTH_CONFIG.OTP_RESEND_COOLDOWN_SECONDS ||
            CONFIG.OTP_RESEND_COOLDOWN_SECONDS ||
            120
        );


    const DEMO_MODE =
        CONFIG.DEMO_MODE === true ||
        AUTH_CONFIG.DEMO_MODE === true;


    const DEMO_MIN_DELAY =
        Number(
            AUTH_CONFIG.DEMO_AUTO_FILL_DELAY_MIN ||
            CONFIG.DEMO_AUTO_FILL_DELAY_MIN ||
            3000
        );


    const DEMO_MAX_DELAY =
        Number(
            AUTH_CONFIG.DEMO_AUTO_FILL_DELAY_MAX ||
            CONFIG.DEMO_AUTO_FILL_DELAY_MAX ||
            5000
        );


    /* =====================================================
       STORAGE KEYS
       ===================================================== */

    const STORAGE_KEYS = {

        verification:
            "STOCKFLOW_VERIFICATION_STATE",

        uid:
            AUTH_CONFIG.OTP_UID_KEY ||
            "STOCKFLOW_OTP_UID",

        email:
            AUTH_CONFIG.OTP_EMAIL_KEY ||
            "STOCKFLOW_OTP_EMAIL",

        phone:
            AUTH_CONFIG.OTP_PHONE_KEY ||
            "STOCKFLOW_OTP_PHONE",

        username:
            AUTH_CONFIG.OTP_USERNAME_KEY ||
            "STOCKFLOW_OTP_USERNAME",

        identity:
            AUTH_CONFIG.OTP_IDENTITY_KEY ||
            "STOCKFLOW_OTP_IDENTITY",

        channel:
            AUTH_CONFIG.OTP_CHANNEL_KEY ||
            "STOCKFLOW_OTP_CHANNEL",

        user:
            AUTH_CONFIG.USER_KEY ||
            "STOCKFLOW_USER",

        session:
            AUTH_CONFIG.SESSION_KEY ||
            "STOCKFLOW_SESSION"
    };


    /* =====================================================
       DOM ELEMENTS
       ===================================================== */

    const verifyForm =
        document.getElementById(
            "verifyForm"
        );


    const verifyButton =
        document.getElementById(
            "verifyOtpBtn"
        ) ||
        document.getElementById(
            "verifyButton"
        );


    const verifyMessage =
        document.getElementById(
            "otpMessage"
        ) ||
        document.getElementById(
            "verifyMessage"
        );


    const verificationDescription =
        document.getElementById(
            "verificationDescription"
        );


    const emailMethod =
        document.getElementById(
            "emailMethod"
        );


    const phoneMethod =
        document.getElementById(
            "phoneMethod"
        );


    const emailButton =
        document.getElementById(
            "sendEmailCode"
        );


    const phoneButton =
        document.getElementById(
            "sendPhoneCode"
        );


    const emailDeliveryStatus =
        document.getElementById(
            "emailDeliveryStatus"
        );


    const phoneDeliveryStatus =
        document.getElementById(
            "phoneDeliveryStatus"
        );


    const emailTimer =
        document.getElementById(
            "emailOtpTimer"
        ) ||
        document.getElementById(
            "emailCountdown"
        );


    const phoneTimer =
        document.getElementById(
            "phoneOtpTimer"
        ) ||
        document.getElementById(
            "phoneCountdown"
        );


    const destination =
        document.getElementById(
            "otpDestination"
        ) ||
        document.getElementById(
            "verifyDestination"
        );


    const otpHidden =
        document.getElementById(
            "otp"
        );


    const otpHelp =
        document.getElementById(
            "otpHelp"
        );


    const otpBoxes =
        Array.from(
            document.querySelectorAll(
                "#otpInputs .otp-digit"
            )
        );


    /* =====================================================
       BASIC CHECKS
       ===================================================== */

    if (!verifyForm) {

        console.error(
            "[STOCKFLOW VERIFY] verifyForm was not found."
        );

        return;
    }


    if (!API) {

        console.error(
            "[STOCKFLOW VERIFY] API is not available."
        );

        showMessage(
            "The verification system is not available right now.",
            "error"
        );

        return;
    }


    /* =====================================================
       STATE
       ===================================================== */

    const state = {

        uid: "",

        identity: "",

        username: "",

        name: "",

        gmail: "",

        email: "",

        phone: "",

        role: "",

        accountStatus: "",

        channel: "email",

        requesting: false,

        verifying: false,

        demoOtp: "",

        otpReady: false,

        cooldowns: {

            email: 0,

            phone: 0
        }
    };


    const timers = {

        email: null,

        phone: null
    };


    /* =====================================================
       STORAGE HELPERS
       ===================================================== */

    function readStorage(key) {

        let value = "";

        try {

            value =
                sessionStorage.getItem(
                    key
                ) || "";

        } catch (error) {

            console.warn(
                "[STOCKFLOW VERIFY] sessionStorage read failed:",
                error
            );
        }


        if (value) {
            return value;
        }


        try {

            value =
                localStorage.getItem(
                    key
                ) || "";

        } catch (error) {

            console.warn(
                "[STOCKFLOW VERIFY] localStorage read failed:",
                error
            );
        }


        return value;
    }


    function writeSession(
        key,
        value
    ) {

        try {

            sessionStorage.setItem(
                key,
                value
            );

        } catch (error) {

            console.warn(
                "[STOCKFLOW VERIFY] sessionStorage write failed:",
                error
            );
        }
    }


    function writeBoth(
        key,
        value
    ) {

        try {

            sessionStorage.setItem(
                key,
                value
            );

        } catch (error) {

            console.warn(
                "[STOCKFLOW VERIFY] sessionStorage write failed:",
                error
            );
        }


        try {

            localStorage.setItem(
                key,
                value
            );

        } catch (error) {

            console.warn(
                "[STOCKFLOW VERIFY] localStorage write failed:",
                error
            );
        }
    }


    function removeStorage(key) {

        try {

            sessionStorage.removeItem(
                key
            );

        } catch (error) {

            console.warn(error);
        }


        try {

            localStorage.removeItem(
                key
            );

        } catch (error) {

            console.warn(error);
        }
    }


    /* =====================================================
       LOAD VERIFICATION STATE
       ===================================================== */

    function loadVerificationState() {

        let loaded = false;


        /* -------------------------------------------------
           1. Unified verification state
           ------------------------------------------------- */

        try {

            const raw =
                readStorage(
                    STORAGE_KEYS.verification
                );


            if (raw) {

                const saved =
                    JSON.parse(
                        raw
                    );


                if (
                    saved &&
                    typeof saved === "object"
                ) {

                    state.uid =
                        saved.uid ||
                        state.uid;

                    state.identity =
                        saved.identity ||
                        state.identity;

                    state.username =
                        saved.username ||
                        state.username;

                    state.name =
                        saved.name ||
                        state.name;

                    state.gmail =
                        saved.gmail ||
                        state.gmail;

                    state.email =
                        saved.email ||
                        state.email;

                    state.phone =
                        saved.phone ||
                        state.phone;

                    state.role =
                        saved.role ||
                        state.role;

                    state.accountStatus =
                        saved.accountStatus ||
                        state.accountStatus;

                    state.channel =
                        saved.channel ||
                        state.channel;

                    loaded = true;
                }
            }

        } catch (error) {

            console.warn(
                "[STOCKFLOW VERIFY] Invalid verification state:",
                error
            );
        }


        /* -------------------------------------------------
           2. Individual OTP compatibility keys
           ------------------------------------------------- */

        const storedUid =
            readStorage(
                STORAGE_KEYS.uid
            );


        const storedEmail =
            readStorage(
                STORAGE_KEYS.email
            );


        const storedPhone =
            readStorage(
                STORAGE_KEYS.phone
            );


        const storedUsername =
            readStorage(
                STORAGE_KEYS.username
            );


        const storedIdentity =
            readStorage(
                STORAGE_KEYS.identity
            );


        const storedChannel =
            readStorage(
                STORAGE_KEYS.channel
            );


        if (storedUid) {

            state.uid =
                state.uid ||
                storedUid;

            loaded = true;
        }


        if (storedEmail) {

            state.email =
                state.email ||
                storedEmail;

            state.gmail =
                state.gmail ||
                storedEmail;

            loaded = true;
        }


        if (storedPhone) {

            state.phone =
                state.phone ||
                storedPhone;

            loaded = true;
        }


        if (storedUsername) {

            state.username =
                state.username ||
                storedUsername;

            loaded = true;
        }


        if (storedIdentity) {

            state.identity =
                state.identity ||
                storedIdentity;

            loaded = true;
        }


        if (storedChannel) {

            state.channel =
                storedChannel;
        }


        /* -------------------------------------------------
           3. Stored user compatibility
           ------------------------------------------------- */

        try {

            const rawUser =
                readStorage(
                    STORAGE_KEYS.user
                );


            if (rawUser) {

                const user =
                    JSON.parse(
                        rawUser
                    );


                if (
                    user &&
                    typeof user === "object"
                ) {

                    state.uid =
                        state.uid ||
                        user.uid ||
                        user.UID ||
                        "";

                    state.username =
                        state.username ||
                        user.username ||
                        user.USERNAME ||
                        "";

                    state.name =
                        state.name ||
                        user.name ||
                        user.NAME ||
                        "";

                    state.email =
                        state.email ||
                        user.email ||
                        user.gmail ||
                        user.GMAIL ||
                        "";

                    state.gmail =
                        state.gmail ||
                        user.gmail ||
                        user.email ||
                        user.GMAIL ||
                        "";

                    state.phone =
                        state.phone ||
                        user.phone ||
                        user.phoneNumber ||
                        user["PHONE NO."] ||
                        "";

                    state.role =
                        state.role ||
                        user.role ||
                        user.ROLE ||
                        "";

                    state.accountStatus =
                        state.accountStatus ||
                        user.accountStatus ||
                        user.ACCOUNT_S ||
                        "";

                    state.identity =
                        state.identity ||
                        user.identity ||
                        user.username ||
                        user.email ||
                        user.gmail ||
                        user.uid ||
                        "";

                    if (
                        state.identity ||
                        state.uid
                    ) {

                        loaded = true;
                    }
                }
            }

        } catch (error) {

            console.warn(
                "[STOCKFLOW VERIFY] Unable to read stored user:",
                error
            );
        }


        /* -------------------------------------------------
           4. Derive identity
           ------------------------------------------------- */

        if (!state.identity) {

            state.identity =
                state.uid ||
                state.username ||
                state.email ||
                state.gmail ||
                state.phone ||
                "";
        }


        /* -------------------------------------------------
           5. Normalize email
           ------------------------------------------------- */

        if (!state.email) {

            state.email =
                state.gmail ||
                "";
        }


        if (!state.gmail) {

            state.gmail =
                state.email ||
                "";
        }


        /* -------------------------------------------------
           6. Save normalized state
           ------------------------------------------------- */

        if (
            loaded &&
            (
                state.identity ||
                state.uid
            )
        ) {

            saveVerificationState();
        }


        return Boolean(
            state.identity ||
            state.uid ||
            state.username ||
            state.email ||
            state.phone
        );
    }


    /* =====================================================
       SAVE VERIFICATION STATE
       ===================================================== */

    function saveVerificationState() {

        const verificationState = {

            uid:
                state.uid,

            identity:
                state.identity,

            username:
                state.username,

            name:
                state.name,

            gmail:
                state.gmail,

            email:
                state.email,

            phone:
                state.phone,

            role:
                state.role,

            accountStatus:
                state.accountStatus,

            channel:
                state.channel
        };


        try {

            writeSession(
                STORAGE_KEYS.verification,
                JSON.stringify(
                    verificationState
                )
            );

        } catch (error) {

            console.warn(
                "[STOCKFLOW VERIFY] Unable to save verification state:",
                error
            );
        }
    }


    /* =====================================================
       MESSAGE
       ===================================================== */

    function showMessage(
        message,
        type = "info"
    ) {

        if (!verifyMessage) {

            console.log(
                "[STOCKFLOW VERIFY]",
                message
            );

            return;
        }


        verifyMessage.textContent =
            message;


        verifyMessage.classList.remove(
            "success",
            "error",
            "info",
            "warning"
        );


        verifyMessage.classList.add(
            type
        );


        verifyMessage.hidden =
            false;
    }


    function clearMessage() {

        if (!verifyMessage) {
            return;
        }


        verifyMessage.textContent =
            "";


        verifyMessage.hidden =
            true;
    }


    /* =====================================================
       MASK EMAIL
       ===================================================== */

    function maskEmail(email) {

        const value =
            String(
                email || ""
            ).trim();


        const parts =
            value.split("@");


        if (
            parts.length !== 2
        ) {

            return value;
        }


        const name =
            parts[0];


        const domain =
            parts[1];


        if (
            name.length <= 2
        ) {

            return (
                name.charAt(0) +
                "*" +
                "@" +
                domain
            );
        }


        return (
            name.substring(
                0,
                2
            ) +
            "*".repeat(
                Math.max(
                    2,
                    name.length - 2
                )
            ) +
            "@" +
            domain
        );
    }


    /* =====================================================
       MASK PHONE
       ===================================================== */

    function maskPhone(phone) {

        const value =
            String(
                phone || ""
            ).replace(
                /\s+/g,
                ""
            );


        if (
            value.length < 7
        ) {

            return value;
        }


        return (
            value.substring(
                0,
                3
            ) +
            "****" +
            value.substring(
                value.length - 3
            )
        );
    }


    /* =====================================================
       UPDATE DESTINATION
       ===================================================== */

    function updateDestination() {

        if (!destination) {
            return;
        }


        if (
            state.channel === "phone"
        ) {

            destination.textContent =
                state.phone
                    ? maskPhone(
                        state.phone
                    )
                    : "your registered phone number";

            return;
        }


        const email =
            state.gmail ||
            state.email ||
            "";


        destination.textContent =
            email
                ? maskEmail(
                    email
                )
                : "your registered Gmail";
    }


    /* =====================================================
       CHANNEL SELECTION
       ===================================================== */

    function selectChannel(channel) {

        state.channel =
            channel === "phone"
                ? "phone"
                : "email";


        if (emailMethod) {

            emailMethod.classList.toggle(
                "active",
                state.channel === "email"
            );
        }


        if (phoneMethod) {

            phoneMethod.classList.toggle(
                "active",
                state.channel === "phone"
            );
        }


        updateDestination();
    }


    if (emailMethod) {

        emailMethod.addEventListener(
            "click",
            event => {

                if (
                    event.target.closest(
                        "button"
                    )
                ) {

                    return;
                }


                selectChannel(
                    "email"
                );
            }
        );
    }


    if (phoneMethod) {

        phoneMethod.addEventListener(
            "click",
            event => {

                if (
                    event.target.closest(
                        "button"
                    )
                ) {

                    return;
                }


                selectChannel(
                    "phone"
                );
            }
        );
    }


    /* =====================================================
       OTP
       ===================================================== */

    function clearOtp() {

        otpBoxes.forEach(
            input => {

                input.value =
                    "";
            }
        );


        if (otpHidden) {

            otpHidden.value =
                "";
        }
    }


    function getOtp() {

        return otpBoxes
            .map(
                input =>
                    String(
                        input.value || ""
                    )
                        .replace(
                            /\D/g,
                            ""
                        )
                        .charAt(0)
            )
            .join("");
    }


    function updateHiddenOtp() {

        if (!otpHidden) {
            return;
        }


        otpHidden.value =
            getOtp();
    }


    function fillOtp(otp) {

        const code =
            String(
                otp || ""
            )
                .replace(
                    /\D/g,
                    ""
                )
                .substring(
                    0,
                    OTP_LENGTH
                );


        if (
            code.length !== OTP_LENGTH
        ) {

            return false;
        }


        otpBoxes.forEach(
            (
                input,
                index
            ) => {

                input.value =
                    code.charAt(
                        index
                    );
            }
        );


        updateHiddenOtp();


        if (otpHelp) {

            otpHelp.textContent =
                "Your verification code has been filled. You can verify your account now.";
        }


        if (verifyButton) {

            verifyButton.disabled =
                false;
        }


        return true;
    }


    /* =====================================================
       OTP INPUT EVENTS
       ===================================================== */

    otpBoxes.forEach(
        (
            input,
            index
        ) => {

            input.disabled =
                false;


            input.addEventListener(
                "input",
                event => {

                    const value =
                        String(
                            event.target.value ||
                            ""
                        )
                            .replace(
                                /\D/g,
                                ""
                            )
                            .charAt(0);


                    event.target.value =
                        value;


                    updateHiddenOtp();


                    if (
                        value &&
                        index <
                        otpBoxes.length - 1
                    ) {

                        otpBoxes[
                            index + 1
                        ].focus();
                    }


                    if (
                        getOtp().length ===
                        OTP_LENGTH
                    ) {

                        if (verifyButton) {

                            verifyButton.disabled =
                                false;
                        }
                    }
                }
            );


            input.addEventListener(
                "keydown",
                event => {

                    if (
                        event.key ===
                        "Backspace" &&
                        !input.value &&
                        index > 0
                    ) {

                        otpBoxes[
                            index - 1
                        ].focus();
                    }


                    if (
                        event.key ===
                        "ArrowLeft" &&
                        index > 0
                    ) {

                        otpBoxes[
                            index - 1
                        ].focus();
                    }


                    if (
                        event.key ===
                        "ArrowRight" &&
                        index <
                        otpBoxes.length - 1
                    ) {

                        otpBoxes[
                            index + 1
                        ].focus();
                    }
                }
            );


            input.addEventListener(
                "paste",
                event => {

                    event.preventDefault();


                    const pasted =
                        (
                            event.clipboardData ||
                            window.clipboardData
                        )
                            .getData(
                                "text"
                            )
                            .replace(
                                /\D/g,
                                ""
                            )
                            .substring(
                                0,
                                OTP_LENGTH
                            );


                    if (!pasted) {
                        return;
                    }


                    fillOtp(
                        pasted
                    );
                }
            );
        }
    );


    /* =====================================================
       BUTTON TEXT
       ===================================================== */

    function setButtonText(
        button,
        text
    ) {

        if (!button) {
            return;
        }


        button.textContent =
            text;
    }


    /* =====================================================
       EXTRACT BACKEND OTP
       ===================================================== */

    function extractOtp(response) {

        if (!response) {
            return "";
        }


        const value =
            response.otp ||
            response.codeValue ||
            response.verificationCode ||
            "";


        const normalized =
            String(
                value
            )
                .replace(
                    /\D/g,
                    ""
                );


        return (
            normalized.length ===
            OTP_LENGTH
                ? normalized
                : ""
        );
    }


    /* =====================================================
       UPDATE STATE FROM RESPONSE
       ===================================================== */

    function updateStateFromResponse(
        response
    ) {

        if (!response) {
            return;
        }


        state.uid =
            response.uid ||
            state.uid;


        state.username =
            response.username ||
            state.username;


        state.name =
            response.name ||
            state.name;


        state.gmail =
            response.gmail ||
            response.email ||
            state.gmail;


        state.email =
            response.email ||
            response.gmail ||
            state.email;


        state.phone =
            response.phone ||
            state.phone;


        state.role =
            response.role ||
            state.role;


        state.accountStatus =
            response.accountStatus ||
            state.accountStatus;


        state.identity =
            response.identity ||
            state.identity;


        state.channel =
            response.channel ||
            state.channel;


        if (!state.identity) {

            state.identity =
                state.uid ||
                state.username ||
                state.email ||
                state.phone ||
                "";
        }


        saveVerificationState();


        updateDestination();
    }


    /* =====================================================
       DEMO DELAY
       ===================================================== */

    function getDemoDelay() {

        const min =
            Math.max(
                0,
                DEMO_MIN_DELAY
            );


        const max =
            Math.max(
                min,
                DEMO_MAX_DELAY
            );


        if (
            max <= min
        ) {

            return min;
        }


        /*
         * IMPORTANT:
         *
         * This random value ONLY determines
         * how long the UI waits.
         *
         * It NEVER creates the OTP.
         */

        return (
            min +
            Math.floor(
                Math.random() *
                (
                    max -
                    min +
                    1
                )
            )
        );
    }


    function wait(
        milliseconds
    ) {

        return new Promise(
            resolve =>
                setTimeout(
                    resolve,
                    milliseconds
                )
        );
    }


    /* =====================================================
       AUTO-FILL BACKEND OTP
       ===================================================== */

    async function autoFillBackendOtp(
        response
    ) {

        if (!DEMO_MODE) {
            return;
        }


        const otp =
            extractOtp(
                response
            );


        if (
            otp.length !== OTP_LENGTH
        ) {

            console.warn(
                "[STOCKFLOW VERIFY] Backend did not return a demo OTP."
            );

            return;
        }


        state.demoOtp =
            otp;


        state.otpReady =
            true;


        /*
         * DELAY STARTS HERE.
         *
         * This function is called ONLY from
         * verify.html after prepareOtp()
         * succeeds.
         *
         * Registration itself does NOT wait.
         */

        const delay =
            getDemoDelay();


        console.log(
            "[STOCKFLOW VERIFY] Demo OTP received from backend. Auto-fill delay:",
            delay,
            "ms"
        );


        if (verificationDescription) {

            verificationDescription.textContent =
                "Verification code sent. Preparing the code...";
        }


        await wait(
            delay
        );


        /*
         * Make sure the user has not already
         * requested another code.
         */

        if (
            !state.requesting &&
            state.otpReady &&
            state.demoOtp === otp
        ) {

            fillOtp(
                otp
            );


            if (verificationDescription) {

                verificationDescription.textContent =
                    "Your verification code is ready.";
            }
        }
    }


    /* =====================================================
       COOLDOWN
       ===================================================== */

    function formatCountdown(
        seconds
    ) {

        const value =
            Math.max(
                0,
                Number(
                    seconds
                ) || 0
            );


        const minutes =
            Math.floor(
                value / 60
            );


        const secondsLeft =
            value % 60;


        return (
            String(
                minutes
            ).padStart(
                2,
                "0"
            ) +
            ":" +
            String(
                secondsLeft
            ).padStart(
                2,
                "0"
            )
        );
    }


    function updateCooldownUI(
        channel
    ) {

        const seconds =
            Math.max(
                0,
                Number(
                    state.cooldowns[
                        channel
                    ] || 0
                )
            );


        const button =
            channel === "email"
                ? emailButton
                : phoneButton;


        const timer =
            channel === "email"
                ? emailTimer
                : phoneTimer;


        if (button) {

            button.disabled =
                seconds > 0 ||
                state.requesting;
        }


        if (timer) {

            if (
                seconds > 0
            ) {

                timer.textContent =
                    (
                        channel === "email"
                            ? "Email code available in "
                            : "Phone code available in "
                    ) +
                    formatCountdown(
                        seconds
                    );

            } else {

                timer.textContent =
                    channel === "email"
                        ? "Email code available."
                        : "Phone code available.";
            }
        }
    }


    function stopCooldown(
        channel
    ) {

        if (
            timers[channel]
        ) {

            clearInterval(
                timers[channel]
            );


            timers[channel] =
                null;
        }


        state.cooldowns[
            channel
        ] = 0;


        updateCooldownUI(
            channel
        );
    }


    function startCooldown(
        channel,
        seconds
    ) {

        stopCooldown(
            channel
        );


        state.cooldowns[
            channel
        ] =
            Math.max(
                0,
                Number(
                    seconds
                ) ||
                RESEND_COOLDOWN
            );


        updateCooldownUI(
            channel
        );


        timers[channel] =
            setInterval(
                () => {

                    state.cooldowns[
                        channel
                    ]--;


                    if (
                        state.cooldowns[
                            channel
                        ] <= 0
                    ) {

                        stopCooldown(
                            channel
                        );


                        return;
                    }


                    updateCooldownUI(
                        channel
                    );

                },
                1000
            );
    }


    /* =====================================================
       INITIAL OTP
       ===================================================== */

    async function prepareInitialOtp() {

        if (
            state.requesting
        ) {

            return;
        }


        if (
            !state.identity &&
            !state.uid &&
            !state.username &&
            !state.email &&
            !state.phone
        ) {

            showMessage(
                "No pending registration account was found. Please register first.",
                "error"
            );


            setTimeout(
                () => {

                    window.location.href =
                        REGISTER_ROUTE;

                },
                1500
            );


            return;
        }


        state.requesting =
            true;


        clearMessage();


        /*
         * INITIAL OTP IS ALWAYS EMAIL.
         *
         * Phone remains available until
         * the user explicitly requests it.
         */

        selectChannel(
            "email"
        );


        try {

            if (verificationDescription) {

                verificationDescription.textContent =
                    "Preparing your verification code...";
            }


            const response =
                await API.prepareOtp({

                    identity:
                        state.identity,

                    uid:
                        state.uid,

                    username:
                        state.username,

                    email:
                        state.email,

                    gmail:
                        state.gmail,

                    phone:
                        state.phone,

                    channel:
                        "email"
                });


            console.log(
                "[STOCKFLOW VERIFY] Initial OTP response:",
                response
            );


            updateStateFromResponse(
                response
            );


            if (
                response &&
                response.success === true
            ) {

                state.otpReady =
                    response.otpReady === true;


                const cooldown =
                    Number(
                        response.cooldownSeconds ||
                        RESEND_COOLDOWN
                    );


                /*
                 * Email receives its cooldown.
                 *
                 * Phone remains available.
                 */

                startCooldown(
                    "email",
                    cooldown
                );


                if (emailDeliveryStatus) {

                    emailDeliveryStatus.textContent =
                        response.message ||
                        "Verification code prepared.";
                }


                if (verificationDescription) {

                    verificationDescription.textContent =
                        "Your verification code is ready.";
                }


                showMessage(
                    response.message ||
                    "Verification code generated successfully.",
                    "success"
                );


                /*
                 * IMPORTANT:
                 *
                 * The demo delay begins AFTER
                 * verify.html has loaded and AFTER
                 * the backend returns the OTP.
                 */

                await autoFillBackendOtp(
                    response
                );


                return;
            }


            handleResponseError(
                response
            );

        } catch (error) {

            handleError(
                error
            );

        } finally {

            state.requesting =
                false;


            updateCooldownUI(
                "email"
            );


            updateCooldownUI(
                "phone"
            );
        }
    }


    /* =====================================================
       REQUEST OTP
       ===================================================== */

    async function requestOtp(
        channel
    ) {

        const selected =
            channel === "phone"
                ? "phone"
                : "email";


        selectChannel(
            selected
        );


        if (
            state.requesting
        ) {

            return;
        }


        if (
            state.cooldowns[
                selected
            ] > 0
        ) {

            showMessage(
                "Please wait " +
                state.cooldowns[
                    selected
                ] +
                " seconds before requesting another " +
                selected +
                " code.",
                "warning"
            );


            return;
        }


        state.requesting =
            true;


        clearMessage();


        clearOtp();


        state.demoOtp =
            "";


        state.otpReady =
            false;


        const button =
            selected === "email"
                ? emailButton
                : phoneButton;


        if (button) {

            button.disabled =
                true;


            setButtonText(
                button,
                "Generating code..."
            );
        }


        try {

            const response =
                await API.prepareOtp({

                    identity:
                        state.identity,

                    uid:
                        state.uid,

                    username:
                        state.username,

                    email:
                        state.email,

                    gmail:
                        state.gmail,

                    phone:
                        state.phone,

                    channel:
                        selected
                });


            console.log(
                "[STOCKFLOW VERIFY] OTP request response:",
                response
            );


            updateStateFromResponse(
                response
            );


            if (
                response &&
                response.success === true
            ) {

                state.channel =
                    response.channel ||
                    selected;


                state.otpReady =
                    response.otpReady === true;


                const cooldown =
                    Number(
                        response.cooldownSeconds ||
                        RESEND_COOLDOWN
                    );


                /*
                 * ONLY selected channel
                 * receives cooldown.
                 */

                startCooldown(
                    selected,
                    cooldown
                );


                if (
                    selected === "email" &&
                    emailDeliveryStatus
                ) {

                    emailDeliveryStatus.textContent =
                        response.message ||
                        "A new email verification code was generated.";
                }


                if (
                    selected === "phone" &&
                    phoneDeliveryStatus
                ) {

                    phoneDeliveryStatus.textContent =
                        response.message ||
                        "A new phone verification code was generated.";
                }


                showMessage(
                    response.message ||
                    "A new verification code was generated.",
                    "success"
                );


                await autoFillBackendOtp(
                    response
                );


                return;
            }


            handleResponseError(
                response
            );

        } catch (error) {

            handleError(
                error
            );

        } finally {

            state.requesting =
                false;


            if (button) {

                setButtonText(
                    button,
                    selected === "email"
                        ? "Send code by email"
                        : "Send code by phone"
                );
            }


            updateCooldownUI(
                "email"
            );


            updateCooldownUI(
                "phone"
            );
        }
    }


    /* =====================================================
       EMAIL BUTTON
       ===================================================== */

    if (emailButton) {

        emailButton.addEventListener(
            "click",
            event => {

                event.preventDefault();


                requestOtp(
                    "email"
                );
            }
        );
    }


    /* =====================================================
       PHONE BUTTON
       ===================================================== */

    if (phoneButton) {

        phoneButton.addEventListener(
            "click",
            event => {

                event.preventDefault();


                requestOtp(
                    "phone"
                );
            }
        );
    }


    /* =====================================================
       VERIFY ACCOUNT
       ===================================================== */

    verifyForm.addEventListener(
        "submit",
        async event => {

            event.preventDefault();


            if (
                state.verifying
            ) {

                return;
            }


            clearMessage();


            const otp =
                getOtp();


            if (
                otp.length !== OTP_LENGTH
            ) {

                showMessage(
                    "Please enter the complete 6-digit verification code.",
                    "error"
                );


                return;
            }


            if (
                !state.identity &&
                !state.uid &&
                !state.username &&
                !state.email
            ) {

                showMessage(
                    "The pending account information is missing. Please register again.",
                    "error"
                );


                return;
            }


            state.verifying =
                true;


            if (verifyButton) {

                verifyButton.disabled =
                    true;


                setButtonText(
                    verifyButton,
                    "Verifying..."
                );
            }


            try {

                const response =
                    await API.verifyOtp({

                        identity:
                            state.identity,

                        uid:
                            state.uid,

                        username:
                            state.username,

                        email:
                            state.email,

                        gmail:
                            state.gmail,

                        phone:
                            state.phone,

                        channel:
                            state.channel,

                        otp:
                            otp
                    });


                console.log(
                    "[STOCKFLOW VERIFY] Verification response:",
                    response
                );


                if (
                    response &&
                    response.success === true
                ) {

                    /*
                     * BACKEND CONFIRMED:
                     *
                     * VERIFIED = TRUE
                     * ACCOUNT_S = ACTIVE
                     */

                    updateStateFromResponse(
                        response
                    );


                    saveVerifiedSession(
                        response
                    );


                    state.otpReady =
                        false;


                    state.demoOtp =
                        "";


                    showMessage(
                        response.message ||
                        "Account verified successfully.",
                        "success"
                    );


                    /*
                     * Remove temporary verification
                     * state ONLY after successful
                     * backend verification.
                     */

                    clearVerificationState();


                    const redirect =
                        response.redirect ||
                        DASHBOARD_ROUTE;


                    console.log(
                        "[STOCKFLOW VERIFY] Redirecting to dashboard:",
                        redirect
                    );


                    setTimeout(
                        () => {

                            window.location.href =
                                redirect;

                        },
                        700
                    );


                    return;
                }


                handleResponseError(
                    response
                );

            } catch (error) {

                handleError(
                    error
                );

            } finally {

                state.verifying =
                    false;


                if (
                    verifyButton
                ) {

                    verifyButton.disabled =
                        getOtp().length !==
                        OTP_LENGTH;


                    setButtonText(
                        verifyButton,
                        "Verify Account"
                    );
                }
            }
        }
    );


    /* =====================================================
       SAVE VERIFIED SESSION
       ===================================================== */

    function saveVerifiedSession(
        response
    ) {

        const user = {

            uid:
                response.uid ||
                state.uid,

            username:
                response.username ||
                state.username,

            name:
                response.name ||
                state.name,

            gmail:
                response.gmail ||
                response.email ||
                state.gmail,

            email:
                response.email ||
                response.gmail ||
                state.email,

            phone:
                response.phone ||
                state.phone,

            role:
                response.role ||
                state.role ||
                "Employee",

            verified:
                true,

            accountStatus:
                response.accountStatus ||
                "ACTIVE"
        };


        const auth = {

            authenticated:
                true,

            verified:
                true,

            uid:
                user.uid,

            username:
                user.username,

            role:
                user.role,

            accountStatus:
                user.accountStatus,

            loginTime:
                new Date().toISOString()
        };


        try {

            /*
             * Session storage
             */

            sessionStorage.setItem(
                "STOCKFLOW_USER",
                JSON.stringify(
                    user
                )
            );


            sessionStorage.setItem(
                "STOCKFLOW_AUTH",
                JSON.stringify(
                    auth
                )
            );


            /*
             * Local storage
             *
             * Dashboard compatibility.
             */

            localStorage.setItem(
                "STOCKFLOW_USER",
                JSON.stringify(
                    user
                )
            );


            localStorage.setItem(
                "STOCKFLOW_AUTH",
                JSON.stringify(
                    auth
                )
            );


            localStorage.setItem(
                "STOCKFLOW_TOKEN",
                JSON.stringify(
                    user
                )
            );


            console.log(
                "[STOCKFLOW VERIFY] Verified session saved:",
                user
            );

        } catch (error) {

            console.error(
                "[STOCKFLOW VERIFY] Unable to save verified session:",
                error
            );
        }
    }


    /* =====================================================
       CLEAR VERIFICATION STATE
       ===================================================== */

    function clearVerificationState() {

        /*
         * Remove only temporary verification state.
         *
         * Do NOT delete:
         *
         * STOCKFLOW_USER
         * STOCKFLOW_AUTH
         * STOCKFLOW_TOKEN
         *
         * because dashboard needs them.
         */

        removeStorage(
            STORAGE_KEYS.verification
        );
    }


    /* =====================================================
       RESPONSE ERROR HANDLING
       ===================================================== */

    function handleResponseError(
        response
    ) {

        if (!response) {

            showMessage(
                "No response was received from the verification system.",
                "error"
            );


            return;
        }


        const code =
            String(
                response.code ||
                ""
            ).toUpperCase();


        const message =
            String(
                response.message ||
                ""
            ).trim();


        switch (code) {

            case "ACCOUNT_NOT_FOUND":

                showMessage(
                    "Account does not exist.",
                    "error"
                );

                break;


            case "ALREADY_VERIFIED":

                showMessage(
                    "This account is already verified.",
                    "success"
                );


                saveVerifiedSession(
                    response
                );


                clearVerificationState();


                setTimeout(
                    () => {

                        window.location.href =
                            DASHBOARD_ROUTE;

                    },
                    700
                );

                break;


            case "OTP_EXPIRED":

                clearOtp();


                showMessage(
                    "The verification code has expired. Please request a new code.",
                    "error"
                );

                break;


            case "OTP_NOT_READY":

                clearOtp();


                showMessage(
                    "No active verification code was found. Please request a new code.",
                    "error"
                );

                break;


            case "INVALID_OTP":

                showMessage(
                    message ||
                    "Incorrect verification code. Please try again.",
                    "error"
                );

                break;


            case "INVALID_OTP_FORMAT":

                showMessage(
                    "Please enter the complete 6-digit verification code.",
                    "error"
                );

                break;


            case "OTP_LOCKED":

                showMessage(
                    message ||
                    "Too many incorrect attempts. Verification is temporarily locked.",
                    "error"
                );


                disableOtpInputs(
                    true
                );

                break;


            case "OTP_COOLDOWN":

                showMessage(
                    message ||
                    "Please wait before requesting another code.",
                    "warning"
                );


                if (
                    response.channel
                ) {

                    startCooldown(
                        response.channel,
                        Number(
                            response.cooldownSeconds ||
                            RESEND_COOLDOWN
                        )
                    );
                }

                break;


            case "ACCOUNT_DISABLED":

                showMessage(
                    "This account is disabled.",
                    "error"
                );

                break;


            case "ACCOUNT_SUSPENDED":

                showMessage(
                    "This account is suspended.",
                    "error"
                );

                break;


            case "ACCOUNT_BLOCKED":

                showMessage(
                    "This account is blocked.",
                    "error"
                );

                break;


            case "REQUIRES_VERIFICATION":

                showMessage(
                    "This account still needs verification.",
                    "warning"
                );

                break;


            default:

                showMessage(
                    message ||
                    "Unable to verify the account right now. Please try again.",
                    "error"
                );
        }
    }


    /* =====================================================
       GENERAL ERROR
       ===================================================== */

    function handleError(
        error
    ) {

        console.error(
            "[STOCKFLOW VERIFY ERROR]",
            error
        );


        const code =
            String(
                error?.code ||
                error?.data?.code ||
                ""
            ).toUpperCase();


        const message =
            String(
                error?.message ||
                error?.data?.message ||
                ""
            ).trim();


        if (code) {

            handleResponseError({

                success:
                    false,

                code:
                    code,

                message:
                    message
            });


            return;
        }


        showMessage(
            message ||
            "Unable to connect to the verification system right now. Please try again.",
            "error"
        );
    }


    /* =====================================================
       DISABLE OTP INPUTS
       ===================================================== */

    function disableOtpInputs(
        disabled
    ) {

        otpBoxes.forEach(
            input => {

                input.disabled =
                    disabled;
            }
        );


        if (verifyButton) {

            verifyButton.disabled =
                disabled;
        }
    }


    /* =====================================================
       INITIALIZE VERIFY PAGE
       ===================================================== */

    const hasVerificationState =
        loadVerificationState();


    /*
     * CRITICAL:
     *
     * There must be NO automatic redirect
     * immediately after registration.
     *
     * Registration sends the browser to
     * verify.html.
     *
     * verify.html then loads the saved
     * registration state.
     */

    if (!hasVerificationState) {

        console.warn(
            "[STOCKFLOW VERIFY] No pending verification state found."
        );


        showMessage(
            "No account is waiting for verification. Please register first.",
            "error"
        );


        setTimeout(
            () => {

                window.location.href =
                    REGISTER_ROUTE;

            },
            1500
        );


        return;
    }


    /* =====================================================
       VERIFY PAGE IS NOW READY
       ===================================================== */

    console.log(
        "[STOCKFLOW VERIFY] Pending account found:",
        {
            uid:
                state.uid,

            identity:
                state.identity,

            username:
                state.username,

            email:
                state.email,

            phone:
                state.phone
        }
    );


    /*
     * Default initial channel is EMAIL.
     */

    selectChannel(
        "email"
    );


    updateDestination();


    updateCooldownUI(
        "email"
    );


    updateCooldownUI(
        "phone"
    );


    if (verificationDescription) {

        verificationDescription.textContent =
            "Preparing your verification code...";
    }


    /*
     * THIS is where the backend OTP request
     * begins.
     *
     * Therefore the 3–5 second demo delay
     * starts AFTER verify.html is shown.
     */

    prepareInitialOtp();


    /* =====================================================
       CLEANUP
       ===================================================== */

    window.addEventListener(
        "beforeunload",
        () => {

            Object.keys(
                timers
            ).forEach(
                channel => {

                    if (
                        timers[channel]
                    ) {

                        clearInterval(
                            timers[channel]
                        );
                    }
                }
            );
        }
    );

});
