/* =========================================================
   STOCKFLOW - VERIFY ACCOUNT
   verify.js
   ========================================================= */

document.addEventListener("DOMContentLoaded", () => {
    "use strict";

    /* =====================================================
       CONFIGURATION
       ===================================================== */

    const CONFIG =
        window.STOCKFLOW_CONFIG ||
        window.CONFIG ||
        {};

    const AUTH_CONFIG =
        CONFIG.AUTH ||
        {};

    const API =
        window.StockFlowAPI ||
        window.API;

    const ROUTES =
        CONFIG.ROUTES ||
        {};

    const VERIFY_ROUTE =
        ROUTES.VERIFY ||
        "verify.html";

    const DASHBOARD_ROUTE =
        ROUTES.DASHBOARD ||
        "dashboard.html";

    const STORAGE_KEYS = {
        verification:
            "STOCKFLOW_VERIFICATION_STATE",

        session:
            "STOCKFLOW_SESSION",

        auth:
            "STOCKFLOW_AUTH",

        user:
            "STOCKFLOW_USER"
    };

    const OTP_LENGTH =
        Number(
            AUTH_CONFIG.OTP_LENGTH ||
            6
        );

    const RESEND_COOLDOWN =
        Number(
            AUTH_CONFIG.RESEND_COOLDOWN ||
            120
        );

    const DEMO_MODE =
        CONFIG.DEMO_MODE === true ||
        AUTH_CONFIG.DEMO_AUTO_FILL === true;

    const DEMO_MIN_DELAY =
        Number(
            AUTH_CONFIG.DEMO_AUTO_FILL_DELAY_MIN ||
            3000
        );

    const DEMO_MAX_DELAY =
        Number(
            AUTH_CONFIG.DEMO_AUTO_FILL_DELAY_MAX ||
            5000
        );


    /* =====================================================
       DOM ELEMENTS
       ===================================================== */

    const verifyForm =
        document.getElementById(
            "verifyForm"
        );

    const verifyButton =
        document.getElementById(
            "verifyButton"
        );

    const verifyMessage =
        document.getElementById(
            "verifyMessage"
        );

    const otpInputs =
        document.querySelectorAll(
            "#otpInputs input"
        );

    const emailMethod =
        document.getElementById(
            "emailMethod"
        );

    const phoneMethod =
        document.getElementById(
            "phoneMethod"
        );

    const emailButton =
        document.getElementById(
            "sendEmailCode"
        );

    const phoneButton =
        document.getElementById(
            "sendPhoneCode"
        );

    const emailCountdown =
        document.getElementById(
            "emailCountdown"
        );

    const phoneCountdown =
        document.getElementById(
            "phoneCountdown"
        );

    const destination =
        document.getElementById(
            "verifyDestination"
        );

    const resendMessage =
        document.getElementById(
            "resendMessage"
        );


    /* =====================================================
       ACCEPT MULTIPLE POSSIBLE HTML ID NAMES
       ===================================================== */

    const otpBoxes =
        otpInputs.length === OTP_LENGTH
            ? Array.from(otpInputs)
            : Array.from(
                document.querySelectorAll(
                    ".otp-input"
                )
            ).slice(
                0,
                OTP_LENGTH
            );


    /* =====================================================
       ELEMENT CHECK
       ===================================================== */

    if (!verifyForm) {
        console.warn(
            "StockFlow verify.js: verifyForm was not found."
        );

        return;
    }

    if (!API) {
        console.error(
            "StockFlow verify.js: StockFlowAPI/API is not available."
        );

        showMessage(
            "The verification system is not available right now.",
            "error"
        );

        return;
    }


    /* =====================================================
       STATE
       ===================================================== */

    let state = {
        identity: "",
        uid: "",
        username: "",
        name: "",
        gmail: "",
        email: "",
        phone: "",

        channel: "email",

        otpReady: false,

        /*
         * IMPORTANT:
         * This is only the backend-returned OTP.
         *
         * It is NEVER generated by this file.
         */
        demoOtp: "",

        verifying: false,
        requesting: false,

        cooldowns: {
            email: 0,
            phone: 0
        }
    };


    /* =====================================================
       TIMERS
       ===================================================== */

    const timers = {
        email: null,
        phone: null
    };


    /* =====================================================
       STORAGE
       ===================================================== */

    function loadVerificationState() {
        try {
            const raw =
                sessionStorage.getItem(
                    STORAGE_KEYS.verification
                );

            if (!raw) {
                return false;
            }

            const saved =
                JSON.parse(raw);

            if (
                !saved ||
                typeof saved !== "object"
            ) {
                return false;
            }

            state.identity =
                saved.identity ||
                saved.uid ||
                saved.username ||
                saved.gmail ||
                saved.email ||
                saved.phone ||
                "";

            state.uid =
                saved.uid ||
                "";

            state.username =
                saved.username ||
                "";

            state.name =
                saved.name ||
                "";

            state.gmail =
                saved.gmail ||
                saved.email ||
                "";

            state.email =
                saved.email ||
                saved.gmail ||
                "";

            state.phone =
                saved.phone ||
                "";

            /*
             * Never trust/store OTP from the
             * registration page.
             */
            state.demoOtp = "";

            state.otpReady =
                false;

            return Boolean(
                state.identity ||
                state.uid
            );

        } catch (error) {
            console.warn(
                "Unable to load verification state:",
                error
            );

            return false;
        }
    }


    function saveVerificationState() {
        try {
            sessionStorage.setItem(
                STORAGE_KEYS.verification,
                JSON.stringify({
                    identity:
                        state.identity,

                    uid:
                        state.uid,

                    username:
                        state.username,

                    name:
                        state.name,

                    gmail:
                        state.gmail,

                    email:
                        state.email,

                    phone:
                        state.phone,

                    channel:
                        state.channel,

                    /*
                     * Do not store OTP here.
                     */
                    otpReady:
                        false
                })
            );

        } catch (error) {
            console.warn(
                "Unable to save verification state:",
                error
            );
        }
    }


    /* =====================================================
       REDIRECT IF NO REGISTRATION STATE
       ===================================================== */

    if (
        !loadVerificationState()
    ) {
        showMessage(
            "No account is waiting for verification. Please register first.",
            "error"
        );

        setTimeout(() => {
            window.location.href =
                CONFIG.ROUTES &&
                CONFIG.ROUTES.REGISTER
                    ? CONFIG.ROUTES.REGISTER
                    : "auth.html#register";
        }, 1500);

        return;
    }


    /* =====================================================
       MESSAGE
       ===================================================== */

    function showMessage(
        message,
        type = "info"
    ) {
        const targets = [
            verifyMessage,
            resendMessage
        ];

        let target =
            verifyMessage;

        if (
            resendMessage &&
            type === "resend"
        ) {
            target =
                resendMessage;
        }

        if (!target) {
            console.log(
                message
            );

            return;
        }

        target.textContent =
            message;

        target.classList.remove(
            "success",
            "error",
            "info",
            "warning"
        );

        target.classList.add(
            type
        );

        target.hidden =
            false;
    }


    function clearMessage() {
        if (verifyMessage) {
            verifyMessage.textContent =
                "";

            verifyMessage.hidden =
                true;
        }

        if (resendMessage) {
            resendMessage.textContent =
                "";

            resendMessage.hidden =
                true;
        }
    }


    /* =====================================================
       MASK DESTINATION
       ===================================================== */

    function maskEmail(email) {
        const value =
            String(
                email || ""
            ).trim();

        const parts =
            value.split("@");

        if (
            parts.length !== 2
        ) {
            return value;
        }

        const name =
            parts[0];

        const domain =
            parts[1];

        if (
            name.length <= 2
        ) {
            return (
                name.charAt(0) +
                "*".repeat(
                    Math.max(
                        1,
                        name.length - 1
                    )
                ) +
                "@" +
                domain
            );
        }

        return (
            name.substring(
                0,
                2
            ) +
            "*".repeat(
                Math.max(
                    2,
                    name.length - 2
                )
            ) +
            "@" +
            domain
        );
    }


    function maskPhone(phone) {
        const value =
            String(
                phone || ""
            ).replace(
                /\s+/g,
                ""
            );

        if (
            value.length < 7
        ) {
            return value;
        }

        return (
            value.substring(
                0,
                3
            ) +
            "****" +
            value.substring(
                value.length - 3
            )
        );
    }


    function updateDestination() {
        if (!destination) {
            return;
        }

        if (
            state.channel === "phone"
        ) {
            destination.textContent =
                state.phone
                    ? maskPhone(
                        state.phone
                    )
                    : "your registered phone number";

            return;
        }

        destination.textContent =
            state.gmail ||
            state.email
                ? maskEmail(
                    state.gmail ||
                    state.email
                )
                : "your registered Gmail";
    }


    /* =====================================================
       METHOD SELECTION
       ===================================================== */

    function selectChannel(
        channel
    ) {
        const selected =
            channel === "phone"
                ? "phone"
                : "email";

        state.channel =
            selected;

        if (emailMethod) {
            emailMethod.classList.toggle(
                "active",
                selected === "email"
            );

            emailMethod.setAttribute(
                "aria-selected",
                selected === "email"
                    ? "true"
                    : "false"
            );
        }

        if (phoneMethod) {
            phoneMethod.classList.toggle(
                "active",
                selected === "phone"
            );

            phoneMethod.setAttribute(
                "aria-selected",
                selected === "phone"
                    ? "true"
                    : "false"
            );
        }

        updateDestination();
    }


    if (emailMethod) {
        emailMethod.addEventListener(
            "click",
            () => {
                /*
                 * IMPORTANT:
                 * Selecting the card DOES NOT
                 * generate an OTP.
                 */
                selectChannel(
                    "email"
                );
            }
        );
    }


    if (phoneMethod) {
        phoneMethod.addEventListener(
            "click",
            () => {
                /*
                 * Selecting the card DOES NOT
                 * generate an OTP.
                 */
                selectChannel(
                    "phone"
                );
            }
        );
    }


    /* =====================================================
       OTP BOX HELPERS
       ===================================================== */

    function clearOtpBoxes() {
        otpBoxes.forEach(
            input => {
                input.value = "";
            }
        );
    }


    function getOtpFromBoxes() {
        return otpBoxes
            .map(
                input =>
                    String(
                        input.value || ""
                    )
                        .replace(
                            /\D/g,
                            ""
                        )
                        .charAt(0)
            )
            .join("");
    }


    function fillOtpBoxes(
        otp
    ) {
        const code =
            String(
                otp || ""
            )
                .replace(
                    /\D/g,
                    ""
                )
                .substring(
                    0,
                    OTP_LENGTH
                );

        if (
            code.length !== OTP_LENGTH
        ) {
            return false;
        }

        otpBoxes.forEach(
            (
                input,
                index
            ) => {
                input.value =
                    code.charAt(
                        index
                    );
            }
        );

        /*
         * Trigger input events so any
         * existing UI validation reacts.
         */
        otpBoxes.forEach(
            input => {
                input.dispatchEvent(
                    new Event(
                        "input",
                        {
                            bubbles: true
                        }
                    )
                );
            }
        );

        return true;
    }


    /* =====================================================
       OTP INPUT BEHAVIOR
       ===================================================== */

    otpBoxes.forEach(
        (
            input,
            index
        ) => {

            input.setAttribute(
                "maxlength",
                "1"
            );

            input.setAttribute(
                "inputmode",
                "numeric"
            );

            input.addEventListener(
                "input",
                event => {
                    const value =
                        String(
                            event.target.value ||
                            ""
                        ).replace(
                            /\D/g,
                            ""
                        );

                    event.target.value =
                        value.charAt(0);

                    if (
                        value &&
                        index <
                        otpBoxes.length - 1
                    ) {
                        otpBoxes[
                            index + 1
                        ].focus();
                    }
                }
            );


            input.addEventListener(
                "keydown",
                event => {

                    if (
                        event.key ===
                        "Backspace" &&
                        !input.value &&
                        index > 0
                    ) {
                        otpBoxes[
                            index - 1
                        ].focus();
                    }


                    if (
                        event.key ===
                        "ArrowLeft" &&
                        index > 0
                    ) {
                        otpBoxes[
                            index - 1
                        ].focus();
                    }


                    if (
                        event.key ===
                        "ArrowRight" &&
                        index <
                        otpBoxes.length - 1
                    ) {
                        otpBoxes[
                            index + 1
                        ].focus();
                    }
                }
            );


            input.addEventListener(
                "paste",
                event => {
                    event.preventDefault();

                    const pasted =
                        (
                            event.clipboardData ||
                            window.clipboardData
                        )
                            .getData(
                                "text"
                            )
                            .replace(
                                /\D/g,
                                ""
                            )
                            .substring(
                                0,
                                OTP_LENGTH
                            );

                    if (!pasted) {
                        return;
                    }

                    fillOtpBoxes(
                        pasted
                    );

                    const lastIndex =
                        Math.min(
                            pasted.length,
                            otpBoxes.length
                        ) - 1;

                    if (
                        otpBoxes[
                            lastIndex
                        ]
                    ) {
                        otpBoxes[
                            lastIndex
                        ].focus();
                    }
                }
            );
        }
    );


    /* =====================================================
       BUTTON STATE
       ===================================================== */

    function setButtonLoading(
        button,
        loading,
        normalText,
        loadingText
    ) {
        if (!button) {
            return;
        }

        if (loading) {
            button.disabled =
                true;

            button.dataset.originalText =
                button.textContent;

            button.textContent =
                loadingText ||
                "Please wait...";
        } else {
            button.disabled =
                false;

            button.textContent =
                button.dataset.originalText ||
                normalText ||
                button.textContent;
        }
    }


    /* =====================================================
       BACKEND RESPONSE DATA
       ===================================================== */

    function extractOtp(
        response
    ) {
        if (!response) {
            return "";
        }

        const otp =
            response.otp ||
            response.codeValue ||
            response.verificationCode ||
            "";

        const normalized =
            String(
                otp
            )
                .replace(
                    /\D/g,
                    ""
                );

        if (
            normalized.length ===
            OTP_LENGTH
        ) {
            return normalized;
        }

        return "";
    }


    function updateStateFromResponse(
        response
    ) {
        if (!response) {
            return;
        }

        state.uid =
            response.uid ||
            state.uid;

        state.username =
            response.username ||
            state.username;

        state.name =
            response.name ||
            state.name;

        state.gmail =
            response.gmail ||
            response.email ||
            state.gmail;

        state.email =
            response.email ||
            response.gmail ||
            state.email;

        state.phone =
            response.phone ||
            state.phone;

        state.channel =
            response.channel ||
            state.channel;

        saveVerificationState();

        updateDestination();
    }


    /* =====================================================
       DEMO DELAY
       ===================================================== */

    function getDemoDelay() {
        /*
         * This does NOT generate an OTP.
         *
         * It only chooses how long to wait before
         * displaying the OTP that was already
         * generated by Apps Script.
         */

        const min =
            Math.max(
                0,
                DEMO_MIN_DELAY
            );

        const max =
            Math.max(
                min,
                DEMO_MAX_DELAY
            );

        if (
            max <= min
        ) {
            return min;
        }

        return (
            min +
            Math.floor(
                Math.random() *
                (
                    max -
                    min +
                    1
                )
            )
        );
    }


    /* =====================================================
       WAIT
       ===================================================== */

    function wait(
        milliseconds
    ) {
        return new Promise(
            resolve =>
                setTimeout(
                    resolve,
                    milliseconds
                )
        );
    }


    /* =====================================================
       AUTO-FILL BACKEND OTP
       ===================================================== */

    async function autoFillBackendOtp(
        response
    ) {
        if (
            !DEMO_MODE
        ) {
            return false;
        }

        const otp =
            extractOtp(
                response
            );

        if (
            otp.length !== OTP_LENGTH
        ) {
            return false;
        }

        state.demoOtp =
            otp;

        state.otpReady =
            true;

        /*
         * Wait approximately 3–5 seconds
         * before displaying the backend OTP.
         */
        await wait(
            getDemoDelay()
        );

        /*
         * The OTP is still the exact OTP
         * returned by Apps Script.
         */
        return fillOtpBoxes(
            otp
        );
    }


    /* =====================================================
       COOLDOWN DISPLAY
       ===================================================== */

    function updateCooldownUI(
        channel
    ) {
        const seconds =
            Math.max(
                0,
                Number(
                    state.cooldowns[
                        channel
                    ] || 0
                )
            );

        const button =
            channel === "email"
                ? emailButton
                : phoneButton;

        const countdown =
            channel === "email"
                ? emailCountdown
                : phoneCountdown;

        if (button) {
            button.disabled =
                seconds > 0 ||
                state.requesting;
        }

        if (countdown) {
            if (
                seconds > 0
            ) {
                countdown.textContent =
                    formatCountdown(
                        seconds
                    );

                countdown.hidden =
                    false;
            } else {
                countdown.textContent =
                    "";

                countdown.hidden =
                    true;
            }
        }
    }


    function formatCountdown(
        seconds
    ) {
        const safe =
            Math.max(
                0,
                Number(seconds) || 0
            );

        const minutes =
            Math.floor(
                safe / 60
            );

        const remainingSeconds =
            safe % 60;

        return (
            String(
                minutes
            ).padStart(
                2,
                "0"
            ) +
            ":" +
            String(
                remainingSeconds
            ).padStart(
                2,
                "0"
            )
        );
    }


    function stopCooldown(
        channel
    ) {
        if (
            timers[channel]
        ) {
            clearInterval(
                timers[channel]
            );

            timers[channel] =
                null;
        }

        state.cooldowns[
            channel
        ] = 0;

        updateCooldownUI(
            channel
        );
    }


    function startCooldown(
        channel,
        seconds
    ) {
        stopCooldown(
            channel
        );

        state.cooldowns[
            channel
        ] =
            Math.max(
                0,
                Number(seconds) ||
                RESEND_COOLDOWN
            );

        updateCooldownUI(
            channel
        );

        timers[channel] =
            setInterval(
                () => {

                    state.cooldowns[
                        channel
                    ]--;

                    if (
                        state.cooldowns[
                            channel
                        ] <= 0
                    ) {
                        stopCooldown(
                            channel
                        );

                        return;
                    }

                    updateCooldownUI(
                        channel
                    );

                },
                1000
            );
    }


    /* =====================================================
       INITIAL OTP REQUEST
       ===================================================== */

    async function prepareInitialOtp() {

        if (
            state.requesting
        ) {
            return;
        }

        state.requesting =
            true;

        clearMessage();

        selectChannel(
            "email"
        );

        setButtonLoading(
            verifyButton,
            false
        );

        try {

            /*
             * IMPORTANT:
             *
             * Initial OTP is generated by
             * Apps Script.
             *
             * This frontend NEVER creates it.
             */
            const response =
                await API.prepareOtp({
                    identity:
                        state.identity,

                    uid:
                        state.uid,

                    username:
                        state.username,

                    email:
                        state.email,

                    gmail:
                        state.gmail,

                    phone:
                        state.phone,

                    channel:
                        "email"
                });


            updateStateFromResponse(
                response
            );


            if (
                response &&
                response.success === true
            ) {

                state.channel =
                    response.channel ||
                    "email";

                state.otpReady =
                    response.otpReady === true;

                const cooldown =
                    Number(
                        response.cooldownSeconds ||
                        RESEND_COOLDOWN
                    );

                startCooldown(
                    "email",
                    cooldown
                );

                updateDestination();

                showMessage(
                    response.message ||
                    "Verification code generated. Please check your email.",
                    "success"
                );

                /*
                 * Auto-fill only the OTP that
                 * the backend actually generated.
                 */
                await autoFillBackendOtp(
                    response
                );

                if (
                    !DEMO_MODE
                ) {
                    showMessage(
                        response.message ||
                        "Verification code sent by email.",
                        "success"
                    );
                }

                return;
            }


            showMessage(
                response &&
                response.message
                    ? response.message
                    : "Unable to generate a verification code.",
                "error"
            );

        } catch (error) {

            handleApiError(
                error
            );

        } finally {
            state.requesting =
                false;

            updateCooldownUI(
                "email"
            );

            updateCooldownUI(
                "phone"
            );
        }
    }


    /* =====================================================
       REQUEST OTP BY CHANNEL
       ===================================================== */

    async function requestOtp(
        channel
    ) {

        const selected =
            channel === "phone"
                ? "phone"
                : "email";

        selectChannel(
            selected
        );

        if (
            state.requesting
        ) {
            return;
        }

        if (
            state.cooldowns[
                selected
            ] > 0
        ) {
            showMessage(
                "Please wait " +
                state.cooldowns[
                    selected
                ] +
                " seconds before requesting another " +
                selected +
                " code.",
                "warning"
            );

            return;
        }

        state.requesting =
            true;

        clearMessage();

        /*
         * Clear previous OTP boxes because
         * this request generates a NEW backend OTP.
         */
        clearOtpBoxes();

        state.demoOtp =
            "";

        state.otpReady =
            false;

        const button =
            selected === "email"
                ? emailButton
                : phoneButton;

        setButtonLoading(
            button,
            true,
            selected === "email"
                ? "Send code by email"
                : "Send code by phone",
            "Generating code..."
        );

        try {

            const response =
                await API.prepareOtp({
                    identity:
                        state.identity,

                    uid:
                        state.uid,

                    username:
                        state.username,

                    email:
                        state.email,

                    gmail:
                        state.gmail,

                    phone:
                        state.phone,

                    channel:
                        selected
                });


            updateStateFromResponse(
                response
            );


            if (
                response &&
                response.success === true
            ) {

                state.channel =
                    response.channel ||
                    selected;

                state.otpReady =
                    response.otpReady === true;

                const cooldown =
                    Number(
                        response.cooldownSeconds ||
                        RESEND_COOLDOWN
                    );

                /*
                 * Only the channel that was
                 * requested receives a cooldown.
                 *
                 * Email and phone remain
                 * independent.
                 */
                startCooldown(
                    selected,
                    cooldown
                );

                updateDestination();

                if (
                    selected === "email"
                ) {
                    showMessage(
                        response.message ||
                        "A new verification code was generated.",
                        "success"
                    );
                } else {
                    showMessage(
                        response.message ||
                        "A new verification code was generated.",
                        "success"
                    );
                }

                /*
                 * DEMO_MODE:
                 * Wait 3–5 seconds, then put the
                 * exact backend OTP into the six boxes.
                 */
                await autoFillBackendOtp(
                    response
                );

                return;
            }


            showMessage(
                response &&
                response.message
                    ? response.message
                    : "Unable to generate a new verification code.",
                "error"
            );

        } catch (error) {

            handleApiError(
                error
            );

        } finally {

            state.requesting =
                false;

            setButtonLoading(
                button,
                false,
                selected === "email"
                    ? "Send code by email"
                    : "Send code by phone"
            );

            updateCooldownUI(
                "email"
            );

            updateCooldownUI(
                "phone"
            );
        }
    }


    /* =====================================================
       SEND EMAIL BUTTON
       ===================================================== */

    if (emailButton) {
        emailButton.addEventListener(
            "click",
            event => {
                event.preventDefault();

                requestOtp(
                    "email"
                );
            }
        );
    }


    /* =====================================================
       SEND PHONE BUTTON
       ===================================================== */

    if (phoneButton) {
        phoneButton.addEventListener(
            "click",
            event => {
                event.preventDefault();

                requestOtp(
                    "phone"
                );
            }
        );
    }


    /* =====================================================
       VERIFY ACCOUNT
       ===================================================== */

    verifyForm.addEventListener(
        "submit",
        async event => {

            event.preventDefault();

            if (
                state.verifying
            ) {
                return;
            }

            clearMessage();

            const otp =
                getOtpFromBoxes();

            if (
                otp.length !== OTP_LENGTH
            ) {
                showMessage(
                    "Please enter the complete 6-digit verification code.",
                    "error"
                );

                const firstEmpty =
                    otpBoxes.find(
                        input =>
                            !input.value
                    );

                if (
                    firstEmpty
                ) {
                    firstEmpty.focus();
                }

                return;
            }

            state.verifying =
                true;

            if (verifyButton) {
                verifyButton.disabled =
                    true;

                verifyButton.dataset.originalText =
                    verifyButton.textContent;

                verifyButton.textContent =
                    "Verifying...";
            }

            try {

                const response =
                    await API.verifyOtp({
                        identity:
                            state.identity,

                        uid:
                            state.uid,

                        username:
                            state.username,

                        email:
                            state.email,

                        gmail:
                            state.gmail,

                        phone:
                            state.phone,

                        channel:
                            state.channel,

                        otp:
                            otp
                    });


                if (
                    response &&
                    response.success === true
                ) {

                    updateStateFromResponse(
                        response
                    );

                    /*
                     * Save verified session/user
                     * information for dashboard.
                     */
                    saveVerifiedSession(
                        response
                    );

                    state.otpReady =
                        false;

                    state.demoOtp =
                        "";

                    clearOtpBoxes();

                    showMessage(
                        response.message ||
                        "Account verified successfully.",
                        "success"
                    );

                    /*
                     * Remove registration verification
                     * state after successful verification.
                     */
                    clearVerificationState();

                    setTimeout(
                        () => {
                            window.location.href =
                                response.redirect ||
                                DASHBOARD_ROUTE;
                        },
                        700
                    );

                    return;
                }


                handleApiResponseError(
                    response
                );

            } catch (error) {

                handleApiError(
                    error
                );

            } finally {

                state.verifying =
                    false;

                if (verifyButton) {
                    verifyButton.disabled =
                        false;

                    verifyButton.textContent =
                        verifyButton.dataset.originalText ||
                        "Verify Account";
                }
            }
        }
    );


    /* =====================================================
       SAVE VERIFIED SESSION
       ===================================================== */

    function saveVerifiedSession(
        response
    ) {
        const user = {
            uid:
                response.uid ||
                state.uid,

            username:
                response.username ||
                state.username,

            name:
                response.name ||
                state.name,

            gmail:
                response.gmail ||
                response.email ||
                state.gmail,

            email:
                response.email ||
                response.gmail ||
                state.email,

            phone:
                response.phone ||
                state.phone,

            role:
                response.role ||
                "Employee",

            verified:
                true,

            accountStatus:
                response.accountStatus ||
                "VERIFIED"
        };

        try {

            sessionStorage.setItem(
                STORAGE_KEYS.session,
                JSON.stringify(
                    user
                )
            );

            sessionStorage.setItem(
                STORAGE_KEYS.auth,
                JSON.stringify({
                    authenticated:
                        true,

                    verified:
                        true,

                    uid:
                        user.uid,

                    username:
                        user.username,

                    role:
                        user.role,

                    loginTime:
                        new Date().toISOString()
                })
            );

            sessionStorage.setItem(
                STORAGE_KEYS.user,
                JSON.stringify(
                    user
                )
            );

            /*
             * Also keep localStorage compatible
             * with dashboards that use it.
             */
            localStorage.setItem(
                STORAGE_KEYS.session,
                JSON.stringify(
                    user
                )
            );

        } catch (error) {
            console.warn(
                "Unable to save verified session:",
                error
            );
        }
    }


    /* =====================================================
       CLEAR VERIFICATION STATE
       ===================================================== */

    function clearVerificationState() {
        try {
            sessionStorage.removeItem(
                STORAGE_KEYS.verification
            );
        } catch (error) {
            console.warn(
                "Unable to clear verification state:",
                error
            );
        }
    }


    /* =====================================================
       ERROR HANDLING
       ===================================================== */

    function getErrorCode(
        error
    ) {
        if (!error) {
            return "";
        }

        return String(
            error.code ||
            error.data?.code ||
            ""
        ).toUpperCase();
    }


    function getErrorMessage(
        error
    ) {
        if (!error) {
            return "";
        }

        return String(
            error.message ||
            error.data?.message ||
            ""
        ).trim();
    }


    function handleApiResponseError(
        response
    ) {
        if (!response) {
            showMessage(
                "No response was received from the verification system.",
                "error"
            );

            return;
        }

        const code =
            String(
                response.code ||
                ""
            ).toUpperCase();

        const message =
            String(
                response.message ||
                ""
            ).trim();


        switch (code) {

            case "ACCOUNT_NOT_FOUND":
                showMessage(
                    "Account does not exist.",
                    "error"
                );
                break;


            case "ALREADY_VERIFIED":
                showMessage(
                    "This account is already verified.",
                    "success"
                );

                setTimeout(
                    () => {
                        window.location.href =
                            DASHBOARD_ROUTE;
                    },
                    1000
                );

                break;


            case "OTP_EXPIRED":
                clearOtpBoxes();

                showMessage(
                    "The verification code has expired. Please request a new code.",
                    "error"
                );

                break;


            case "OTP_NOT_READY":
                clearOtpBoxes();

                showMessage(
                    "No verification code is active. Please request a new code.",
                    "error"
                );

                break;


            case "INVALID_OTP":
                showMessage(
                    message ||
                    "Incorrect verification code. Please try again.",
                    "error"
                );

                break;


            case "INVALID_OTP_FORMAT":
                showMessage(
                    "Please enter the complete 6-digit verification code.",
                    "error"
                );

                break;


            case "OTP_LOCKED":
                showMessage(
                    message ||
                    "Too many incorrect attempts. Verification is temporarily locked.",
                    "error"
                );

                disableOtpInputs(
                    true
                );

                break;


            case "OTP_COOLDOWN":

                showMessage(
                    message ||
                    "Please wait before requesting another code.",
                    "warning"
                );

                if (
                    response.channel
                ) {
                    startCooldown(
                        response.channel,
                        Number(
                            response.cooldownSeconds ||
                            RESEND_COOLDOWN
                        )
                    );
                }

                break;


            case "ACCOUNT_DISABLED":
                showMessage(
                    "This account is disabled.",
                    "error"
                );

                break;


            case "ACCOUNT_SUSPENDED":
                showMessage(
                    "This account is suspended.",
                    "error"
                );

                break;


            case "ACCOUNT_BLOCKED":
                showMessage(
                    "This account is blocked.",
                    "error"
                );

                break;


            case "OTP_STORAGE_FAILED":
            case "OTP_DELIVERY_FAILED":
                showMessage(
                    message ||
                    "The verification code could not be generated. Please try again.",
                    "error"
                );

                break;


            default:
                showMessage(
                    message ||
                    "Unable to verify the account right now. Please try again.",
                    "error"
                );
        }
    }


    function handleApiError(
        error
    ) {
        console.error(
            "StockFlow verification error:",
            error
        );

        const code =
            getErrorCode(
                error
            );

        const message =
            getErrorMessage(
                error
            );


        /*
         * IMPORTANT:
         *
         * Business errors from Code.gs are NOT
         * treated as network errors.
         */

        if (
            code
        ) {
            handleApiResponseError({
                success:
                    false,

                code:
                    code,

                message:
                    message
            });

            return;
        }


        /*
         * Actual network/transport error.
         */
        if (
            error &&
            (
                error.name ===
                "AbortError" ||
                error.name ===
                "TypeError"
            )
        ) {
            showMessage(
                "Unable to connect to the verification system right now. Please check your internet connection and try again.",
                "error"
            );

            return;
        }


        showMessage(
            message ||
            "Unable to verify the account right now. Please try again.",
            "error"
        );
    }


    /* =====================================================
       DISABLE OTP INPUTS
       ===================================================== */

    function disableOtpInputs(
        disabled
    ) {
        otpBoxes.forEach(
            input => {
                input.disabled =
                    disabled;
            }
        );
    }


    /* =====================================================
       INITIAL UI
       ===================================================== */

    selectChannel(
        "email"
    );

    updateDestination();

    updateCooldownUI(
        "email"
    );

    updateCooldownUI(
        "phone"
    );

    /*
     * Initial OTP generation.
     *
     * This calls the backend.
     *
     * It does NOT create an OTP in the browser.
     */
    prepareInitialOtp();


    /* =====================================================
       CLEANUP
       ===================================================== */

    window.addEventListener(
        "beforeunload",
        () => {
            Object.keys(
                timers
            ).forEach(
                channel => {
                    if (
                        timers[channel]
                    ) {
                        clearInterval(
                            timers[channel]
                        );
                    }
                }
            );
        }
    );

});
